ITEMS = [
# --- Pastry / bakery / dessert pantry ---
("Couverture 70%",["Couverture dunkel 70%"],"Universal","Chocolate & Cocoa","kg",16.0,"Switzerland",[], "Dark chocolate couverture",550,7.0,35.0,42.0,"Dry Storage"),
("Ruby Chocolate",["Ruby-Schokolade"],"Universal","Chocolate & Cocoa","kg",22.0,"Belgium/Switzerland",[], "White chocolate couverture",560,7.0,50.0,36.0,"Dry Storage"),
("Cocoa Nibs",["Kakaonibs"],"Universal","Chocolate & Cocoa","kg",18.0,"Ecuador/Peru",[], "Dark chocolate",600,14.0,10.0,52.0,"Dry Storage"),
("Cocoa Butter",["Kakaobutter"],"Universal","Chocolate & Cocoa","kg",20.0,"Ivory Coast",[], "Clarified butter",884,0.0,0.0,100.0,"Dry Storage"),
("Dutch Cocoa Powder",["Kakaopulver alkalisiert"],"Universal","Chocolate & Cocoa","kg",9.0,"Netherlands",[], "Cocoa powder",355,19.6,57.9,13.7,"Dry Storage"),
("Gianduja",["Gianduja"],"European","Chocolate & Cocoa","kg",18.0,"Piedmont, Italy",[], "Hazelnut paste + chocolate",560,8.0,45.0,38.0,"Dry Storage"),
("Hazelnut Paste",["Haselnusspaste 100%"],"European","Chocolate & Cocoa","kg",24.0,"Piedmont, Italy",[], "Praline paste",646,15.0,17.0,61.0,"Dry Storage"),
("Praline Paste",["Pralinépaste"],"European","Chocolate & Cocoa","kg",20.0,"France",[], "Hazelnut paste",560,8.0,45.0,36.0,"Dry Storage"),
("Pistachio Paste",["Pistazienpaste 100%"],"European","Chocolate & Cocoa","kg",48.0,"Sicily/Iran",[], "Hazelnut paste",590,20.0,18.0,50.0,"Dry Storage"),
("Almond Paste",["Mandelmasse"],"European","Bakery","kg",11.0,"Germany/Spain",[], "Marzipan",480,9.0,45.0,28.0,"Dry Storage"),
("Marzipan",["Marzipan"],"European","Bakery","kg",9.5,"Germany",[], "Almond paste",460,7.5,55.0,22.0,"Dry Storage"),
("Fondant",["Fondantmasse"],"European","Bakery","kg",5.5,"Switzerland/Germany",[], "Icing sugar",390,0.0,97.0,0.0,"Dry Storage"),
("Glucose Syrup",["Glukosesirup"],"Universal","Sweeteners","kg",4.0,"EU",[], "Corn syrup",320,0.0,80.0,0.0,"Dry Storage"),
("Invert Sugar",["Invertzucker","Trimoline"],"Universal","Sweeteners","kg",6.0,"EU",[], "Glucose syrup",340,0.0,85.0,0.0,"Dry Storage"),
("Isomalt",["Isomalt"],"Universal","Sweeteners","kg",9.0,"Germany",[], "Sugar",240,0.0,98.0,0.0,"Dry Storage"),
("Pectin NH",["Pektin NH"],"Universal","Other","kg",38.0,"EU",[], "Agar-agar",250,0.0,80.0,0.0,"Dry Storage"),
("Agar-Agar",["Agar-Agar"],"Asian","Other","kg",42.0,"Japan/Chile",[], "Gelatin",306,6.0,80.0,0.3,"Dry Storage"),
("Gelatin Leaves",["Blattgelatine Gold"],"Universal","Other","kg",28.0,"Germany",[], "Agar-agar",343,84.0,0.0,0.1,"Dry Storage"),
("Xanthan Gum",["Xanthan"],"Universal","Other","kg",26.0,"EU",[], "Cornstarch",330,10.0,78.0,0.0,"Dry Storage"),
("Soy Lecithin",["Sojalecithin"],"Universal","Other","kg",18.0,"EU",[], None,760,0.0,8.0,80.0,"Dry Storage"),
("Tapioca Starch",["Tapiokastärke"],"Asian","Other","kg",4.5,"Thailand",[], "Cornstarch",358,0.2,88.7,0.0,"Dry Storage"),
("Potato Starch",["Kartoffelstärke"],"European","Other","kg",3.0,"Switzerland/Germany",[], "Cornstarch",357,0.1,83.1,0.1,"Dry Storage"),
("Dried Yeast",["Trockenhefe"],"Universal","Bakery","kg",12.0,"EU",[], "Fresh yeast",325,40.4,41.2,7.6,"Dry Storage"),
("Fresh Yeast",["Frischhefe"],"Universal","Bakery","kg",4.5,"Switzerland",[], "Dried yeast",105,12.1,12.5,1.7,"Refrigerated"),
("Sourdough Starter",["Sauerteig-Starter"],"European","Bakery","kg",6.0,"Switzerland",[], "Fresh yeast",120,4.0,24.0,0.5,"Refrigerated"),
("Baking Powder",["Backpulver"],"Universal","Bakery","kg",5.0,"Switzerland/Germany",[], "Baking soda + cream of tartar",53,0.0,27.7,0.0,"Dry Storage"),
("Baking Soda",["Natron"],"Universal","Bakery","kg",3.5,"EU",[], "Baking powder",0,0.0,0.0,0.0,"Dry Storage"),
("Cream of Tartar",["Weinstein"],"Universal","Bakery","kg",14.0,"EU",[], None,258,0.0,61.5,0.0,"Dry Storage"),
("Filo Pastry",["Filoteig","Strudelteig"],"European","Bakery","kg",7.5,"Greece/Austria",[], "Puff pastry block",300,7.0,55.0,5.0,"Freezer"),
("Brik Pastry",["Brickteig"],"Universal","Bakery","kg",9.0,"Tunisia/France",[], "Filo pastry",310,8.0,58.0,4.5,"Refrigerated"),
("Kataifi",["Kataifi-Teig","Engelshaar"],"European","Bakery","kg",9.5,"Greece",[], "Filo pastry",320,7.5,60.0,5.5,"Freezer"),
("Choux Pastry Mix",["Brandteig-Mix"],"European","Bakery","kg",8.0,"France/Switzerland",[], None,420,10.0,60.0,15.0,"Dry Storage"),
("Ladyfingers",["Löffelbiskuits"],"European","Bakery","kg",8.5,"Italy",[], "Sponge cake",390,8.0,75.0,5.0,"Dry Storage"),
("Amaretti",["Amaretti"],"European","Bakery","kg",14.0,"Italy",[], "Ladyfingers",440,9.0,70.0,14.0,"Dry Storage"),
("Waffle Cones",["Waffeltüten"],"European","Bakery","pc",0.25,"Switzerland/Germany",[], None,410,7.0,80.0,7.0,"Dry Storage"),
("Meringue Shells",["Meringues"],"European","Bakery","kg",16.0,"Switzerland",[], None,390,5.0,92.0,0.0,"Dry Storage"),
("Vermicelles Purée",["Vermicelles-Masse"],"European","Bakery","kg",11.0,"Switzerland",["Autumn","Winter"], "Chestnut purée",240,3.0,50.0,3.0,"Freezer"),
("Läckerli",["Basler Läckerli"],"European","Bakery","kg",16.0,"Basel, Switzerland",["Winter"], "Gingerbread",390,6.0,75.0,8.0,"Dry Storage"),
("Gingerbread Spice",["Lebkuchengewürz"],"European","Spices & Seasonings","kg",18.0,"Switzerland/Germany",["Winter"], "Cinnamon + cloves",300,8.0,55.0,8.0,"Dry Storage"),
# --- Sweeteners ---
("Acacia Honey",["Akazienhonig"],"European","Sweeteners","kg",12.0,"Switzerland/Hungary",[], "Honey",304,0.3,82.4,0.0,"Dry Storage"),
("Swiss Mountain Honey",["Schweizer Berghonig"],"European","Sweeteners","kg",22.0,"Swiss Alps",[], "Acacia honey",304,0.3,82.4,0.0,"Dry Storage"),
("Chestnut Honey",["Kastanienhonig"],"European","Sweeteners","kg",18.0,"Ticino/Italy",[], "Mountain honey",304,0.3,82.4,0.0,"Dry Storage"),
("Maple Syrup Grade A",["Ahornsirup"],"Universal","Sweeteners","l",14.0,"Canada",[], "Honey",260,0.0,67.0,0.1,"Dry Storage"),
("Agave Syrup",["Agavendicksaft"],"Universal","Sweeteners","l",7.0,"Mexico",[], "Maple syrup",310,0.0,76.0,0.2,"Dry Storage"),
("Coconut Sugar",["Kokosblütenzucker"],"Asian","Sweeteners","kg",9.0,"Indonesia",[], "Brown sugar",380,1.0,93.0,0.4,"Dry Storage"),
("Muscovado Sugar",["Muscovado-Zucker"],"Universal","Sweeteners","kg",6.5,"Mauritius",[], "Brown sugar",380,0.1,97.0,0.0,"Dry Storage"),
("Pearl Sugar",["Hagelzucker"],"European","Sweeteners","kg",3.5,"Switzerland/Belgium",[], "Sugar",400,0.0,100.0,0.0,"Dry Storage"),
("Vanilla Sugar",["Vanillezucker"],"European","Sweeteners","kg",8.0,"Switzerland",[], "Sugar + vanilla",398,0.0,99.0,0.0,"Dry Storage"),
("Molasses",["Melasse"],"Universal","Sweeteners","kg",5.0,"Caribbean",[], "Date syrup",290,0.0,74.7,0.1,"Dry Storage"),
("Elderflower Syrup",["Holunderblütensirup"],"European","Sweeteners","l",8.0,"Switzerland/Austria",["Spring"], None,280,0.0,70.0,0.0,"Dry Storage"),
# --- Cooking alcohol ---
("Marsala",["Marsala"],"European","Alcohol","l",9.0,"Sicily",[], "Madeira",160,0.0,12.0,0.0,"Dry Storage"),
("Madeira",["Madeira"],"European","Alcohol","l",11.0,"Portugal",[], "Marsala",160,0.0,10.0,0.0,"Dry Storage"),
("Port Wine",["Portwein"],"European","Alcohol","l",12.0,"Portugal",[], "Madeira",160,0.0,12.0,0.0,"Dry Storage"),
("Dry Sherry",["Sherry Fino"],"European","Alcohol","l",10.0,"Jerez, Spain",[], "Dry white wine",120,0.0,1.5,0.0,"Dry Storage"),
("Vermouth Dry",["Noilly Prat","Wermut trocken"],"European","Alcohol","l",12.0,"France/Italy",[], "Dry white wine",130,0.0,4.0,0.0,"Dry Storage"),
("Pastis",["Pastis"],"European","Alcohol","l",18.0,"France",[], "Pernod",274,0.0,10.0,0.0,"Dry Storage"),
("Calvados",["Calvados"],"European","Alcohol","l",26.0,"Normandy, France",[], "Apple brandy",240,0.0,0.5,0.0,"Dry Storage"),
("Armagnac",["Armagnac"],"European","Alcohol","l",32.0,"Gascony, France",[], "Cognac",240,0.0,0.5,0.0,"Dry Storage"),
("Amaretto",["Amaretto"],"European","Alcohol","l",16.0,"Italy",[], "Almond extract + brandy",280,0.0,28.0,0.0,"Dry Storage"),
("Limoncello",["Limoncello"],"European","Alcohol","l",15.0,"Amalfi, Italy",[], "Lemon zest + vodka",300,0.0,30.0,0.0,"Dry Storage"),
("Kirsch",["Kirschwasser"],"European","Alcohol","l",28.0,"Zug, Switzerland",[], "Cherry brandy",240,0.0,0.0,0.0,"Dry Storage"),
("Williams Brandy",["Williamsbrand"],"European","Alcohol","l",26.0,"Valais, Switzerland",[], "Kirsch",240,0.0,0.0,0.0,"Dry Storage"),
("Absinthe",["Absinth"],"European","Alcohol","l",38.0,"Val-de-Travers, Switzerland",[], "Pastis",280,0.0,1.0,0.0,"Dry Storage"),
("Damassine",["Damassine AOP"],"European","Alcohol","l",42.0,"Jura, Switzerland",[], "Plum brandy",240,0.0,0.0,0.0,"Dry Storage"),
("Fendant Wine",["Fendant","Chasselas"],"European","Alcohol","l",9.0,"Valais, Switzerland",[], "Dry white wine",120,0.0,1.0,0.0,"Dry Storage"),
("Pinot Noir Cooking",["Pinot Noir CH"],"European","Alcohol","l",8.5,"Switzerland",[], "Red wine",125,0.0,1.5,0.0,"Dry Storage"),
("Prosecco",["Prosecco"],"European","Alcohol","l",8.0,"Veneto, Italy",[], "Dry white wine",128,0.0,2.5,0.0,"Refrigerated"),
("Dark Beer",["Dunkelbier"],"European","Alcohol","l",3.5,"Switzerland",[], "Lager",48,0.5,4.5,0.0,"Dry Storage"),
("Cider Dry",["Cidre brut","Suure Moscht"],"European","Alcohol","l",4.5,"Thurgau, Switzerland",[], "Dry white wine",45,0.0,3.0,0.0,"Dry Storage"),
# --- Coffee / beverages ---
("Espresso Beans",["Espressobohnen"],"Universal","Other","kg",22.0,"Brazil/Ethiopia blend",[], "Coffee beans",2,0.1,0.3,0.0,"Dry Storage"),
("Decaf Coffee Beans",["entkoffeinierte Bohnen"],"Universal","Other","kg",24.0,"Colombia",[], "Espresso beans",2,0.1,0.3,0.0,"Dry Storage"),
("Matcha",["Matcha-Pulver"],"Asian","Other","kg",120.0,"Japan",[], "Green tea powder",324,30.0,38.0,5.0,"Refrigerated"),
("Earl Grey Tea",["Earl-Grey-Tee"],"European","Other","kg",28.0,"Sri Lanka/India",[], "Black tea",1,0.1,0.2,0.0,"Dry Storage"),
("Verbena Tea",["Eisenkraut","Verveine"],"European","Other","kg",34.0,"France",[], "Chamomile",1,0.1,0.2,0.0,"Dry Storage"),
("Chamomile",["Kamillenblüten"],"European","Other","kg",26.0,"Egypt/Croatia",[], "Verbena tea",1,0.1,0.2,0.0,"Dry Storage"),
("Hibiscus Flowers",["Hibiskusblüten"],"Universal","Other","kg",18.0,"Egypt/Sudan",[], None,49,1.9,11.0,0.1,"Dry Storage"),
("Elderflowers Dried",["Holunderblüten getrocknet"],"European","Other","kg",32.0,"Switzerland/Austria",["Spring"], "Elderflower syrup",50,2.0,10.0,0.5,"Dry Storage"),
("Apple Juice Cloudy",["Apfelsaft naturtrüb","Süssmost"],"European","Other","l",2.2,"Thurgau, Switzerland",[], "Apple juice",46,0.1,11.0,0.1,"Dry Storage"),
("Grape Juice Red",["roter Traubensaft"],"European","Other","l",3.0,"Switzerland/Italy",[], "Apple juice cloudy",60,0.2,14.5,0.1,"Dry Storage"),
("Rivella",["Rivella rot"],"European","Other","l",2.0,"Switzerland",[], None,38,0.0,9.0,0.0,"Dry Storage"),
("Sparkling Water",["Mineralwasser mit Kohlensäure"],"Universal","Other","l",0.8,"Switzerland",[], None,0,0.0,0.0,0.0,"Dry Storage"),
]
