ITEMS = [
# --- Seafood (species-level, chef-grade) ---
("Turbot",["Steinbutt"],"European","Seafood","kg",42.0,"North Atlantic",[], "Halibut",95,16.0,0.0,3.0,"Refrigerated"),
("Halibut",["Heilbutt"],"European","Seafood","kg",34.0,"North Atlantic",[], "Turbot",110,20.5,0.0,2.5,"Refrigerated"),
("Dover Sole",["Seezunge"],"European","Seafood","kg",46.0,"North Sea",[], "Plaice",90,17.0,0.0,1.5,"Refrigerated"),
("Plaice",["Scholle","Goldbutt"],"European","Seafood","kg",18.0,"North Sea",[], "Dover sole",85,16.5,0.0,1.5,"Refrigerated"),
("Monkfish",["Seeteufel","Lotte"],"European","Seafood","kg",36.0,"North Atlantic",[], "Halibut",76,15.5,0.0,1.5,"Refrigerated"),
("Sea Bass Whole",["Loup de mer","Wolfsbarsch"],"European","Seafood","kg",24.0,"Mediterranean",[], "Sea bream",124,18.5,0.0,5.5,"Refrigerated"),
("Sea Bream",["Dorade royale"],"European","Seafood","kg",22.0,"Mediterranean",[], "Sea bass",115,19.5,0.0,4.0,"Refrigerated"),
("Red Mullet",["Rotbarbe"],"European","Seafood","kg",32.0,"Mediterranean",[], "Sea bream",117,19.0,0.0,4.5,"Refrigerated"),
("John Dory",["Petersfisch","St. Pierre"],"European","Seafood","kg",38.0,"Atlantic",[], "Turbot",90,17.5,0.0,1.5,"Refrigerated"),
("Skate Wing",["Rochenflügel"],"European","Seafood","kg",20.0,"North Atlantic",[], "Plaice",95,20.0,0.0,1.0,"Refrigerated"),
("Mackerel",["Makrele"],"European","Seafood","kg",12.0,"North Atlantic",[], "Sardines",205,18.5,0.0,14.0,"Refrigerated"),
("Sardines",["Sardinen frisch"],"European","Seafood","kg",10.0,"Mediterranean",[], "Mackerel",208,20.0,0.0,13.5,"Refrigerated"),
("Anchovies Fresh",["frische Sardellen","Boquerones"],"European","Seafood","kg",14.0,"Mediterranean",[], "Sardines",131,20.0,0.0,5.0,"Refrigerated"),
("Whole Salmon",["Lachs ganz"],"European","Seafood","kg",16.5,"Norway",[], None,208,20.5,0.0,13.5,"Refrigerated"),
("Smoked Salmon",["Räucherlachs"],"European","Seafood","kg",34.0,"Norway/Scotland",[], "Smoked trout",142,23.0,0.5,5.5,"Refrigerated"),
("Smoked Trout",["Räucherforelle"],"European","Seafood","kg",28.0,"Switzerland",[], "Smoked salmon",135,23.5,0.5,4.5,"Refrigerated"),
("Whole Trout",["Forelle ganz"],"European","Seafood","kg",14.0,"Switzerland",[], None,119,20.5,0.0,4.0,"Refrigerated"),
("Perch Fillet",["Eglifilet"],"European","Seafood","kg",38.0,"Switzerland",[], "Pike-perch fillet",91,18.5,0.0,1.5,"Refrigerated"),
("Whitefish Fillet",["Felchenfilet"],"European","Seafood","kg",30.0,"Swiss lakes",[], "Perch fillet",100,19.0,0.0,2.5,"Refrigerated"),
("Pike",["Hecht"],"European","Seafood","kg",22.0,"Swiss lakes",[], "Pike-perch fillet",88,19.5,0.0,0.7,"Refrigerated"),
("Octopus",["Oktopus","Pulpo"],"European","Seafood","kg",16.0,"Mediterranean",[], "Squid",82,15.0,2.0,1.0,"Freezer"),
("Squid",["Tintenfisch","Calamari"],"European","Seafood","kg",12.0,"Mediterranean",[], "Octopus",92,15.5,3.0,1.5,"Freezer"),
("Cuttlefish",["Sepia"],"European","Seafood","kg",14.0,"Mediterranean",[], "Squid",80,16.0,1.0,0.7,"Freezer"),
("Blue Mussels",["Miesmuscheln","Moules"],"European","Seafood","kg",6.5,"Netherlands",["Autumn","Winter","Spring"], "Clams",86,12.0,3.5,2.0,"Refrigerated"),
("Clams",["Venusmuscheln","Vongole"],"European","Seafood","kg",14.0,"Mediterranean",[], "Blue mussels",86,14.5,2.5,1.0,"Refrigerated"),
("Oysters",["Austern","Fines de Claire"],"European","Seafood","pc",1.8,"France",["Autumn","Winter","Spring"], None,68,7.0,4.0,2.5,"Refrigerated"),
("Scallops",["Jakobsmuscheln","Coquilles St-Jacques"],"European","Seafood","kg",38.0,"North Atlantic",["Autumn","Winter"], "Prawns",88,16.5,3.0,0.8,"Freezer"),
("Langoustines",["Kaisergranat","Scampi"],"European","Seafood","kg",42.0,"North Atlantic",[], "Prawns",91,18.5,0.5,1.0,"Freezer"),
("Lobster",["Hummer"],"European","Seafood","kg",48.0,"North Atlantic",[], "Langoustines",89,19.0,0.5,0.9,"Refrigerated"),
("Crab Meat",["Krabbenfleisch"],"Universal","Seafood","kg",36.0,"North Atlantic",[], "Prawns",97,19.5,0.0,1.5,"Freezer"),
("Snails",["Weinbergschnecken","Escargots"],"European","Seafood","kg",22.0,"France",[], None,90,16.0,2.0,1.5,"Freezer"),
("Caviar",["Kaviar","Osietra"],"European","Seafood","kg",1200.0,"Farmed, various",[], "Trout roe",264,25.0,4.0,18.0,"Refrigerated"),
("Trout Roe",["Forellenkaviar"],"European","Seafood","kg",120.0,"Switzerland",[], "Salmon roe",250,29.0,3.0,14.0,"Refrigerated"),
("Salted Anchovies",["Sardellenfilets in Öl"],"European","Seafood","kg",22.0,"Italy",[], "Fresh anchovies",210,29.0,0.0,10.0,"Room Temperature"),
("Salt Cod",["Stockfisch","Bacalao"],"European","Seafood","kg",24.0,"Norway",[], "Cod loin",290,62.0,0.0,2.5,"Refrigerated"),
("Tuna Loin",["Thunfisch Loin","Yellowfin"],"Universal","Seafood","kg",32.0,"Indian Ocean",[], "Swordfish",109,24.5,0.0,1.0,"Freezer"),
("Swordfish",["Schwertfisch"],"European","Seafood","kg",28.0,"Mediterranean",[], "Tuna loin",144,20.0,0.0,7.0,"Freezer"),
("Eel Smoked",["Räucheraal"],"European","Seafood","kg",44.0,"Netherlands",[], "Smoked trout",305,18.5,0.0,25.5,"Refrigerated"),
# --- Vegetables (varieties & chef staples missing so far) ---
("Jerusalem Artichoke",["Topinambur"],"European","Vegetable","kg",6.5,"Switzerland",["Autumn","Winter"], "Parsnip",73,2.0,17.0,0.1,"Refrigerated"),
("Celeriac",["Knollensellerie"],"European","Vegetable","kg",2.8,"Switzerland",["Autumn","Winter"], "Parsley root",42,1.5,9.0,0.3,"Refrigerated"),
("Parsley Root",["Petersilienwurzel"],"European","Vegetable","kg",5.5,"Switzerland",["Autumn","Winter"], "Celeriac",55,3.0,12.0,0.6,"Refrigerated"),
("Black Radish",["Schwarzer Rettich"],"European","Vegetable","kg",4.5,"Switzerland",["Autumn","Winter"], "Daikon",20,1.0,4.0,0.1,"Refrigerated"),
("Daikon",["Rettich weiss"],"Asian","Vegetable","kg",4.0,"Switzerland",[], "Black radish",18,0.6,4.0,0.1,"Refrigerated"),
("Chioggia Beet",["Ringelbete"],"European","Vegetable","kg",5.0,"Switzerland",["Autumn","Winter"], "Beetroot",43,1.6,10.0,0.2,"Refrigerated"),
("Yellow Beet",["Gelbe Bete"],"European","Vegetable","kg",5.0,"Switzerland",["Autumn","Winter"], "Beetroot",43,1.6,10.0,0.2,"Refrigerated"),
("Purple Carrot",["Urkarotte violett"],"European","Vegetable","kg",4.8,"Switzerland",["Autumn","Winter"], "Carrot",41,0.9,10.0,0.2,"Refrigerated"),
("Rainbow Chard",["Bunter Mangold"],"European","Vegetable","kg",7.5,"Switzerland",["Spring","Summer","Autumn"], "Swiss chard",19,1.8,3.7,0.2,"Refrigerated"),
("Cavolo Nero",["Schwarzkohl","Palmkohl"],"European","Vegetable","kg",8.0,"Italy/Switzerland",["Autumn","Winter"], "Kale",49,4.3,8.8,0.9,"Refrigerated"),
("Pointed Cabbage",["Spitzkohl"],"European","Vegetable","kg",3.2,"Switzerland",["Spring","Summer"], "White cabbage",27,1.4,6.0,0.1,"Refrigerated"),
("Chinese Cabbage",["Chinakohl"],"Asian","Vegetable","kg",3.0,"Switzerland",["Autumn","Winter"], "Pointed cabbage",16,1.2,3.2,0.2,"Refrigerated"),
("Pak Choi",["Bok Choy"],"Asian","Vegetable","kg",6.5,"Switzerland",[], "Chinese cabbage",13,1.5,2.2,0.2,"Refrigerated"),
("Kohlrabi Fresh",["Kohlrabi ganz"],"European","Vegetable","kg",3.5,"Switzerland",["Spring","Summer","Autumn"], "Turnip",27,1.7,6.2,0.1,"Refrigerated"),
("Turnip",["Weisse Rübe","Navet"],"European","Vegetable","kg",3.8,"Switzerland",["Autumn","Winter"], "Kohlrabi",28,0.9,6.4,0.1,"Refrigerated"),
("Swede",["Steckrübe","Kohlrübe"],"European","Vegetable","kg",3.0,"Switzerland",["Autumn","Winter"], "Turnip",37,1.1,8.6,0.2,"Refrigerated"),
("Radicchio",["Radicchio rosso"],"European","Vegetable","kg",7.0,"Italy",["Autumn","Winter"], "Chicory",23,1.4,4.5,0.2,"Refrigerated"),
("Chicory",["Chicorée","Brüsseler"],"European","Vegetable","kg",5.5,"Belgium/Switzerland",["Autumn","Winter"], "Radicchio",17,0.9,3.3,0.1,"Refrigerated"),
("Puntarelle",["Puntarelle"],"European","Vegetable","kg",9.0,"Italy",["Winter","Spring"], "Chicory",23,1.5,4.0,0.2,"Refrigerated"),
("Frisée",["Friséesalat"],"European","Vegetable","kg",6.0,"Switzerland",[], "Escarole",18,1.3,3.4,0.2,"Refrigerated"),
("Escarole",["Endivie glatt"],"European","Vegetable","kg",5.0,"Switzerland",["Autumn","Winter"], "Frisée",17,1.2,3.2,0.2,"Refrigerated"),
("Lamb's Lettuce",["Nüsslisalat","Feldsalat"],"European","Vegetable","kg",14.0,"Switzerland",["Autumn","Winter"], "Baby spinach",21,2.0,3.6,0.4,"Refrigerated"),
("Watercress",["Brunnenkresse"],"European","Vegetable","kg",12.0,"Switzerland",["Spring"], "Arugula",11,2.3,1.3,0.1,"Refrigerated"),
("Purslane",["Portulak"],"European","Vegetable","kg",11.0,"Switzerland",["Summer"], "Watercress",20,2.0,3.4,0.4,"Refrigerated"),
("Wild Garlic",["Bärlauch"],"European","Herbs","kg",16.0,"Switzerland",["Spring"], "Garlic + chives",35,3.0,6.0,0.3,"Refrigerated"),
("Green Kohlrabi Leaves",["Kohlrabiblätter"],"European","Vegetable","kg",4.0,"Switzerland",["Spring","Summer"], "Kale",30,2.8,5.5,0.4,"Refrigerated"),
("Salsify Fresh",["Schwarzwurzel frisch"],"European","Vegetable","kg",7.0,"Switzerland",["Winter"], "Parsnip",82,3.3,18.6,0.2,"Refrigerated"),
("Cardoon",["Kardone"],"European","Vegetable","kg",9.0,"Geneva, Switzerland",["Winter"], "Artichoke",17,0.7,4.1,0.1,"Refrigerated"),
("Fennel Bulb",["Fenchelknolle"],"European","Vegetable","kg",4.2,"Switzerland/Italy",["Autumn","Winter"], "Celery",31,1.2,7.3,0.2,"Refrigerated"),
("Romanesco Fresh",["Romanesco frisch"],"European","Vegetable","kg",5.5,"Switzerland",["Summer","Autumn"], "Cauliflower",30,2.5,4.5,0.3,"Refrigerated"),
("Green Zucchini Flowers",["Zucchiniblüten"],"European","Vegetable","pc",1.2,"Switzerland/Italy",["Summer"], None,16,1.0,3.0,0.1,"Refrigerated"),
("Padron Peppers",["Pimientos de Padrón"],"European","Vegetable","kg",12.0,"Spain",["Summer"], "Shishito peppers",27,1.3,5.5,0.4,"Refrigerated"),
("Heirloom Tomatoes",["Ochsenherz","Coeur de Boeuf"],"European","Vegetable","kg",8.5,"Switzerland",["Summer"], "Tomato",20,0.9,3.9,0.2,"Room Temperature"),
("San Marzano Tomatoes",["San Marzano"],"European","Vegetable","kg",6.5,"Italy",["Summer"], "Plum tomatoes",22,1.0,4.5,0.2,"Room Temperature"),
("Datterini Tomatoes",["Datteltomaten"],"European","Vegetable","kg",9.0,"Italy",["Summer"], "Cherry tomatoes",25,1.0,5.0,0.3,"Room Temperature"),
("Green Tomatoes",["Grüne Tomaten"],"European","Vegetable","kg",5.5,"Switzerland",["Summer","Autumn"], "Tomatillo",23,1.2,5.1,0.2,"Room Temperature"),
("White Asparagus Fresh",["Spargel weiss frisch"],"European","Vegetable","kg",14.0,"Switzerland/Germany",["Spring"], "Green asparagus",21,2.0,4.0,0.1,"Refrigerated"),
("Ramp Bulbs",["Bärlauchzwiebeln"],"European","Vegetable","kg",18.0,"Switzerland",["Spring"], "Spring onion",40,2.0,8.0,0.2,"Refrigerated"),
("Samphire",["Queller","Meeresspargel"],"European","Vegetable","kg",22.0,"France",["Summer"], "Green asparagus",18,1.8,2.5,0.3,"Refrigerated"),
("Baby Gem Lettuce",["Baby Gem","Sucrine"],"European","Vegetable","kg",8.0,"Switzerland/Spain",[], "Romaine",17,1.2,3.3,0.2,"Refrigerated"),
("Tatsoi",["Tatsoi"],"Asian","Vegetable","kg",10.0,"Switzerland",[], "Pak choi",22,2.2,3.9,0.3,"Refrigerated"),
("Mizuna",["Mizuna"],"Asian","Vegetable","kg",11.0,"Switzerland",[], "Arugula",21,2.0,3.5,0.3,"Refrigerated"),
("Shiso Leaves",["Shiso","Perilla"],"Asian","Herbs","kg",45.0,"Netherlands",[], "Thai basil",37,3.9,7.0,0.5,"Refrigerated"),
("Lotus Root",["Lotuswurzel"],"Asian","Vegetable","kg",9.0,"China",[], "Water chestnut",74,2.6,17.2,0.1,"Refrigerated"),
("Bamboo Shoots Fresh",["Bambussprossen"],"Asian","Vegetable","kg",8.0,"China",[], "Lotus root",27,2.6,5.2,0.3,"Refrigerated"),
("Galangal",["Galgant"],"Asian","Spices & Seasonings","kg",16.0,"Thailand",[], "Ginger",71,1.0,15.0,0.7,"Refrigerated"),
("Fresh Turmeric",["Kurkuma frisch"],"Asian","Spices & Seasonings","kg",14.0,"Peru/India",[], "Ground turmeric",312,9.7,67.0,3.3,"Refrigerated"),
("Kaffir Lime Leaves",["Kaffirlimettenblätter"],"Asian","Herbs","kg",38.0,"Thailand",[], "Lime zest",75,5.0,15.0,1.0,"Freezer"),
("Curry Leaves",["Curryblätter"],"Asian","Herbs","kg",32.0,"India",[], "Kaffir lime leaves",108,6.0,18.7,1.0,"Refrigerated"),
]
