ITEMS = [
# --- Cheese (Swiss AOP + international, beyond what exists) ---
("Emmentaler AOP Cave-Aged",["Emmentaler höhlengereift"],"European","Dairy","kg",26.0,"Emmental, Switzerland",[], "Emmentaler",403,29.0,0.5,31.5,"Refrigerated"),
("L'Etivaz AOP",["L'Etivaz"],"European","Dairy","kg",34.0,"Vaud Alps, Switzerland",[], "Gruyère",410,28.5,0.5,33.0,"Refrigerated"),
("Berner Alpkäse AOP",["Berner Alpkäse"],"European","Dairy","kg",28.0,"Bernese Oberland, Switzerland",[], "L'Etivaz AOP",400,28.0,0.5,32.0,"Refrigerated"),
("Berner Hobelkäse AOP",["Hobelkäse"],"European","Dairy","kg",36.0,"Bernese Oberland, Switzerland",[], "Sbrinz",420,31.0,0.5,33.5,"Refrigerated"),
("Vacherin Mont-d'Or AOP",["Mont d'Or"],"European","Dairy","kg",30.0,"Vaud, Switzerland",["Autumn","Winter"], "Vacherin Fribourgeois",330,20.0,1.0,27.5,"Refrigerated"),
("Glarner Schabziger",["Schabziger","Zigerklee"],"European","Dairy","kg",16.0,"Glarus, Switzerland",[], None,130,32.0,2.0,0.5,"Refrigerated"),
("Belper Knolle",["Belper Knolle"],"European","Dairy","pc",9.0,"Belp, Bern, Switzerland",[], "Sbrinz",420,28.0,1.0,34.0,"Refrigerated"),
("Formaggini Ticinesi",["Formaggini"],"European","Dairy","kg",22.0,"Ticino, Switzerland",[], "Fresh goat cheese",250,16.0,1.5,20.0,"Refrigerated"),
("Tomme Vaudoise",["Tomme Vaudoise"],"European","Dairy","kg",24.0,"Vaud, Switzerland",[], "Camembert",300,18.0,1.0,25.0,"Refrigerated"),
("Fresh Goat Cheese",["Ziegenfrischkäse","Chèvre frais"],"European","Dairy","kg",18.0,"Switzerland/France",[], "Fresh cheese",268,18.5,2.5,21.0,"Refrigerated"),
("Aged Goat Cheese",["Ziegenkäse gereift","Crottin"],"European","Dairy","kg",32.0,"France",[], "Fresh goat cheese",364,21.5,2.0,30.0,"Refrigerated"),
("Sheep Cheese",["Schafkäse gereift"],"European","Dairy","kg",26.0,"Switzerland",[], "Pecorino",370,22.0,1.0,31.0,"Refrigerated"),
("Pecorino Romano",["Pecorino"],"European","Dairy","kg",24.0,"Italy",[], "Parmesan",387,28.5,0.2,29.5,"Refrigerated"),
("Parmigiano Reggiano 24m",["Parmesan 24 Monate"],"European","Dairy","kg",28.0,"Italy",[], "Grana Padano",392,32.4,0.0,29.7,"Refrigerated"),
("Taleggio DOP",["Taleggio"],"European","Dairy","kg",22.0,"Lombardy, Italy",[], "Reblochon",315,19.0,0.5,26.5,"Refrigerated"),
("Fontina DOP",["Fontina"],"European","Dairy","kg",25.0,"Aosta, Italy",[], "Raclette cheese",343,25.0,1.0,27.0,"Refrigerated"),
("Provolone",["Provolone"],"European","Dairy","kg",18.0,"Italy",[], "Fontina",351,25.5,2.0,27.0,"Refrigerated"),
("Scamorza Affumicata",["Scamorza geräuchert"],"European","Dairy","kg",16.0,"Italy",[], "Provolone",334,25.0,1.0,26.0,"Refrigerated"),
("Burrata",["Burrata"],"European","Dairy","kg",18.0,"Puglia, Italy",[], "Mozzarella",330,13.0,2.0,30.0,"Refrigerated"),
("Stracciatella Cheese",["Stracciatella di burrata"],"European","Dairy","kg",20.0,"Puglia, Italy",[], "Burrata",300,11.0,2.0,28.0,"Refrigerated"),
("Reblochon AOP",["Reblochon"],"European","Dairy","kg",26.0,"Savoie, France",[], "Taleggio",330,20.0,0.5,27.5,"Refrigerated"),
("Comté AOP",["Comté 18 Monate"],"European","Dairy","kg",28.0,"Jura, France",[], "Gruyère",410,28.0,0.5,33.5,"Refrigerated"),
("Roquefort AOP",["Roquefort"],"European","Dairy","kg",32.0,"France",[], "Gorgonzola",369,21.5,2.0,30.5,"Refrigerated"),
("Époisses AOP",["Epoisses"],"European","Dairy","kg",38.0,"Burgundy, France",[], "Vacherin Mont-d'Or",300,17.0,0.5,25.5,"Refrigerated"),
("Manchego",["Manchego"],"European","Dairy","kg",26.0,"Spain",[], "Pecorino Romano",390,26.0,0.5,32.0,"Refrigerated"),
("Halloumi",["Halloumi","Grillkäse"],"European","Dairy","kg",16.0,"Cyprus",[], "Paneer",321,22.0,2.2,25.0,"Refrigerated"),
("Stilton",["Stilton"],"European","Dairy","kg",30.0,"England",[], "Roquefort",393,23.7,0.1,33.0,"Refrigerated"),
("Cheddar Aged",["Cheddar gereift"],"European","Dairy","kg",18.0,"England/Ireland",[], "Appenzeller",403,25.0,1.3,33.0,"Refrigerated"),
# --- Dairy (missing basics) ---
("Buttermilk",["Buttermilch"],"European","Dairy","l",2.2,"Switzerland",[], "Yogurt",37,3.4,4.0,0.6,"Refrigerated"),
("Kefir",["Kefir"],"European","Dairy","l",3.8,"Switzerland",[], "Buttermilk",55,3.3,4.5,3.0,"Refrigerated"),
("Greek Yogurt",["griechischer Jogurt"],"European","Dairy","kg",5.5,"Greece/Switzerland",[], "Yogurt",97,9.0,3.9,5.0,"Refrigerated"),
("Skyr",["Skyr"],"European","Dairy","kg",6.0,"Iceland/Switzerland",[], "Greek yogurt",63,11.0,4.0,0.2,"Refrigerated"),
("Clarified Butter",["Butterschmalz","Ghee"],"Universal","Dairy","kg",14.0,"Switzerland",[], "Butter",897,0.0,0.0,99.6,"Room Temperature"),
("Double Cream",["Doppelrahm","Crème double"],"European","Dairy","l",12.0,"Gruyère, Switzerland",[], "Whipping cream",450,2.0,3.0,48.0,"Refrigerated"),
("Condensed Milk",["Kondensmilch gezuckert"],"Universal","Dairy","kg",5.0,"Switzerland",[], "Evaporated milk",321,7.9,54.4,8.7,"Dry Storage"),
("Evaporated Milk",["Kondensmilch ungezuckert"],"Universal","Dairy","l",3.5,"Switzerland",[], "Condensed milk",134,6.8,10.0,7.5,"Dry Storage"),
("Milk Powder",["Milchpulver"],"Universal","Dairy","kg",9.0,"Switzerland",[], None,496,26.3,38.4,26.7,"Dry Storage"),
("Goat Milk",["Ziegenmilch"],"European","Dairy","l",4.5,"Switzerland",[], "Whole milk",69,3.6,4.5,4.1,"Refrigerated"),
("Sour Cream",["Sauerrahm"],"European","Dairy","kg",6.0,"Switzerland",[], "Crème fraîche",193,2.8,3.5,19.0,"Refrigerated"),
# --- Dairy alternatives ---
("Oat Milk",["Hafermilch","Haferdrink"],"Universal","Dairy Alternatives","l",2.5,"Sweden/Switzerland",[], "Soy milk",46,0.8,7.0,1.4,"Dry Storage"),
("Almond Milk",["Mandeldrink"],"Universal","Dairy Alternatives","l",2.8,"Italy/Spain",[], "Oat milk",24,0.5,3.0,1.1,"Dry Storage"),
("Coconut Cream",["Kokoscreme"],"Asian","Dairy Alternatives","l",5.5,"Thailand/Sri Lanka",[], "Coconut milk",330,3.3,6.7,34.7,"Dry Storage"),
("Vegan Butter",["vegane Butter","Margarine pflanzlich"],"Universal","Dairy Alternatives","kg",8.0,"Switzerland",[], "Margarine",717,0.2,0.5,79.0,"Refrigerated"),
("Cashew Cream",["Cashewcreme"],"Universal","Dairy Alternatives","kg",14.0,"Vietnam (nuts)",[], "Coconut cream",320,10.0,18.0,24.0,"Refrigerated"),
("Silken Tofu",["Seidentofu"],"Asian","Dairy Alternatives","kg",6.5,"Switzerland/France",[], "Firm tofu",55,4.8,2.0,2.7,"Refrigerated"),
("Firm Tofu",["Tofu fest"],"Asian","Dairy Alternatives","kg",7.0,"Switzerland/France",[], "Silken tofu",144,15.5,2.5,8.0,"Refrigerated"),
("Smoked Tofu",["Räuchertofu"],"Asian","Dairy Alternatives","kg",9.0,"Switzerland",[], "Firm tofu",150,16.0,2.0,9.0,"Refrigerated"),
("Tempeh",["Tempeh"],"Asian","Dairy Alternatives","kg",11.0,"Indonesia/Switzerland",[], "Firm tofu",192,20.3,7.6,10.8,"Refrigerated"),
("Seitan",["Seitan"],"Asian","Dairy Alternatives","kg",10.0,"Switzerland",[], "Tempeh",144,25.0,7.0,2.0,"Refrigerated"),
# --- Spices (specific, pro pantry) ---
("Vanilla Beans",["Vanilleschoten","Bourbon-Vanille"],"Universal","Spices & Seasonings","kg",420.0,"Madagascar",[], "Vanilla paste",288,1.2,55.0,0.1,"Dry Storage"),
("Vanilla Paste",["Vanillepaste"],"Universal","Spices & Seasonings","kg",95.0,"Madagascar",[], "Vanilla beans",290,0.5,60.0,0.1,"Dry Storage"),
("Saffron",["Safranfäden"],"Universal","Spices & Seasonings","kg",4200.0,"Iran/Spain",[], None,310,11.4,65.4,5.9,"Dry Storage"),
("Sumac",["Sumach"],"Universal","Spices & Seasonings","kg",14.0,"Turkey",[], "Lemon zest",330,3.0,60.0,10.0,"Dry Storage"),
("Za'atar",["Zatar-Gewürzmischung"],"Universal","Spices & Seasonings","kg",16.0,"Lebanon",[], "Dried thyme + sumac",280,10.0,45.0,10.0,"Dry Storage"),
("Ras el Hanout",["Ras el-Hanout"],"Universal","Spices & Seasonings","kg",22.0,"Morocco",[], "Garam masala",320,10.0,50.0,10.0,"Dry Storage"),
("Baharat",["Baharat"],"Universal","Spices & Seasonings","kg",18.0,"Middle East",[], "Ras el Hanout",330,11.0,52.0,11.0,"Dry Storage"),
("Dukkah",["Dukkah"],"Universal","Spices & Seasonings","kg",24.0,"Egypt",[], "Za'atar",480,17.0,25.0,38.0,"Dry Storage"),
("Piment d'Espelette",["Espelette-Pfeffer"],"European","Spices & Seasonings","kg",90.0,"Basque Country, France",[], "Smoked paprika",280,10.0,50.0,8.0,"Dry Storage"),
("Urfa Biber",["Urfa-Chiliflocken"],"Universal","Spices & Seasonings","kg",22.0,"Turkey",[], "Aleppo pepper",320,11.0,55.0,10.0,"Dry Storage"),
("Aleppo Pepper",["Pul Biber"],"Universal","Spices & Seasonings","kg",20.0,"Turkey/Syria",[], "Urfa biber",320,11.0,55.0,10.0,"Dry Storage"),
("Sichuan Pepper",["Szechuanpfeffer"],"Asian","Spices & Seasonings","kg",38.0,"China",[], "Black pepper",300,10.0,55.0,8.0,"Dry Storage"),
("Long Pepper",["Langer Pfeffer"],"Asian","Spices & Seasonings","kg",45.0,"Indonesia",[], "Black pepper",300,10.0,55.0,8.0,"Dry Storage"),
("Grains of Paradise",["Paradieskörner"],"Universal","Spices & Seasonings","kg",55.0,"West Africa",[], "Black pepper + cardamom",300,10.0,55.0,8.0,"Dry Storage"),
("Tonka Beans",["Tonkabohnen"],"Universal","Spices & Seasonings","kg",85.0,"Venezuela/Brazil",[], "Vanilla beans",350,5.0,60.0,10.0,"Dry Storage"),
("Mace",["Muskatblüte","Macis"],"Universal","Spices & Seasonings","kg",48.0,"Indonesia",[], "Nutmeg",475,6.7,50.5,32.4,"Dry Storage"),
("Ajwain",["Ajwain","Königskümmel"],"Asian","Spices & Seasonings","kg",16.0,"India",[], "Thyme + cumin",305,16.0,43.0,25.0,"Dry Storage"),
("Nigella Seeds",["Schwarzkümmel"],"Universal","Spices & Seasonings","kg",12.0,"India/Egypt",[], "Black sesame",345,16.0,44.0,15.0,"Dry Storage"),
("Fenugreek",["Bockshornklee"],"Asian","Spices & Seasonings","kg",8.0,"India",[], None,323,23.0,58.4,6.4,"Dry Storage"),
("Asafoetida",["Asant","Hing"],"Asian","Spices & Seasonings","kg",26.0,"India/Iran",[], "Garlic + onion powder",297,4.0,68.0,1.1,"Dry Storage"),
("Amchur",["Mangopulver"],"Asian","Spices & Seasonings","kg",18.0,"India",[], "Lime juice",320,2.5,76.0,1.0,"Dry Storage"),
("Wasabi Paste",["Wasabi"],"Asian","Spices & Seasonings","kg",32.0,"Japan (mostly horseradish blend)",[], "Horseradish",110,2.0,24.0,0.6,"Refrigerated"),
("Yuzu Kosho",["Yuzu Kosho"],"Asian","Spices & Seasonings","kg",65.0,"Japan",[], "Wasabi paste",90,2.0,18.0,0.5,"Refrigerated"),
("Shichimi Togarashi",["Shichimi"],"Asian","Spices & Seasonings","kg",42.0,"Japan",[], "Chili flakes + sesame",350,12.0,50.0,15.0,"Dry Storage"),
("Furikake",["Furikake"],"Asian","Spices & Seasonings","kg",38.0,"Japan",[], "Shichimi togarashi",380,18.0,40.0,18.0,"Dry Storage"),
("Curry Powder Madras",["Currypulver Madras"],"Asian","Spices & Seasonings","kg",12.0,"India",[], "Garam masala",325,12.7,58.2,13.8,"Dry Storage"),
("Tandoori Masala",["Tandoori-Gewürz"],"Asian","Spices & Seasonings","kg",14.0,"India",[], "Curry powder Madras",320,12.0,55.0,12.0,"Dry Storage"),
("Chinese Five Spice",["Fünf-Gewürze-Pulver"],"Asian","Spices & Seasonings","kg",16.0,"China",[], "Garam masala",340,10.0,60.0,10.0,"Dry Storage"),
("Herbes de Provence",["Kräuter der Provence"],"European","Spices & Seasonings","kg",14.0,"France",[], "Dried thyme + rosemary",280,9.0,50.0,7.0,"Dry Storage"),
("Juniper Berries",["Wacholderbeeren"],"European","Spices & Seasonings","kg",16.0,"Balkans",[], None,310,4.0,65.0,8.0,"Dry Storage"),
("Caraway Seeds",["Kümmel ganz"],"European","Spices & Seasonings","kg",8.0,"Netherlands/Poland",[], "Fennel seeds",333,19.8,49.9,14.6,"Dry Storage"),
("Dill Seeds",["Dillsamen"],"European","Spices & Seasonings","kg",10.0,"India",[], "Caraway seeds",305,16.0,55.2,14.5,"Dry Storage"),
("Celery Salt",["Selleriesalz"],"European","Spices & Seasonings","kg",6.0,"Switzerland",[], "Salt + celery seeds",120,4.0,20.0,3.0,"Dry Storage"),
("Fleur de Sel",["Fleur de Sel"],"European","Spices & Seasonings","kg",18.0,"Guérande, France",[], "Sea salt",0,0.0,0.0,0.0,"Dry Storage"),
("Smoked Salt",["Rauchsalz"],"Universal","Spices & Seasonings","kg",14.0,"Denmark/Wales",[], "Fleur de sel + smoked paprika",0,0.0,0.0,0.0,"Dry Storage"),
("Pink Peppercorns",["rosa Beeren"],"Universal","Spices & Seasonings","kg",28.0,"Madagascar/Brazil",[], "Black pepper",300,10.0,55.0,10.0,"Dry Storage"),
("White Peppercorns",["weisser Pfeffer ganz"],"Universal","Spices & Seasonings","kg",22.0,"Vietnam/Indonesia",[], "Black pepper",296,10.4,68.6,2.1,"Dry Storage"),
]
