ITEMS = [
# --- Dried pasta shapes ---
("Bucatini",["Bucatini"],"European","Dry Goods & Pantry","kg",3.5,"Italy",[], "Spaghetti",371,13.0,74.7,1.5,"Dry Storage"),
("Orecchiette",["Orecchiette"],"European","Dry Goods & Pantry","kg",3.8,"Puglia, Italy",[], "Penne",371,13.0,74.7,1.5,"Dry Storage"),
("Paccheri",["Paccheri"],"European","Dry Goods & Pantry","kg",4.5,"Campania, Italy",[], "Rigatoni",371,13.0,74.7,1.5,"Dry Storage"),
("Trofie",["Trofie"],"European","Dry Goods & Pantry","kg",4.2,"Liguria, Italy",[], "Fusilli",371,13.0,74.7,1.5,"Dry Storage"),
("Linguine",["Linguine"],"European","Dry Goods & Pantry","kg",3.2,"Italy",[], "Spaghetti",371,13.0,74.7,1.5,"Dry Storage"),
("Pappardelle",["Pappardelle"],"European","Dry Goods & Pantry","kg",4.8,"Tuscany, Italy",[], "Tagliatelle",371,13.0,74.7,1.5,"Dry Storage"),
("Conchiglie",["Conchiglie","Muschelnudeln"],"European","Dry Goods & Pantry","kg",3.4,"Italy",[], "Penne",371,13.0,74.7,1.5,"Dry Storage"),
("Farfalle",["Farfalle"],"European","Dry Goods & Pantry","kg",3.4,"Italy",[], "Fusilli",371,13.0,74.7,1.5,"Dry Storage"),
("Orzo",["Orzo","Risoni"],"European","Dry Goods & Pantry","kg",3.6,"Italy/Greece",[], "Israeli couscous",371,13.0,74.7,1.5,"Dry Storage"),
("Gnocchetti Sardi",["Malloreddus"],"European","Dry Goods & Pantry","kg",4.0,"Sardinia, Italy",[], "Orecchiette",371,13.0,74.7,1.5,"Dry Storage"),
("Cannelloni Tubes",["Cannelloni-Röhren"],"European","Dry Goods & Pantry","kg",5.0,"Italy",[], "Lasagne sheets",370,13.0,74.0,1.5,"Dry Storage"),
("Lasagne Sheets",["Lasagneblätter"],"European","Dry Goods & Pantry","kg",3.8,"Italy",[], "Cannelloni tubes",370,13.0,74.0,1.5,"Dry Storage"),
("Egg Tagliatelle Dry",["Eiernudeln"],"European","Dry Goods & Pantry","kg",4.5,"Italy/Switzerland",[], "Tagliatelle",380,14.0,70.0,3.5,"Dry Storage"),
("Spätzli Dry",["Spätzli getrocknet"],"European","Dry Goods & Pantry","kg",4.2,"Switzerland",[], "Egg tagliatelle dry",380,14.0,70.0,3.5,"Dry Storage"),
("Knöpfli Fresh",["Knöpfli frisch"],"European","Dry Goods & Pantry","kg",5.5,"Switzerland",[], "Spätzli dry",190,7.0,35.0,2.5,"Refrigerated"),
("Pizzoccheri",["Pizzoccheri"],"European","Dry Goods & Pantry","kg",6.0,"Valtellina, Italy",[], "Buckwheat pasta",350,12.0,70.0,2.0,"Dry Storage"),
# --- Cheese round 2 ---
("Robiola",["Robiola"],"European","Dairy","kg",24.0,"Piedmont, Italy",[], "Fresh goat cheese",300,17.0,2.0,25.0,"Refrigerated"),
("Asiago",["Asiago"],"European","Dairy","kg",19.0,"Veneto, Italy",[], "Fontina",380,26.0,1.5,30.0,"Refrigerated"),
("Caciocavallo",["Caciocavallo"],"European","Dairy","kg",20.0,"Southern Italy",[], "Provolone",350,25.0,1.5,27.5,"Refrigerated"),
("Montasio",["Montasio"],"European","Dairy","kg",21.0,"Friuli, Italy",[], "Asiago",390,26.5,1.0,31.0,"Refrigerated"),
("Ossau-Iraty",["Ossau-Iraty"],"European","Dairy","kg",28.0,"Basque Country, France",[], "Manchego",400,26.0,0.5,33.0,"Refrigerated"),
("Morbier",["Morbier"],"European","Dairy","kg",22.0,"Jura, France",[], "Raclette cheese",340,23.5,0.5,28.0,"Refrigerated"),
("Munster AOP",["Munster"],"European","Dairy","kg",24.0,"Alsace, France",[], "Époisses",330,21.0,1.0,27.0,"Refrigerated"),
("Chabichou",["Chabichou du Poitou"],"European","Dairy","kg",34.0,"Poitou, France",[], "Aged goat cheese",340,20.0,2.0,28.0,"Refrigerated"),
("Mimolette",["Mimolette"],"European","Dairy","kg",26.0,"Lille, France",[], "Aged gouda",400,26.0,0.5,33.0,"Refrigerated"),
("Aged Gouda",["Gouda gereift 24M"],"European","Dairy","kg",20.0,"Netherlands",[], "Mimolette",410,27.0,1.5,33.5,"Refrigerated"),
("Queso Fresco",["Queso Fresco"],"Universal","Dairy","kg",14.0,"Spain/Mexico",[], "Feta",145,12.0,3.0,10.0,"Refrigerated"),
("Labneh",["Labneh"],"Universal","Dairy","kg",10.0,"Lebanon",[], "Greek yogurt",180,7.5,4.5,15.0,"Refrigerated"),
("Ayran",["Ayran"],"Universal","Dairy","l",2.8,"Turkey",[], "Buttermilk",36,1.7,2.5,1.8,"Refrigerated"),
# --- Seafood round 2 ---
("Arctic Char Whole",["Saibling ganz"],"European","Seafood","kg",22.0,"Switzerland/Iceland",[], "Whole trout",130,20.5,0.0,5.5,"Refrigerated"),
("Sturgeon",["Stör"],"European","Seafood","kg",30.0,"Switzerland (farmed)",[], "Monkfish",135,17.0,0.0,7.0,"Refrigerated"),
("Catfish Fillet",["Welsfilet","Zeller"],"European","Seafood","kg",18.0,"Switzerland/Hungary",[], "Pangasius fillet",105,16.5,0.0,4.5,"Refrigerated"),
("Carp",["Karpfen"],"European","Seafood","kg",12.0,"Czech Republic/Hungary",["Winter"], "Catfish fillet",127,17.8,0.0,5.6,"Refrigerated"),
("Herring",["Hering","Matjes"],"European","Seafood","kg",11.0,"North Sea",[], "Mackerel",158,18.0,0.0,9.0,"Refrigerated"),
("Haddock",["Schellfisch"],"European","Seafood","kg",19.0,"North Atlantic",[], "Cod loin",74,16.3,0.0,0.5,"Refrigerated"),
("Hake",["Seehecht"],"European","Seafood","kg",16.0,"Atlantic",[], "Haddock",78,17.0,0.0,1.0,"Freezer"),
("Sea Urchin",["Seeigel"],"European","Seafood","kg",90.0,"Mediterranean/Galicia",["Winter"], None,120,13.0,3.0,5.0,"Refrigerated"),
("Razor Clams",["Schwertmuscheln"],"European","Seafood","kg",22.0,"Scotland/Spain",[], "Clams",85,14.0,3.0,1.0,"Refrigerated"),
("Whelks",["Wellhornschnecken"],"European","Seafood","kg",14.0,"France",[], "Snails",90,16.0,3.0,0.8,"Refrigerated"),
("Bottarga",["Bottarga"],"European","Seafood","kg",180.0,"Sardinia, Italy",[], "Salted anchovies",390,43.0,1.0,23.0,"Refrigerated"),
("Surimi",["Surimi"],"Asian","Seafood","kg",8.0,"Japan/Thailand",[], "Crab meat",99,7.6,15.0,0.9,"Refrigerated"),
# --- Spices / dried herbs round 2 ---
("Dried Oregano",["Oregano getrocknet"],"European","Spices & Seasonings","kg",9.0,"Greece/Turkey",[], "Dried marjoram",265,9.0,68.9,4.3,"Dry Storage"),
("Dried Marjoram",["Majoran getrocknet"],"European","Spices & Seasonings","kg",12.0,"Egypt",[], "Dried oregano",271,12.7,60.6,7.0,"Dry Storage"),
("Dried Tarragon",["Estragon getrocknet"],"European","Spices & Seasonings","kg",22.0,"France",[], "Dried chervil",295,22.8,50.2,7.2,"Dry Storage"),
("Dried Dill",["Dill getrocknet"],"European","Spices & Seasonings","kg",16.0,"Egypt",[], "Dried tarragon",253,20.0,55.8,4.4,"Dry Storage"),
("Dried Mint",["Minze getrocknet","Nane"],"Universal","Spices & Seasonings","kg",14.0,"Turkey/Egypt",[], "Fresh mint",285,19.9,52.0,6.0,"Dry Storage"),
("Dried Sage",["Salbei getrocknet"],"European","Spices & Seasonings","kg",15.0,"Albania/Turkey",[], "Fresh sage",315,10.6,60.7,12.7,"Dry Storage"),
("Dried Rosemary",["Rosmarin getrocknet"],"European","Spices & Seasonings","kg",10.0,"Morocco/Spain",[], "Fresh rosemary",331,4.9,64.1,15.2,"Dry Storage"),
("Onion Powder",["Zwiebelpulver"],"Universal","Spices & Seasonings","kg",7.0,"EU/India",[], "Garlic powder",341,10.4,79.1,1.0,"Dry Storage"),
("Garlic Powder",["Knoblauchpulver"],"Universal","Spices & Seasonings","kg",8.0,"China/EU",[], "Onion powder",331,16.6,72.7,0.7,"Dry Storage"),
("Ginger Powder",["Ingwerpulver"],"Asian","Spices & Seasonings","kg",9.5,"India/China",[], "Fresh ginger",335,9.0,71.6,4.2,"Dry Storage"),
("Chili Powder",["Chilipulver"],"Universal","Spices & Seasonings","kg",10.0,"India/Spain",[], "Cayenne",282,13.5,49.7,14.3,"Dry Storage"),
("Chipotle Dried",["Chipotle getrocknet"],"Universal","Spices & Seasonings","kg",26.0,"Mexico",[], "Smoked paprika",280,12.0,60.0,7.0,"Dry Storage"),
("Ancho Chili",["Ancho-Chili getrocknet"],"Universal","Spices & Seasonings","kg",22.0,"Mexico",[], "Chipotle dried",280,11.0,60.0,8.0,"Dry Storage"),
("Bird's Eye Chili",["Thai-Chili frisch"],"Asian","Vegetable","kg",14.0,"Thailand",[], "Red chili",40,1.9,8.8,0.4,"Refrigerated"),
("Habanero",["Habanero frisch"],"Universal","Vegetable","kg",18.0,"Mexico/Netherlands",[], "Bird's eye chili",40,1.9,8.8,0.4,"Refrigerated"),
("Jalapeño Fresh",["Jalapeño frisch"],"Universal","Vegetable","kg",9.0,"Spain/Mexico",[], "Green chili",29,0.9,6.5,0.4,"Refrigerated"),
("Curry Paste Red",["rote Currypaste"],"Asian","Sauces & Condiments","kg",9.5,"Thailand",[], "Curry paste green",120,3.0,15.0,5.0,"Refrigerated"),
("Curry Paste Green",["grüne Currypaste"],"Asian","Sauces & Condiments","kg",9.5,"Thailand",[], "Curry paste red",115,3.0,14.0,5.0,"Refrigerated"),
("Massaman Curry Paste",["Massaman-Currypaste"],"Asian","Sauces & Condiments","kg",11.0,"Thailand",[], "Curry paste red",130,3.5,16.0,5.5,"Refrigerated"),
("Tom Yum Paste",["Tom-Yum-Paste"],"Asian","Sauces & Condiments","kg",10.5,"Thailand",[], "Curry paste red",140,2.5,20.0,5.0,"Refrigerated"),
("Tamarind Paste",["Tamarindenpaste"],"Asian","Sauces & Condiments","kg",8.5,"Thailand/India",[], "Lime juice + date syrup",240,2.8,57.4,0.6,"Dry Storage"),
("Palm Sugar",["Palmzucker"],"Asian","Sweeteners","kg",7.5,"Thailand/Indonesia",[], "Coconut sugar",380,0.5,94.0,0.0,"Dry Storage"),
("Shrimp Paste",["Garnelenpaste","Belacan"],"Asian","Sauces & Condiments","kg",12.0,"Malaysia/Thailand",[], "Fish sauce",155,20.0,4.5,6.0,"Refrigerated"),
("Katsu Curry Roux",["Curry-Roux japanisch"],"Asian","Sauces & Condiments","kg",11.0,"Japan",[], "Curry powder + roux",480,6.0,55.0,26.0,"Dry Storage"),
# --- Swiss & regional specialties ---
("Alpine Herb Mix",["Alpenkräuter-Mischung"],"European","Spices & Seasonings","kg",26.0,"Swiss Alps",[], "Herbes de Provence",280,10.0,50.0,7.0,"Dry Storage"),
("Dried Apple Rings",["Apfelringe getrocknet"],"European","Fruit","kg",12.0,"Thurgau, Switzerland",[], "Dried apricots",243,0.9,64.0,0.3,"Dry Storage"),
("Dried Pears",["Dörrbirnen"],"European","Fruit","kg",13.0,"Switzerland",[], "Dried apple rings",250,1.5,62.0,0.5,"Dry Storage"),
("Birnel",["Birnendicksaft","Birnel"],"European","Sweeteners","kg",11.0,"Switzerland",[], "Date syrup",300,0.5,73.0,0.2,"Dry Storage"),
("Alplermagronen Cheese Mix",["Älplermagronen-Käsemischung"],"European","Dairy","kg",17.0,"Central Switzerland",[], "Reibkäse Hausmischung",395,26.0,1.0,32.0,"Refrigerated"),
("Fondue Moitié-Moitié",["Fonduemischung Moitié-Moitié"],"European","Dairy","kg",24.0,"Fribourg, Switzerland",["Autumn","Winter"], "Fondue mix",380,24.0,1.5,31.0,"Refrigerated"),
("Bircher Base",["Birchermüesli-Basis"],"European","Grains & Flour","kg",6.0,"Switzerland",[], "Rolled oats",370,11.0,65.0,6.0,"Dry Storage"),
("Aromat",["Aromat"],"European","Spices & Seasonings","kg",14.0,"Switzerland",[], "Celery salt",150,10.0,25.0,3.0,"Dry Storage"),
("Sbrinz Rinds",["Sbrinz-Rinden für Bouillon"],"European","Dairy","kg",6.0,"Central Switzerland",[], "Parmesan rinds",400,30.0,0.5,30.0,"Refrigerated"),
("Rösti Prepared",["Rösti fixfertig gekühlt"],"European","Vegetable","kg",4.5,"Switzerland",[], "Charlotte potatoes",150,2.5,20.0,7.0,"Refrigerated"),
("Chäschüechli Base",["Chäschüechli-Teiglinge"],"European","Bakery","pc",0.9,"Switzerland",[], "Shortcrust + cheese",380,10.0,32.0,24.0,"Freezer"),
("Bündner Nusstorte",["Nusstorte"],"European","Bakery","kg",22.0,"Graubünden, Switzerland",[], "Caramel + walnuts + pastry",450,7.0,50.0,25.0,"Room Temperature"),
("Appenzeller Biber",["Biber"],"European","Bakery","kg",18.0,"Appenzell, Switzerland",[], "Läckerli",380,6.0,72.0,8.0,"Dry Storage"),
("Alpine Butter",["Alpbutter"],"European","Dairy","kg",22.0,"Swiss Alps",["Summer"], "Butter",745,0.7,0.6,82.0,"Refrigerated"),
("Raw Milk",["Rohmilch"],"European","Dairy","l",2.2,"Switzerland",[], "Whole milk",66,3.3,4.8,3.8,"Refrigerated"),
("Whey",["Molke"],"European","Dairy","l",1.5,"Switzerland",[], "Buttermilk",25,0.9,4.7,0.2,"Refrigerated"),
("Ziger",["Ziger","Ricotta CH"],"European","Dairy","kg",9.0,"Switzerland",[], "Ricotta",160,11.0,3.5,11.0,"Refrigerated"),
# --- Frozen & convenience (chef-relevant, non-branded) ---
("IQF Raspberries",["Himbeeren IQF"],"Universal","Fruit","kg",8.5,"Serbia/Poland",[], "Raspberry",52,1.2,11.9,0.7,"Freezer"),
("IQF Mango Chunks",["Mango IQF"],"Universal","Fruit","kg",6.0,"India/Peru",[], "Mango",60,0.8,15.0,0.4,"Freezer"),
("Frozen Peas Fine",["Erbsen fein TK"],"European","Vegetable","kg",3.0,"Switzerland/EU",[], "Peas",81,5.4,14.5,0.4,"Freezer"),
("Frozen Spinach Leaf",["Blattspinat TK"],"European","Vegetable","kg",3.2,"EU",[], "Spinach",23,2.9,3.6,0.4,"Freezer"),
("Frozen Artichoke Bottoms",["Artischockenböden TK"],"European","Vegetable","kg",11.5,"Egypt/Spain",[], "Artichoke hearts",47,3.3,10.5,0.2,"Freezer"),
("Frozen Berries Mix",["Beerenmischung TK"],"Universal","Fruit","kg",7.5,"EU",[], "IQF raspberries",50,1.0,11.5,0.5,"Freezer"),
("Puff Pastry Sheets",["Blätterteig ausgerollt"],"European","Bakery","kg",6.5,"Switzerland",[], "Puff pastry block",390,6.0,36.0,25.0,"Refrigerated"),
("Pizza Dough Balls",["Pizzateig-Kugeln"],"European","Bakery","kg",4.5,"Switzerland/Italy",[], "Tipo 00 flour + yeast",250,8.0,48.0,3.0,"Refrigerated"),
("Croissant Dough",["Croissant-Teiglinge"],"European","Bakery","kg",8.0,"France/Switzerland",[], "Puff pastry sheets",420,7.5,45.0,24.0,"Freezer"),
("Vol-au-Vent Shells",["Pastetli"],"European","Bakery","pc",0.65,"Switzerland",[], "Puff pastry",400,6.5,38.0,26.0,"Dry Storage"),
("French Fries 10mm",["Pommes Frites 10mm TK"],"Universal","Vegetable","kg",2.8,"Switzerland/Belgium",[], "Agria potatoes",160,2.5,24.0,5.5,"Freezer"),
("Sweet Potato Fries",["Süsskartoffel-Pommes TK"],"Universal","Vegetable","kg",5.5,"Belgium/USA",[], "French fries 10mm",170,2.0,27.0,6.0,"Freezer"),
("Hash Browns",["Rösti-Ecken TK"],"Universal","Vegetable","kg",4.0,"EU",[], "Rösti prepared",190,2.5,25.0,9.0,"Freezer"),
("Onion Rings Battered",["Zwiebelringe TK"],"Universal","Vegetable","kg",6.5,"EU",[], None,220,3.5,28.0,10.5,"Freezer"),
("Edamame in Pod",["Edamame in Schote TK"],"Asian","Vegetable","kg",6.0,"China/Taiwan",[], "Edamame",121,11.0,9.0,5.0,"Freezer"),
("Gyoza Vegetable",["Gemüse-Gyoza TK"],"Asian","Dry Goods & Pantry","kg",11.0,"Japan/China",[], "Gyoza wrappers + filling",190,6.0,30.0,5.0,"Freezer"),
("Ice Cream Vanilla Pro",["Vanilleglace Gastro"],"Universal","Dairy","l",7.0,"Switzerland",[], "Vanilla beans + cream",207,3.5,23.6,11.0,"Freezer"),
("Sorbet Lemon Pro",["Zitronensorbet Gastro"],"Universal","Fruit","l",8.0,"Switzerland/Italy",[], "Lemon purée + sugar",130,0.2,32.0,0.1,"Freezer"),
# --- Misc pro pantry ---
("Activated Charcoal",["Aktivkohle Lebensmittel"],"Universal","Other","kg",45.0,"EU",[], None,0,0.0,0.0,0.0,"Dry Storage"),
("Gold Leaf Edible",["Blattgold essbar"],"Universal","Other","pc",4.5,"Germany/Italy",[], None,0,0.0,0.0,0.0,"Dry Storage"),
("Dried Rose Petals",["Rosenblätter getrocknet"],"Universal","Other","kg",48.0,"Iran/Morocco",[], "Edible flowers mix",300,8.0,65.0,2.0,"Dry Storage"),
("Popping Candy",["Knallbrause"],"Universal","Other","kg",22.0,"Spain",[], None,390,0.0,97.0,0.0,"Dry Storage"),
("Liquid Nitrogen Note",["Flüssigstickstoff (Hinweisartikel)"],"Universal","Other","l",3.0,"Switzerland (gas supplier)",[], None,0,0.0,0.0,0.0,"Dry Storage"),
("Vacuum Bags 20x30",["Vakuumbeutel 20x30"],"Universal","Other","pc",0.12,"EU",[], None,0,0.0,0.0,0.0,"Dry Storage"),
("Sosa Maltodextrin",["Maltodextrin"],"Universal","Other","kg",14.0,"Spain",[], None,380,0.0,95.0,0.0,"Dry Storage"),
("Citric Acid",["Zitronensäure"],"Universal","Other","kg",6.0,"EU",[], "Lemon juice",0,0.0,0.0,0.0,"Dry Storage"),
("Ascorbic Acid",["Ascorbinsäure","Vitamin C Pulver"],"Universal","Other","kg",12.0,"EU",[], "Citric acid",0,0.0,0.0,0.0,"Dry Storage"),
("Transglutaminase",["Transglutaminase","Meat Glue"],"Universal","Other","kg",65.0,"Japan/EU",[], None,380,90.0,0.0,0.0,"Refrigerated"),
("Kappa Carrageenan",["Kappa-Carrageen"],"Universal","Other","kg",48.0,"Philippines/EU",[], "Agar-agar",250,2.0,80.0,0.0,"Dry Storage"),
("Sodium Alginate",["Natriumalginat"],"Universal","Other","kg",38.0,"EU",[], None,250,2.0,75.0,0.0,"Dry Storage"),
("Calcium Lactate",["Calciumlactat"],"Universal","Other","kg",26.0,"EU",[], None,0,0.0,0.0,0.0,"Dry Storage"),
("Espuma Charger N2O",["Rahmbläser-Kapseln N2O"],"Universal","Other","pc",0.6,"Austria/Hungary",[], None,0,0.0,0.0,0.0,"Dry Storage"),
("Fryer Cleaner Note",["Frittierfett-Filterpulver"],"Universal","Other","kg",12.0,"EU",[], None,0,0.0,0.0,0.0,"Dry Storage"),
# --- Juices & bar basics ---
("Orange Juice Fresh",["Orangensaft frisch gepresst"],"Universal","Other","l",4.5,"Spain",[], "Orange",45,0.7,10.4,0.2,"Refrigerated"),
("Lemon Juice",["Zitronensaft"],"Universal","Other","l",5.0,"Italy/Spain",[], "Lemon",22,0.4,6.9,0.2,"Refrigerated"),
("Lime Juice",["Limettensaft"],"Universal","Other","l",6.5,"Mexico/Brazil",[], "Lemon juice",25,0.4,8.4,0.1,"Refrigerated"),
("Cranberry Juice",["Cranberrysaft"],"Universal","Other","l",3.5,"USA/Canada",[], "Grape juice red",46,0.4,12.2,0.1,"Dry Storage"),
("Tomato Juice",["Tomatensaft"],"Universal","Other","l",2.5,"Italy/Switzerland",[], "Tomato passata",17,0.8,3.5,0.1,"Dry Storage"),
("Coconut Water",["Kokoswasser"],"Asian","Other","l",4.0,"Thailand/Philippines",[], None,19,0.7,3.7,0.2,"Dry Storage"),
("Ginger Beer",["Ginger Beer"],"Universal","Other","l",3.5,"UK/Switzerland",[], "Ginger + sparkling water",38,0.0,9.5,0.0,"Dry Storage"),
("Tonic Water",["Tonic Water"],"Universal","Other","l",2.5,"UK/Switzerland",[], "Sparkling water",34,0.0,8.5,0.0,"Dry Storage"),
("Grenadine",["Grenadine"],"Universal","Sweeteners","l",7.0,"France",[], "Pomegranate molasses + sugar",270,0.0,67.0,0.0,"Dry Storage"),
("Almond Syrup",["Mandelsirup","Orgeat"],"Universal","Sweeteners","l",8.5,"France",[], "Almond butter + sugar syrup",300,0.5,72.0,1.5,"Dry Storage"),
]
