ITEMS = [
# --- Fruit varieties & specialty fruit ---
("Gala Apple",["Apfel Gala"],"European","Fruit","kg",3.2,"Switzerland",["Autumn","Winter"], "Braeburn apple",52,0.3,14.0,0.2,"Refrigerated"),
("Braeburn Apple",["Apfel Braeburn"],"European","Fruit","kg",3.2,"Switzerland",["Autumn","Winter"], "Gala apple",52,0.3,14.0,0.2,"Refrigerated"),
("Boskoop Apple",["Apfel Boskoop"],"European","Fruit","kg",3.5,"Switzerland",["Autumn","Winter"], "Braeburn apple",50,0.3,13.5,0.2,"Refrigerated"),
("Granny Smith Apple",["Apfel Granny Smith"],"European","Fruit","kg",3.4,"Switzerland/Italy",["Autumn","Winter"], "Boskoop apple",54,0.3,14.5,0.2,"Refrigerated"),
("Williams Pear",["Williamsbirne"],"European","Fruit","kg",4.0,"Switzerland",["Autumn"], "Conference pear",57,0.4,15.2,0.1,"Refrigerated"),
("Conference Pear",["Birne Conference"],"European","Fruit","kg",3.8,"Switzerland",["Autumn","Winter"], "Williams pear",57,0.4,15.2,0.1,"Refrigerated"),
("Quince",["Quitte"],"European","Fruit","kg",5.0,"Switzerland",["Autumn"], "Apple",57,0.4,15.3,0.1,"Refrigerated"),
("Mirabelle Plum",["Mirabellen"],"European","Fruit","kg",7.0,"France",["Summer"], "Plum",63,0.7,15.5,0.2,"Refrigerated"),
("Greengage",["Reineclauden"],"European","Fruit","kg",6.5,"France/Switzerland",["Summer"], "Plum",55,0.8,13.0,0.1,"Refrigerated"),
("Damson Plum",["Zwetschge Fellenberg"],"European","Fruit","kg",4.2,"Switzerland",["Autumn"], "Plum",47,0.7,11.0,0.2,"Refrigerated"),
("Apricot Valais",["Walliser Aprikosen"],"European","Fruit","kg",7.5,"Valais, Switzerland",["Summer"], "Apricot",48,1.4,11.0,0.4,"Refrigerated"),
("White Peach",["Weisser Pfirsich"],"European","Fruit","kg",6.0,"Italy/France",["Summer"], "Peach",39,0.9,9.5,0.3,"Refrigerated"),
("Flat Peach",["Plattpfirsich","Saturnpfirsich"],"European","Fruit","kg",5.8,"Spain/Italy",["Summer"], "White peach",42,0.9,10.0,0.3,"Refrigerated"),
("Nectarine",["Nektarine"],"European","Fruit","kg",5.0,"Spain/Italy",["Summer"], "Peach",44,1.1,10.5,0.3,"Refrigerated"),
("Blood Orange",["Blutorange"],"European","Fruit","kg",4.5,"Sicily",["Winter"], "Orange",50,0.9,12.0,0.2,"Refrigerated"),
("Bergamot",["Bergamotte"],"European","Fruit","kg",9.0,"Calabria, Italy",["Winter"], "Lemon",38,0.8,9.0,0.2,"Refrigerated"),
("Yuzu",["Yuzu frisch"],"Asian","Fruit","kg",48.0,"Japan/France",["Autumn","Winter"], "Bergamot + lime",45,0.5,11.0,0.1,"Refrigerated"),
("Kumquat",["Kumquats"],"Asian","Fruit","kg",12.0,"Spain",["Winter"], "Mandarin",71,1.9,16.0,0.9,"Refrigerated"),
("Clementine",["Clementinen"],"European","Fruit","kg",3.8,"Spain",["Winter"], "Mandarin",47,0.9,12.0,0.2,"Refrigerated"),
("Pomelo",["Pomelo"],"Asian","Fruit","kg",4.5,"China/Israel",["Winter"], "Grapefruit",38,0.8,9.6,0.0,"Refrigerated"),
("Cape Gooseberry",["Physalis"],"Universal","Fruit","kg",16.0,"Colombia",[], "Gooseberry",53,1.9,11.2,0.7,"Refrigerated"),
("Gooseberry",["Stachelbeeren"],"European","Fruit","kg",9.0,"Switzerland",["Summer"], "Cape gooseberry",44,0.9,10.2,0.6,"Refrigerated"),
("White Currant",["Weisse Johannisbeeren"],"European","Fruit","kg",10.0,"Switzerland",["Summer"], "Redcurrant",56,1.4,13.8,0.2,"Refrigerated"),
("Mulberry",["Maulbeeren"],"European","Fruit","kg",18.0,"Turkey",["Summer"], "Blackberry",43,1.4,9.8,0.4,"Refrigerated"),
("Fresh Fig",["Feigen frisch"],"European","Fruit","kg",9.5,"Turkey/Italy",["Summer","Autumn"], "Dried fig",74,0.8,19.2,0.3,"Refrigerated"),
("Persimmon",["Kaki"],"Asian","Fruit","kg",5.5,"Spain/Italy",["Autumn","Winter"], "Mango",70,0.6,18.6,0.2,"Refrigerated"),
("Pomegranate",["Granatapfel"],"Universal","Fruit","kg",5.0,"Spain/Israel",["Autumn","Winter"], None,83,1.7,18.7,1.2,"Refrigerated"),
("Passion Fruit",["Passionsfrucht","Maracuja"],"Universal","Fruit","kg",14.0,"Colombia/Vietnam",[], "Passion fruit purée",97,2.2,23.4,0.7,"Refrigerated"),
("Lychee",["Litschi"],"Asian","Fruit","kg",11.0,"Madagascar/Vietnam",["Winter"], "Rambutan",66,0.8,16.5,0.4,"Refrigerated"),
("Papaya",["Papaya"],"Universal","Fruit","kg",6.5,"Brazil",[], "Mango",43,0.5,10.8,0.3,"Refrigerated"),
("Dragon Fruit",["Pitahaya"],"Asian","Fruit","kg",12.0,"Vietnam",[], "Kiwi",60,1.2,13.0,0.4,"Refrigerated"),
("Starfruit",["Karambole"],"Asian","Fruit","kg",10.0,"Malaysia",[], None,31,1.0,6.7,0.3,"Refrigerated"),
("Guava",["Guave"],"Universal","Fruit","kg",9.0,"Brazil",[], "Guava purée",68,2.6,14.3,1.0,"Refrigerated"),
("Watermelon",["Wassermelone"],"Universal","Fruit","kg",1.6,"Spain/Italy",["Summer"], "Cantaloupe",30,0.6,7.6,0.2,"Room Temperature"),
("Cantaloupe",["Cantaloupe-Melone"],"European","Fruit","kg",3.0,"Spain/France",["Summer"], "Galia melon",34,0.8,8.2,0.2,"Room Temperature"),
("Galia Melon",["Galia-Melone"],"European","Fruit","kg",2.8,"Spain",["Summer"], "Cantaloupe",33,0.8,8.0,0.2,"Room Temperature"),
("Honeydew Melon",["Honigmelone"],"European","Fruit","kg",2.6,"Spain",["Summer"], "Galia melon",36,0.5,9.1,0.1,"Room Temperature"),
("Concord Grapes",["Trauben blau"],"European","Fruit","kg",4.5,"Italy/Switzerland",["Autumn"], "White grapes",67,0.7,17.2,0.2,"Refrigerated"),
("White Grapes",["Trauben weiss"],"European","Fruit","kg",4.5,"Italy",["Autumn"], "Concord grapes",69,0.7,18.1,0.2,"Refrigerated"),
("Banana",["Bananen"],"Universal","Fruit","kg",2.2,"Ecuador/Colombia",[], None,89,1.1,22.8,0.3,"Room Temperature"),
("Plantain",["Kochbananen"],"Universal","Fruit","kg",4.0,"Ecuador",[], "Banana",122,1.3,31.9,0.4,"Room Temperature"),
("Coconut Whole",["Kokosnuss ganz"],"Asian","Fruit","pc",2.5,"Sri Lanka",[], "Coconut milk",354,3.3,15.2,33.5,"Room Temperature"),
("Medjool Dates",["Medjool-Datteln"],"Universal","Fruit","kg",14.0,"Israel/Jordan",[], "Dried dates",277,1.8,75.0,0.2,"Room Temperature"),
("Dried Apricots",["getrocknete Aprikosen"],"Universal","Fruit","kg",9.0,"Turkey",[], "Dried dates",241,3.4,62.6,0.5,"Dry Storage"),
("Dried Figs",["getrocknete Feigen"],"Universal","Fruit","kg",10.0,"Turkey",[], "Dried apricots",249,3.3,63.9,0.9,"Dry Storage"),
("Prunes",["Dörrpflaumen"],"European","Fruit","kg",8.0,"France",[], "Dried figs",240,2.2,63.9,0.4,"Dry Storage"),
("Raisins",["Rosinen","Sultaninen"],"Universal","Fruit","kg",5.5,"Turkey",[], "Dried currants",299,3.1,79.2,0.5,"Dry Storage"),
("Dried Currants",["Korinthen"],"European","Fruit","kg",7.0,"Greece",[], "Raisins",283,4.1,74.1,0.3,"Dry Storage"),
("Candied Orange Peel",["Orangeat"],"European","Fruit","kg",9.5,"Italy",[], "Candied lemon peel",316,0.4,80.0,0.2,"Dry Storage"),
("Candied Lemon Peel",["Zitronat"],"European","Fruit","kg",9.5,"Italy",[], "Candied orange peel",316,0.4,80.0,0.2,"Dry Storage"),
# --- Mushrooms (fresh specialty) ---
("King Oyster Mushroom",["Kräuterseitling"],"Asian","Vegetable","kg",12.0,"Switzerland/Netherlands",[], "Oyster mushroom",35,3.3,6.0,0.4,"Refrigerated"),
("Oyster Mushroom",["Austernpilze"],"Universal","Vegetable","kg",10.0,"Switzerland",[], "King oyster mushroom",33,3.3,6.1,0.4,"Refrigerated"),
("Shiitake Fresh",["Shiitake frisch"],"Asian","Vegetable","kg",14.0,"Switzerland/Netherlands",[], "Dried shiitake",34,2.2,6.8,0.5,"Refrigerated"),
("Enoki",["Enoki-Pilze"],"Asian","Vegetable","kg",16.0,"Netherlands/Korea",[], "Shimeji",37,2.7,7.8,0.3,"Refrigerated"),
("Shimeji",["Buchenpilze"],"Asian","Vegetable","kg",15.0,"Netherlands",[], "Enoki",35,2.5,7.0,0.3,"Refrigerated"),
("Portobello",["Portobello-Pilze"],"Universal","Vegetable","kg",9.0,"Netherlands/Switzerland",[], "Button mushrooms",26,2.5,4.0,0.3,"Refrigerated"),
("Brown Mushrooms",["Champignons braun"],"Universal","Vegetable","kg",7.0,"Switzerland",[], "Button mushrooms",26,2.5,4.3,0.3,"Refrigerated"),
("Black Trumpet",["Totentrompeten"],"European","Vegetable","kg",34.0,"France",["Autumn"], "Chanterelle",38,3.8,6.9,0.5,"Refrigerated"),
("Hedgehog Mushroom",["Semmelstoppelpilze"],"European","Vegetable","kg",26.0,"Switzerland/France",["Autumn"], "Chanterelle",35,3.5,6.5,0.4,"Refrigerated"),
("Dried Porcini",["Steinpilze getrocknet"],"European","Vegetable","kg",95.0,"Italy",[], "Fresh porcini",370,30.0,50.0,3.0,"Dry Storage"),
("Dried Morels",["Morcheln getrocknet"],"European","Vegetable","kg",380.0,"India/Turkey",[], "Fresh morels",340,32.0,45.0,4.0,"Dry Storage"),
("Dried Shiitake",["Shiitake getrocknet"],"Asian","Vegetable","kg",42.0,"China",[], "Fresh shiitake",296,9.6,75.4,1.0,"Dry Storage"),
("Truffle Black Winter",["Schwarze Trüffel","Périgord-Trüffel"],"European","Vegetable","kg",900.0,"France/Italy",["Winter"], "Truffle paste",92,6.0,16.0,0.5,"Refrigerated"),
("Truffle Summer",["Sommertrüffel"],"European","Vegetable","kg",280.0,"Italy",["Summer","Autumn"], "Black winter truffle",92,6.0,16.0,0.5,"Refrigerated"),
("Wood Ear Mushroom",["Mu-Err","Judasohr"],"Asian","Vegetable","kg",28.0,"China",[], "Dried shiitake",25,0.5,6.8,0.0,"Dry Storage"),
# --- Grains, flours, pulses (specific types) ---
("Spelt Flour",["Dinkelmehl"],"European","Grains & Flour","kg",2.8,"Switzerland",[], "Wheat flour",338,14.6,68.0,2.4,"Dry Storage"),
("Rye Flour",["Roggenmehl"],"European","Grains & Flour","kg",2.2,"Switzerland",[], "Spelt flour",325,10.9,69.8,1.7,"Dry Storage"),
("Buckwheat Flour",["Buchweizenmehl"],"European","Grains & Flour","kg",4.5,"France",[], "Rye flour",335,12.6,70.6,3.1,"Dry Storage"),
("Chestnut Flour",["Kastanienmehl"],"European","Grains & Flour","kg",12.0,"Italy/Ticino",[], "Buckwheat flour",343,6.1,76.2,3.7,"Dry Storage"),
("Semolina",["Hartweizengriess"],"European","Grains & Flour","kg",2.4,"Italy",[], "Polenta",360,12.7,72.8,1.1,"Dry Storage"),
("Chickpea Flour",["Kichererbsenmehl"],"Universal","Grains & Flour","kg",4.8,"Italy/India",[], "Semolina",387,22.4,57.8,6.7,"Dry Storage"),
("Rice Flour",["Reismehl"],"Asian","Grains & Flour","kg",3.5,"Thailand",[], "Cornstarch",366,6.0,80.1,1.4,"Dry Storage"),
("Tipo 00 Flour",["Mehl Tipo 00","Pizzamehl"],"European","Grains & Flour","kg",1.8,"Italy",[], "White flour",364,11.0,74.0,1.0,"Dry Storage"),
("Wholegrain Flour",["Vollkornmehl"],"European","Grains & Flour","kg",2.0,"Switzerland",[], "Spelt flour",340,13.2,68.0,2.5,"Dry Storage"),
("Freekeh",["Freekeh"],"Universal","Grains & Flour","kg",8.5,"Lebanon",[], "Bulgur",352,13.0,72.0,2.5,"Dry Storage"),
("Farro",["Farro","Emmer"],"European","Grains & Flour","kg",6.0,"Italy",[], "Spelt",340,14.0,67.0,2.5,"Dry Storage"),
("Pearl Barley",["Rollgerste","Perlgraupen"],"European","Grains & Flour","kg",2.5,"Switzerland",[], "Farro",352,9.9,77.7,1.2,"Dry Storage"),
("Millet",["Hirse"],"Universal","Grains & Flour","kg",3.8,"Austria/France",[], "Quinoa",378,11.0,72.9,4.2,"Dry Storage"),
("Amaranth",["Amaranth"],"Universal","Grains & Flour","kg",6.5,"Peru",[], "Quinoa",371,13.6,65.2,7.0,"Dry Storage"),
("Black Quinoa",["Quinoa schwarz"],"Universal","Grains & Flour","kg",8.0,"Peru/Bolivia",[], "Quinoa",368,14.1,64.2,6.1,"Dry Storage"),
("Wild Rice",["Wildreis"],"Universal","Grains & Flour","kg",9.5,"Canada",[], "Black rice",357,14.7,74.9,1.1,"Dry Storage"),
("Black Rice",["schwarzer Reis","Venere"],"Asian","Grains & Flour","kg",7.5,"Italy",[], "Wild rice",356,8.9,75.6,3.3,"Dry Storage"),
("Carnaroli Rice",["Carnaroli"],"European","Grains & Flour","kg",5.5,"Italy",[], "Arborio rice",349,7.0,77.0,0.6,"Dry Storage"),
("Sushi Rice",["Sushireis"],"Asian","Grains & Flour","kg",4.5,"Italy/Japan",[], "Carnaroli rice",356,6.5,79.0,0.6,"Dry Storage"),
("Sticky Rice",["Klebreis"],"Asian","Grains & Flour","kg",4.8,"Thailand",[], "Sushi rice",370,6.8,81.7,0.6,"Dry Storage"),
("Beluga Lentils",["Beluga-Linsen"],"Universal","Grains & Flour","kg",6.5,"Canada/France",[], "Puy lentils",352,24.6,52.7,1.6,"Dry Storage"),
("Puy Lentils",["Puy-Linsen"],"European","Grains & Flour","kg",7.5,"France",[], "Beluga lentils",352,24.6,52.7,1.6,"Dry Storage"),
("Red Lentils",["rote Linsen"],"Universal","Grains & Flour","kg",3.5,"Turkey",[], "Yellow lentils",358,24.0,56.3,2.2,"Dry Storage"),
("Split Peas",["halbe Erbsen","Spälterbsen"],"European","Grains & Flour","kg",3.0,"Canada",[], "Red lentils",341,24.6,60.4,1.2,"Dry Storage"),
("Borlotti Beans",["Borlotti-Bohnen"],"European","Grains & Flour","kg",5.5,"Italy",[], "Cannellini beans",335,23.0,60.0,1.2,"Dry Storage"),
("Cannellini Beans",["Cannellini-Bohnen"],"European","Grains & Flour","kg",5.0,"Italy",[], "Borlotti beans",333,23.4,60.3,0.9,"Dry Storage"),
("Black Beans",["schwarze Bohnen"],"Universal","Grains & Flour","kg",4.5,"South America",[], "Kidney beans",341,21.6,62.4,1.4,"Dry Storage"),
("Flageolet Beans",["Flageolet-Bohnen"],"European","Grains & Flour","kg",7.0,"France",[], "Cannellini beans",330,22.0,58.0,1.5,"Dry Storage"),
("Couscous",["Couscous"],"Universal","Grains & Flour","kg",2.8,"Morocco/France",[], "Bulgur",376,12.8,77.4,0.6,"Dry Storage"),
("Israeli Couscous",["Ptitim","Perlcouscous"],"Universal","Grains & Flour","kg",5.5,"Israel",[], "Couscous",378,13.0,77.0,1.0,"Dry Storage"),
("Polenta Bramata",["Polenta grob"],"European","Grains & Flour","kg",2.6,"Italy/Ticino",[], "Semolina",362,8.1,79.0,1.2,"Dry Storage"),
("Rolled Oats",["Haferflocken"],"European","Grains & Flour","kg",2.0,"Switzerland",[], "Spelt flakes",379,13.5,67.7,6.5,"Dry Storage"),
("Panko",["Panko-Paniermehl"],"Asian","Dry Goods & Pantry","kg",5.0,"Japan/Netherlands",[], "Breadcrumb",360,11.0,72.0,2.5,"Dry Storage"),
]
