ITEMS = [
# --- Asian / international pantry ---
("Dark Soy Sauce",["dunkle Sojasauce"],"Asian","Sauces & Condiments","l",6.5,"China",[], "Soy sauce",60,6.0,9.0,0.0,"Dry Storage"),
("Tamari",["Tamari glutenfrei"],"Asian","Sauces & Condiments","l",9.0,"Japan",[], "Soy sauce",65,10.5,5.6,0.1,"Dry Storage"),
("White Miso",["Miso hell","Shiro Miso"],"Asian","Sauces & Condiments","kg",9.5,"Japan",[], "Red miso",200,12.0,26.0,6.0,"Refrigerated"),
("Red Miso",["Miso dunkel","Aka Miso"],"Asian","Sauces & Condiments","kg",10.5,"Japan",[], "White miso",210,13.0,25.0,6.5,"Refrigerated"),
("Gochujang",["Gochujang"],"Asian","Sauces & Condiments","kg",11.0,"Korea",[], "Miso + chili",180,4.0,40.0,1.5,"Refrigerated"),
("Gochugaru",["Gochugaru","koreanische Chiliflocken"],"Asian","Spices & Seasonings","kg",24.0,"Korea",[], "Aleppo pepper",280,12.0,50.0,10.0,"Dry Storage"),
("Doubanjiang",["Doubanjiang","Bohnenpaste scharf"],"Asian","Sauces & Condiments","kg",10.0,"Sichuan, China",[], "Gochujang",150,8.0,20.0,5.0,"Refrigerated"),
("Black Bean Sauce",["schwarze Bohnensauce"],"Asian","Sauces & Condiments","kg",8.5,"China",[], "Doubanjiang",140,7.0,20.0,4.0,"Dry Storage"),
("Hoisin Sauce",["Hoisinsauce"],"Asian","Sauces & Condiments","l",7.5,"China",[], "Black bean sauce + honey",220,2.5,44.0,3.5,"Dry Storage"),
("Ponzu",["Ponzu"],"Asian","Sauces & Condiments","l",12.0,"Japan",[], "Soy sauce + citrus",55,4.0,9.0,0.0,"Refrigerated"),
("Mirin",["Mirin"],"Asian","Sauces & Condiments","l",8.5,"Japan",[], "Rice wine + sugar",240,0.2,43.0,0.0,"Dry Storage"),
("Sake Cooking",["Kochsake","Ryorishu"],"Asian","Alcohol","l",7.0,"Japan",[], "Dry white wine",134,0.5,5.0,0.0,"Dry Storage"),
("Shaoxing Wine",["Shaoxing-Reiswein"],"Asian","Alcohol","l",7.5,"China",[], "Sake",125,0.5,5.0,0.0,"Dry Storage"),
("Rice Vinegar",["Reisessig"],"Asian","Oils & Vinegars","l",5.0,"Japan/China",[], "White wine vinegar",20,0.0,1.0,0.0,"Dry Storage"),
("Black Vinegar",["Chinkiang-Essig"],"Asian","Oils & Vinegars","l",7.0,"China",[], "Balsamic vinegar",25,0.5,3.0,0.0,"Dry Storage"),
("Fish Sauce Premium",["Fischsauce","Nam Pla"],"Asian","Sauces & Condiments","l",8.0,"Thailand/Vietnam",[], "Soy sauce + anchovy",50,10.0,3.5,0.0,"Dry Storage"),
("Oyster Sauce Premium",["Austernsauce"],"Asian","Sauces & Condiments","l",7.0,"China",[], "Hoisin sauce",120,2.5,25.0,0.2,"Refrigerated"),
("Sambal Oelek",["Sambal Oelek"],"Asian","Sauces & Condiments","kg",8.0,"Indonesia",[], "Sriracha",80,2.0,14.0,1.0,"Refrigerated"),
("Sriracha",["Sriracha-Sauce"],"Asian","Sauces & Condiments","l",7.0,"Thailand",[], "Sambal oelek",100,1.8,20.0,1.0,"Dry Storage"),
("Tahini",["Tahin","Sesampaste"],"Universal","Sauces & Condiments","kg",11.0,"Lebanon/Turkey",[], "Peanut butter",595,17.0,21.2,53.8,"Dry Storage"),
("Harissa",["Harissa"],"Universal","Sauces & Condiments","kg",10.0,"Tunisia",[], "Sambal oelek",120,4.0,18.0,4.0,"Refrigerated"),
("Preserved Lemons",["Salzzitronen"],"Universal","Sauces & Condiments","kg",12.0,"Morocco",[], "Lemon + salt",35,0.7,8.0,0.3,"Refrigerated"),
("Pomegranate Molasses",["Granatapfelsirup"],"Universal","Sauces & Condiments","l",13.0,"Lebanon/Turkey",[], "Balsamic reduction",270,0.5,67.0,0.1,"Dry Storage"),
("Date Syrup",["Dattelsirup"],"Universal","Sweeteners","l",9.5,"Israel/Iraq",[], "Maple syrup",290,1.0,72.0,0.2,"Dry Storage"),
("Rose Water",["Rosenwasser"],"Universal","Sauces & Condiments","l",8.0,"Iran/Lebanon",[], "Orange blossom water",0,0.0,0.0,0.0,"Dry Storage"),
("Orange Blossom Water",["Orangenblütenwasser"],"Universal","Sauces & Condiments","l",8.5,"Lebanon/Morocco",[], "Rose water",0,0.0,0.0,0.0,"Dry Storage"),
("Dashi Powder",["Dashi-Pulver","Hondashi"],"Asian","Sauces & Condiments","kg",32.0,"Japan",[], "Kombu + bonito flakes",240,25.0,30.0,1.0,"Dry Storage"),
("Kombu",["Kombu-Alge"],"Asian","Other","kg",38.0,"Japan/Korea",[], "Dashi powder",170,8.0,50.0,1.0,"Dry Storage"),
("Wakame",["Wakame-Alge"],"Asian","Other","kg",34.0,"Japan/Korea",[], "Kombu",180,15.0,40.0,2.5,"Dry Storage"),
("Nori Sheets",["Nori-Blätter"],"Asian","Other","kg",55.0,"Japan/Korea",[], "Wakame",350,40.0,40.0,3.0,"Dry Storage"),
("Bonito Flakes",["Katsuobushi"],"Asian","Other","kg",65.0,"Japan",[], "Dashi powder",350,75.0,1.0,4.0,"Dry Storage"),
("Rice Paper",["Reispapier"],"Asian","Dry Goods & Pantry","kg",9.0,"Vietnam",[], "Spring roll pastry",334,2.5,80.0,0.5,"Dry Storage"),
("Rice Noodles",["Reisnudeln"],"Asian","Dry Goods & Pantry","kg",5.5,"Thailand/Vietnam",[], "Glass noodles",364,3.4,83.2,0.6,"Dry Storage"),
("Glass Noodles",["Glasnudeln"],"Asian","Dry Goods & Pantry","kg",6.5,"China/Thailand",[], "Rice noodles",351,0.2,86.1,0.1,"Dry Storage"),
("Soba Noodles",["Soba-Nudeln"],"Asian","Dry Goods & Pantry","kg",8.5,"Japan",[], "Udon noodles",336,14.4,69.0,0.7,"Dry Storage"),
("Udon Noodles",["Udon-Nudeln"],"Asian","Dry Goods & Pantry","kg",6.0,"Japan",[], "Soba noodles",337,8.5,69.5,1.0,"Dry Storage"),
("Ramen Noodles",["Ramen-Nudeln"],"Asian","Dry Goods & Pantry","kg",7.0,"Japan/China",[], "Udon noodles",380,10.5,74.0,4.0,"Dry Storage"),
("Wonton Wrappers",["Wonton-Teigblätter"],"Asian","Dry Goods & Pantry","kg",8.0,"China",[], "Gyoza wrappers",290,9.0,58.0,1.5,"Freezer"),
("Gyoza Wrappers",["Gyoza-Teigblätter"],"Asian","Dry Goods & Pantry","kg",8.5,"Japan/China",[], "Wonton wrappers",280,8.5,57.0,1.2,"Freezer"),
("Panettone",["Panettone"],"European","Bakery","kg",14.0,"Italy",["Winter"], "Brioche",380,7.0,52.0,15.0,"Room Temperature"),
("Kimchi",["Kimchi"],"Asian","Sauces & Condiments","kg",9.0,"Korea/Switzerland",[], "Sauerkraut",25,1.5,4.0,0.5,"Refrigerated"),
("Capers in Salt",["Kapern in Salz"],"European","Sauces & Condiments","kg",16.0,"Pantelleria, Italy",[], "Capers in brine",50,2.5,5.0,0.8,"Dry Storage"),
("Caper Berries",["Kapernäpfel"],"European","Sauces & Condiments","kg",12.0,"Spain",[], "Capers in salt",30,1.5,3.5,0.5,"Refrigerated"),
("Cornichons",["Cornichons"],"European","Sauces & Condiments","kg",7.0,"France/Switzerland",[], "Pickled cucumber",15,0.8,2.5,0.2,"Dry Storage"),
("Pickled Silverskin Onions",["Silberzwiebeln eingelegt"],"European","Sauces & Condiments","kg",6.5,"Netherlands",[], "Cornichons",30,0.8,6.0,0.1,"Dry Storage"),
("Dijon Mustard",["Dijon-Senf"],"European","Sauces & Condiments","kg",6.0,"France",[], "Mustard",145,7.0,10.0,10.0,"Refrigerated"),
("Wholegrain Mustard",["grobkörniger Senf"],"European","Sauces & Condiments","kg",7.0,"France",[], "Dijon mustard",160,8.0,12.0,10.5,"Refrigerated"),
("Horseradish Fresh",["Meerrettich frisch"],"European","Vegetable","kg",9.0,"Switzerland/Austria",["Autumn","Winter"], "Wasabi paste",48,1.2,11.0,0.3,"Refrigerated"),
("Truffle Paste",["Trüffelpaste"],"European","Sauces & Condiments","kg",85.0,"Italy",[], "Truffle oil",180,5.0,10.0,14.0,"Refrigerated"),
("Anchovy Paste",["Sardellenpaste"],"European","Sauces & Condiments","kg",18.0,"Italy",[], "Salted anchovies",180,20.0,3.0,10.0,"Refrigerated"),
("Tomato Passata",["Passata"],"European","Sauces & Condiments","l",2.4,"Italy",[], "Canned tomatoes",35,1.5,7.0,0.2,"Dry Storage"),
("Tomato Paste Double",["Tomatenmark 2-fach"],"European","Sauces & Condiments","kg",4.5,"Italy",[], "Tomato passata",95,4.5,19.0,0.5,"Dry Storage"),
("Sun-Dried Tomato Paste",["getrocknete Tomatenpaste"],"European","Sauces & Condiments","kg",12.0,"Italy",[], "Tomato paste",180,4.0,25.0,8.0,"Dry Storage"),
("Roasted Peppers in Oil",["gegrillte Peperoni eingelegt"],"European","Sauces & Condiments","kg",9.0,"Spain/Italy",[], "Grilled peppers",90,1.2,8.0,6.0,"Dry Storage"),
("Artichokes in Oil",["Artischocken eingelegt"],"European","Sauces & Condiments","kg",11.0,"Italy",[], "Artichoke hearts",130,2.5,8.0,10.0,"Dry Storage"),
("Green Olive Tapenade",["grüne Oliventapenade"],"European","Sauces & Condiments","kg",13.0,"France",[], "Black olive tapenade",250,2.0,6.0,24.0,"Refrigerated"),
("Black Olive Tapenade",["schwarze Oliventapenade"],"European","Sauces & Condiments","kg",13.0,"France",[], "Green olive tapenade",260,2.2,6.5,25.0,"Refrigerated"),
("Pesto Genovese",["Pesto"],"European","Sauces & Condiments","kg",14.0,"Liguria, Italy",[], "Basil + parmesan + pine nuts",450,5.0,6.0,45.0,"Refrigerated"),
("Taggiasca Olives",["Taggiasca-Oliven"],"European","Sauces & Condiments","kg",15.0,"Liguria, Italy",[], "Kalamata olives",230,1.5,6.0,22.0,"Refrigerated"),
("Kalamata Olives",["Kalamata-Oliven"],"European","Sauces & Condiments","kg",11.0,"Greece",[], "Taggiasca olives",240,1.5,6.5,23.0,"Refrigerated"),
# --- Oils & vinegars ---
("Extra Virgin Olive Oil",["Olivenöl extra vergine"],"European","Oils & Vinegars","l",12.0,"Italy/Greece/Spain",[], "Olive oil",884,0.0,0.0,100.0,"Dry Storage"),
("Rapeseed Oil Swiss",["Rapsöl CH","HOLL-Rapsöl"],"European","Oils & Vinegars","l",4.5,"Switzerland",[], "Sunflower oil",884,0.0,0.0,100.0,"Dry Storage"),
("Pumpkin Seed Oil",["Kürbiskernöl"],"European","Oils & Vinegars","l",22.0,"Styria, Austria",[], "Walnut oil",884,0.0,0.0,100.0,"Dry Storage"),
("Walnut Oil",["Baumnussöl"],"European","Oils & Vinegars","l",24.0,"France/Switzerland",[], "Hazelnut oil",884,0.0,0.0,100.0,"Refrigerated"),
("Hazelnut Oil",["Haselnussöl"],"European","Oils & Vinegars","l",26.0,"France",[], "Walnut oil",884,0.0,0.0,100.0,"Refrigerated"),
("Grapeseed Oil",["Traubenkernöl"],"European","Oils & Vinegars","l",9.0,"Italy/France",[], "Sunflower oil",884,0.0,0.0,100.0,"Dry Storage"),
("Toasted Sesame Oil",["geröstetes Sesamöl"],"Asian","Oils & Vinegars","l",14.0,"Japan/China",[], "Sesame oil",884,0.0,0.0,100.0,"Dry Storage"),
("Truffle Oil",["Trüffelöl"],"European","Oils & Vinegars","l",45.0,"Italy",[], "Truffle paste",884,0.0,0.0,100.0,"Dry Storage"),
("Peanut Oil",["Erdnussöl"],"Asian","Oils & Vinegars","l",7.0,"China/Argentina",[], "Sunflower oil",884,0.0,0.0,100.0,"Dry Storage"),
("Frying Oil HO",["Frittieröl High Oleic"],"Universal","Oils & Vinegars","l",4.0,"Switzerland/EU",[], "Sunflower oil",884,0.0,0.0,100.0,"Dry Storage"),
("Aged Balsamic 12y",["Aceto Balsamico Tradizionale"],"European","Oils & Vinegars","l",120.0,"Modena, Italy",[], "Balsamic vinegar",250,0.5,60.0,0.0,"Dry Storage"),
("Sherry Vinegar",["Sherryessig"],"European","Oils & Vinegars","l",9.0,"Jerez, Spain",[], "Red wine vinegar",20,0.0,1.0,0.0,"Dry Storage"),
("Champagne Vinegar",["Champagneressig"],"European","Oils & Vinegars","l",11.0,"France",[], "White wine vinegar",19,0.0,0.8,0.0,"Dry Storage"),
("Apple Balsamic",["Apfelbalsamico"],"European","Oils & Vinegars","l",14.0,"Switzerland/Italy",[], "Sherry vinegar",90,0.1,20.0,0.0,"Dry Storage"),
("Verjus",["Verjus"],"European","Oils & Vinegars","l",12.0,"France/Switzerland",[], "Champagne vinegar",40,0.1,9.0,0.0,"Refrigerated"),
# --- Nuts & seeds ---
("Marcona Almonds",["Marcona-Mandeln"],"European","Nuts & Seeds","kg",22.0,"Spain",[], "Almonds",610,20.0,17.0,55.0,"Dry Storage"),
("Piedmont Hazelnuts",["Piemont-Haselnüsse IGP"],"European","Nuts & Seeds","kg",24.0,"Piedmont, Italy",[], "Hazelnuts",646,15.0,17.0,61.0,"Dry Storage"),
("Pecans",["Pekannüsse"],"Universal","Nuts & Seeds","kg",20.0,"USA/Mexico",[], "Walnuts",691,9.2,13.9,72.0,"Dry Storage"),
("Macadamia",["Macadamianüsse"],"Universal","Nuts & Seeds","kg",28.0,"Australia/South Africa",[], "Cashews",718,7.9,13.8,75.8,"Dry Storage"),
("Brazil Nuts",["Paranüsse"],"Universal","Nuts & Seeds","kg",16.0,"Bolivia/Brazil",[], "Macadamia",659,14.3,11.7,67.1,"Dry Storage"),
("Black Sesame",["schwarzer Sesam"],"Asian","Nuts & Seeds","kg",9.0,"Japan/China",[], "White sesame",573,17.7,23.4,49.7,"Dry Storage"),
("Hemp Seeds",["Hanfsamen geschält"],"Universal","Nuts & Seeds","kg",14.0,"Switzerland/Canada",[], "Flax seeds",553,31.6,8.7,48.8,"Dry Storage"),
("Flax Seeds",["Leinsamen"],"Universal","Nuts & Seeds","kg",4.0,"Switzerland/Canada",[], "Chia seeds",534,18.3,28.9,42.2,"Dry Storage"),
("Pumpkin Seeds",["Kürbiskerne"],"European","Nuts & Seeds","kg",9.5,"Austria/China",[], "Sunflower seeds",559,30.2,10.7,49.1,"Dry Storage"),
("Candied Chestnuts",["Marrons glacés"],"European","Nuts & Seeds","kg",32.0,"France/Italy",["Winter"], "Chestnuts",320,2.0,72.0,1.5,"Dry Storage"),
("Nut Mix Roasted",["geröstete Nussmischung"],"Universal","Nuts & Seeds","kg",15.0,"various",[], None,620,18.0,18.0,54.0,"Dry Storage"),
]
