ITEMS = [
("Green Peppercorns in Brine",["grüner Pfeffer eingelegt"],"European","Spices & Seasonings","kg",18.0,"Madagascar",[], "Pink peppercorns",95,3.0,15.0,2.0,"Dry Storage"),
("Smoked Paprika Sweet",["Paprika geräuchert süss","Pimentón dulce"],"European","Spices & Seasonings","kg",13.0,"La Vera, Spain",[], "Paprika",282,14.1,54.0,13.0,"Dry Storage"),
("Smoked Paprika Hot",["Pimentón picante"],"European","Spices & Seasonings","kg",13.5,"La Vera, Spain",[], "Smoked paprika sweet",282,14.1,54.0,13.0,"Dry Storage"),
("Vadouvan",["Vadouvan"],"Universal","Spices & Seasonings","kg",28.0,"France/India",[], "Curry powder Madras",330,12.0,52.0,12.0,"Dry Storage"),
("Berbere",["Berbere"],"Universal","Spices & Seasonings","kg",20.0,"Ethiopia",[], "Baharat",320,12.0,50.0,10.0,"Dry Storage"),
("Cajun Spice",["Cajun-Gewürz"],"Universal","Spices & Seasonings","kg",12.0,"USA",[], "Chili powder + paprika",300,10.0,55.0,8.0,"Dry Storage"),
("Jerk Seasoning",["Jerk-Gewürz"],"Universal","Spices & Seasonings","kg",16.0,"Jamaica",[], "Cajun spice",310,10.0,56.0,9.0,"Dry Storage"),
("Quatre Épices",["Quatre-Épices"],"European","Spices & Seasonings","kg",24.0,"France",[], "Allspice + nutmeg",320,9.0,58.0,10.0,"Dry Storage"),
("Pickling Spice",["Einmachgewürz"],"European","Spices & Seasonings","kg",11.0,"EU",[], "Juniper + mustard seeds",320,12.0,55.0,11.0,"Dry Storage"),
("Mulled Wine Spice",["Glühweingewürz"],"European","Spices & Seasonings","kg",15.0,"EU",["Winter"], "Cinnamon + cloves + star anise",300,7.0,60.0,7.0,"Dry Storage"),
("Yellow Mustard Seeds",["Senfkörner gelb"],"European","Spices & Seasonings","kg",5.5,"Canada",[], "Brown mustard seeds",508,26.1,28.1,36.2,"Dry Storage"),
("Brown Mustard Seeds",["Senfkörner braun"],"Asian","Spices & Seasonings","kg",6.5,"India/Canada",[], "Yellow mustard seeds",508,26.1,28.1,36.2,"Dry Storage"),
("Annatto Seeds",["Annatto","Achiote"],"Universal","Spices & Seasonings","kg",14.0,"Peru/Mexico",[], "Saffron (color only)",350,12.0,50.0,15.0,"Dry Storage"),
("Dried Lime",["Limu Omani","Schwarze Limette"],"Universal","Spices & Seasonings","kg",22.0,"Iran/Oman",[], "Lime zest",280,4.0,70.0,2.0,"Dry Storage"),
("Barberries",["Berberitzen"],"Universal","Fruit","kg",18.0,"Iran",[], "Dried currants",316,3.6,63.9,3.5,"Dry Storage"),
("Freeze-Dried Raspberry",["Himbeeren gefriergetrocknet"],"Universal","Fruit","kg",65.0,"EU",[], "IQF raspberries",380,8.0,75.0,4.0,"Dry Storage"),
("Freeze-Dried Strawberry",["Erdbeeren gefriergetrocknet"],"Universal","Fruit","kg",60.0,"EU",[], "Freeze-dried raspberry",370,7.0,77.0,3.0,"Dry Storage"),
("Banana Chips",["Bananenchips"],"Universal","Fruit","kg",8.0,"Philippines",[], "Dried apple rings",520,2.3,58.0,33.6,"Dry Storage"),
("Goji Berries",["Gojibeeren"],"Asian","Fruit","kg",16.0,"China",[], "Barberries",349,14.3,77.1,0.4,"Dry Storage"),
("Dried Cranberries",["Cranberries getrocknet"],"Universal","Fruit","kg",9.0,"USA/Canada",[], "Raisins",308,0.2,82.0,1.1,"Dry Storage"),
("Dried Mango",["Mango getrocknet"],"Asian","Fruit","kg",14.0,"Philippines/Thailand",[], "Dried apricots",319,2.5,78.6,1.2,"Dry Storage"),
("Apple Chips",["Apfelchips"],"European","Fruit","kg",18.0,"Switzerland",[], "Dried apple rings",380,1.5,90.0,0.5,"Dry Storage"),
("Pear Williams Purée",["Williamsbirnen-Püree"],"European","Fruit","kg",14.5,"France",[], "Pear purée",90,0.3,21.0,0.1,"Freezer"),
("Rhubarb Purée",["Rhabarber-Püree"],"European","Fruit","kg",13.0,"France",["Spring"], "Rhubarb",60,0.5,14.0,0.1,"Freezer"),
("Fig Purée",["Feigen-Püree"],"European","Fruit","kg",19.5,"France",[], "Fresh fig",100,0.8,24.0,0.3,"Freezer"),
("Melon Purée",["Melonen-Püree"],"European","Fruit","kg",17.0,"France",["Summer"], "Cantaloupe",55,0.6,13.0,0.2,"Freezer"),
("Quince Paste",["Quittenpaste","Membrillo"],"European","Fruit","kg",13.0,"Spain",[], "Quince",230,0.3,57.0,0.1,"Refrigerated"),
("Chestnut Purée Sweetened",["Kastanienpüree gezuckert"],"European","Fruit","kg",10.0,"France",["Autumn","Winter"], "Vermicelles purée",210,2.0,50.0,1.0,"Dry Storage"),
("Yuzu Juice",["Yuzusaft"],"Asian","Sauces & Condiments","l",65.0,"Japan",[], "Lime juice + mandarin",25,0.5,7.0,0.1,"Refrigerated"),
("Calamansi Purée",["Calamansi-Püree"],"Asian","Fruit","kg",24.0,"Philippines/France",[], "Kalamansi purée",50,0.4,12.0,0.1,"Freezer"),
("Blackberry Purée",["Brombeer-Püree"],"European","Fruit","kg",21.5,"France/Chile",[], "Blackberry",55,0.8,12.0,0.4,"Freezer"),
("Apricot Glaze",["Aprikosen-Glasur","Aprikotur"],"European","Bakery","kg",7.5,"EU",[], "Apricot jam sieved",260,0.3,64.0,0.1,"Dry Storage"),
("Neutral Glaze",["neutrale Glasur","Nappage"],"European","Bakery","kg",8.0,"EU",[], "Apricot glaze",250,0.0,62.0,0.0,"Dry Storage"),
("Chocolate Glaze Mirror",["Mirror Glaze Schokolade"],"European","Bakery","kg",12.0,"EU",[], "Couverture + glucose",320,3.0,55.0,10.0,"Dry Storage"),
("Cake Flour",["Kuchenmehl"],"Universal","Grains & Flour","kg",2.2,"Switzerland",[], "Tipo 00 flour",362,9.0,76.0,1.0,"Dry Storage"),
("Bread Flour Strong",["Brotmehl stark","Manitoba"],"Universal","Grains & Flour","kg",2.4,"Canada/Italy",[], "Tipo 00 flour",350,13.5,70.0,1.5,"Dry Storage"),
("Kamut Flour",["Kamutmehl"],"European","Grains & Flour","kg",5.5,"Canada/Italy",[], "Spelt flour",337,14.5,66.0,2.2,"Dry Storage"),
("Einkorn Flour",["Einkornmehl"],"European","Grains & Flour","kg",6.5,"Switzerland/Germany",[], "Spelt flour",330,14.0,64.0,2.5,"Dry Storage"),
("Teff Flour",["Teffmehl"],"Universal","Grains & Flour","kg",9.0,"Ethiopia",[], "Buckwheat flour",366,13.3,73.1,2.4,"Dry Storage"),
("Cornmeal Fine",["Maismehl fein"],"Universal","Grains & Flour","kg",2.6,"Italy/France",[], "Polenta bramata",362,8.1,79.0,1.2,"Dry Storage"),
("Masa Harina",["Masa Harina"],"Universal","Grains & Flour","kg",5.5,"Mexico",[], "Cornmeal fine",365,8.5,76.0,4.0,"Dry Storage"),
("Vital Wheat Gluten",["Weizengluten"],"Universal","Grains & Flour","kg",8.5,"EU",[], None,370,75.0,14.0,2.0,"Dry Storage"),
("Bulgur Coarse",["Bulgur grob"],"Universal","Grains & Flour","kg",3.2,"Turkey",[], "Freekeh",342,12.3,75.9,1.3,"Dry Storage"),
("Fregola",["Fregola Sarda"],"European","Dry Goods & Pantry","kg",7.0,"Sardinia, Italy",[], "Israeli couscous",370,13.0,75.0,1.5,"Dry Storage"),
("Mung Beans Dry",["Mungbohnen getrocknet"],"Asian","Grains & Flour","kg",4.5,"India/Myanmar",[], "Green lentils",347,23.9,62.6,1.2,"Dry Storage"),
("Urad Dal",["Urad Dal"],"Asian","Grains & Flour","kg",5.5,"India",[], "Mung beans dry",341,25.2,58.9,1.6,"Dry Storage"),
("Chana Dal",["Chana Dal"],"Asian","Grains & Flour","kg",4.5,"India",[], "Split peas",360,22.0,60.0,5.0,"Dry Storage"),
("Gigantes Beans",["Gigantes-Bohnen"],"European","Grains & Flour","kg",8.0,"Greece",[], "Butter beans",330,21.0,60.0,1.5,"Dry Storage"),
("Lupini Beans",["Lupinen"],"European","Grains & Flour","kg",7.0,"Italy/Portugal",[], "Chickpea",371,36.2,40.4,9.7,"Dry Storage"),
("Popcorn Kernels",["Popcorn-Mais"],"Universal","Grains & Flour","kg",3.0,"USA/Argentina",[], None,375,11.0,74.0,4.5,"Dry Storage"),
("Arborio Superfino",["Arborio Superfino"],"European","Grains & Flour","kg",4.8,"Piedmont, Italy",[], "Carnaroli rice",349,7.0,77.0,0.6,"Dry Storage"),
("Vialone Nano",["Vialone Nano"],"European","Grains & Flour","kg",6.0,"Veneto, Italy",[], "Carnaroli rice",349,7.0,77.0,0.6,"Dry Storage"),
("Bomba Rice",["Bomba-Reis"],"European","Grains & Flour","kg",8.5,"Valencia, Spain",[], "Carnaroli rice",350,7.0,77.5,0.6,"Dry Storage"),
("Red Rice Camargue",["roter Camargue-Reis"],"European","Grains & Flour","kg",7.0,"Camargue, France",[], "Black rice",352,8.0,74.0,2.5,"Dry Storage"),
("Paella Rice Senia",["Paella-Reis"],"European","Grains & Flour","kg",5.0,"Spain",[], "Bomba rice",350,7.0,77.5,0.6,"Dry Storage"),
("Jasmine Rice Premium",["Jasminreis AAA"],"Asian","Grains & Flour","kg",4.2,"Thailand",[], "Basmati rice",365,7.1,79.5,0.7,"Dry Storage"),
("Brown Basmati",["Vollkorn-Basmati"],"Asian","Grains & Flour","kg",5.5,"India/Pakistan",[], "Basmati rice",362,8.5,76.0,2.7,"Dry Storage"),
("Rice Flakes",["Reisflocken"],"Asian","Grains & Flour","kg",4.5,"India",[], "Rolled oats",360,7.0,78.0,1.0,"Dry Storage"),
("Spelt Flakes",["Dinkelflocken"],"European","Grains & Flour","kg",3.0,"Switzerland",[], "Rolled oats",370,14.0,63.0,2.7,"Dry Storage"),
("Rye Flakes",["Roggenflocken"],"European","Grains & Flour","kg",2.8,"Switzerland/Germany",[], "Spelt flakes",349,10.0,70.0,1.7,"Dry Storage"),
("Bee Pollen",["Blütenpollen"],"European","Other","kg",32.0,"Switzerland/Spain",[], None,314,21.0,48.0,5.0,"Dry Storage"),
("Royal Jelly Note",["Gelée Royale"],"European","Other","kg",380.0,"Switzerland/China",[], None,150,12.0,15.0,5.0,"Refrigerated"),
("Spirulina Powder",["Spirulina-Pulver"],"Universal","Other","kg",38.0,"India/China",[], "Matcha (color)",290,57.5,23.9,7.7,"Dry Storage"),
("Beetroot Powder",["Randenpulver"],"European","Other","kg",26.0,"EU",[], "Beetroot juice reduced",340,12.0,70.0,1.0,"Dry Storage"),
("Tomato Powder",["Tomatenpulver"],"European","Other","kg",28.0,"EU",[], "Tomato paste dried",300,10.0,60.0,2.0,"Dry Storage"),
("Porcini Powder",["Steinpilzpulver"],"European","Spices & Seasonings","kg",70.0,"Italy",[], "Dried porcini ground",370,30.0,50.0,3.0,"Dry Storage"),
("Yeast Flakes",["Hefeflocken","Nutritional Yeast"],"Universal","Other","kg",18.0,"EU",[], "Parmesan (vegan swap)",380,45.0,32.0,5.0,"Dry Storage"),
("Kala Namak",["Kala Namak","Schwarzsalz"],"Asian","Spices & Seasonings","kg",9.0,"India",[], "Fleur de sel",0,0.0,0.0,0.0,"Dry Storage"),
("Pretzel Salt",["Brezelsalz"],"European","Spices & Seasonings","kg",4.0,"Germany",[], "Coarse sea salt",0,0.0,0.0,0.0,"Dry Storage"),
("Curing Salt",["Pökelsalz","Nitritpökelsalz"],"European","Spices & Seasonings","kg",3.5,"Switzerland/Germany",[], None,0,0.0,0.0,0.0,"Dry Storage"),
("Rock Salt Coarse",["grobes Steinsalz"],"Universal","Spices & Seasonings","kg",2.0,"Switzerland (Bex)",[], "Coarse sea salt",0,0.0,0.0,0.0,"Dry Storage"),
("Vanilla Extract",["Vanilleextrakt"],"Universal","Spices & Seasonings","l",48.0,"Madagascar",[], "Vanilla paste",288,0.1,12.7,0.1,"Dry Storage"),
("Almond Extract",["Bittermandelaroma"],"Universal","Spices & Seasonings","l",32.0,"EU",[], "Amaretto",250,0.0,10.0,0.0,"Dry Storage"),
("Orange Extract",["Orangenaroma"],"Universal","Spices & Seasonings","l",30.0,"EU",[], "Orange zest",240,0.0,10.0,0.0,"Dry Storage"),
("Coffee Extract",["Kaffee-Extrakt"],"Universal","Spices & Seasonings","l",28.0,"EU",[], "Espresso reduced",180,1.0,40.0,0.0,"Dry Storage"),
("Pandan Extract",["Pandan-Extrakt"],"Asian","Spices & Seasonings","l",22.0,"Thailand",[], "Vanilla extract",200,0.5,45.0,0.0,"Dry Storage"),
("Ube Purée",["Ube-Püree","lila Yam"],"Asian","Fruit","kg",16.0,"Philippines",[], "Sweet potato purée",120,1.0,27.0,0.1,"Freezer"),
("Passion Fruit Seeds Note",["Passionsfruchtkerne"],"Universal","Fruit","kg",30.0,"Ecuador",[], None,100,2.0,23.0,0.7,"Freezer"),
("Duck Confit Legs",["Confit de Canard"],"European","Poultry","kg",24.0,"France",[], "Duck legs",290,22.0,0.0,22.0,"Refrigerated"),
("Foie Gras",["Foie Gras","Entenstopfleber"],"European","Poultry","kg",95.0,"France/Hungary",[], "Chicken liver parfait",462,7.5,4.7,44.0,"Refrigerated"),
("Chicken Liver Parfait",["Geflügelleber-Parfait"],"European","Poultry","kg",18.0,"Switzerland/France",[], "Foie gras",320,10.0,4.0,29.0,"Refrigerated"),
("Rillettes",["Rillettes"],"European","Meat","kg",16.0,"France",[], "Chicken liver parfait",430,15.0,1.0,41.0,"Refrigerated"),
("Duck Prosciutto",["Entenschinken"],"European","Poultry","kg",48.0,"France",[], "Bresaola",240,25.0,0.5,15.0,"Refrigerated"),
("Lardo",["Lardo di Colonnata"],"European","Meat","kg",24.0,"Tuscany, Italy",[], "Guanciale",770,3.0,0.0,84.0,"Refrigerated"),
("Speck Alto Adige",["Südtiroler Speck"],"European","Meat","kg",24.0,"South Tyrol, Italy",[], "Prosciutto crudo",300,28.0,0.5,20.0,"Refrigerated"),
("Salsiccia Fresh",["Salsiccia frisch"],"European","Meat","kg",13.0,"Italy",[], "Bratwurst",280,15.0,1.0,24.0,"Refrigerated"),
("Merguez",["Merguez"],"Universal","Meat","kg",15.0,"North Africa/France",[], "Salsiccia fresh",280,15.5,1.5,23.5,"Refrigerated"),
("Chipolata",["Chipolata"],"European","Meat","kg",12.5,"France/Switzerland",[], "Bratwurst",300,13.0,1.5,27.0,"Refrigerated"),
("Toulouse Sausage",["Saucisse de Toulouse"],"European","Meat","kg",14.0,"France",[], "Salsiccia fresh",290,15.0,1.0,25.0,"Refrigerated"),
("Saucisson Vaudois",["Saucisson Vaudois IGP"],"European","Meat","kg",22.0,"Vaud, Switzerland",[], "Saucisse de Toulouse",340,16.0,1.0,30.0,"Refrigerated"),
("Longeole",["Longeole IGP"],"European","Meat","kg",20.0,"Geneva, Switzerland",[], "Saucisson Vaudois",330,15.0,2.0,29.0,"Refrigerated"),
("Appenzeller Siedwurst",["Siedwurst"],"European","Meat","kg",14.0,"Appenzell, Switzerland",[], "Cervelat",260,12.5,2.0,22.0,"Refrigerated"),
("Schüblig",["Schüblig"],"European","Meat","kg",15.0,"St. Gallen, Switzerland",[], "Cervelat",290,12.0,1.5,26.0,"Refrigerated"),
("Salametti",["Salametti"],"European","Meat","kg",24.0,"Ticino, Switzerland",[], "Salami Milano",420,24.0,1.5,35.0,"Room Temperature"),
("Coppa Ticinese",["Coppa Ticinese"],"European","Meat","kg",34.0,"Ticino, Switzerland",[], "Coppa",310,22.0,0.5,25.0,"Refrigerated"),
("Smoked Duck Breast",["geräucherte Entenbrust"],"European","Poultry","kg",38.0,"France",[], "Duck prosciutto",220,22.0,0.5,14.5,"Refrigerated"),
("Pastrami",["Pastrami"],"Universal","Meat","kg",26.0,"USA style/EU",[], "Smoked ham",150,21.0,1.5,6.5,"Refrigerated"),
("Corned Beef",["Corned Beef"],"Universal","Meat","kg",16.0,"Brazil/EU",[], "Pastrami",220,26.0,0.5,12.5,"Refrigerated"),
("Beef Jerky",["Beef Jerky"],"Universal","Meat","kg",42.0,"USA/EU",[], "Dried beef",410,50.0,10.0,17.0,"Dry Storage"),
("Bone Broth Concentrate",["Knochenbrühe konzentriert"],"Universal","Sauces & Condiments","l",14.0,"Switzerland/Germany",[], "Veal stock",40,7.0,1.0,1.0,"Refrigerated"),
("Marrow Bones Split",["Markknochen längs halbiert"],"European","Meat","kg",5.5,"Switzerland",[], "Beef bones",120,10.0,0.0,9.0,"Freezer"),
("Pig Trotters",["Schweinsfüsse"],"European","Meat","kg",4.5,"Switzerland",[], "Pork knuckle",212,22.0,0.0,14.0,"Freezer"),
("Beef Tallow",["Rindertalg"],"European","Meat","kg",5.0,"Switzerland",[], "Duck fat",902,0.0,0.0,100.0,"Refrigerated"),
("Suet",["Nierenfett"],"European","Meat","kg",4.5,"Switzerland/UK",[], "Beef tallow",854,1.5,0.0,94.0,"Refrigerated"),
("Ox Cheek Braised",["geschmorte Ochsenbacken vorgegart"],"European","Meat","kg",26.0,"Switzerland",[], "Beef cheeks",180,24.0,2.0,8.5,"Freezer"),
("Pulled Pork Cooked",["Pulled Pork vorgegart"],"Universal","Meat","kg",16.0,"EU",[], "Pork shoulder",210,24.0,1.0,12.0,"Freezer"),
("Beef Burger Patty 180g",["Burger-Patty 180g"],"Universal","Meat","pc",2.4,"Switzerland",[], "Ground beef",250,17.0,0.0,20.0,"Freezer"),
("Veggie Patty",["Gemüse-Patty"],"Universal","Dairy Alternatives","pc",1.6,"Switzerland/EU",[], "Beef burger patty",180,6.0,18.0,9.0,"Freezer"),
("Plant-Based Mince",["veganes Hack"],"Universal","Dairy Alternatives","kg",11.0,"Switzerland/EU",[], "Ground beef",190,18.0,6.0,10.0,"Refrigerated"),
("Jackfruit Young",["junge Jackfrucht"],"Asian","Vegetable","kg",7.5,"Sri Lanka/Thailand",[], "Pulled pork (vegan swap)",30,1.5,6.5,0.2,"Dry Storage"),
("Banana Blossom",["Bananenblüte"],"Asian","Vegetable","kg",8.0,"Sri Lanka/Vietnam",[], "Artichoke hearts",50,1.5,10.0,0.5,"Dry Storage"),
("Hearts of Palm",["Palmherzen"],"Universal","Vegetable","kg",9.5,"Ecuador/Costa Rica",[], "White asparagus",28,2.5,4.5,0.5,"Dry Storage"),
("Grape Leaves in Brine",["Weinblätter eingelegt"],"European","Vegetable","kg",8.0,"Turkey/Greece",[], "Chard leaves",50,3.5,8.5,1.0,"Dry Storage"),
("Pickled Ginger",["eingelegter Ingwer","Gari"],"Asian","Sauces & Condiments","kg",8.5,"Japan/China",[], "Fresh ginger",50,0.3,12.0,0.2,"Refrigerated"),
("Menma",["Menma","fermentierter Bambus"],"Asian","Sauces & Condiments","kg",12.0,"Japan/China",[], "Bamboo shoots fresh",40,2.0,7.0,0.5,"Refrigerated"),
("Pickled Red Onions",["eingelegte rote Zwiebeln"],"Universal","Sauces & Condiments","kg",7.0,"Switzerland (house-style)",[], "Red onion + vinegar",45,1.0,10.0,0.1,"Refrigerated"),
("Giardiniera",["Giardiniera"],"European","Sauces & Condiments","kg",7.5,"Italy",[], "Cornichons",35,1.0,7.0,0.2,"Dry Storage"),
("Pickled Beetroot",["Randen eingelegt"],"European","Sauces & Condiments","kg",5.0,"Switzerland",[], "Beetroot",60,1.2,13.0,0.1,"Dry Storage"),
("Fermented Black Beans",["fermentierte schwarze Bohnen","Douchi"],"Asian","Sauces & Condiments","kg",9.5,"China",[], "Black bean sauce",240,20.0,25.0,8.0,"Dry Storage"),
("Umeboshi",["Umeboshi","Salzpflaumen"],"Asian","Sauces & Condiments","kg",26.0,"Japan",[], "Preserved lemons",35,0.9,8.0,0.2,"Refrigerated"),
("Yuzu Marmalade",["Yuzu-Marmelade","Yuja-cheong"],"Asian","Sauces & Condiments","kg",22.0,"Korea/Japan",[], "Bitter orange marmalade",250,0.3,62.0,0.1,"Refrigerated"),
("XO Sauce",["XO-Sauce"],"Asian","Sauces & Condiments","kg",48.0,"Hong Kong",[], "Doubanjiang + dried shrimp",320,12.0,15.0,25.0,"Refrigerated"),
("Chili Crisp",["Chili Crisp","Chiliöl mit Crunch"],"Asian","Sauces & Condiments","kg",14.0,"China",[], "Chili oil",520,5.0,20.0,46.0,"Dry Storage"),
("Chili Oil",["Chiliöl"],"Asian","Oils & Vinegars","l",11.0,"China/Italy",[], "Chili crisp",884,0.0,0.0,100.0,"Dry Storage"),
("Garlic Oil",["Knoblauchöl"],"Universal","Oils & Vinegars","l",10.0,"Italy/Spain",[], "Garlic + olive oil",884,0.0,0.0,100.0,"Dry Storage"),
("Basil Oil",["Basilikumöl"],"European","Oils & Vinegars","l",16.0,"Italy",[], "Basil + olive oil",884,0.0,0.0,100.0,"Refrigerated"),
("Lemon Olive Oil",["Zitronen-Olivenöl"],"European","Oils & Vinegars","l",15.0,"Italy",[], "Olive oil + lemon zest",884,0.0,0.0,100.0,"Dry Storage"),
("Avocado Oil",["Avocadoöl"],"Universal","Oils & Vinegars","l",16.0,"Mexico/Kenya",[], "Grapeseed oil",884,0.0,0.0,100.0,"Dry Storage"),
("Coconut Oil Virgin",["Kokosöl nativ"],"Asian","Oils & Vinegars","kg",9.0,"Philippines/Sri Lanka",[], "Clarified butter",892,0.0,0.0,99.1,"Dry Storage"),
("Argan Oil Culinary",["Arganöl"],"Universal","Oils & Vinegars","l",48.0,"Morocco",[], "Walnut oil",884,0.0,0.0,100.0,"Dry Storage"),
("Raspberry Vinegar",["Himbeeressig"],"European","Oils & Vinegars","l",10.0,"France/Switzerland",[], "Red wine vinegar",30,0.2,5.0,0.0,"Dry Storage"),
("Tarragon Vinegar",["Estragonessig"],"European","Oils & Vinegars","l",8.5,"France",[], "White wine vinegar",20,0.0,1.0,0.0,"Dry Storage"),
("Malt Vinegar",["Malzessig"],"European","Oils & Vinegars","l",5.0,"UK",[], "Cider vinegar",18,0.0,1.0,0.0,"Dry Storage"),
("Ume Vinegar",["Ume-Essig"],"Asian","Oils & Vinegars","l",16.0,"Japan",[], "Rice vinegar + salt",25,0.5,3.0,0.0,"Dry Storage"),
("White Balsamic",["Condimento bianco"],"European","Oils & Vinegars","l",8.0,"Modena, Italy",[], "Champagne vinegar",90,0.2,20.0,0.0,"Dry Storage"),
("Pine Nuts Mediterranean",["Pinienkerne mediterran"],"European","Nuts & Seeds","kg",48.0,"Spain/Italy",[], "Pine nuts",673,13.7,13.1,68.4,"Refrigerated"),
("Tigernuts",["Erdmandeln","Chufa"],"European","Nuts & Seeds","kg",12.0,"Valencia, Spain",[], "Almonds",450,4.5,63.0,24.0,"Dry Storage"),
("Watermelon Seeds",["Wassermelonenkerne geröstet"],"Universal","Nuts & Seeds","kg",14.0,"Middle East",[], "Pumpkin seeds",557,28.3,15.3,47.4,"Dry Storage"),
("Sacha Inchi",["Sacha-Inchi-Samen"],"Universal","Nuts & Seeds","kg",26.0,"Peru",[], "Hemp seeds",560,27.0,17.0,45.0,"Dry Storage"),
("Candlenuts",["Kemiri-Nüsse"],"Asian","Nuts & Seeds","kg",18.0,"Indonesia",[], "Macadamia",620,8.0,8.0,63.0,"Dry Storage"),
("Chestnuts Vacuum Cooked",["Marroni vakuum gegart"],"European","Nuts & Seeds","kg",13.0,"France/Italy",["Autumn","Winter"], "Chestnuts",165,2.4,35.0,1.4,"Dry Storage"),
("Sesame Brittle",["Sesamkrokant"],"Universal","Nuts & Seeds","kg",12.0,"Greece/Turkey",[], "Nut brittle",500,12.0,55.0,26.0,"Dry Storage"),
("Nut Brittle",["Nusskrokant"],"European","Nuts & Seeds","kg",11.0,"Switzerland/Germany",[], "Sesame brittle",520,10.0,58.0,28.0,"Dry Storage"),
("Candied Ginger",["kandierter Ingwer"],"Asian","Sweeteners","kg",10.0,"Thailand/Australia",[], "Candied orange peel",340,0.3,86.0,0.2,"Dry Storage"),
("Candied Violets",["kandierte Veilchen"],"European","Sweeteners","kg",90.0,"Toulouse, France",[], "Candied rose petals",380,0.0,95.0,0.0,"Dry Storage"),
("Honeycomb",["Wabenhonig"],"European","Sweeteners","kg",26.0,"Switzerland",[], "Mountain honey",320,0.3,82.0,0.5,"Dry Storage"),
("Stevia Powder",["Stevia-Pulver"],"Universal","Sweeteners","kg",45.0,"Paraguay/China",[], "Erythritol",0,0.0,0.0,0.0,"Dry Storage"),
("Erythritol",["Erythrit"],"Universal","Sweeteners","kg",9.0,"EU/China",[], "Stevia powder",20,0.0,100.0,0.0,"Dry Storage"),
("Dulce de Leche",["Dulce de Leche"],"Universal","Sweeteners","kg",8.5,"Argentina",[], "Caramel + condensed milk",315,6.5,55.0,7.5,"Dry Storage"),
("Caramel Sauce",["Caramelsauce"],"European","Sweeteners","kg",7.0,"Switzerland/France",[], "Dulce de leche",320,1.5,65.0,7.0,"Dry Storage"),
("Salted Butter Caramel",["Caramel au Beurre Salé"],"European","Sweeteners","kg",12.0,"Brittany, France",[], "Caramel sauce",380,1.5,60.0,15.0,"Dry Storage"),
("Rice Syrup",["Reissirup"],"Asian","Sweeteners","l",8.0,"EU/Asia",[], "Glucose syrup",310,0.5,78.0,0.2,"Dry Storage"),
("Malt Extract",["Malzextrakt"],"European","Sweeteners","kg",7.5,"Switzerland/Germany",[], "Molasses",300,6.0,71.0,0.5,"Dry Storage"),
("Barley Malt Syrup",["Gerstenmalzsirup"],"European","Sweeteners","l",8.0,"Germany",[], "Malt extract",300,6.0,71.0,0.5,"Dry Storage"),
("Chicory Syrup",["Zichoriensirup"],"European","Sweeteners","l",9.5,"Belgium/France",[], "Date syrup",290,0.0,70.0,0.0,"Dry Storage"),
("Mostarda di Cremona",["Mostarda"],"European","Sauces & Condiments","kg",16.0,"Cremona, Italy",["Winter"], "Chutney mango",280,0.5,68.0,0.2,"Dry Storage"),
("Membrillo Sticks Note",["Quittenschnitten"],"European","Sweeteners","kg",14.0,"Spain",[], "Quince paste",235,0.3,58.0,0.1,"Dry Storage"),
("Elderberry Syrup",["Holundersirup"],"European","Sweeteners","l",9.0,"Switzerland/Austria",["Autumn"], "Elderflower syrup",280,0.2,69.0,0.0,"Dry Storage"),
("Mint Syrup",["Minzsirup"],"European","Sweeteners","l",6.5,"France",[], "Elderflower syrup",270,0.0,68.0,0.0,"Dry Storage"),
("Violet Syrup",["Veilchensirup"],"European","Sweeteners","l",12.0,"Toulouse, France",[], "Mint syrup",270,0.0,68.0,0.0,"Dry Storage"),
("Vanilla Ice Base",["Vanille-Glacebasis"],"Universal","Dairy","l",5.5,"Switzerland",[], "Ice cream vanilla pro",180,3.5,22.0,8.5,"Refrigerated"),
("Panna Cotta Base",["Panna-Cotta-Basis"],"European","Dairy","l",6.5,"Italy/Switzerland",[], "Cream + gelatin",220,2.5,20.0,14.0,"Refrigerated"),
("Crème Anglaise",["Crème Anglaise Gastro"],"European","Dairy","l",7.0,"France/Switzerland",[], "Vanilla ice base",150,3.5,17.0,7.0,"Refrigerated"),
("Custard Powder",["Puddingpulver Vanille"],"European","Bakery","kg",6.0,"Switzerland/UK",[], "Crème anglaise",380,0.5,88.0,1.5,"Dry Storage"),
("Mascarpone Cream Base",["Tiramisu-Basis"],"European","Dairy","kg",9.5,"Italy",[], "Mascarpone + eggs",320,5.5,18.0,25.0,"Refrigerated"),
("Egg Wash Ready",["Eistreiche"],"European","Eggs","l",6.0,"Switzerland",[], "Liquid whole egg",150,11.0,1.5,10.5,"Refrigerated"),
("Aquafaba",["Aquafaba","Kichererbsenwasser"],"Universal","Eggs","l",3.0,"EU",[], "Egg white",15,1.0,2.5,0.1,"Refrigerated"),
("Ostrich Egg Note",["Straussenei"],"Universal","Eggs","pc",28.0,"South Africa/Switzerland",[], "24 chicken eggs",143,12.5,0.7,9.7,"Refrigerated"),
("Century Egg",["tausendjähriges Ei"],"Asian","Eggs","pc",1.8,"China",[], None,180,13.0,3.0,13.0,"Refrigerated"),
("Salted Duck Egg",["gesalzenes Entenei"],"Asian","Eggs","pc",1.5,"China/Vietnam",[], "Century egg",190,13.5,2.0,14.5,"Refrigerated"),
("Smoked Egg",["geräuchertes Ei"],"European","Eggs","pc",0.9,"Switzerland (house-style)",[], "Free-range eggs",145,12.5,0.8,9.8,"Refrigerated"),
("Truffle Honey",["Trüffelhonig"],"European","Sweeteners","kg",42.0,"Italy",[], "Acacia honey + truffle",310,0.4,80.0,0.5,"Dry Storage"),
("Saffron Honey",["Safranhonig"],"European","Sweeteners","kg",36.0,"Switzerland (Mund)",[], "Mountain honey",305,0.3,82.0,0.0,"Dry Storage"),
("Lavender Honey",["Lavendelhonig"],"European","Sweeteners","kg",18.0,"Provence, France",[], "Acacia honey",304,0.3,82.4,0.0,"Dry Storage"),
("Pine Honey",["Waldhonig Tanne"],"European","Sweeteners","kg",20.0,"Switzerland/Greece",[], "Chestnut honey",302,0.4,80.5,0.0,"Dry Storage"),
("Fir Tip Syrup",["Tannenschösslisirup"],"European","Sweeteners","l",16.0,"Swiss Alps",["Spring"], "Pine honey",280,0.0,70.0,0.0,"Dry Storage"),
]
