ITEMS = [
# --- Herbs (fresh, missing kinds) ---
("Lemon Verbena Fresh",["Zitronenverbene frisch"],"European","Herbs","kg",38.0,"Switzerland/France",["Summer"], "Lemon balm",50,3.0,10.0,0.5,"Refrigerated"),
("Lemon Balm",["Zitronenmelisse"],"European","Herbs","kg",22.0,"Switzerland",["Summer"], "Lemon verbena",49,3.7,8.0,0.4,"Refrigerated"),
("Lovage",["Liebstöckel","Maggikraut"],"European","Herbs","kg",18.0,"Switzerland",["Summer"], "Celery leaves",50,3.5,9.0,0.6,"Refrigerated"),
("Sorrel",["Sauerampfer"],"European","Herbs","kg",16.0,"Switzerland",["Spring","Summer"], "Spinach + lemon",22,2.0,3.2,0.7,"Refrigerated"),
("Chervil",["Kerbel"],"European","Herbs","kg",24.0,"Switzerland/France",["Spring"], "Parsley + tarragon",48,3.3,8.5,0.9,"Refrigerated"),
("Savory",["Bohnenkraut"],"European","Herbs","kg",18.0,"Switzerland",["Summer"], "Thyme",50,4.0,9.0,1.0,"Refrigerated"),
("Marjoram Fresh",["Majoran frisch"],"European","Herbs","kg",20.0,"Switzerland",["Summer"], "Oregano",60,4.0,11.0,1.5,"Refrigerated"),
("Borage",["Borretsch"],"European","Herbs","kg",16.0,"Switzerland",["Summer"], "Cucumber + parsley",21,1.8,3.0,0.7,"Refrigerated"),
("Nasturtium",["Kapuzinerkresse"],"European","Herbs","kg",28.0,"Switzerland",["Summer"], "Watercress",25,2.0,4.0,0.3,"Refrigerated"),
("Edible Flowers Mix",["Essblüten-Mischung"],"European","Herbs","kg",95.0,"Switzerland",["Spring","Summer"], "Nasturtium",25,2.0,4.0,0.3,"Refrigerated"),
("Micro Greens Mix",["Microgreens"],"Universal","Herbs","kg",65.0,"Switzerland",[], "Cress",30,3.0,4.5,0.5,"Refrigerated"),
("Garden Cress",["Gartenkresse"],"European","Herbs","kg",18.0,"Switzerland",[], "Watercress",32,2.6,5.5,0.7,"Refrigerated"),
("Thai Basil",["Thai-Basilikum"],"Asian","Herbs","kg",26.0,"Thailand/Netherlands",[], "Basil",23,3.2,2.7,0.6,"Refrigerated"),
("Vietnamese Coriander",["Rau Ram"],"Asian","Herbs","kg",30.0,"Vietnam/Netherlands",[], "Cilantro",25,3.0,4.0,0.5,"Refrigerated"),
("Epazote",["Epazote"],"Universal","Herbs","kg",32.0,"Mexico",[], "Oregano",32,0.3,7.4,0.5,"Refrigerated"),
("Fresh Bay Leaves",["Lorbeer frisch"],"European","Herbs","kg",14.0,"Mediterranean",[], "Dried bay leaves",313,7.6,75.0,8.4,"Refrigerated"),
("Fresh Oregano",["Oregano frisch"],"European","Herbs","kg",19.0,"Switzerland/Italy",["Summer"], "Marjoram fresh",66,2.2,9.0,2.0,"Refrigerated"),
("Fresh Lavender",["Lavendel frisch"],"European","Herbs","kg",30.0,"Provence, France",["Summer"], "Rosemary",49,4.0,10.0,1.0,"Refrigerated"),
# --- Vegetables round 2 (potato varieties, alliums, misc) ---
("Ratte Potatoes",["Ratte-Kartoffeln"],"European","Vegetable","kg",4.2,"France/Switzerland",["Autumn","Winter"], "Fingerling potatoes",77,2.0,17.0,0.1,"Dry Storage"),
("Fingerling Potatoes",["Bamberger Hörnchen"],"European","Vegetable","kg",4.5,"Switzerland/Germany",["Autumn","Winter"], "Ratte potatoes",77,2.0,17.0,0.1,"Dry Storage"),
("Agria Potatoes",["Agria-Kartoffeln"],"European","Vegetable","kg",1.4,"Switzerland",[], "Floury potatoes",77,2.0,17.0,0.1,"Dry Storage"),
("Charlotte Potatoes",["Charlotte-Kartoffeln"],"European","Vegetable","kg",1.6,"Switzerland",[], "Waxy potatoes",77,2.0,17.0,0.1,"Dry Storage"),
("New Potatoes",["Frühkartoffeln"],"European","Vegetable","kg",2.8,"Switzerland",["Spring","Summer"], "Charlotte potatoes",70,1.9,15.5,0.1,"Refrigerated"),
("Blue Potatoes",["blaue Kartoffeln","Vitelotte"],"European","Vegetable","kg",5.5,"France/Switzerland",["Autumn","Winter"], "Agria potatoes",80,2.0,17.5,0.1,"Dry Storage"),
("Banana Shallots",["Bananenschalotten","Echalion"],"European","Vegetable","kg",6.0,"France",[], "Shallots",72,2.5,16.8,0.1,"Dry Storage"),
("Red Onion",["rote Zwiebeln"],"Universal","Vegetable","kg",2.2,"Switzerland/Italy",[], "Onion",40,1.1,9.3,0.1,"Dry Storage"),
("White Onion",["weisse Zwiebeln"],"European","Vegetable","kg",2.4,"Italy/Spain",[], "Onion",40,1.1,9.3,0.1,"Dry Storage"),
("Cipollini Onions",["Cipollini","Borettane"],"European","Vegetable","kg",6.5,"Italy",[], "Silverskin onions",42,1.2,10.0,0.1,"Dry Storage"),
("Smoked Garlic",["geräucherter Knoblauch"],"European","Vegetable","kg",14.0,"France",[], "Garlic",149,6.4,33.1,0.5,"Dry Storage"),
("Black Garlic",["schwarzer Knoblauch"],"Asian","Vegetable","kg",42.0,"Korea/Spain",[], "Garlic + balsamic",220,9.0,48.0,0.5,"Dry Storage"),
("Garlic Scapes",["Knoblauchsprossen"],"European","Vegetable","kg",12.0,"Switzerland",["Spring"], "Spring onion + garlic",60,2.0,13.0,0.2,"Refrigerated"),
("Baby Corn",["Baby-Mais"],"Asian","Vegetable","kg",8.0,"Thailand",[], "Corn kernels",26,1.9,5.0,0.2,"Refrigerated"),
("Okra",["Okra"],"Universal","Vegetable","kg",9.0,"Turkey/India",["Summer"], "Green beans",33,1.9,7.5,0.2,"Refrigerated"),
("Tomatillo",["Tomatillo"],"Universal","Vegetable","kg",11.0,"Mexico",["Summer"], "Green tomatoes",32,1.0,5.8,1.0,"Refrigerated"),
("Bitter Melon",["Bittermelone"],"Asian","Vegetable","kg",9.5,"India/Thailand",[], "Zucchini",17,1.0,3.7,0.2,"Refrigerated"),
("Chayote",["Chayote"],"Universal","Vegetable","kg",7.0,"Costa Rica",[], "Zucchini",19,0.8,4.5,0.1,"Refrigerated"),
("Yuca Root",["Maniok","Cassava"],"Universal","Vegetable","kg",5.5,"Costa Rica/Ghana",[], "Potato",160,1.4,38.1,0.3,"Dry Storage"),
("Taro",["Taro"],"Asian","Vegetable","kg",7.5,"China/Fiji",[], "Yuca root",112,1.5,26.5,0.2,"Dry Storage"),
("Water Chestnuts Fresh",["Wasserkastanien"],"Asian","Vegetable","kg",10.0,"China",[], "Lotus root",97,1.4,23.9,0.1,"Refrigerated"),
("Hokkaido Pumpkin",["Hokkaido-Kürbis"],"European","Vegetable","kg",2.8,"Switzerland",["Autumn","Winter"], "Butternut squash",63,1.7,12.6,0.5,"Dry Storage"),
("Butternut Squash",["Butternusskürbis"],"Universal","Vegetable","kg",2.6,"Switzerland/Portugal",["Autumn","Winter"], "Hokkaido pumpkin",45,1.0,11.7,0.1,"Dry Storage"),
("Spaghetti Squash",["Spaghettikürbis"],"Universal","Vegetable","kg",3.8,"Switzerland/Spain",["Autumn"], "Butternut squash",31,0.6,7.0,0.6,"Dry Storage"),
("Patisson",["Patisson","Ufo-Kürbis"],"European","Vegetable","kg",4.5,"Switzerland",["Summer"], "Zucchini",18,1.2,3.8,0.2,"Refrigerated"),
("Mini Cucumbers",["Snack-Gurken"],"European","Vegetable","kg",5.0,"Switzerland/Spain",["Summer"], "Cucumber",15,0.7,3.6,0.1,"Refrigerated"),
("Avocado Hass",["Avocado Hass"],"Universal","Fruit","kg",7.5,"Peru/Spain",[], None,160,2.0,8.5,14.7,"Room Temperature"),
("Sprouted Mung Beans",["Mungobohnensprossen"],"Asian","Vegetable","kg",5.5,"Switzerland",[], "Soy sprouts",30,3.0,5.9,0.2,"Refrigerated"),
("Alfalfa Sprouts",["Alfalfa-Sprossen"],"Universal","Vegetable","kg",12.0,"Switzerland",[], "Sprouted mung beans",23,4.0,2.1,0.7,"Refrigerated"),
("Pea Shoots",["Erbsensprossen"],"Universal","Vegetable","kg",18.0,"Switzerland",["Spring"], "Micro greens mix",42,4.0,7.5,0.4,"Refrigerated"),
# --- Eggs & convenience basics ---
("Free-Range Eggs",["Freilandeier CH"],"Universal","Eggs","pc",0.55,"Switzerland",[], "Egg",143,12.6,0.7,9.5,"Refrigerated"),
("Organic Eggs",["Bio-Eier CH"],"Universal","Eggs","pc",0.75,"Switzerland",[], "Free-range eggs",143,12.6,0.7,9.5,"Refrigerated"),
("Duck Eggs",["Enteneier"],"European","Eggs","pc",1.2,"Switzerland/France",[], "Chicken egg",185,12.8,1.5,13.8,"Refrigerated"),
("Egg White Powder",["Eiweisspulver"],"Universal","Eggs","kg",28.0,"EU",[], "Liquid egg white",380,82.0,7.0,0.5,"Dry Storage"),
("Mayonnaise Pro",["Mayonnaise Gastro"],"Universal","Sauces & Condiments","kg",5.5,"Switzerland",[], "Mayonnaise",680,1.0,2.5,74.0,"Refrigerated"),
("Veal Stock",["Kalbsfond"],"European","Sauces & Condiments","l",9.0,"Switzerland",[], "Beef stock",25,3.0,2.5,0.5,"Refrigerated"),
("Chicken Stock",["Geflügelfond"],"Universal","Sauces & Condiments","l",7.0,"Switzerland",[], "Vegetable stock",20,2.5,2.0,0.5,"Refrigerated"),
("Fish Stock",["Fischfond"],"European","Sauces & Condiments","l",8.5,"Switzerland/France",[], "Vegetable stock",18,2.5,1.5,0.4,"Refrigerated"),
("Vegetable Stock Paste",["Gemüsebouillon-Paste"],"Universal","Sauces & Condiments","kg",9.0,"Switzerland",[], "Vegetable stock",180,8.0,25.0,5.0,"Refrigerated"),
("Demi-Glace",["Demi-Glace"],"European","Sauces & Condiments","kg",18.0,"Switzerland/France",[], "Veal stock reduced",120,10.0,12.0,3.0,"Refrigerated"),
("Glace de Viande",["Fleischglace"],"European","Sauces & Condiments","kg",26.0,"Switzerland/France",[], "Demi-glace",180,18.0,15.0,4.0,"Refrigerated"),
("Lobster Bisque Base",["Hummerfond"],"European","Sauces & Condiments","l",16.0,"France",[], "Fish stock",45,4.0,4.5,1.5,"Refrigerated"),
("Beurre Blanc Base",["Beurre-Blanc-Basis"],"European","Sauces & Condiments","kg",14.0,"France",[], "Butter + white wine",450,1.0,3.0,48.0,"Refrigerated"),
("Hollandaise Pro",["Sauce Hollandaise Gastro"],"European","Sauces & Condiments","l",9.5,"Switzerland/Germany",[], "Beurre blanc base",330,2.0,5.0,34.0,"Refrigerated"),
("BBQ Sauce",["Barbecuesauce"],"Universal","Sauces & Condiments","l",6.0,"USA/EU",[], "Ketchup + smoke",150,1.0,35.0,0.5,"Dry Storage"),
("Chimichurri",["Chimichurri"],"Universal","Sauces & Condiments","kg",12.0,"Argentina",[], "Salsa verde",250,2.0,5.0,25.0,"Refrigerated"),
("Salsa Verde",["Salsa verde italienisch"],"European","Sauces & Condiments","kg",13.0,"Italy",[], "Chimichurri",260,2.5,4.0,26.0,"Refrigerated"),
("Aioli",["Aioli"],"European","Sauces & Condiments","kg",9.0,"Spain/France",[], "Mayonnaise + garlic",650,1.5,3.5,70.0,"Refrigerated"),
("Tzatziki",["Tzatziki"],"European","Sauces & Condiments","kg",7.0,"Greece",[], "Greek yogurt + cucumber",85,3.5,4.0,6.0,"Refrigerated"),
("Guacamole",["Guacamole"],"Universal","Sauces & Condiments","kg",11.0,"Mexico/Peru",[], "Avocado Hass",150,1.9,8.0,13.0,"Freezer"),
("Baba Ganoush",["Baba Ghanoush"],"Universal","Sauces & Condiments","kg",10.0,"Lebanon",[], "Hummus",120,2.5,8.0,9.0,"Refrigerated"),
("Ajvar",["Ajvar"],"European","Sauces & Condiments","kg",7.5,"Serbia/Macedonia",[], "Roasted peppers in oil",80,1.5,12.0,3.0,"Dry Storage"),
("Chutney Mango",["Mango-Chutney"],"Asian","Sauces & Condiments","kg",8.5,"India",[], "Apricot jam + vinegar",220,0.5,54.0,0.2,"Dry Storage"),
("Cranberry Sauce",["Preiselbeerkompott"],"European","Sauces & Condiments","kg",8.0,"Switzerland/Scandinavia",["Autumn","Winter"], "Lingonberry",190,0.3,47.0,0.1,"Dry Storage"),
("Apple Compote",["Apfelkompott"],"European","Sauces & Condiments","kg",4.0,"Switzerland",[], "Apple purée",80,0.2,19.5,0.2,"Dry Storage"),
("Strawberry Jam",["Erdbeerkonfitüre"],"European","Sauces & Condiments","kg",6.0,"Switzerland",[], "Raspberry jam",250,0.4,60.0,0.1,"Dry Storage"),
("Raspberry Jam",["Himbeerkonfitüre"],"European","Sauces & Condiments","kg",6.5,"Switzerland",[], "Strawberry jam",250,0.5,60.0,0.2,"Dry Storage"),
("Bitter Orange Marmalade",["Orangenmarmelade"],"European","Sauces & Condiments","kg",7.0,"Scotland/Spain",[], "Strawberry jam",246,0.3,60.0,0.1,"Dry Storage"),
("Rosehip Jam",["Hagenbuttenkonfitüre"],"European","Sauces & Condiments","kg",9.0,"Switzerland",["Autumn"], "Bitter orange marmalade",240,0.5,58.0,0.2,"Dry Storage"),
("Nut-Nougat Spread",["Nuss-Nougat-Creme"],"European","Sauces & Condiments","kg",8.0,"Italy/Switzerland",[], "Gianduja",540,6.0,57.0,31.0,"Dry Storage"),
("Peanut Butter",["Erdnussbutter"],"Universal","Sauces & Condiments","kg",7.5,"Argentina/USA",[], "Tahini",588,25.1,20.0,50.0,"Dry Storage"),
("Almond Butter",["Mandelmus"],"Universal","Sauces & Condiments","kg",16.0,"Spain/USA",[], "Peanut butter",614,21.0,18.8,55.5,"Dry Storage"),
("Coconut Flakes",["Kokosraspel"],"Asian","Nuts & Seeds","kg",6.0,"Philippines/Sri Lanka",[], "Coconut flour",660,6.9,23.7,64.5,"Dry Storage"),
("Coconut Flour",["Kokosmehl"],"Asian","Grains & Flour","kg",7.5,"Philippines",[], "Almond flour",400,19.0,45.0,12.0,"Dry Storage"),
("Almond Flour",["Mandelmehl"],"Universal","Grains & Flour","kg",13.0,"Spain/USA",[], "Ground almonds",590,21.0,20.0,50.0,"Dry Storage"),
("Croutons",["Croûtons"],"European","Bakery","kg",7.0,"Switzerland",[], "Stale bread",410,10.0,70.0,10.0,"Dry Storage"),
("Grissini",["Grissini"],"European","Bakery","kg",8.0,"Piedmont, Italy",[], "Croutons",420,11.0,72.0,9.0,"Dry Storage"),
("Taco Shells",["Taco-Schalen"],"Universal","Bakery","kg",12.0,"Mexico/EU",[], "Tortillas",480,7.0,60.0,23.0,"Dry Storage"),
("Corn Tortillas",["Maistortillas"],"Universal","Bakery","kg",7.5,"Mexico/EU",[], "Wheat tortillas",220,5.5,45.0,2.5,"Refrigerated"),
("Wheat Tortillas",["Weizentortillas","Wraps"],"Universal","Bakery","kg",6.0,"EU",[], "Corn tortillas",300,8.0,50.0,7.0,"Refrigerated"),
("Naan Bread",["Naan-Brot"],"Asian","Bakery","kg",8.0,"India/EU",[], "Pita bread",310,9.0,50.0,8.5,"Freezer"),
("Pita Bread",["Pitabrot"],"Universal","Bakery","kg",6.5,"Lebanon/EU",[], "Naan bread",275,9.0,55.0,1.2,"Freezer"),
("Brioche Buns",["Brioche-Buns"],"European","Bakery","pc",0.85,"France/Switzerland",[], "Burger buns",330,8.5,45.0,13.0,"Freezer"),
("Pretzel",["Laugenbrezel"],"European","Bakery","pc",0.9,"Germany/Switzerland",[], "Brioche buns",310,9.0,60.0,3.5,"Freezer"),
("Zopf",["Butterzopf"],"European","Bakery","kg",7.0,"Switzerland",[], "Brioche",350,9.5,52.0,11.0,"Room Temperature"),
("Ruchbrot",["Ruchbrot"],"European","Bakery","kg",4.5,"Switzerland",[], "Sourdough bread",250,8.5,50.0,1.5,"Room Temperature"),
("Walliser Roggenbrot AOP",["Walliser Roggenbrot"],"European","Bakery","kg",7.5,"Valais, Switzerland",[], "Rye bread",240,7.0,48.0,1.5,"Room Temperature"),
]
