-- 176_ingredient_info_backfill_batch6.sql
-- Ingredient info backfill — batch 6 (Richard, 23.7.2026). Same safety contract as db/171–175:
-- ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by name,
-- never overwrites — idempotent. Price stays per-kitchen and untouched.
-- Covers the alphabetical range "Edamame" → "Goat Milk" (180 names).
with m(name, flavour, origin, season) as (values
  ('Edamame', 'Sweet, grassy, buttery young soybean', 'Immature soybean, East Asia', 'Summer'),
  ('Edamame in Pod', 'Sweet, grassy, salted and eaten from the pod', 'Immature soybean, East Asia', 'Summer'),
  ('Edible Flower Mix', 'Delicate, floral, faintly sweet or peppery', 'Assorted edible flowers', 'Spring to summer'),
  ('Edible Flowers Mix', 'Delicate, floral, faintly sweet or peppery', 'Assorted edible flowers', 'Spring to summer'),
  ('Edible Gold Leaf', 'Flavourless; purely decorative', 'Hammered pure gold', 'Year-round'),
  ('Eel Bone', 'Savoury, gelatinous; used for stock and crisping', 'Eel frame', 'Year-round'),
  ('Eel Smoked', 'Rich, oily, deeply smoky', 'Smoked eel, Northern Europe', 'Autumn to winter'),
  ('Egg Noodles Or Dried Pasta', 'Rich and eggy, or neutral and wheaty', 'Egg noodles or durum pasta', 'Year-round'),
  ('Egg Powder', 'Neutral-eggy, concentrated', 'Dried whole egg', 'Year-round'),
  ('Egg Tagliatelle Dry', 'Rich, eggy, silky ribbons', 'Dried egg pasta, Emilia-Romagna, Italy', 'Year-round'),
  ('Egg Wash', 'Neutral; gives pastry a golden glaze', 'Beaten egg with milk or water', 'Year-round'),
  ('Egg Wash Ready', 'Neutral; ready-mixed glaze for pastry', 'Prepared beaten egg glaze', 'Year-round'),
  ('Egg White Powder', 'Neutral; whips to a stable foam', 'Dried egg white', 'Year-round'),
  ('Einkorn Flour', 'Sweet, nutty, golden ancient wheat', 'Milled einkorn wheat', 'Year-round'),
  ('Elbow Macaroni', 'Neutral, wheaty; classic short pasta', 'Durum-wheat pasta, Italy', 'Year-round'),
  ('Elderberry', 'Deep, tart, musky; must be cooked', 'Berry of the elder, Europe', 'Late summer to autumn'),
  ('Elderberry Syrup', 'Deep, tart-sweet, musky', 'Cooked elderberries with sugar', 'Made in autumn'),
  ('Elderflower', 'Intensely floral, honeyed, muscat-like', 'Elder blossom, Europe', 'Late spring to early summer'),
  ('Elderflower Syrup', 'Floral, honeyed, delicately sweet', 'Elderflower infusion with sugar', 'Made in early summer'),
  ('Elderflowers Dried', 'Muted floral, honeyed', 'Dried elder blossom, Europe', 'Year-round'),
  ('Emmentaler', 'Mild, nutty, sweet with large holes', 'Cow''s-milk cheese, Emmental, Switzerland', 'Year-round'),
  ('Emmentaler AOP', 'Nutty, sweet, firm; the protected original', 'Raw-milk cheese, Emmental, Switzerland', 'Year-round'),
  ('Emmentaler AOP Cave-Aged', 'Deeper, fruitier, more piquant with age', 'Cave-matured Emmentaler, Switzerland', 'Year-round'),
  ('English Mustard', 'Fiercely hot, sharp, clean', 'Mustard seed and turmeric, England', 'Year-round'),
  ('Enoki', 'Delicate, crisp, faintly fruity', 'Cultivated mushroom, East Asia', 'Year-round'),
  ('Enoki Mushroom', 'Delicate, crisp, faintly fruity', 'Cultivated mushroom, East Asia', 'Year-round'),
  ('Epazote', 'Pungent, resinous, faintly medicinal', 'Herb, Mexico', 'Summer'),
  ('Erythritol', 'Clean sweetness with a cooling finish', 'Sugar alcohol from fermentation', 'Year-round'),
  ('Escarole', 'Mildly bitter, sturdy, broad-leaved chicory', 'Chicory, Mediterranean', 'Autumn to winter'),
  ('Espelette Pepper', 'Fruity, warm, gently smoky mild heat', 'Ground chilli AOP, Basque Country, France', 'Harvested in autumn'),
  ('Espresso Beans', 'Dark-roasted, intense, bittersweet', 'Roasted coffee for espresso', 'Year-round'),
  ('Espresso Ground', 'Dark-roasted, intense, bittersweet', 'Finely ground espresso coffee', 'Year-round'),
  ('Espresso Powder', 'Concentrated, bitter, deeply roasted', 'Instant espresso powder', 'Year-round'),
  ('Espuma Charger N2O', 'Flavourless; the gas that aerates foams', 'Nitrous oxide charger', 'Year-round'),
  ('Etivaz Rebibes', 'Intense, fruity, shaved in fine curls', 'Shavings of L''Etivaz AOP, Vaud, Switzerland', 'Year-round'),
  ('Evaporated Milk', 'Concentrated, faintly cooked-milk sweetness', 'Milk with water removed', 'Year-round'),
  ('Farfalle', 'Neutral, wheaty; bow-tie shape', 'Durum-wheat pasta, Italy', 'Year-round'),
  ('Farro', 'Nutty, chewy, wholesome', 'Ancient wheat grain, Italy', 'Year-round'),
  ('Fava Bean', 'Sweet, green, faintly bitter skin', 'Broad bean, Mediterranean', 'Spring to early summer'),
  ('Fava Beans', 'Sweet, green, faintly bitter skin', 'Broad beans, Mediterranean', 'Spring to early summer'),
  ('Fendant Wine', 'Dry, mineral, gently floral white', 'Chasselas wine, Valais, Switzerland', 'Year-round'),
  ('Fennel', 'Sweet, aniseed, crisp', 'Bulb vegetable, Mediterranean', 'Autumn to spring'),
  ('Fennel Bulb', 'Sweet, aniseed, crisp', 'Bulb vegetable, Mediterranean', 'Autumn to spring'),
  ('Fennel Seed', 'Sweet, aniseed, warm', 'Dried seed, Mediterranean', 'Year-round'),
  ('Fennel Shaving', 'Crisp, sweet, delicately aniseed', 'Thinly shaved fennel bulb', 'Autumn to spring'),
  ('Fenugreek', 'Maple-sweet, bitter, curry-like', 'Seed/leaf, India/Middle East', 'Year-round'),
  ('Fenugreek Seed', 'Maple-sweet, distinctly bitter', 'Dried seed, India/Middle East', 'Year-round'),
  ('Fermented Bean Curd', 'Intensely salty, funky, cheese-like', 'Fermented tofu, China', 'Year-round'),
  ('Feta PDO', 'Salty, tangy, crumbly', 'Brined sheep/goat-milk cheese PDO, Greece', 'Year-round'),
  ('Feuilletine', 'Crisp, buttery, caramelised shards', 'Crushed thin wafer, France', 'Year-round'),
  ('Fiddlehead Fern', 'Green, grassy, between asparagus and green bean', 'Young fern frond, temperate forests', 'Spring'),
  ('Fig Jam', 'Deeply sweet, jammy, seedy', 'Cooked figs with sugar', 'Made in late summer'),
  ('Fig Purée', 'Sweet, honeyed, dense', 'Sieved figs', 'Late summer fruit, year-round frozen'),
  ('Filling', 'Varies entirely with what is used', 'Prepared filling mixture', 'Year-round'),
  ('Filling (Fish, Vegetables, etc.)', 'Savoury; varies with the components chosen', 'Prepared fish or vegetable filling', 'Year-round'),
  ('Filling (Tuna, Cucumber, Avocado)', 'Fresh, savoury, creamy-crisp', 'Classic maki filling combination', 'Year-round'),
  ('Filo Pastry', 'Neutral, paper-thin, shatters when baked', 'Thin unleavened pastry, Greece/Turkey', 'Year-round'),
  ('Fine Sea Salt', 'Clean, even salinity', 'Finely ground sea salt', 'Year-round'),
  ('Finger Lime', 'Sharp citrus pearls that burst; lime-like', 'Citrus fruit, Australia', 'Autumn to winter'),
  ('Fingerling Potatoes', 'Waxy, buttery, nutty', 'Small elongated potato variety', 'Summer to autumn'),
  ('Fior di Latte Mozzarella', 'Milky, sweet, delicate', 'Cow''s-milk mozzarella, Italy', 'Year-round'),
  ('Fir Tip Syrup', 'Resinous, citrus-pine, gently sweet', 'Young fir shoots in syrup, Alps', 'Made in spring'),
  ('Firm Tofu', 'Neutral, faintly beany; holds its shape', 'Pressed soybean curd, East Asia', 'Year-round'),
  ('Fish Bones', 'Clean, marine; the base of fish stock', 'Fish frames', 'Year-round'),
  ('Fish Or Shellfish Stock', 'Clean and marine, or sweeter and richer', 'Simmered fish bones or shellfish shells', 'Year-round'),
  ('Fish Sauce', 'Intensely salty, funky, deeply umami', 'Fermented anchovy sauce, SE Asia', 'Year-round'),
  ('Fish Sauce Premium', 'Rounder, cleaner, deeply savoury', 'First-press fermented anchovy sauce, Vietnam', 'Year-round'),
  ('Fish Stock', 'Clean, delicate, marine', 'Simmered fish bones and aromatics', 'Year-round'),
  ('Five-Spice Powder', 'Warm, sweet, anise-forward', 'Spice blend, China', 'Year-round'),
  ('Flageolet Bean', 'Delicate, creamy, faintly grassy', 'Pale green bean, France', 'Year-round'),
  ('Flageolet Beans', 'Delicate, creamy, faintly grassy', 'Pale green beans, France', 'Year-round'),
  ('Flank Steak', 'Lean, coarse-grained, intensely beefy', 'Cattle flank cut', 'Year-round'),
  ('Flat Peach', 'Intensely sweet, low-acid, honeyed', 'Doughnut peach, Mediterranean', 'Summer'),
  ('Flax Seed', 'Nutty, faintly oily; gels when soaked', 'Linseed, temperate regions', 'Year-round'),
  ('Flax Seeds', 'Nutty, faintly oily; gel when soaked', 'Linseed, temperate regions', 'Year-round'),
  ('Fleur de Sel', 'Delicate, moist, crystalline salinity', 'Hand-harvested surface sea salt, France', 'Harvested in summer'),
  ('Fleur De Sel / Pepper', 'Crystalline salinity with woody pepper heat', 'Finishing salt and pepper', 'Year-round'),
  ('Foie Gras', 'Ultra-rich, buttery, delicately sweet', 'Fattened duck or goose liver, France', 'Autumn to winter'),
  ('Fondant', 'Purely sweet, smooth, sets to a sheen', 'Cooked sugar paste', 'Year-round'),
  ('Fondant Icing', 'Purely sweet, pliable, matte finish', 'Sugar paste for covering cakes', 'Year-round'),
  ('Fondue Moitié-Moitié', 'Nutty, tangy, deeply savoury melted cheese', 'Gruyère and Vacherin blend, Switzerland', 'Autumn to winter'),
  ('Fontina DOP', 'Nutty, earthy, superb melting', 'Cow''s-milk cheese, Aosta Valley, Italy', 'Year-round'),
  ('Formaggini Ticinesi', 'Fresh, lactic, delicate small cheeses', 'Fresh cheeses, Ticino, Switzerland', 'Year-round'),
  ('Formaggio di Fossa', 'Pungent, earthy, intensely aromatic', 'Pit-aged cheese, Emilia-Romagna, Italy', 'Autumn (unearthed November)'),
  ('Framboise', 'Intensely raspberry, dry and fiery', 'Raspberry eau-de-vie, France/Switzerland', 'Year-round'),
  ('Frangelico', 'Sweet, toasted hazelnut liqueur', 'Hazelnut liqueur, Italy', 'Year-round'),
  ('Free-Range Eggs', 'Savoury, rich yolk; deeper colour', 'Hen''s eggs, free-range', 'Year-round'),
  ('Freekeh', 'Smoky, nutty, chewy green wheat', 'Roasted young wheat, Middle East', 'Year-round'),
  ('Freeze-Dried Mango Powder', 'Intensely tropical, sweet-tart', 'Freeze-dried ground mango', 'Year-round'),
  ('Freeze-Dried Raspberry', 'Intensely tart-sweet, crisp', 'Freeze-dried raspberries', 'Year-round'),
  ('Freeze-Dried Raspberry Powder', 'Concentrated tart raspberry; vivid pink', 'Freeze-dried ground raspberries', 'Year-round'),
  ('Freeze-Dried Strawberry', 'Intensely sweet-tart, crisp', 'Freeze-dried strawberries', 'Year-round'),
  ('Freeze-Dried Strawberry Powder', 'Concentrated strawberry; vivid red', 'Freeze-dried ground strawberries', 'Year-round'),
  ('Fregola', 'Toasty, nutty, chewy pearls', 'Toasted semolina pasta, Sardinia, Italy', 'Year-round'),
  ('French Fries 10mm', 'Potato-sweet, crisp outside, fluffy inside', 'Cut potatoes for frying', 'Year-round'),
  ('Fresh Basil Leaf', 'Sweet, peppery, anise-clove aroma', 'Aromatic herb, Mediterranean', 'Summer'),
  ('Fresh Bay Leaves', 'Greener, brighter and more floral than dried', 'Laurel leaves, Mediterranean', 'Year-round'),
  ('Fresh Chervil', 'Delicate, anise-parsley, fragile', 'Aromatic herb, Europe', 'Spring'),
  ('Fresh Chestnut', 'Sweet, starchy, earthy-nutty', 'Tree nut, southern Europe', 'Autumn'),
  ('Fresh Coconut', 'Sweet, rich, milky flesh', 'Palm fruit, tropical regions', 'Year-round'),
  ('Fresh Cranberry', 'Sharply tart, astringent, firm', 'Berry, North America/Northern Europe', 'Autumn'),
  ('Fresh Dill', 'Grassy, anise-like, fresh', 'Aromatic herb, temperate regions', 'Spring to summer'),
  ('Fresh Fava Bean', 'Sweet, green, tender when young', 'Broad bean, Mediterranean', 'Spring to early summer'),
  ('Fresh Fig', 'Honeyed, jammy, delicately seedy', 'Fig, Mediterranean', 'Late summer to autumn'),
  ('Fresh Ginger', 'Warm, pungent, citrus-peppery', 'Rhizome, tropical Asia', 'Year-round'),
  ('Fresh Goat Cheese', 'Bright, lactic, gently goaty', 'Fresh goat''s-milk cheese', 'Spring to autumn'),
  ('Fresh Green Peppercorn', 'Bright, herbal, mildly hot', 'Unripe pepper berries, SE Asia', 'Year-round'),
  ('Fresh Horseradish Root', 'Fiercely pungent, sinus-clearing', 'Root, Central/Eastern Europe', 'Autumn to spring'),
  ('Fresh Lavender', 'Intensely floral, faintly camphorous', 'Lavender buds, Provence', 'Summer'),
  ('Fresh Lemon Balm', 'Lemony, soft, gently minty', 'Herb, Europe', 'Spring to summer'),
  ('Fresh Lovage', 'Intensely celery-like, savoury', 'Herb, Europe', 'Spring to summer'),
  ('Fresh Maccheroncini', 'Tender, eggy, delicate short pasta', 'Fresh egg pasta, Italy', 'Year-round'),
  ('Fresh Marjoram', 'Warm, sweet, gently oregano-like', 'Herb, Mediterranean', 'Summer'),
  ('Fresh Oregano', 'Warm, peppery, brighter than dried', 'Herb, Mediterranean', 'Summer'),
  ('Fresh Parsley', 'Fresh, green, peppery', 'Herb, temperate regions', 'Year-round'),
  ('Fresh Porcini Mushroom', 'Nutty, meaty, deeply woodland', 'Wild mushroom, European forests', 'Late summer to autumn'),
  ('Fresh Rosemary', 'Piney, resinous, camphor-like', 'Woody herb, Mediterranean', 'Year-round'),
  ('Fresh Sage', 'Musty, warm, faintly medicinal', 'Woody herb, Mediterranean', 'Spring to autumn'),
  ('Fresh Shiso Leaf', 'Minty, basil-like, faintly citrus-anise', 'Perilla leaf, Japan', 'Summer'),
  ('Fresh Sorrel', 'Sharply lemony, green, acidic', 'Leafy herb, Europe', 'Spring to summer'),
  ('Fresh Strawberry', 'Sweet, fragrant, gently tart', 'Berry, temperate regions', 'Late spring to summer'),
  ('Fresh Tarragon', 'Anise-like, sweet, aromatic', 'Herb, France', 'Spring to summer'),
  ('Fresh Thyme', 'Earthy, floral, slightly minty', 'Woody herb, Mediterranean', 'Year-round'),
  ('Fresh Turmeric', 'Earthy, peppery, faintly bitter; stains gold', 'Rhizome, South/SE Asia', 'Autumn to winter'),
  ('Fresh Turmeric Root', 'Earthy, peppery, faintly bitter', 'Rhizome, South/SE Asia', 'Autumn to winter'),
  ('Fresh Verbena', 'Intensely lemony, floral', 'Lemon verbena leaf, South America/Europe', 'Summer'),
  ('Fresh Wasabi Rhizome', 'Clean, sharp, fleeting sinus heat', 'Wasabia japonica rhizome, Japan', 'Year-round'),
  ('Fresh Yeast', 'Yeasty, faintly sweet; the leavening agent', 'Compressed baker''s yeast', 'Year-round'),
  ('Fresno Chili', 'Fruity, bright, medium heat', 'Chilli variety, USA', 'Summer to autumn'),
  ('Fried Tofu Puff', 'Neutral, spongy; soaks up broth', 'Deep-fried tofu, East Asia', 'Year-round'),
  ('Frisée', 'Crisp, pleasantly bitter, feathery', 'Curly endive, Europe', 'Autumn to winter'),
  ('Frozen Artichoke Bottoms', 'Nutty, tender, mildly bitter', 'Prepared frozen artichoke', 'Year-round'),
  ('Frozen Berries Mix', 'Sweet-tart, mixed berry', 'Assorted frozen berries', 'Year-round'),
  ('Frozen Peas Fine', 'Sweet, tender, bright green', 'Young peas, frozen at harvest', 'Year-round'),
  ('Frozen Spinach Leaf', 'Mineral, green, mild', 'Blanched frozen spinach', 'Year-round'),
  ('Fruit Juice', 'Sweet-tart; varies with the fruit', 'Pressed fruit', 'Year-round'),
  ('Fryer Cleaner Note', 'Not a food — a cleaning product for the fryer', 'Kitchen cleaning supply', 'Year-round'),
  ('Frying Oil', 'Neutral, clean; high smoke point', 'Refined vegetable oil', 'Year-round'),
  ('Frying Oil HO', 'Neutral, very stable at high heat', 'High-oleic frying oil', 'Year-round'),
  ('Furikake', 'Savoury, marine, sesame-toasted sprinkle', 'Rice seasoning, Japan', 'Year-round'),
  ('Furikake Nori Komi', 'Seaweed-forward, sesame, savoury', 'Nori rice seasoning, Japan', 'Year-round'),
  ('Fusilli', 'Neutral, wheaty; spirals that grip sauce', 'Durum-wheat pasta, Italy', 'Year-round'),
  ('Gala Apple', 'Sweet, mild, crisp', 'Apple variety, New Zealand origin', 'Autumn'),
  ('Galangal', 'Sharp, piney, citrus-peppery; firmer than ginger', 'Rhizome, SE Asia', 'Year-round'),
  ('Galia Melon', 'Sweet, aromatic, honeyed', 'Melon, Mediterranean/Middle East', 'Summer'),
  ('Garam Masala', 'Warm, sweet-spicy finishing blend', 'Spice blend, India', 'Year-round'),
  ('Garden Cress', 'Peppery, sharp, tender', 'Sprouted cress, Europe', 'Year-round'),
  ('Garlic Clove', 'Pungent raw; sweet and mellow cooked', 'Allium bulb, widely grown', 'Year-round'),
  ('Garlic Oil', 'Deeply garlicky, aromatic', 'Garlic infused into oil', 'Year-round'),
  ('Garlic Paste', 'Concentrated, pungent garlic', 'Ground garlic', 'Year-round'),
  ('Garlic Powder', 'Sweet-savoury, muted garlic', 'Dried ground garlic', 'Year-round'),
  ('Garlic Scapes', 'Green, mildly garlicky, crisp', 'Flower stalk of garlic, temperate regions', 'Late spring'),
  ('Gelatin Leaves', 'Flavourless; sets to a clean, melting gel', 'Leaf gelatine from collagen', 'Year-round'),
  ('Gelatine', 'Flavourless; sets to a clean, melting gel', 'Gelatine from collagen', 'Year-round'),
  ('Gelatine Leaf', 'Flavourless; sets to a clean, melting gel', 'Leaf gelatine from collagen', 'Year-round'),
  ('Gellan Gum', 'Flavourless; sets firm, heat-stable gels', 'Fermentation-derived hydrocolloid', 'Year-round'),
  ('Genepy', 'Herbal, alpine, bittersweet', 'Alpine herb liqueur, Alps', 'Year-round'),
  ('Genmai', 'Nutty, toasty brown rice', 'Whole-grain rice, Japan', 'Year-round'),
  ('Ghee', 'Nutty, deeply buttery; very high smoke point', 'Clarified butter, India', 'Year-round'),
  ('Ghee Or Neutral Oil', 'Nutty-buttery, or clean and neutral', 'Clarified butter or refined oil', 'Year-round'),
  ('Gianduja', 'Sweet, hazelnut-chocolate, melting', 'Hazelnut chocolate, Piedmont, Italy', 'Year-round'),
  ('Giardiniera', 'Sharp, crunchy, herby pickled vegetables', 'Pickled vegetable mix, Italy', 'Year-round'),
  ('Gigantes Beans', 'Creamy, large, mild and buttery', 'Giant white beans, Greece', 'Year-round'),
  ('Gin', 'Juniper-forward, botanical, crisp', 'Juniper-flavoured spirit, Europe', 'Year-round'),
  ('Ginger Beer', 'Spicy, sweet, sharply gingery', 'Fermented or carbonated ginger drink', 'Year-round'),
  ('Ginger Powder', 'Warm, pungent, drier than fresh', 'Dried ground ginger', 'Year-round'),
  ('Gingerbread Spice', 'Warm, sweet; cinnamon, clove, ginger', 'Spice blend, Central Europe', 'Year-round'),
  ('Gingerbread Spice Mix', 'Warm, sweet; cinnamon, clove, ginger', 'Spice blend, Central Europe', 'Year-round'),
  ('Glace de Viande', 'Intensely savoury, glossy, concentrated', 'Heavily reduced meat stock, France', 'Year-round'),
  ('Glarner Schabziger', 'Sharp, herbal, pungent; grated finely', 'Herb cheese, Glarus, Switzerland', 'Year-round'),
  ('Glass Noodles', 'Neutral, slippery, translucent', 'Mung-bean or sweet-potato starch noodles, Asia', 'Year-round'),
  ('Glucose', 'Cleanly sweet; controls crystallisation', 'Glucose from starch', 'Year-round'),
  ('Glucose Powder', 'Cleanly sweet, less sweet than sucrose', 'Dried glucose', 'Year-round'),
  ('Glucose Syrup', 'Mildly sweet, thick; prevents crystallisation', 'Glucose syrup from starch', 'Year-round'),
  ('Glutinous (Mochiko) Rice Flour', 'Neutral; turns chewy and elastic', 'Milled glutinous rice, Japan', 'Year-round'),
  ('Glutinous Rice', 'Sweet, sticky, chewy', 'Sticky rice, SE/East Asia', 'Year-round'),
  ('Glutinous Rice Flour', 'Neutral; turns chewy and elastic', 'Milled glutinous rice, Asia', 'Year-round'),
  ('Gnocchetti Sardi', 'Neutral, ridged; holds hearty sauce', 'Durum-wheat pasta, Sardinia, Italy', 'Year-round'),
  ('Goat Cheese', 'Bright, tangy, distinctly goaty', 'Goat''s-milk cheese', 'Spring to autumn'),
  ('Goat Milk', 'Tangy, faintly grassy, slightly sweet', 'Goat''s milk', 'Spring to autumn')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
