-- 171_ingredient_info_backfill_batch1.sql
-- Ingredient info backfill (Richard, 23.7.2026) — batch 1 of the flavour/origin/season fill.
-- SAFETY: this ONLY fills fields that are currently empty (coalesce + nullif), matched
-- case-insensitively by name. It NEVER overwrites a value that already exists (so the ~1,376
-- rows the seeds already gave an origin/season keep theirs; only their empty flavour is filled).
-- Reference facts (taste / where it comes from / season) are universal, so this fills the field
-- for every kitchen's copy of the ingredient — not price, which stays per-kitchen and untouched.
-- Non-destructive backfill: no deletes, no drops, only empty text fields set.
with m(name, flavour, origin, season) as (values
  ('Sugar', 'Clean, pure sweetness with no aroma', 'Refined from sugar cane or sugar beet', 'Year-round'),
  ('Salt', 'Pure salinity; sharpens and balances other flavours', 'Sea evaporation or rock-salt mines', 'Year-round'),
  ('Fine Salt', 'Clean, even salinity that dissolves fast', 'Sea evaporation or rock-salt mines', 'Year-round'),
  ('Sea Salt', 'Bright, mineral salinity', 'Evaporated seawater', 'Year-round'),
  ('Flaky Sea Salt', 'Crisp, briny crunch that dissolves on the tongue', 'Evaporated seawater (e.g. Maldon)', 'Year-round'),
  ('Black Pepper', 'Sharp, woody heat with citrus-pine aroma', 'Dried berries of the pepper vine, mainly India/Vietnam', 'Year-round'),
  ('White Pepper', 'Earthy, fermented heat, milder aroma than black', 'Ripened, hulled pepper berries, SE Asia', 'Year-round'),
  ('Flour', 'Neutral, faintly nutty; the base of most doughs', 'Milled wheat', 'Year-round'),
  ('Plain Flour', 'Neutral, mild wheat taste', 'Milled soft/medium wheat', 'Year-round'),
  ('All-Purpose Flour', 'Neutral, mild wheat taste', 'Milled medium-protein wheat', 'Year-round'),
  ('Bread Flour', 'Neutral, faintly nutty; strong and chewy', 'Milled high-protein wheat', 'Year-round'),
  ('00 Flour', 'Silky, delicate, low-flavour finely milled wheat', 'Finely milled Italian soft wheat', 'Year-round'),
  ('Whole Wheat Flour', 'Nutty, earthy, slightly bitter', 'Milled whole wheat grain', 'Year-round'),
  ('Cornstarch', 'Flavourless; pure thickening starch', 'Extracted from maize', 'Year-round'),
  ('Baking Soda', 'Sharp, slightly soapy alkaline note', 'Mined or processed sodium bicarbonate', 'Year-round'),
  ('Baking Powder', 'Neutral leavening with a faint saline edge', 'Blend of bicarbonate and acid salts', 'Year-round'),
  ('Butter', 'Rich, creamy, faintly sweet and lactic', 'Churned cow''s cream', 'Year-round'),
  ('Unsalted Butter', 'Clean, sweet cream with no added salt', 'Churned cow''s cream', 'Year-round'),
  ('Milk', 'Mild, sweet, creamy', 'Cow''s milk', 'Year-round'),
  ('Whole Milk', 'Full, creamy, gently sweet', 'Cow''s milk', 'Year-round'),
  ('Heavy Cream', 'Lush, rich, subtly sweet dairy', 'High-fat cow''s cream', 'Year-round'),
  ('Double Cream', 'Very rich, thick, sweet cream', 'High-fat cow''s cream', 'Year-round'),
  ('Sour Cream', 'Tangy, thick, cool dairy', 'Cultured cow''s cream', 'Year-round'),
  ('Creme Fraiche', 'Rich, nutty, gently sour cream', 'Cultured cow''s cream, France', 'Year-round'),
  ('Yogurt', 'Tangy, fresh, creamy', 'Cultured milk', 'Year-round'),
  ('Greek Yogurt', 'Thick, rich, pleasantly sour', 'Strained cultured milk', 'Year-round'),
  ('Eggs', 'Savoury, rich yolk; neutral white', 'Hen''s eggs', 'Year-round'),
  ('Egg', 'Savoury, rich yolk; neutral white', 'Hen''s egg', 'Year-round'),
  ('Egg Yolk', 'Rich, fatty, savoury', 'Hen''s egg', 'Year-round'),
  ('Egg White', 'Neutral, faintly saline; whips to foam', 'Hen''s egg', 'Year-round'),
  ('Parmesan', 'Sharp, salty, nutty, umami-rich', 'Aged cow''s-milk cheese, Emilia-Romagna, Italy', 'Year-round'),
  ('Parmigiano Reggiano', 'Sharp, crystalline, deeply savoury and nutty', 'Aged cow''s-milk cheese, Emilia-Romagna, Italy', 'Year-round'),
  ('Mozzarella', 'Milky, mild, delicately sweet', 'Fresh pulled-curd cheese, Italy', 'Year-round'),
  ('Cheddar', 'Sharp, tangy, savoury', 'Aged cow''s-milk cheese, England', 'Year-round'),
  ('Gruyere', 'Nutty, sweet-salty, complex', 'Aged cow''s-milk cheese, Switzerland', 'Year-round'),
  ('Feta', 'Salty, tangy, crumbly', 'Brined sheep/goat-milk cheese, Greece', 'Year-round'),
  ('Cream Cheese', 'Mild, rich, gently tangy', 'Fresh cultured cow''s-milk cheese', 'Year-round'),
  ('Mascarpone', 'Sweet, buttery, ultra-rich', 'Cream-based fresh cheese, Italy', 'Year-round'),
  ('Olive Oil', 'Fruity, peppery, grassy', 'Pressed olives, Mediterranean', 'Year-round'),
  ('Extra Virgin Olive Oil', 'Bright, fruity, peppery finish', 'First cold-pressed olives, Mediterranean', 'Year-round'),
  ('Vegetable Oil', 'Neutral, clean; high smoke point', 'Refined seed/plant oils', 'Year-round'),
  ('Sunflower Oil', 'Light, neutral, clean', 'Pressed sunflower seeds', 'Year-round'),
  ('Rapeseed Oil', 'Light, grassy, mild', 'Pressed rapeseed (canola)', 'Year-round'),
  ('Sesame Oil', 'Deep, nutty, toasty', 'Pressed toasted sesame seeds, East Asia', 'Year-round'),
  ('Coconut Oil', 'Sweet, tropical, coconut aroma', 'Pressed coconut flesh', 'Year-round'),
  ('Garlic', 'Pungent, sharp raw; sweet and mellow cooked', 'Bulb of the allium family, widely grown', 'Year-round (fresh summer)'),
  ('Onion', 'Sharp and pungent raw; sweet when cooked', 'Allium bulb, widely grown', 'Year-round'),
  ('Red Onion', 'Milder, sweeter, slightly peppery', 'Allium bulb, widely grown', 'Year-round'),
  ('Shallot', 'Delicate, sweet, garlicky-onion', 'Allium bulb, widely grown', 'Year-round'),
  ('Spring Onion', 'Fresh, mild, grassy onion', 'Young allium, widely grown', 'Spring to summer'),
  ('Leek', 'Sweet, gentle onion flavour', 'Allium stalk, temperate regions', 'Autumn to spring'),
  ('Carrot', 'Sweet, earthy', 'Root vegetable, widely grown', 'Year-round (peak autumn)'),
  ('Celery', 'Fresh, peppery, saline-green', 'Stalk vegetable, temperate regions', 'Year-round'),
  ('Potato', 'Earthy, mild, starchy', 'Tuber, widely grown', 'Year-round (harvest autumn)'),
  ('Tomato', 'Sweet-tart, juicy, umami', 'Fruit of the nightshade family', 'Summer to early autumn'),
  ('Cherry Tomato', 'Intensely sweet-tart, juicy', 'Small tomato variety', 'Summer'),
  ('Cucumber', 'Cool, crisp, mildly green', 'Gourd, widely grown', 'Summer'),
  ('Bell Pepper', 'Sweet, crisp, grassy', 'Capsicum fruit, widely grown', 'Summer to autumn'),
  ('Red Bell Pepper', 'Sweet, ripe, mild', 'Ripened capsicum fruit', 'Summer to autumn'),
  ('Zucchini', 'Mild, green, delicate', 'Summer squash', 'Summer'),
  ('Eggplant', 'Mild, earthy; silky when cooked', 'Nightshade fruit, warm regions', 'Summer to autumn'),
  ('Mushroom', 'Earthy, savoury, umami', 'Cultivated fungus', 'Year-round'),
  ('Button Mushroom', 'Mild, earthy, savoury', 'Cultivated Agaricus fungus', 'Year-round'),
  ('Spinach', 'Mineral, green, mildly bitter', 'Leafy green, temperate regions', 'Spring and autumn'),
  ('Broccoli', 'Green, faintly sweet, sulphurous', 'Brassica, temperate regions', 'Autumn to spring'),
  ('Cauliflower', 'Mild, nutty, faintly sweet', 'Brassica, temperate regions', 'Autumn to spring'),
  ('Cabbage', 'Peppery-sweet, sulphurous', 'Brassica, temperate regions', 'Autumn to winter'),
  ('Lettuce', 'Crisp, fresh, faintly bitter', 'Leafy salad green', 'Spring to summer'),
  ('Basil', 'Sweet, peppery, anise-clove aroma', 'Aromatic herb, Mediterranean/Asia', 'Summer'),
  ('Parsley', 'Fresh, green, peppery', 'Aromatic herb, temperate regions', 'Year-round'),
  ('Flat-Leaf Parsley', 'Fresh, green, clean and peppery', 'Aromatic herb, temperate regions', 'Year-round'),
  ('Cilantro', 'Bright, citrusy, pungent', 'Coriander leaf, warm regions', 'Year-round'),
  ('Coriander', 'Citrusy leaf; warm, nutty seed', 'Herb/spice plant, warm regions', 'Year-round'),
  ('Thyme', 'Earthy, floral, slightly minty', 'Woody herb, Mediterranean', 'Year-round (peak summer)'),
  ('Rosemary', 'Piney, resinous, camphor-like', 'Woody herb, Mediterranean', 'Year-round'),
  ('Oregano', 'Warm, peppery, faintly bitter', 'Aromatic herb, Mediterranean', 'Summer'),
  ('Mint', 'Cool, sweet, menthol-fresh', 'Aromatic herb, temperate regions', 'Spring to summer'),
  ('Dill', 'Grassy, anise-like, fresh', 'Aromatic herb, temperate regions', 'Spring to summer'),
  ('Chives', 'Delicate, oniony, fresh', 'Allium herb, temperate regions', 'Spring to summer'),
  ('Bay Leaf', 'Aromatic, herbal, faintly bitter', 'Dried laurel leaf, Mediterranean', 'Year-round'),
  ('Ginger', 'Warm, pungent, citrus-peppery', 'Rhizome, tropical Asia', 'Year-round'),
  ('Lemon', 'Bright, sour, floral zest', 'Citrus fruit, warm regions', 'Winter to spring'),
  ('Lime', 'Sharp, sour, aromatic', 'Citrus fruit, tropical regions', 'Year-round'),
  ('Orange', 'Sweet-tart, fragrant', 'Citrus fruit, warm regions', 'Winter'),
  ('Honey', 'Floral, sweet, aromatic', 'Made by bees from flower nectar', 'Year-round'),
  ('Maple Syrup', 'Sweet, woody, caramel', 'Boiled sap of the maple tree, N. America', 'Year-round (tapped late winter)'),
  ('Vanilla', 'Sweet, floral, creamy-woody', 'Cured orchid pods, tropical regions', 'Year-round'),
  ('Cinnamon', 'Warm, sweet, woody-spicy', 'Dried inner bark, Sri Lanka/Indonesia', 'Year-round'),
  ('Nutmeg', 'Warm, sweet, nutty-spicy', 'Dried seed of the nutmeg tree, tropics', 'Year-round'),
  ('Paprika', 'Sweet, warm, mildly smoky', 'Ground dried red peppers, Hungary/Spain', 'Year-round'),
  ('Cumin', 'Warm, earthy, slightly bitter', 'Dried seed, Middle East/India', 'Year-round'),
  ('Chili Flakes', 'Sharp, fruity heat', 'Dried crushed red chilies', 'Year-round'),
  ('Bay Leaves', 'Aromatic, herbal, faintly bitter', 'Dried laurel leaves, Mediterranean', 'Year-round'),
  ('Soy Sauce', 'Salty, savoury, deeply umami', 'Fermented soybeans and wheat, East Asia', 'Year-round'),
  ('Rice', 'Mild, clean, faintly sweet', 'Cereal grain, Asia and worldwide', 'Year-round'),
  ('Basmati Rice', 'Fragrant, nutty, delicate', 'Long-grain rice, Indian subcontinent', 'Year-round'),
  ('Arborio Rice', 'Creamy, starchy, mild', 'Short-grain risotto rice, Italy', 'Year-round'),
  ('Pasta', 'Neutral, wheaty; carries sauce', 'Durum-wheat dough, Italy', 'Year-round'),
  ('Honey Mustard', 'Sweet-sharp, tangy', 'Blend of mustard and honey', 'Year-round'),
  ('Dijon Mustard', 'Sharp, tangy, clean heat', 'Mustard seed and wine/verjus, France', 'Year-round'),
  ('Red Wine Vinegar', 'Sharp, fruity, acidic', 'Fermented red wine', 'Year-round'),
  ('White Wine Vinegar', 'Bright, clean, acidic', 'Fermented white wine', 'Year-round'),
  ('Balsamic Vinegar', 'Sweet-sour, syrupy, mellow', 'Cooked grape must aged in wood, Modena, Italy', 'Year-round'),
  ('Tomato Paste', 'Concentrated sweet-tart umami', 'Reduced cooked tomatoes', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
