-- 172_ingredient_info_backfill_batch2.sql
-- Ingredient info backfill — batch 2 of the flavour/origin/season fill (Richard, 23.7.2026).
-- Same safety contract as db/171: ONLY fills fields that are currently empty (coalesce + nullif),
-- matched case-insensitively by name. It NEVER overwrites an existing value. Reference facts
-- (taste / where it comes from / season) are universal, so this fills every kitchen's copy of the
-- ingredient — price stays per-kitchen and untouched. Non-destructive: no deletes, no drops.
-- Covers the alphabetical range "00 Flour Or Strong Bread Flour" → "Beef Rump" (150 names).
with m(name, flavour, origin, season) as (values
  ('00 Flour Or Strong Bread Flour', 'Neutral, faintly nutty; silky or strong depending on the choice', 'Milled Italian soft wheat or high-protein bread wheat', 'Year-round'),
  ('Abalone', 'Delicate, sweet-briny, firm and buttery', 'Marine sea snail, Pacific and East Asian coasts', 'Year-round (farmed)'),
  ('Absinthe', 'Intense anise and wormwood, herbal and bitter', 'Distilled spirit, Switzerland/France', 'Year-round'),
  ('Acacia Honey', 'Very mild, floral, clean sweetness; stays liquid', 'Nectar of black locust blossom, Europe', 'Harvested late spring'),
  ('Acid (Vinegar)', 'Sharp, sour; used to balance and lift a dish', 'Fermented alcohol (wine, cider or grain)', 'Year-round'),
  ('Acorn Squash', 'Sweet, nutty, mildly earthy', 'Winter squash, the Americas', 'Autumn to winter'),
  ('Activated Charcoal', 'Flavourless; used purely for black colour', 'Carbonised coconut shell or wood', 'Year-round'),
  ('Activated Charcoal Powder', 'Flavourless; a natural black colouring', 'Carbonised coconut shell or wood', 'Year-round'),
  ('Active Sourdough Starter', 'Sour, yeasty, lactic and lively', 'Wild-fermented flour and water culture', 'Year-round'),
  ('Aekjeot', 'Salty, deeply savoury fermented fish sauce', 'Fermented anchovy sauce, Korea', 'Year-round'),
  ('Agar Agar', 'Flavourless; a firm, brittle plant-based gelling agent', 'Red seaweed, East Asia', 'Year-round'),
  ('Agar-Agar', 'Flavourless; a firm, brittle plant-based gelling agent', 'Red seaweed, East Asia', 'Year-round'),
  ('Agave Syrup', 'Clean, neutral sweetness, thinner than honey', 'Sap of the blue agave, Mexico', 'Year-round'),
  ('Aged Balsamic 12y', 'Dense, sweet-sour, figgy and syrupy', 'Cooked grape must aged 12 years, Modena, Italy', 'Year-round'),
  ('Aged Goat Cheese', 'Sharp, tangy, nutty with a firm crumble', 'Matured goat''s-milk cheese, Europe', 'Year-round'),
  ('Aged Gouda', 'Deep caramel, butterscotch, crunchy crystals', 'Matured cow''s-milk cheese, Netherlands', 'Year-round'),
  ('Agria Potatoes', 'Floury, earthy, deeply potato; ideal for frying', 'Potato variety, widely grown in Switzerland', 'Autumn harvest, stored year-round'),
  ('Aioli', 'Rich, garlicky, creamy and sharp', 'Emulsion of garlic, oil and egg, Provence/Catalonia', 'Year-round'),
  ('Aji Amarillo Paste', 'Fruity, sunny, medium heat', 'Yellow chilli paste, Peru', 'Year-round'),
  ('Ajvar', 'Sweet, smoky, mildly peppery', 'Roasted red pepper and aubergine relish, Balkans', 'Made in autumn'),
  ('Ajwain', 'Sharp, thyme-like, bitter and pungent', 'Dried seed, India', 'Year-round'),
  ('Akazu', 'Mellow, malty, gently sour', 'Red rice vinegar, Japan', 'Year-round'),
  ('Aleppo Pepper', 'Fruity, sun-dried, gentle lingering heat', 'Dried chilli flakes, Syria/Turkey', 'Year-round'),
  ('Alfalfa Sprouts', 'Fresh, grassy, faintly nutty', 'Sprouted alfalfa seed', 'Year-round (sprouted)'),
  ('Allspice', 'Warm; clove, cinnamon and nutmeg in one berry', 'Dried berry of the pimento tree, Caribbean', 'Year-round'),
  ('Almensberger Cheese', 'Mild, creamy, gently nutty', 'Regional Swiss cow''s-milk cheese', 'Year-round'),
  ('Almond Butter', 'Rich, sweet-nutty, smooth', 'Ground roasted almonds', 'Year-round'),
  ('Almond Extract', 'Intense marzipan and bitter-almond aroma', 'Extract of bitter almond or apricot kernel', 'Year-round'),
  ('Almond Flour', 'Sweet, nutty, moist; naturally gluten-free', 'Ground blanched almonds', 'Year-round'),
  ('Almond Milk', 'Light, faintly nutty, subtly sweet', 'Pressed almonds and water', 'Year-round'),
  ('Almond Paste', 'Sweet, dense marzipan', 'Ground almonds and sugar', 'Year-round'),
  ('Almond Powder', 'Sweet, nutty, fine', 'Finely ground almonds', 'Year-round'),
  ('Almond Praline', 'Toasted, caramelised, deeply nutty', 'Caramelised almonds ground to a paste', 'Year-round'),
  ('Almond Syrup', 'Sweet orgeat, marzipan-like', 'Almond, sugar and orange-flower syrup', 'Year-round'),
  ('Alpine Butter', 'Rich, grassy, deeply lactic', 'Churned mountain-pasture cow''s cream, Alps', 'Best in summer pasture season'),
  ('Alpine Dried Sausage', 'Salty, smoky, firm and savoury', 'Air-dried cured sausage, Alpine regions', 'Year-round'),
  ('Alpine Herb Mix', 'Aromatic, hay-like, floral and savoury', 'Dried mountain herbs, Alps', 'Dried after summer'),
  ('Alplermagronen Cheese Mix', 'Melting, savoury, nutty Alpine cheese blend', 'Swiss cheese blend for the classic dish', 'Year-round'),
  ('Amaranth', 'Earthy, nutty, faintly peppery tiny grain', 'Pseudocereal, the Americas', 'Year-round'),
  ('Amaretti', 'Sweet, crisp, bitter-almond', 'Almond biscuits, Italy', 'Year-round'),
  ('Amaretto', 'Sweet, almond-marzipan liqueur', 'Almond/apricot-kernel liqueur, Italy', 'Year-round'),
  ('Amazake', 'Gently sweet, malty, low-alcohol rice drink', 'Fermented rice with koji, Japan', 'Year-round'),
  ('Amazu-Pickled Onion', 'Sweet-sour, crisp, lightly pickled', 'Onion in sweet rice vinegar, Japan', 'Year-round'),
  ('Amchur', 'Sharp, sour, fruity-tart', 'Dried green mango powder, India', 'Year-round'),
  ('Anago', 'Delicate, soft, subtly sweet sea eel', 'Saltwater conger eel, Japan', 'Summer'),
  ('Anaheim Chili', 'Mild, grassy, gently warm', 'Chilli variety, southwestern USA/Mexico', 'Summer to autumn'),
  ('Ancho Chili', 'Sweet, raisiny, mild smoky heat', 'Dried poblano chilli, Mexico', 'Year-round'),
  ('Anchovies Fresh', 'Clean, oily, delicately briny', 'Small oily fish, Mediterranean/Atlantic', 'Spring to summer'),
  ('Anchovy', 'Intensely salty, savoury, deeply umami', 'Cured small oily fish, Mediterranean', 'Year-round (cured)'),
  ('Anchovy Fillet', 'Salty, rich, melting umami', 'Salt-cured anchovy in oil, Mediterranean', 'Year-round'),
  ('Anchovy Paste', 'Concentrated salty umami', 'Ground cured anchovies', 'Year-round'),
  ('Anise Seed', 'Sweet, liquorice-like, warm', 'Dried seed, Mediterranean/Middle East', 'Year-round'),
  ('Annatto Seeds', 'Mild, peppery-earthy; prized for orange colour', 'Achiote tree seed, Latin America', 'Year-round'),
  ('Ao Nori', 'Marine, green, savoury seaweed flakes', 'Dried green laver, Japan', 'Year-round'),
  ('Aperol', 'Bittersweet orange and rhubarb, low alcohol', 'Aperitif liqueur, Italy', 'Year-round'),
  ('Apfelmus', 'Sweet-tart, smooth cooked apple', 'Cooked apple purée, German-speaking Europe', 'Autumn harvest, year-round jarred'),
  ('Appenzeller', 'Spicy, tangy, herb-washed and pungent', 'Cow''s-milk cheese, Appenzell, Switzerland', 'Year-round'),
  ('Appenzeller Biber', 'Sweet, spiced gingerbread with almond filling', 'Traditional pastry, Appenzell, Switzerland', 'Year-round (peak winter)'),
  ('Appenzeller Siedwurst', 'Mild, savoury, finely spiced boiling sausage', 'Traditional sausage, Appenzell, Switzerland', 'Year-round'),
  ('Apple', 'Crisp, sweet-tart, juicy', 'Pome fruit, temperate regions', 'Autumn (stored into spring)'),
  ('Apple Balsamic', 'Sweet-sour, fruity, mellow', 'Apple must aged like balsamic', 'Year-round'),
  ('Apple Chips', 'Sweet, concentrated apple, crisp', 'Dehydrated apple slices', 'Year-round'),
  ('Apple Cider Vinegar', 'Fruity, sharp, faintly sweet acidity', 'Fermented apple cider', 'Year-round'),
  ('Apple Compote', 'Sweet-tart, soft, gently spiced', 'Cooked apple with sugar', 'Autumn harvest, year-round'),
  ('Apple Juice', 'Sweet-tart, clean, fruity', 'Pressed apples', 'Pressed in autumn'),
  ('Apple Juice Cloudy', 'Fuller, rounder apple with more body', 'Unfiltered pressed apples', 'Pressed in autumn'),
  ('Apple Purée', 'Smooth, sweet-tart apple', 'Cooked and sieved apples', 'Autumn harvest, year-round'),
  ('Apple Vinegar', 'Fruity, sharp, faintly sweet acidity', 'Fermented apple cider', 'Year-round'),
  ('Apricot', 'Honeyed, floral, sweet-tart', 'Stone fruit, warm temperate regions', 'Summer'),
  ('Apricot Glaze', 'Sweet, glossy, mildly tart', 'Reduced apricot jam, used to finish pastry', 'Year-round'),
  ('Apricot Purée', 'Intense sweet-tart apricot', 'Sieved apricots', 'Summer fruit, year-round frozen'),
  ('Apricot Valais', 'Aromatic, honeyed, exceptionally perfumed', 'Luizet apricot from Valais, Switzerland', 'July to August'),
  ('Aquafaba', 'Nearly neutral, faintly beany; whips like egg white', 'Cooking liquid of chickpeas', 'Year-round'),
  ('Arborio Superfino', 'Creamy, starchy, mild; holds a bite', 'Superfino risotto rice, Italy', 'Year-round'),
  ('Arctic Char', 'Delicate, clean, between salmon and trout', 'Cold-water fish, Arctic and Alpine lakes', 'Year-round (farmed)'),
  ('Arctic Char Fillet', 'Delicate, clean, gently rich', 'Cold-water fish, Arctic and Alpine lakes', 'Year-round (farmed)'),
  ('Arctic Char Whole', 'Delicate, clean, gently rich', 'Cold-water fish, Arctic and Alpine lakes', 'Year-round (farmed)'),
  ('Argan Oil Culinary', 'Deeply nutty, toasted, aromatic', 'Pressed roasted argan kernels, Morocco', 'Year-round'),
  ('Ariake Nori', 'Fine, marine, gently sweet seaweed', 'Cultivated nori from the Ariake Sea, Japan', 'Harvested winter'),
  ('Armagnac', 'Rich, rustic, prune and oak brandy', 'Grape brandy, Gascony, France', 'Year-round'),
  ('Aromat', 'Savoury, salty, umami seasoning powder', 'Seasoning blend, Switzerland', 'Year-round'),
  ('Arrowroot Starch', 'Flavourless; a clear, glossy thickener', 'Root starch, tropical regions', 'Year-round'),
  ('Artichoke', 'Nutty, faintly bitter, vegetal-sweet', 'Thistle flower bud, Mediterranean', 'Spring and autumn'),
  ('Artichoke Hearts', 'Tender, nutty, mildly bitter', 'Trimmed artichoke centres, Mediterranean', 'Spring and autumn'),
  ('Artichokes in Oil', 'Tangy, herbal, tender', 'Marinated artichokes, Italy', 'Year-round'),
  ('Asafoetida', 'Pungent raw; onion-garlic savoury when cooked', 'Dried resin, Iran/Afghanistan/India', 'Year-round'),
  ('Ascorbic Acid', 'Clean, sharp sourness; also an antioxidant', 'Vitamin C, produced by fermentation', 'Year-round'),
  ('Asiago', 'Mild and milky when young; sharp and nutty when aged', 'Cow''s-milk cheese, Veneto, Italy', 'Year-round'),
  ('Assorted Sashimi-Grade Fish', 'Clean, delicate, varying by species', 'Sashimi-quality fish selection', 'Year-round'),
  ('Aubergine', 'Mild, earthy; silky and rich when cooked', 'Nightshade fruit, warm regions', 'Summer to autumn'),
  ('Avocado', 'Buttery, mild, faintly nutty', 'Tree fruit, tropical/subtropical regions', 'Year-round'),
  ('Avocado Hass', 'Rich, creamy, nutty; the classic variety', 'Hass avocado, Mexico/Peru/Spain', 'Year-round'),
  ('Avocado Oil', 'Buttery, mild, grassy; high smoke point', 'Pressed avocado flesh', 'Year-round'),
  ('Awase Miso', 'Balanced savoury-sweet umami', 'Blend of red and white miso, Japan', 'Year-round'),
  ('Ayran', 'Salty, tangy, refreshing yoghurt drink', 'Yoghurt, water and salt, Turkey', 'Year-round'),
  ('Baba Ganoush', 'Smoky, creamy, sesame-rich', 'Roasted aubergine and tahini dip, Levant', 'Year-round'),
  ('Baby Artichoke', 'Tender, nutty, barely bitter; eaten whole', 'Young artichoke, Mediterranean', 'Spring'),
  ('Baby Bok Choy', 'Crisp, juicy, mildly mustardy', 'Young Chinese cabbage, East Asia', 'Autumn to spring'),
  ('Baby Corn', 'Sweet, crisp, delicate', 'Immature corn cobs, SE Asia', 'Year-round'),
  ('Baby Gem Lettuce', 'Crisp, sweet, faintly bitter heart', 'Small cos lettuce, temperate regions', 'Spring to autumn'),
  ('Baby Leek', 'Sweet, delicate, gently oniony', 'Young leek, temperate regions', 'Spring to early summer'),
  ('Baby Spinach / Wild Herb', 'Tender, mineral-green with wild herbal notes', 'Young spinach leaves and wild herbs', 'Spring'),
  ('Baby Squid', 'Sweet, tender, delicately marine', 'Young squid, Mediterranean/Atlantic', 'Summer to autumn'),
  ('Bacon', 'Salty, smoky, rich', 'Cured pork belly or back', 'Year-round'),
  ('Baguette', 'Wheaty, faintly sweet crumb with a crisp crust', 'French wheat bread', 'Year-round'),
  ('Baharat', 'Warm, sweet-spicy; pepper, cinnamon and clove', 'Spice blend, Middle East', 'Year-round'),
  ('Baking Ammonia', 'Sharp ammonia while baking; leaves crisp, clean crumb', 'Ammonium bicarbonate, a classic leavener', 'Year-round'),
  ('Balsamic / Sweet Soy Reduction', 'Sweet-sour, syrupy, deeply savoury', 'Reduced balsamic vinegar or sweet soy', 'Year-round'),
  ('Balsamic Glaze', 'Sweet-sour, thick, mellow', 'Reduced balsamic vinegar, Italy', 'Year-round'),
  ('Bamboo Shoot', 'Crisp, mild, faintly earthy-sweet', 'Young bamboo shoots, East/SE Asia', 'Spring'),
  ('Bamboo Shoots Fresh', 'Crisp, sweet, delicately grassy', 'Freshly harvested bamboo shoots, East Asia', 'Spring'),
  ('Banana', 'Sweet, creamy, tropical', 'Tropical fruit, Central/South America and Asia', 'Year-round'),
  ('Banana Blossom', 'Mild, artichoke-like, faintly astringent', 'Flower of the banana plant, SE Asia', 'Year-round'),
  ('Banana Chips', 'Sweet, crisp, concentrated banana', 'Fried or dried banana slices', 'Year-round'),
  ('Banana Pepper', 'Mild, tangy, sweet-sour', 'Pepper variety, the Americas', 'Summer to autumn'),
  ('Banana Purée', 'Sweet, smooth, intensely tropical', 'Sieved ripe bananas', 'Year-round'),
  ('Banana Shallot', 'Sweet, mild, elongated shallot', 'Allium bulb, Europe', 'Year-round'),
  ('Banana Shallots', 'Sweet, mild, elongated shallots', 'Allium bulb, Europe', 'Year-round'),
  ('Banyuls Vinegar', 'Nutty, mellow, sweet-sour', 'Vinegar from Banyuls fortified wine, France', 'Year-round'),
  ('Barberries', 'Sharp, bright, cranberry-like tartness', 'Dried berries, Iran', 'Year-round'),
  ('Barley Flakes', 'Nutty, mild, faintly sweet', 'Rolled barley grain', 'Year-round'),
  ('Barley Malt Syrup', 'Malty, dark, mildly sweet', 'Sprouted barley syrup', 'Year-round'),
  ('Barley Miso', 'Robust, earthy, deeply savoury', 'Barley-koji fermented soybean paste, Japan', 'Year-round'),
  ('Barnacle', 'Intensely marine, sweet-briny', 'Gooseneck barnacle, Iberian Atlantic coast', 'Autumn to spring'),
  ('Basil Oil', 'Bright, herbal, peppery-green', 'Basil infused into oil', 'Year-round'),
  ('Basil Pesto', 'Herbal, garlicky, nutty and cheesy', 'Basil, pine nut, garlic and cheese, Liguria, Italy', 'Peak in summer'),
  ('BBQ Sauce', 'Sweet, smoky, tangy', 'Tomato, vinegar and spice sauce, USA', 'Year-round'),
  ('BBQ-Marinated Thigh Steak', 'Smoky, sweet-savoury, juicy', 'Marinated poultry thigh', 'Year-round'),
  ('Beansprout', 'Crisp, watery, faintly nutty', 'Sprouted mung bean, East Asia', 'Year-round (sprouted)'),
  ('Beaufort AOP', 'Nutty, floral, dense and fruity', 'Alpine cow''s-milk cheese, Savoie, France', 'Year-round (summer milk prized)'),
  ('Bee Pollen', 'Floral, faintly bitter, honeyed', 'Pollen collected by bees', 'Harvested spring to summer'),
  ('Beef', 'Rich, savoury, deeply meaty', 'Cattle, farmed worldwide', 'Year-round'),
  ('Beef Bones', 'Deep, roasted, marrow-rich; the base of stock', 'Cattle bones', 'Year-round'),
  ('Beef Brisket', 'Rich, beefy, becomes meltingly tender', 'Cattle breast cut', 'Year-round'),
  ('Beef Burger Patty 180g', 'Juicy, savoury, deeply beefy', 'Minced beef patty', 'Year-round'),
  ('Beef Cheek', 'Deeply savoury, gelatinous when braised', 'Cattle cheek muscle', 'Year-round'),
  ('Beef Cheeks', 'Deeply savoury, gelatinous when braised', 'Cattle cheek muscle', 'Year-round'),
  ('Beef Chuck', 'Full-flavoured, marbled; ideal for slow cooking', 'Cattle shoulder cut', 'Year-round'),
  ('Beef Chuck Flap', 'Rich, marbled, loose-grained and beefy', 'Cattle shoulder cut', 'Year-round'),
  ('Beef Fillet', 'Very tender, mild, lean', 'Cattle tenderloin', 'Year-round'),
  ('Beef Fillet Or Sirloin', 'Tender and mild, or fuller and beefier', 'Cattle tenderloin or loin', 'Year-round'),
  ('Beef Flat Iron', 'Tender, well-marbled, richly beefy', 'Cattle shoulder (top blade) cut', 'Year-round'),
  ('Beef Gyoza', 'Savoury, juicy, seasoned beef in a thin wrapper', 'Pan-fried dumpling, Japan/China', 'Year-round'),
  ('Beef Jerky', 'Intensely savoury, salty, chewy', 'Dried seasoned beef', 'Year-round'),
  ('Beef Marrow', 'Unctuous, nutty, deeply rich', 'Cattle bone marrow', 'Year-round'),
  ('Beef Marrow Bone', 'Unctuous, nutty, deeply rich', 'Cattle marrow bones', 'Year-round'),
  ('Beef Neck', 'Full-flavoured, sinewy; excellent braised', 'Cattle neck cut', 'Year-round'),
  ('Beef Oxtail', 'Deeply beefy, gelatinous, rich', 'Cattle tail', 'Year-round'),
  ('Beef Ribeye', 'Richly marbled, buttery, intensely beefy', 'Cattle rib cut', 'Year-round'),
  ('Beef Rump', 'Lean, firm, robustly beefy', 'Cattle hindquarter cut', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
