-- 173_ingredient_info_backfill_batch3.sql
-- Ingredient info backfill — batch 3 (Richard, 23.7.2026). Same safety contract as db/171–172:
-- ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by name,
-- never overwrites. Reference facts are universal, so every kitchen's copy is filled; price stays
-- per-kitchen and untouched. Non-destructive: no deletes, no drops.
-- Covers the alphabetical range "Beef Shank" → "Cannellini Bean" (150 names).
with m(name, flavour, origin, season) as (values
  ('Beef Shank', 'Deeply beefy, sinewy; gelatinous when braised', 'Cattle leg cut', 'Year-round'),
  ('Beef Short Rib', 'Rich, marbled, intensely beefy', 'Cattle rib cut', 'Year-round'),
  ('Beef Short Ribs', 'Rich, marbled, intensely beefy', 'Cattle rib cut', 'Year-round'),
  ('Beef Sirloin', 'Firm, juicy, robustly beefy', 'Cattle loin cut', 'Year-round'),
  ('Beef Sirloin Steak', 'Firm, juicy, robustly beefy', 'Cattle loin cut', 'Year-round'),
  ('Beef Stock', 'Deep, roasted, savoury and gelatinous', 'Simmered beef bones and vegetables', 'Year-round'),
  ('Beef Tallow', 'Rich, beefy, clean frying fat', 'Rendered beef fat', 'Year-round'),
  ('Beef Tenderloin', 'Very tender, lean, mild', 'Cattle tenderloin', 'Year-round'),
  ('Beef Tongue', 'Rich, tender, delicately beefy', 'Cattle tongue', 'Year-round'),
  ('Beet Powder', 'Sweet, earthy; a natural deep-red colour', 'Dried ground beetroot', 'Year-round'),
  ('Beetroot', 'Sweet, earthy, faintly mineral', 'Root vegetable, temperate regions', 'Autumn to winter'),
  ('Beetroot Powder', 'Sweet, earthy; a natural deep-red colour', 'Dried ground beetroot', 'Year-round'),
  ('Belacan (Shrimp Paste)', 'Pungent, intensely savoury fermented shrimp', 'Fermented shrimp paste, SE Asia', 'Year-round'),
  ('Belgian Endive', 'Crisp, refreshing, pleasantly bitter', 'Forced chicory, Belgium/Netherlands', 'Autumn to spring'),
  ('Belper Knolle', 'Intense garlic and pepper, hard and gratable', 'Cow''s-milk cheese ball, Belp, Switzerland', 'Year-round'),
  ('Beluga Black Lentil', 'Earthy, firm, holds its shape; caviar-like look', 'Small black lentil', 'Year-round'),
  ('Beluga Lentils', 'Earthy, firm, holds its shape', 'Small black lentils', 'Year-round'),
  ('Beni Shoga', 'Sharp, salty-sour, bright red pickled ginger', 'Pickled ginger, Japan', 'Year-round'),
  ('Berbere', 'Hot, warm-spiced, aromatic chilli blend', 'Spice blend, Ethiopia/Eritrea', 'Year-round'),
  ('Bergamot', 'Intensely floral, bitter-citrus perfume', 'Citrus fruit, Calabria, Italy', 'Winter'),
  ('Bergamot Juice', 'Sharp, floral, bitter-citrus', 'Pressed bergamot, Calabria, Italy', 'Winter'),
  ('Bergamot Zest', 'Highly perfumed, floral bitter-citrus oil', 'Bergamot peel, Calabria, Italy', 'Winter'),
  ('Berner Alpkäse AOP', 'Firm, fruity, nutty Alpine cheese', 'Alpine cow''s-milk cheese, Bern, Switzerland', 'Made in summer, aged year-round'),
  ('Berner Hobelkäse AOP', 'Very hard, intense, shaved in fine curls', 'Long-aged Alpine cheese, Bern, Switzerland', 'Year-round'),
  ('Beurre Blanc Base', 'Buttery, sharp, silky wine-shallot reduction', 'Classic French butter sauce base', 'Year-round'),
  ('Bircher Base', 'Oaty, creamy, gently sweet-tart', 'Soaked oats with dairy and apple, Switzerland', 'Year-round'),
  ('Bird''s Eye Chili', 'Fierce, clean, immediate heat', 'Small hot chilli, SE Asia', 'Year-round'),
  ('Bird''s Eye Chilli', 'Fierce, clean, immediate heat', 'Small hot chilli, SE Asia', 'Year-round'),
  ('Birnel', 'Dark, malty, sweet pear syrup', 'Concentrated pear juice, Switzerland', 'Made after autumn harvest'),
  ('Biscotti', 'Crisp, twice-baked, almond-sweet', 'Dry biscuit, Tuscany, Italy', 'Year-round'),
  ('Bitter Melon', 'Distinctly bitter, cooling, crisp', 'Gourd, Asia', 'Summer'),
  ('Bitter Orange Marmalade', 'Sweet-bitter, aromatic citrus', 'Seville orange preserve', 'Made in winter'),
  ('Black Bean', 'Earthy, sweet, creamy when cooked', 'Dried pulse, the Americas', 'Year-round'),
  ('Black Bean Sauce', 'Salty, funky, deeply savoury', 'Fermented black soybean sauce, China', 'Year-round'),
  ('Black Beans', 'Earthy, sweet, creamy when cooked', 'Dried pulse, the Americas', 'Year-round'),
  ('Black Cardamom', 'Smoky, camphorous, boldly resinous', 'Dried smoked pod, Himalayas', 'Year-round'),
  ('Black Eyed Pea', 'Earthy, faintly sweet, tender', 'Dried pulse, Africa/southern USA', 'Year-round'),
  ('Black Garlic', 'Sweet, balsamic, molasses-like umami', 'Slowly aged garlic, East Asia', 'Year-round'),
  ('Black Garlic Clove', 'Sweet, balsamic, molasses-like umami', 'Slowly aged garlic, East Asia', 'Year-round'),
  ('Black Garlic Paste', 'Concentrated sweet-savoury balsamic garlic', 'Aged garlic ground to a paste', 'Year-round'),
  ('Black Lime', 'Sour, musty, intensely citrus-fermented', 'Dried whole lime, Middle East', 'Year-round'),
  ('Black Mustard Seed', 'Sharp, nutty when popped in oil', 'Dried seed, India', 'Year-round'),
  ('Black Olive Tapenade', 'Salty, briny, deeply olive', 'Olive, caper and anchovy paste, Provence', 'Year-round'),
  ('Black Peppercorn', 'Sharp, woody heat with citrus-pine aroma', 'Dried pepper berries, India/Vietnam', 'Year-round'),
  ('Black Quinoa', 'Earthy, crunchy, faintly sweet', 'Pseudocereal, Andes', 'Year-round'),
  ('Black Radish', 'Pungent, peppery, sharply hot', 'Winter radish, Europe', 'Autumn to winter'),
  ('Black Rice', 'Nutty, faintly sweet; turns deep purple', 'Whole-grain rice, East Asia', 'Year-round'),
  ('Black Sesame', 'Deep, toasty, faintly bitter-nutty', 'Sesame seed, East Asia', 'Year-round'),
  ('Black Sesame Paste', 'Intensely nutty, roasted, faintly bitter', 'Ground black sesame, East Asia', 'Year-round'),
  ('Black Sesame Seed', 'Deep, toasty, faintly bitter-nutty', 'Sesame seed, East Asia', 'Year-round'),
  ('Black Tea Leaf', 'Tannic, malty, brisk', 'Fermented tea leaf, Asia', 'Year-round'),
  ('Black Truffle', 'Earthy, musky, deeply perfumed', 'Subterranean fungus, Périgord/Umbria', 'Winter'),
  ('Black Trumpet', 'Smoky, earthy, intensely woodland', 'Wild mushroom, European forests', 'Autumn'),
  ('Black Trumpet Mushroom', 'Smoky, earthy, intensely woodland', 'Wild mushroom, European forests', 'Autumn'),
  ('Black Vinegar', 'Malty, smoky, mellow-sour', 'Aged Chinkiang rice vinegar, China', 'Year-round'),
  ('Blackberry', 'Sweet-tart, winey, deeply fruity', 'Bramble fruit, temperate regions', 'Late summer to autumn'),
  ('Blackberry Purée', 'Intense sweet-tart blackberry', 'Sieved blackberries', 'Late summer fruit, year-round frozen'),
  ('Blackcurrant', 'Sharp, musky, intensely aromatic', 'Berry, temperate regions', 'Summer'),
  ('Blackcurrant Purée', 'Intense, sharp, musky-sweet', 'Sieved blackcurrants', 'Summer fruit, year-round frozen'),
  ('Bloderchäs', 'Fresh, tangy, soft and lactic', 'Traditional sour-milk cheese, Toggenburg, Switzerland', 'Year-round'),
  ('Blood Orange', 'Sweet-tart with raspberry-like depth', 'Citrus fruit, Sicily, Italy', 'Winter to early spring'),
  ('Blood Orange Purée', 'Sweet-tart, berry-tinged citrus', 'Sieved blood oranges', 'Winter fruit, year-round frozen'),
  ('Blood Sausage', 'Deep, mineral-rich, savoury and spiced', 'Cooked blood sausage, Europe', 'Year-round'),
  ('Blue Cheese', 'Sharp, salty, pungent with blue veining', 'Mould-ripened cheese, Europe', 'Year-round'),
  ('Blue Mussels', 'Sweet, briny, tender', 'Farmed mussel, North Atlantic', 'Autumn to spring'),
  ('Blue Potatoes', 'Earthy, nutty, firm; striking violet flesh', 'Heritage potato variety', 'Autumn harvest'),
  ('Blueberry', 'Sweet, mildly tart, gently floral', 'Berry, temperate regions', 'Summer'),
  ('Blueberry Purée', 'Sweet, mildly tart blueberry', 'Sieved blueberries', 'Summer fruit, year-round frozen'),
  ('Bodensee Cheese', 'Mild, creamy, gently nutty', 'Regional cheese, Lake Constance', 'Year-round'),
  ('Boiling Water', 'Neutral; the base of blanching and infusions', 'Potable water, heated', 'Year-round'),
  ('Bomba Rice', 'Absorbent, firm, mild; the paella rice', 'Short-grain rice, Valencia, Spain', 'Year-round'),
  ('Bonaparte Cheese', 'Rich, buttery, soft-ripened', 'Triple-cream cheese', 'Year-round'),
  ('Bone Broth Concentrate', 'Deep, gelatinous, intensely savoury', 'Reduced simmered bones', 'Year-round'),
  ('Bonito Flakes', 'Smoky, savoury, intensely umami', 'Dried fermented skipjack tuna, Japan', 'Year-round'),
  ('Bonito Flakes Powder', 'Concentrated smoky umami', 'Ground dried bonito, Japan', 'Year-round'),
  ('Bonito Loin', 'Rich, meaty, mackerel-like', 'Skipjack/bonito tuna, warm seas', 'Summer to autumn'),
  ('Borage', 'Cool, cucumber-like, faintly saline', 'Herb, Mediterranean', 'Summer'),
  ('Borage Flower', 'Delicate, cucumber-fresh; vivid blue garnish', 'Edible flower, Mediterranean', 'Summer'),
  ('Borlotti Bean', 'Creamy, chestnut-like, mild', 'Dried pulse, Italy', 'Fresh late summer, dried year-round'),
  ('Borlotti Beans', 'Creamy, chestnut-like, mild', 'Dried pulse, Italy', 'Fresh late summer, dried year-round'),
  ('Boskoop Apple', 'Sharply tart, aromatic; excellent cooked', 'Heritage apple, Netherlands', 'Autumn'),
  ('Bottarga', 'Intensely salty, briny, deeply umami', 'Cured fish roe, Sardinia/Sicily', 'Year-round'),
  ('Boudin Blanc', 'Delicate, creamy, mildly spiced white sausage', 'Fine pork/poultry sausage, France', 'Year-round (peak winter)'),
  ('Boutefas AOP', 'Smoky, coarse, richly porky', 'Cured sausage, Vaud, Switzerland', 'Autumn to winter'),
  ('Braeburn Apple', 'Crisp, sweet-tart, aromatic', 'Apple variety, New Zealand origin', 'Autumn to winter'),
  ('Brandy Or Cognac', 'Warm, oaky, fruity spirit', 'Distilled wine, France and elsewhere', 'Year-round'),
  ('Bratwurst', 'Mild, savoury, finely spiced', 'Fresh pork/veal sausage, German-speaking Europe', 'Year-round'),
  ('Brazil Nut', 'Rich, creamy, faintly sweet-resinous', 'Tree nut, Amazon basin', 'Harvested winter'),
  ('Brazil Nuts', 'Rich, creamy, faintly sweet-resinous', 'Tree nut, Amazon basin', 'Harvested winter'),
  ('Bread Flour Strong', 'Neutral, faintly nutty; strong and elastic', 'High-protein milled wheat', 'Year-round'),
  ('Breadcrumb', 'Neutral, toasty; adds crunch and binds', 'Dried ground bread', 'Year-round'),
  ('Bresaola', 'Lean, delicate, salty-sweet air-dried beef', 'Cured beef, Valtellina, Italy', 'Year-round'),
  ('Bretzeli Swiss', 'Crisp, buttery, faintly vanilla wafer', 'Traditional waffle biscuit, Switzerland', 'Year-round'),
  ('Brie', 'Buttery, mushroomy, soft-ripened', 'Cow''s-milk cheese, France', 'Year-round'),
  ('Brie de Meaux AOP', 'Deep, mushroomy, richly creamy', 'Raw-milk cheese, Île-de-France, France', 'Year-round'),
  ('Brik Pastry', 'Very thin, crisp when fried, neutral', 'Thin pastry sheet, Tunisia', 'Year-round'),
  ('Brill', 'Delicate, sweet, fine-flaked white fish', 'Flatfish, North Atlantic', 'Spring to autumn'),
  ('Brioche Buns', 'Rich, buttery, faintly sweet and soft', 'Enriched wheat bread, France', 'Year-round'),
  ('Broccolini', 'Sweet, tender, mildly mustardy', 'Broccoli–gai lan hybrid', 'Autumn to spring'),
  ('Brown Basmati', 'Nutty, chewy, fragrant', 'Whole-grain long rice, Indian subcontinent', 'Year-round'),
  ('Brown Butter', 'Toasted, nutty, deeply aromatic', 'Butter cooked until the solids brown', 'Year-round'),
  ('Brown Crab', 'Sweet white meat, rich savoury brown meat', 'Edible crab, North Atlantic', 'Summer to autumn'),
  ('Brown Mushrooms', 'Earthy, savoury, firmer than white', 'Cultivated chestnut mushroom', 'Year-round'),
  ('Brown Mustard Seeds', 'Pungent, sharp, nutty when toasted', 'Dried seed, India/Europe', 'Year-round'),
  ('Brown Sauce', 'Deep, roasted, savoury-sweet', 'Classic reduced meat sauce', 'Year-round'),
  ('Brown Sugar', 'Sweet with molasses, caramel and toffee', 'Sugar with molasses retained', 'Year-round'),
  ('Brussels Sprout', 'Nutty, sweet when roasted, faintly sulphurous', 'Brassica, temperate regions', 'Autumn to winter'),
  ('Brussels Sprouts', 'Nutty, sweet when roasted, faintly sulphurous', 'Brassica, temperate regions', 'Autumn to winter'),
  ('Bucatini', 'Neutral, wheaty; hollow strands hold sauce', 'Durum-wheat pasta, Italy', 'Year-round'),
  ('Buckwheat Flour', 'Earthy, robust, faintly bitter', 'Milled buckwheat groats', 'Year-round'),
  ('Bulgur', 'Nutty, wheaty, light', 'Parboiled cracked wheat, Middle East', 'Year-round'),
  ('Bulgur Coarse', 'Nutty, chewy, wheaty', 'Coarse parboiled cracked wheat, Middle East', 'Year-round'),
  ('Bulgur Wheat', 'Nutty, wheaty, light', 'Parboiled cracked wheat, Middle East', 'Year-round'),
  ('Burbot', 'Delicate, firm, sweet freshwater fish', 'Freshwater cod, northern lakes and rivers', 'Winter'),
  ('Burrata', 'Milky, sweet, oozing cream centre', 'Fresh cheese, Puglia, Italy', 'Year-round (best very fresh)'),
  ('Butcher''s Twine', 'Not edible — used to tie and truss', 'Food-safe cotton string', 'Year-round'),
  ('Butter Bean', 'Creamy, buttery, mild', 'Large dried lima bean', 'Year-round'),
  ('Butter Beans', 'Creamy, buttery, mild', 'Large dried lima beans', 'Year-round'),
  ('Butter Or Lard', 'Rich and lactic, or clean and porky', 'Churned cream or rendered pork fat', 'Year-round'),
  ('Butterhead Lettuce Heart', 'Soft, sweet, delicately buttery', 'Butterhead lettuce, temperate regions', 'Spring to autumn'),
  ('Buttermilk', 'Tangy, light, gently sour', 'Cultured milk by-product', 'Year-round'),
  ('Buttermilk Powder', 'Tangy, dairy-rich, concentrated', 'Dried buttermilk', 'Year-round'),
  ('Butternut Squash', 'Sweet, nutty, smooth', 'Winter squash, the Americas', 'Autumn to winter'),
  ('Button Mushrooms', 'Mild, earthy, savoury', 'Cultivated Agaricus mushroom', 'Year-round'),
  ('Bündner Bergkäse', 'Firm, fruity, nutty mountain cheese', 'Alpine cow''s-milk cheese, Graubünden, Switzerland', 'Year-round'),
  ('Bündner Nusstorte', 'Caramel-nut filling in a short pastry', 'Walnut tart, Graubünden, Switzerland', 'Year-round'),
  ('Bündnerfleisch', 'Lean, intensely beefy, air-dried and aromatic', 'Air-dried beef, Graubünden, Switzerland', 'Year-round'),
  ('Caciocavallo', 'Firm, tangy, gently piquant stretched-curd cheese', 'Cow''s-milk cheese, southern Italy', 'Year-round'),
  ('Caesar Dressing', 'Creamy, garlicky, anchovy-savoury', 'Emulsified dressing with anchovy and parmesan', 'Year-round'),
  ('Cajun Spice', 'Warm, peppery, herbal and smoky', 'Spice blend, Louisiana, USA', 'Year-round'),
  ('Cake Flour', 'Neutral, very fine; gives a tender crumb', 'Low-protein milled wheat', 'Year-round'),
  ('Calamansi Purée', 'Sharp, floral, lime-mandarin', 'Sieved calamansi citrus, Philippines', 'Year-round'),
  ('Calcium Chloride', 'Faintly saline-bitter; a firming and setting salt', 'Food-grade mineral salt', 'Year-round'),
  ('Calcium Lactate', 'Nearly neutral; used for reverse spherification', 'Food-grade calcium salt', 'Year-round'),
  ('Calvados', 'Warm, appley, oaked brandy', 'Apple brandy, Normandy, France', 'Year-round'),
  ('Cambozola', 'Creamy brie texture with mild blue tang', 'Cow''s-milk cheese, Germany', 'Year-round'),
  ('Camembert AOP', 'Mushroomy, buttery, soft-ripened', 'Raw-milk cheese, Normandy, France', 'Year-round'),
  ('Campari', 'Bitter, herbal, bright red aperitif', 'Bitter liqueur, Italy', 'Year-round'),
  ('Candied Chestnuts', 'Intensely sweet, soft, chestnut-rich', 'Marrons glacés, France/Italy', 'Made after autumn harvest'),
  ('Candied Ginger', 'Sweet-hot, chewy, warming', 'Ginger cooked in sugar syrup', 'Year-round'),
  ('Candied Lemon Peel', 'Sweet, bitter-aromatic citrus', 'Lemon peel cooked in syrup', 'Year-round'),
  ('Candied Orange Peel', 'Sweet, fragrant, gently bitter', 'Orange peel cooked in syrup', 'Year-round'),
  ('Candied Pecan', 'Sweet, toasted, buttery-nutty', 'Pecans cooked in sugar', 'Year-round'),
  ('Candied Violets', 'Delicately floral, sugary', 'Crystallised violet petals, France', 'Made in spring'),
  ('Candlenuts', 'Rich, waxy, mildly nutty; used to thicken', 'Tree nut, SE Asia', 'Year-round'),
  ('Candlenuts Or Macadamia', 'Rich and waxy, or buttery and sweet', 'Tree nuts, SE Asia/Australia', 'Year-round'),
  ('Cane Sugar', 'Clean sweetness with a faint molasses note', 'Refined from sugar cane', 'Year-round'),
  ('Canned Chopped Tomato', 'Sweet-tart, cooked, concentrated', 'Peeled chopped tomatoes, Italy', 'Year-round'),
  ('Canned Tuna Chunks', 'Savoury, firm, mildly oily', 'Cooked preserved tuna', 'Year-round'),
  ('Cannellini Bean', 'Creamy, mild, faintly nutty', 'White kidney bean, Italy', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
