-- 174_ingredient_info_backfill_batch4.sql
-- Ingredient info backfill — batch 4 (Richard, 23.7.2026). Same safety contract as db/171–173:
-- ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by name,
-- never overwrites — so the batch is idempotent and safe to re-run. Reference facts are universal,
-- so every kitchen's copy is filled; price stays per-kitchen and untouched. No deletes, no drops.
-- Covers the alphabetical range "Cannellini Beans" → "Cooking Chocolate" (150 names).
with m(name, flavour, origin, season) as (values
  ('Cannellini Beans', 'Creamy, mild, faintly nutty', 'White kidney beans, Italy', 'Year-round'),
  ('Cannelloni Tubes', 'Neutral, wheaty; a shell for filling', 'Durum-wheat pasta, Italy', 'Year-round'),
  ('Cantal AOP', 'Firm, buttery, tangy with age', 'Cow''s-milk cheese, Auvergne, France', 'Year-round'),
  ('Cantaloupe', 'Sweet, musky, floral melon', 'Melon, warm regions', 'Summer'),
  ('Cantaloupe Melon', 'Sweet, musky, floral melon', 'Melon, warm regions', 'Summer'),
  ('Cape Gooseberry', 'Sweet-tart, tropical, faintly tomato-like', 'Physalis fruit, South America', 'Late summer to autumn'),
  ('Caper', 'Salty, floral, sharply piquant', 'Pickled flower bud, Mediterranean', 'Harvested in summer'),
  ('Caper Berries', 'Milder than capers, briny with a seedy crunch', 'Fruit of the caper bush, Mediterranean', 'Harvested in summer'),
  ('Capers in Salt', 'Intensely floral-piquant; needs rinsing', 'Salt-packed caper buds, Sicily/Pantelleria', 'Harvested in summer'),
  ('Caramel Sauce', 'Sweet, buttery, gently bitter-toasted', 'Cooked sugar with cream and butter', 'Year-round'),
  ('Caramelized Pistachio', 'Sweet, toasted, green-nutty', 'Pistachios cooked in sugar', 'Year-round'),
  ('Caramelized Walnut', 'Sweet, toasted, faintly tannic', 'Walnuts cooked in sugar', 'Year-round'),
  ('Caraway Seed', 'Warm, aniseed-earthy, distinctly rye-like', 'Dried seed, Central/Northern Europe', 'Year-round'),
  ('Caraway Seeds', 'Warm, aniseed-earthy, distinctly rye-like', 'Dried seed, Central/Northern Europe', 'Year-round'),
  ('Cardamom', 'Intensely floral, citrus-eucalyptus, warm', 'Dried pod, India/Guatemala', 'Year-round'),
  ('Cardamom Pod', 'Intensely floral, citrus-eucalyptus, warm', 'Dried pod, India/Guatemala', 'Year-round'),
  ('Cardoon', 'Artichoke-like, bitter-nutty', 'Thistle stalk, Mediterranean', 'Autumn to winter'),
  ('Carnaroli Rice', 'Creamy yet firm; the risotto chef''s rice', 'Superfino rice, Piedmont/Lombardy, Italy', 'Year-round'),
  ('Carp', 'Mild, sweet, soft freshwater fish', 'Freshwater fish, Europe/Asia', 'Autumn to winter'),
  ('Cashew', 'Sweet, buttery, mildly creamy', 'Tree nut, India/Vietnam/Africa', 'Year-round'),
  ('Cashew Butter', 'Sweet, ultra-creamy, mild', 'Ground roasted cashews', 'Year-round'),
  ('Cashew Cream', 'Rich, neutral-sweet, dairy-like', 'Blended soaked cashews', 'Year-round'),
  ('Caster Sugar', 'Clean sweetness; dissolves fast', 'Finely milled refined sugar', 'Year-round'),
  ('Catfish Fillet', 'Mild, firm, faintly sweet', 'Freshwater fish, farmed worldwide', 'Year-round'),
  ('Caviar', 'Delicate, briny, buttery with a clean pop', 'Salted sturgeon roe, Caspian/farmed', 'Year-round (farmed)'),
  ('Cavolo Nero', 'Deep, mineral, gently bitter kale', 'Tuscan kale, Italy', 'Autumn to winter'),
  ('Cayenne Pepper', 'Clean, sharp, building heat', 'Ground dried chilli', 'Year-round'),
  ('Celeriac', 'Nutty, celery-like, earthy-sweet', 'Root vegetable, temperate regions', 'Autumn to winter'),
  ('Celery Salt', 'Savoury, herbal, saline', 'Salt blended with ground celery seed', 'Year-round'),
  ('Celery Stalk', 'Fresh, peppery, saline-green', 'Stalk vegetable, temperate regions', 'Year-round'),
  ('Century Egg', 'Pungent, creamy, deeply savoury and sulphurous', 'Alkaline-cured duck egg, China', 'Year-round'),
  ('Cervelat', 'Mild, smoky, finely ground', 'National sausage of Switzerland', 'Year-round'),
  ('Chabichou', 'Tangy, goaty, dense and chalky', 'Goat''s-milk cheese, Poitou, France', 'Spring to autumn'),
  ('Chai Spice Blend', 'Warm, sweet-spicy; cardamom, ginger, cinnamon, clove', 'Spice blend, India', 'Year-round'),
  ('Chamomile', 'Floral, apple-like, gently honeyed', 'Dried flower, Europe', 'Harvested in summer'),
  ('Chamomile Tea', 'Soft, floral, honeyed infusion', 'Infusion of dried chamomile flowers', 'Year-round'),
  ('Champagne', 'Crisp, brioche-like, finely sparkling', 'Sparkling wine, Champagne, France', 'Year-round'),
  ('Champagne Vinegar', 'Light, elegant, delicately sharp', 'Vinegar from Champagne wine, France', 'Year-round'),
  ('Chana Dal', 'Nutty, earthy, holds its shape', 'Split Bengal gram, India', 'Year-round'),
  ('Chanterelle', 'Fruity, apricot-scented, peppery', 'Wild mushroom, European forests', 'Summer to autumn'),
  ('Chanterelle Mushroom', 'Fruity, apricot-scented, peppery', 'Wild mushroom, European forests', 'Summer to autumn'),
  ('Char Siu Glaze', 'Sweet, savoury, five-spice and honey', 'Cantonese barbecue glaze, China', 'Year-round'),
  ('Charlotte Potatoes', 'Waxy, buttery, firm; ideal for salads', 'Potato variety, France', 'Summer to autumn'),
  ('Chartreuse', 'Intensely herbal, sweet-bitter, 130 botanicals', 'Monastic liqueur, France', 'Year-round'),
  ('Chaumes Cheese', 'Supple, fruity, gently pungent washed rind', 'Cow''s-milk cheese, France', 'Year-round'),
  ('Chayote', 'Crisp, mild, faintly cucumber-like', 'Gourd, Central America', 'Autumn to winter'),
  ('Cheddar Aged', 'Sharp, crystalline, deeply savoury', 'Matured cow''s-milk cheese, England', 'Year-round'),
  ('Chermoula', 'Herbal, lemony, cumin-garlic', 'Marinade of herbs and spices, North Africa', 'Year-round'),
  ('Cherry', 'Sweet-tart, juicy, gently almondy', 'Stone fruit, temperate regions', 'Early summer'),
  ('Cherry Purée', 'Intense sweet-tart cherry', 'Sieved cherries', 'Summer fruit, year-round frozen'),
  ('Chervil', 'Delicate, anise-parsley, fragile', 'Aromatic herb, Europe', 'Spring'),
  ('Chestnut', 'Sweet, starchy, earthy-nutty', 'Tree nut, southern Europe', 'Autumn'),
  ('Chestnut Flour', 'Sweet, nutty, faintly smoky', 'Milled dried chestnuts, Italy/France', 'Milled after autumn'),
  ('Chestnut Honey', 'Dark, bittersweet, resinous and bold', 'Chestnut-blossom honey, southern Europe', 'Harvested in summer'),
  ('Chestnut Mushroom', 'Earthy, savoury, firm', 'Cultivated brown mushroom', 'Year-round'),
  ('Chestnut Purée', 'Sweet, dense, earthy-nutty', 'Cooked sieved chestnuts', 'Autumn harvest, year-round'),
  ('Chestnut Purée Sweetened', 'Very sweet, dense, vanilla-chestnut', 'Sweetened cooked chestnuts, France', 'Year-round'),
  ('Chestnuts Vacuum Cooked', 'Sweet, soft, ready-to-use chestnuts', 'Peeled cooked chestnuts', 'Year-round'),
  ('Chia Seed', 'Neutral, faintly nutty; gels in liquid', 'Seed, Central America', 'Year-round'),
  ('Chicken', 'Mild, savoury, versatile', 'Poultry, farmed worldwide', 'Year-round'),
  ('Chicken Bones/Wings', 'Clean, savoury; the base of light stock', 'Poultry bones and wings', 'Year-round'),
  ('Chicken Breast', 'Lean, mild, tender', 'Poultry breast', 'Year-round'),
  ('Chicken Carcass', 'Clean, savoury; the base of stock', 'Poultry frame', 'Year-round'),
  ('Chicken Drumstick', 'Juicy, richer and darker than breast', 'Poultry leg', 'Year-round'),
  ('Chicken Drumsticks', 'Juicy, richer and darker than breast', 'Poultry legs', 'Year-round'),
  ('Chicken Liver', 'Rich, mineral, faintly sweet', 'Poultry liver', 'Year-round'),
  ('Chicken Liver Parfait', 'Silky, rich, buttery and mineral', 'Puréed chicken liver with butter', 'Year-round'),
  ('Chicken Or Duck Stock', 'Clean and savoury, or deeper and richer', 'Simmered poultry bones', 'Year-round'),
  ('Chicken Or Prawn Stock', 'Savoury poultry, or sweet-marine shellfish', 'Simmered poultry bones or prawn shells', 'Year-round'),
  ('Chicken Or Vegetable Stock', 'Savoury poultry, or lighter and vegetal', 'Simmered poultry bones or vegetables', 'Year-round'),
  ('Chicken Reduction', 'Concentrated, glossy, deeply savoury', 'Reduced chicken stock', 'Year-round'),
  ('Chicken Stock', 'Clean, savoury, lightly gelatinous', 'Simmered chicken bones and vegetables', 'Year-round'),
  ('Chicken Thigh', 'Juicy, richer, more forgiving than breast', 'Poultry leg meat', 'Year-round'),
  ('Chicken Wing', 'Savoury, gelatinous, crisps beautifully', 'Poultry wing', 'Year-round'),
  ('Chicken Wings', 'Savoury, gelatinous, crisps beautifully', 'Poultry wings', 'Year-round'),
  ('Chickpea', 'Nutty, earthy, creamy when cooked', 'Dried pulse, Middle East/India', 'Year-round'),
  ('Chickpea Flour', 'Earthy, nutty, faintly bitter raw', 'Milled dried chickpeas', 'Year-round'),
  ('Chicory Syrup', 'Dark, bittersweet, faintly coffee-like', 'Concentrated chicory root', 'Year-round'),
  ('Chili Crisp', 'Crunchy, savoury, numbing-spicy', 'Chilli in oil with aromatics, China', 'Year-round'),
  ('Chili Oil', 'Hot, aromatic, red-tinted', 'Chilli infused into oil', 'Year-round'),
  ('Chili Powder', 'Warm, earthy, mild to hot', 'Ground dried chillies', 'Year-round'),
  ('Chilli', 'Sharp, fruity heat, varies by variety', 'Capsicum fruit, the Americas/Asia', 'Summer to autumn'),
  ('Chilli Flake', 'Sharp, fruity heat', 'Dried crushed chillies', 'Year-round'),
  ('Chilli Oil', 'Hot, aromatic, red-tinted', 'Chilli infused into oil', 'Year-round'),
  ('Chimichurri', 'Herbal, garlicky, sharp with vinegar', 'Parsley and oregano sauce, Argentina', 'Year-round'),
  ('Chinese Broccoli', 'Faintly bitter, mustardy, crisp stems', 'Gai lan, China', 'Autumn to spring'),
  ('Chinese Cabbage', 'Sweet, mild, juicy and crisp', 'Napa cabbage, East Asia', 'Autumn to winter'),
  ('Chinese Chive', 'Garlicky, grassy, more assertive than chive', 'Allium herb, East Asia', 'Spring to summer'),
  ('Chinese Five Spice', 'Warm, sweet, anise-forward', 'Spice blend, China', 'Year-round'),
  ('Chinkiang Vinegar', 'Malty, smoky, mellow-sour', 'Aged black rice vinegar, China', 'Year-round'),
  ('Chioggia Beet', 'Sweet, mild, earthy; pink-and-white rings', 'Heritage beetroot, Italy', 'Autumn to winter'),
  ('Chipolata', 'Mild, savoury, finely spiced thin sausage', 'Small fresh sausage, France/UK', 'Year-round'),
  ('Chipotle Dried', 'Smoky, sweet, moderately hot', 'Smoke-dried jalapeño, Mexico', 'Year-round'),
  ('Chipotle In Adobo', 'Smoky, tangy, richly hot', 'Chipotle in tomato-vinegar sauce, Mexico', 'Year-round'),
  ('Chive', 'Delicate, oniony, fresh', 'Allium herb, temperate regions', 'Spring to summer'),
  ('Chocolate Glaze Mirror', 'Sweet, cocoa-rich; sets to a glossy mirror', 'Chocolate, cream and gelatine glaze', 'Year-round'),
  ('Chorizo', 'Smoky, paprika-rich, garlicky', 'Cured pork sausage, Spain', 'Year-round'),
  ('Choux Pastry Mix', 'Neutral, eggy; puffs hollow when baked', 'Flour, butter, water and egg paste, France', 'Year-round'),
  ('Choy Sum', 'Sweet, tender, mildly mustardy', 'Flowering brassica, China', 'Autumn to spring'),
  ('Chutney Mango', 'Sweet-sour, spiced, fruity', 'Cooked mango preserve, India', 'Year-round'),
  ('Chällerhocker', 'Dense, nutty, deeply savoury washed rind', 'Cow''s-milk cheese, Toggenburg, Switzerland', 'Year-round'),
  ('Chäschüechli Base', 'Savoury, cheesy, short pastry shell', 'Swiss cheese-tartlet base', 'Year-round'),
  ('Cider Dry', 'Crisp, tart, lightly appley', 'Fermented apple juice, Europe', 'Pressed in autumn'),
  ('Cinnamon Stick', 'Warm, sweet, woody-spicy', 'Dried inner bark, Sri Lanka/Indonesia', 'Year-round'),
  ('Cipollini Onions', 'Sweet, mild, flat; caramelise beautifully', 'Small flat onion, Italy', 'Autumn'),
  ('Citric Acid', 'Clean, sharp sourness', 'Crystalline acid produced by fermentation', 'Year-round'),
  ('Citrus Juice', 'Bright, sour, aromatic', 'Pressed citrus fruit', 'Peak in winter'),
  ('Clam', 'Sweet, briny, tender', 'Bivalve, Atlantic/Mediterranean', 'Autumn to spring'),
  ('Clams', 'Sweet, briny, tender', 'Bivalves, Atlantic/Mediterranean', 'Autumn to spring'),
  ('Clarified Butter', 'Pure, nutty butter; high smoke point', 'Butter with milk solids removed', 'Year-round'),
  ('Clementine', 'Sweet, juicy, easy-peeling citrus', 'Citrus fruit, Mediterranean', 'Winter'),
  ('Clotted Cream', 'Ultra-rich, nutty, thick', 'Slowly heated cream, Devon/Cornwall, England', 'Year-round'),
  ('Clove', 'Intensely warm, sweet, medicinal', 'Dried flower bud, Indonesia/Madagascar', 'Year-round'),
  ('Coarse Black Pepper', 'Sharp, woody, boldly aromatic', 'Coarsely cracked pepper berries', 'Year-round'),
  ('Coarse Rock Salt', 'Clean salinity; a curing and crusting salt', 'Mined rock salt', 'Year-round'),
  ('Coarse Salt', 'Clean salinity with crunch', 'Sea or rock salt, coarsely ground', 'Year-round'),
  ('Cockle', 'Sweet, intensely briny, small and tender', 'Bivalve, Atlantic coasts', 'Autumn to spring'),
  ('Cocktail Sauce', 'Sweet-tangy, tomato with a horseradish kick', 'Tomato and horseradish sauce', 'Year-round'),
  ('Cocoa Butter', 'Mild, cocoa-scented; melts at body temperature', 'Pressed cacao bean fat', 'Year-round'),
  ('Cocoa Butter Colour', 'Neutral; coloured cocoa butter for decoration', 'Cocoa butter with food colour', 'Year-round'),
  ('Cocoa Nibs', 'Bitter, crunchy, intensely cocoa', 'Crushed roasted cacao beans', 'Year-round'),
  ('Cocoa Powder', 'Deep, bitter, intensely chocolatey', 'Defatted ground cacao', 'Year-round'),
  ('Coconut Chips', 'Sweet, toasty, crisp', 'Dried sliced coconut', 'Year-round'),
  ('Coconut Cream', 'Very rich, sweet, intensely coconut', 'Pressed coconut flesh', 'Year-round'),
  ('Coconut Flakes', 'Sweet, chewy, coconut-rich', 'Dried shredded coconut', 'Year-round'),
  ('Coconut Flour', 'Sweet, fibrous, highly absorbent', 'Milled dried coconut', 'Year-round'),
  ('Coconut Milk', 'Creamy, sweet, tropical', 'Pressed coconut flesh and water', 'Year-round'),
  ('Coconut Oil Virgin', 'Sweet, aromatic, distinctly coconut', 'Cold-pressed coconut flesh', 'Year-round'),
  ('Coconut Purée', 'Smooth, sweet, intensely coconut', 'Sieved coconut flesh', 'Year-round'),
  ('Coconut Sugar', 'Caramel, faintly smoky, less sweet than cane', 'Boiled coconut-palm sap, SE Asia', 'Year-round'),
  ('Coconut Water', 'Light, sweet-saline, refreshing', 'Liquid of young green coconuts', 'Year-round'),
  ('Coconut Whole', 'Sweet, rich, fibrous flesh', 'Palm fruit, tropical regions', 'Year-round'),
  ('Cod', 'Clean, sweet, large flaking white fish', 'Whitefish, North Atlantic', 'Autumn to spring'),
  ('Cod Loin', 'Clean, sweet, thick and meaty', 'Whitefish loin, North Atlantic', 'Autumn to spring'),
  ('Coffee Beans', 'Roasted, bitter-sweet, deeply aromatic', 'Roasted coffee cherries, tropical highlands', 'Year-round'),
  ('Coffee Extract', 'Concentrated, bitter, intensely roasted', 'Concentrated coffee', 'Year-round'),
  ('Cognac', 'Warm, fruity, oaked grape brandy', 'Grape brandy, Cognac, France', 'Year-round'),
  ('Colatura di Alici', 'Intensely savoury, salty anchovy essence', 'Anchovy sauce, Cetara, Campania, Italy', 'Year-round'),
  ('Cold Water', 'Neutral; used to chill, rest and hydrate', 'Potable water', 'Year-round'),
  ('Coley', 'Firm, savoury, darker than cod', 'Whitefish (saithe), North Atlantic', 'Autumn to spring'),
  ('Compound Herb Butter', 'Rich, herbal, garlicky', 'Butter blended with herbs', 'Year-round'),
  ('Comté AOP', 'Nutty, fruity, complex; crystalline with age', 'Alpine cow''s-milk cheese, Jura, France', 'Year-round'),
  ('Conchiglie', 'Neutral, wheaty; shells that trap sauce', 'Durum-wheat pasta, Italy', 'Year-round'),
  ('Concord Grapes', 'Intensely musky, sweet-tart, foxy', 'Grape variety, North America', 'Autumn'),
  ('Condensed Milk', 'Intensely sweet, thick, caramel-prone', 'Sweetened evaporated milk', 'Year-round'),
  ('Condimento Balsamico', 'Sweet-sour, syrupy; balsamic outside the DOP rules', 'Cooked grape must, Modena, Italy', 'Year-round'),
  ('Conference Pear', 'Sweet, juicy, faintly grainy', 'Pear variety, Europe', 'Autumn'),
  ('Cooked Ham', 'Mild, salty, tender', 'Brined and cooked pork leg', 'Year-round'),
  ('Cooked Prawn', 'Sweet, firm, gently marine', 'Cooked prawns', 'Year-round'),
  ('Cooking Chocolate', 'Deep, bittersweet, melts smoothly', 'Couverture-style chocolate', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
