-- 175_ingredient_info_backfill_batch5.sql
-- Ingredient info backfill — batch 5 (Richard, 23.7.2026). Same safety contract as db/171–174:
-- ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by name,
-- never overwrites — idempotent and safe to re-run. Price stays per-kitchen and untouched.
-- Covers the alphabetical range "Cooking Sake" → "Ebi Furikake" (150 names).
with m(name, flavour, origin, season) as (values
  ('Cooking Sake', 'Mildly sweet, savoury; lifts and tenderises', 'Rice wine for cooking, Japan', 'Year-round'),
  ('Coppa', 'Sweet, marbled, delicately spiced cured pork', 'Cured pork neck, Italy', 'Year-round'),
  ('Coppa Ticinese', 'Mild, sweet, finely marbled', 'Cured pork neck, Ticino, Switzerland', 'Year-round'),
  ('Coriander Leaf', 'Bright, citrusy, pungent', 'Herb, warm regions', 'Year-round'),
  ('Coriander Seed', 'Warm, nutty, faintly citrus', 'Dried seed, Mediterranean/India', 'Year-round'),
  ('Coriander Stem', 'More intense and aromatic than the leaf', 'Herb stalk, warm regions', 'Year-round'),
  ('Corn Flour', 'Sweet, mild, faintly grainy', 'Milled maize', 'Year-round'),
  ('Corn Kernels', 'Sweet, juicy, tender', 'Maize, the Americas', 'Summer to early autumn'),
  ('Corn Oil', 'Neutral, clean; high smoke point', 'Pressed maize germ', 'Year-round'),
  ('Corn on the Cob', 'Sweet, milky, juicy', 'Maize, the Americas', 'Summer to early autumn'),
  ('Corn Salad', 'Soft, nutty, delicately sweet leaf', 'Lamb''s lettuce, Europe', 'Autumn to spring'),
  ('Corn Syrup', 'Clean, mild sweetness; prevents crystallisation', 'Glucose syrup from maize', 'Year-round'),
  ('Corn Tortillas', 'Toasty, sweet-earthy maize', 'Nixtamalised maize flatbread, Mexico', 'Year-round'),
  ('Corned Beef', 'Salty, spiced, tender cured beef', 'Brine-cured beef brisket', 'Year-round'),
  ('Cornichon', 'Sharp, crisp, tart little pickle', 'Pickled gherkin, France', 'Year-round'),
  ('Cornichons', 'Sharp, crisp, tart little pickles', 'Pickled gherkins, France', 'Year-round'),
  ('Cornmeal Fine', 'Sweet, grainy, faintly toasted', 'Finely ground maize', 'Year-round'),
  ('Cornstarch Or Potato Starch', 'Flavourless; a clear, glossy thickener', 'Starch from maize or potato', 'Year-round'),
  ('Cornstarch Slurry', 'Flavourless; thickens sauces on contact', 'Cornstarch mixed with cold water', 'Year-round'),
  ('Cottage Cheese', 'Mild, milky, gently sour with soft curds', 'Fresh curd cheese', 'Year-round'),
  ('Courgette', 'Mild, green, delicate', 'Summer squash', 'Summer'),
  ('Couscous', 'Neutral, wheaty, fluffy', 'Steamed semolina, North Africa', 'Year-round'),
  ('Couverture 70%', 'Intense, bittersweet, deeply cocoa', 'High-cocoa couverture chocolate', 'Year-round'),
  ('Crab Meat', 'Sweet, delicate, gently marine', 'Picked crab, Atlantic/Pacific', 'Summer to autumn'),
  ('Cranberry', 'Sharply tart, astringent, bright', 'Berry, North America/Northern Europe', 'Autumn'),
  ('Cranberry Compote', 'Sweet-tart, jammy, bright', 'Cooked cranberries with sugar', 'Autumn fruit, year-round'),
  ('Cranberry Juice', 'Sharp, tart, refreshing', 'Pressed cranberries', 'Autumn harvest'),
  ('Cranberry Sauce', 'Sweet-tart, gelled, festive', 'Cooked cranberries with sugar', 'Autumn to winter'),
  ('Crayfish', 'Sweet, delicate, faintly nutty freshwater shellfish', 'Freshwater crustacean, Europe/N. America', 'Summer to autumn'),
  ('Cream', 'Rich, creamy, subtly sweet dairy', 'Separated cow''s milk fat', 'Year-round'),
  ('Cream 35%', 'Rich, whips well, lightly sweet', 'Whipping cream, 35% fat', 'Year-round'),
  ('Cream Of Tartar', 'Faintly sour; stabilises whipped whites', 'Potassium bitartrate from winemaking', 'Year-round'),
  ('Cream Powder', 'Rich, dairy-sweet, concentrated', 'Dried cream', 'Year-round'),
  ('Crispy Fried Shallot', 'Sweet, deeply savoury, crunchy', 'Fried sliced shallots, SE Asia', 'Year-round'),
  ('Crispy Onion', 'Sweet, toasty, crunchy', 'Fried sliced onion', 'Year-round'),
  ('Croissant Dough', 'Buttery, laminated, faintly sweet', 'Laminated yeast dough, France', 'Year-round'),
  ('Crouton', 'Toasty, crisp, neutral-savoury', 'Fried or baked bread cubes', 'Year-round'),
  ('Crème Anglaise', 'Silky, vanilla-rich, gently sweet', 'Egg-yolk and milk custard sauce, France', 'Year-round'),
  ('Crème De Cassis', 'Sweet, deep, intensely blackcurrant', 'Blackcurrant liqueur, Burgundy, France', 'Year-round'),
  ('Crème Double', 'Extremely rich, thick, nutty', 'High-fat cream, Gruyère, Switzerland', 'Year-round'),
  ('Crème Fraîche', 'Rich, nutty, gently sour', 'Cultured cream, France', 'Year-round'),
  ('Crémant', 'Crisp, fine-bubbled, fruity sparkling wine', 'Traditional-method sparkling wine, France', 'Year-round'),
  ('Culinary Pumpkin', 'Sweet, earthy, dense', 'Cooking pumpkin, temperate regions', 'Autumn'),
  ('Cultured Butter', 'Tangy, deeply lactic, complex', 'Butter churned from cultured cream', 'Year-round'),
  ('Cumberland Sauce', 'Sweet-sharp, redcurrant with port and citrus', 'Fruit sauce for game, England', 'Autumn to winter'),
  ('Curing Salt', 'Intensely saline; fixes colour and preserves', 'Salt with sodium nitrite', 'Year-round'),
  ('Curry Ketchup Spice Mix', 'Sweet, tangy, mildly curried', 'Spice blend for curry ketchup, Germany', 'Year-round'),
  ('Curry Leaf', 'Citrus-nutty, uniquely aromatic', 'Fresh leaf, India/Sri Lanka', 'Year-round'),
  ('Curry Leaves', 'Citrus-nutty, uniquely aromatic', 'Fresh leaves, India/Sri Lanka', 'Year-round'),
  ('Curry Paste', 'Aromatic, spicy, herbal-pungent', 'Ground chilli and aromatics paste, SE Asia', 'Year-round'),
  ('Curry Paste Green', 'Herbal, fresh, sharply hot', 'Green chilli and herb paste, Thailand', 'Year-round'),
  ('Curry Paste Red', 'Warm, rounded, moderately hot', 'Red chilli and aromatics paste, Thailand', 'Year-round'),
  ('Curry Powder', 'Warm, earthy, turmeric-forward', 'Spice blend, Indian-British tradition', 'Year-round'),
  ('Curry Powder Madras', 'Hotter, deeper, more chilli-forward', 'Spice blend, southern India', 'Year-round'),
  ('Custard Powder', 'Vanilla-sweet; thickens to a smooth custard', 'Starch and flavour blend, England', 'Year-round'),
  ('Cutlet (Pork, Chicken, Or Firm Fish)', 'Mild and savoury; varies with the protein chosen', 'Pork, poultry or firm white fish', 'Year-round'),
  ('Cuttlefish', 'Sweet, firm, more robust than squid', 'Cephalopod, Mediterranean/Atlantic', 'Spring to autumn'),
  ('Cuttlefish Ink', 'Briny, savoury, deeply marine; stains jet black', 'Ink sac of cuttlefish, Mediterranean', 'Year-round'),
  ('Côte De Boeuf (Spanish Morucha Beef)', 'Deeply beefy, marbled, mature and rich', 'Bone-in rib of Morucha cattle, Spain', 'Year-round'),
  ('Dab', 'Delicate, sweet, fine-flaked flatfish', 'Flatfish, North Atlantic', 'Autumn to spring'),
  ('Daikon', 'Crisp, juicy, mildly peppery', 'White radish, East Asia', 'Autumn to winter'),
  ('Daikon Radish', 'Crisp, juicy, mildly peppery', 'White radish, East Asia', 'Autumn to winter'),
  ('Daikon Sprout', 'Peppery, sharp, delicate', 'Sprouted daikon seed, Japan', 'Year-round (sprouted)'),
  ('Damassine', 'Fruity, stone-fruit, gently fiery', 'Damson plum spirit AOP, Jura, Switzerland', 'Year-round'),
  ('Damson Plum', 'Intensely tart, winey, aromatic', 'Small plum, Europe', 'Late summer to autumn'),
  ('Dandelion Green', 'Sharply bitter, mineral, fresh', 'Wild leaf, temperate regions', 'Spring'),
  ('Dark Beer', 'Malty, roasted, faintly bitter', 'Dark-malt beer, Europe', 'Year-round'),
  ('Dark Chocolate', 'Bittersweet, deep, intensely cocoa', 'Cacao mass with sugar', 'Year-round'),
  ('Dark Chocolate 56%', 'Rounded, sweet-bitter, approachable', 'Couverture chocolate, 56% cocoa', 'Year-round'),
  ('Dark Chocolate 64%', 'Balanced, deep, moderately bitter', 'Couverture chocolate, 64% cocoa', 'Year-round'),
  ('Dark Chocolate 70%', 'Intense, bittersweet, low sugar', 'Couverture chocolate, 70% cocoa', 'Year-round'),
  ('Dark Chocolate Couverture', 'Deep, glossy, tempers to a clean snap', 'High-cocoa-butter chocolate', 'Year-round'),
  ('Dark Rum', 'Rich, molasses, vanilla and oak', 'Aged sugarcane spirit, Caribbean', 'Year-round'),
  ('Dark Soy Sauce', 'Thicker, sweeter, less salty; deep colour', 'Aged soy sauce with molasses, China', 'Year-round'),
  ('Dashi', 'Clean, smoky, profoundly umami', 'Kombu and bonito broth, Japan', 'Year-round'),
  ('Dashi Powder', 'Concentrated smoky-marine umami', 'Dried dashi granules, Japan', 'Year-round'),
  ('Date Syrup', 'Deep, caramel, fruity-sweet', 'Concentrated dates, Middle East', 'Year-round'),
  ('Datterini Tomatoes', 'Intensely sweet, low-acid, dense', 'Small plum tomato, southern Italy', 'Summer'),
  ('Day-Old Cooked Rice', 'Neutral; dried grains that fry separately', 'Cooked rice, chilled overnight', 'Year-round'),
  ('Decaf Coffee Beans', 'Roasted, bitter-sweet, without caffeine', 'Decaffeinated roasted coffee', 'Year-round'),
  ('Demerara Sugar', 'Toffee, molasses, crunchy crystals', 'Partially refined cane sugar', 'Year-round'),
  ('Demi-Glace', 'Deep, glossy, intensely savoury', 'Reduced veal/beef stock, France', 'Year-round'),
  ('Der Scharfe Maxx', 'Piquant, buttery, powerfully aromatic', 'Cow''s-milk cheese, Thurgau, Switzerland', 'Year-round'),
  ('Dextrose Powder', 'Cleanly sweet, less sweet than sucrose', 'Glucose from starch', 'Year-round'),
  ('Diced Vegetable', 'Fresh, mixed vegetal sweetness', 'Assorted vegetables, diced', 'Year-round'),
  ('Digestive Biscuit', 'Wheaty, lightly sweet, crumbly', 'Wholemeal biscuit, England', 'Year-round'),
  ('Dijon Vinaigrette', 'Sharp, mustardy, emulsified', 'Mustard, vinegar and oil dressing, France', 'Year-round'),
  ('Dill Seed', 'Warm, caraway-like, faintly bitter', 'Dried seed, Europe/Asia', 'Year-round'),
  ('Dill Seeds', 'Warm, caraway-like, faintly bitter', 'Dried seed, Europe/Asia', 'Year-round'),
  ('Dill Stalk', 'Grassy, anise-like, more robust than the frond', 'Herb stalk, temperate regions', 'Spring to summer'),
  ('Doenjang', 'Deeply savoury, funky, robustly fermented', 'Fermented soybean paste, Korea', 'Year-round'),
  ('Dolce (Blonde) Chocolate', 'Caramelised, biscuity, milky-sweet', 'Slow-caramelised white chocolate', 'Year-round'),
  ('Doubanjiang', 'Salty, funky, chilli-bean heat', 'Fermented broad-bean chilli paste, Sichuan', 'Year-round'),
  ('Douchi', 'Intensely salty, funky, deeply umami', 'Fermented black soybeans, China', 'Year-round'),
  ('Dover Sole', 'Sweet, firm, refined; the classic flatfish', 'Flatfish, North Atlantic', 'Spring to autumn'),
  ('Dragon Fruit', 'Mild, sweet, faintly kiwi-like', 'Cactus fruit, SE Asia/Central America', 'Summer to autumn'),
  ('Dried Adzuki Bean', 'Sweet, earthy, chestnut-like', 'Dried pulse, East Asia', 'Year-round'),
  ('Dried Apple Rings', 'Concentrated sweet-tart apple, chewy', 'Dehydrated apple', 'Year-round'),
  ('Dried Apricot', 'Intensely sweet-tart, chewy', 'Dehydrated apricot, Turkey/Central Asia', 'Year-round'),
  ('Dried Apricots', 'Intensely sweet-tart, chewy', 'Dehydrated apricots, Turkey/Central Asia', 'Year-round'),
  ('Dried Beef', 'Lean, intensely beefy, air-dried', 'Air-dried cured beef', 'Year-round'),
  ('Dried Cep', 'Deep, woodland, intensely umami', 'Dried porcini mushroom, Europe', 'Year-round'),
  ('Dried Cherry', 'Sweet-tart, chewy, concentrated', 'Dehydrated cherries', 'Year-round'),
  ('Dried Chilli', 'Concentrated fruity heat', 'Dehydrated chillies', 'Year-round'),
  ('Dried Cranberries', 'Sweet-tart, chewy', 'Sweetened dehydrated cranberries', 'Year-round'),
  ('Dried Cranberry', 'Sweet-tart, chewy', 'Sweetened dehydrated cranberries', 'Year-round'),
  ('Dried Currants', 'Intensely sweet, tangy, tiny', 'Dried Zante grapes, Greece', 'Year-round'),
  ('Dried Dill', 'Muted grassy-anise', 'Dehydrated dill', 'Year-round'),
  ('Dried Figs', 'Deeply sweet, jammy, seedy', 'Dehydrated figs, Mediterranean', 'Year-round'),
  ('Dried Hibiscus Flower', 'Sharply tart, cranberry-like, floral', 'Dried roselle calyx, Africa/Mexico', 'Year-round'),
  ('Dried Lavender', 'Intensely floral, faintly camphorous', 'Dried lavender buds, Provence', 'Harvested in summer'),
  ('Dried Lime', 'Sour, musty, intensely fermented citrus', 'Dried whole lime, Middle East', 'Year-round'),
  ('Dried Mango', 'Sweet, tangy, chewy tropical', 'Dehydrated mango', 'Year-round'),
  ('Dried Marjoram', 'Warm, sweet, gently oregano-like', 'Dehydrated marjoram, Mediterranean', 'Year-round'),
  ('Dried Mint', 'Cool, sweet, concentrated menthol', 'Dehydrated mint', 'Year-round'),
  ('Dried Morels', 'Deeply earthy, smoky, honeycombed', 'Dried morel mushrooms, Europe/N. America', 'Year-round'),
  ('Dried Oregano', 'Warm, peppery, faintly bitter', 'Dehydrated oregano, Mediterranean', 'Year-round'),
  ('Dried Pears', 'Sweet, honeyed, chewy', 'Dehydrated pears', 'Year-round'),
  ('Dried Porcini', 'Deep, woodland, intensely umami', 'Dried porcini mushroom, Europe', 'Year-round'),
  ('Dried Portobello', 'Meaty, earthy, concentrated', 'Dried portobello mushroom', 'Year-round'),
  ('Dried Rose Petal', 'Delicately floral, perfumed', 'Dried rose petals, Middle East', 'Year-round'),
  ('Dried Rose Petals', 'Delicately floral, perfumed', 'Dried rose petals, Middle East', 'Year-round'),
  ('Dried Rosemary', 'Piney, resinous, concentrated', 'Dehydrated rosemary, Mediterranean', 'Year-round'),
  ('Dried Sage', 'Musty, warm, faintly medicinal', 'Dehydrated sage, Mediterranean', 'Year-round'),
  ('Dried Scallop', 'Intensely sweet-savoury, concentrated umami', 'Dried scallop (conpoy), East Asia', 'Year-round'),
  ('Dried Shiitake', 'Deep, smoky, powerfully umami', 'Dried shiitake mushroom, East Asia', 'Year-round'),
  ('Dried Shrimp', 'Intensely savoury, salty, marine', 'Dried small shrimp, SE Asia', 'Year-round'),
  ('Dried Tangerine Peel', 'Bitter-citrus, aromatic, faintly medicinal', 'Dried mandarin peel, China', 'Year-round'),
  ('Dried Tarragon', 'Anise-like, muted, warm', 'Dehydrated tarragon, France', 'Year-round'),
  ('Dried Thyme', 'Earthy, floral, concentrated', 'Dehydrated thyme, Mediterranean', 'Year-round'),
  ('Dried Wood Ear Mushroom', 'Nearly neutral; prized for gelatinous crunch', 'Dried wood ear fungus, East Asia', 'Year-round'),
  ('Dried Yeast', 'Yeasty, faintly bready; the leavening agent', 'Dried baker''s yeast', 'Year-round'),
  ('Dry Sherry', 'Nutty, saline, crisply dry', 'Fortified wine, Jerez, Spain', 'Year-round'),
  ('Dry Shiitake', 'Deep, smoky, powerfully umami', 'Dried shiitake mushroom, East Asia', 'Year-round'),
  ('Dry Vermouth', 'Herbal, bitter-floral, crisply dry', 'Aromatised fortified wine, France/Italy', 'Year-round'),
  ('Duck Breast', 'Rich, gamey, with a thick fat cap', 'Duck breast, farmed', 'Year-round (peak autumn/winter)'),
  ('Duck Confit Legs', 'Deeply savoury, tender, salt-cured', 'Duck legs cooked in their own fat, France', 'Year-round'),
  ('Duck Egg', 'Richer, more golden and gelatinous than hen', 'Duck egg', 'Spring to summer'),
  ('Duck Eggs', 'Richer, more golden and gelatinous than hen', 'Duck eggs', 'Spring to summer'),
  ('Duck Fat', 'Silky, savoury; superb for roasting', 'Rendered duck fat', 'Year-round'),
  ('Duck Jus', 'Deep, glossy, intensely ducky', 'Reduced duck stock', 'Year-round'),
  ('Duck Leg', 'Rich, gamey, ideal slow-cooked', 'Duck leg, farmed', 'Year-round'),
  ('Duck Leg Confit', 'Deeply savoury, tender, salt-cured', 'Duck leg cooked in its own fat, France', 'Year-round'),
  ('Duck Liver', 'Rich, mineral, buttery', 'Duck liver', 'Autumn to winter'),
  ('Duck Prosciutto', 'Lean, salty, delicately gamey', 'Salt-cured air-dried duck breast', 'Year-round'),
  ('Dukkah', 'Nutty, toasty, coriander-cumin crunch', 'Nut and spice blend, Egypt', 'Year-round'),
  ('Dulce de Leche', 'Deeply caramel, milky, very sweet', 'Slowly caramelised milk, Latin America', 'Year-round'),
  ('Dutch Cocoa Powder', 'Mellow, dark, less acidic than natural', 'Alkalised cocoa powder', 'Year-round'),
  ('Earl Grey Tea', 'Black tea perfumed with bergamot', 'Flavoured black tea', 'Year-round'),
  ('Ebi Furikake', 'Savoury, marine, shrimp-toasted sprinkle', 'Rice seasoning with shrimp, Japan', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
