-- 177_ingredient_info_backfill_batch7.sql
-- Ingredient info backfill — batch 7 (Richard, 23.7.2026). Same safety contract as db/171–176:
-- ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by name,
-- never overwrites — idempotent. Price, kitchen_id and is_personal are never touched.
--
-- From this batch on the names come from the LIVE database (the 1'220 distinct names that still
-- had an empty flavour, origin or season), not from a written-out culinary list — so recipe-line
-- spellings like 'cherry tomatoes, halved' and supplier codes like '00 flour w260' are matched
-- exactly as they are stored. 174 names, alphabetically '00 flour w260' → 'invertase'.
with m(name, flavour, origin, season) as (values
  ('00 flour w260', 'Neutral, soft, finely milled wheat flour', 'Italian tipo 00 wheat flour, W260 strength', 'Year-round'),
  ('anise', 'Sweet, warm, liquorice-like', 'Pimpinella anisum seed, Mediterranean', 'Year-round; harvested autumn'),
  ('apple purée', 'Sweet-tart, clean apple', 'Cooked and sieved apples', 'Year-round; fruit peaks autumn'),
  ('apricot purée', 'Sweet-tart, honeyed stone fruit', 'Cooked and sieved apricots', 'Year-round; fruit peaks summer'),
  ('bacon jam', 'Sweet, smoky, savoury and sticky', 'Slow-cooked bacon with onion and sugar', 'Year-round'),
  ('banana purée', 'Sweet, creamy, tropical', 'Sieved ripe bananas', 'Year-round'),
  ('berner alpkäse aop', 'Firm, nutty, floral alpine cheese', 'Raw cow''s milk, Bernese alps, Switzerland', 'Made in summer, matured for autumn and winter'),
  ('berner hobelkäse aop', 'Hard, intensely nutty; shaved in fine curls', 'Extra-matured Berner Alpkäse, Switzerland', 'Year-round'),
  ('bio kalamata olives', 'Fruity, winey, meaty black olive', 'Organic Kalamata olives, Messenia, Greece', 'Year-round; harvest autumn'),
  ('black peppercorns', 'Pungent, woody, sharply hot', 'Dried Piper nigrum berries, India and Vietnam', 'Year-round'),
  ('blackberry purée', 'Deep, winey, sweet-tart berry', 'Sieved blackberries', 'Year-round; fruit peaks late summer'),
  ('blackcurrant purée', 'Intense, tart, musky berry', 'Sieved blackcurrants', 'Year-round; fruit peaks summer'),
  ('bloderchäs', 'Fresh, sour, lightly salty soft cheese', 'Raw cow''s milk, Toggenburg, Switzerland', 'Year-round'),
  ('blood orange purée', 'Sweet-tart citrus with red-berry notes', 'Sieved blood oranges, Sicily', 'Year-round; fruit peaks winter'),
  ('blueberry purée', 'Sweet, mild, faintly floral berry', 'Sieved blueberries', 'Year-round; fruit peaks summer'),
  ('bündner bergkäse', 'Firm, nutty, mildly spicy mountain cheese', 'Cow''s milk, Graubünden, Switzerland', 'Year-round'),
  ('bündner nusstorte', 'Buttery shortcrust with caramelised walnut filling', 'Traditional pastry, Graubünden, Switzerland', 'Year-round'),
  ('bündnerfleisch', 'Lean, salty air-dried beef with herbal notes', 'Air-dried beef, Graubünden, Switzerland', 'Year-round'),
  ('burrata pugliese 250g', 'Milky and creamy with a stracciatella centre', 'Cow''s milk, Puglia, Italy', 'Year-round; best within days of making'),
  ('butter (soft)', 'Rich, creamy, mildly sweet', 'Churned cream, softened to room temperature', 'Year-round'),
  ('calamansi purée', 'Sharp, floral, sour citrus', 'Sieved calamansi, Philippines', 'Year-round'),
  ('carrots', 'Sweet, earthy, crunchy', 'Daucus carota root', 'Year-round; peak summer to autumn'),
  ('cherry tomatoes, halved', 'Sweet, bright, acidic', 'Small tomatoes, halved for service', 'Summer to early autumn'),
  ('chicken liver, cleaned', 'Rich, mineral, faintly sweet offal', 'Chicken liver, sinew removed', 'Year-round'),
  ('clarified butter or neutral oil, for pan-frying', 'Neutral to lightly nutty; high smoke point', 'Clarified butter or refined vegetable oil', 'Year-round'),
  ('coleslaw', 'Creamy, tangy, crunchy cabbage salad', 'Cabbage and carrot in dressing', 'Year-round'),
  ('cooked ham, thinly sliced', 'Mild, salty, lightly smoky', 'Brined and cooked pork leg', 'Year-round'),
  ('crouton: 10g', 'Toasted, crisp, buttery bread', 'Diced bread, fried or oven-baked', 'Year-round'),
  ('cucumber, sliced', 'Cool, watery, faintly green', 'Cucumis sativus, sliced', 'Summer'),
  ('cured guanciale', 'Deeply porky, fatty, peppery', 'Cured pork jowl, Lazio and Umbria, Italy', 'Year-round'),
  ('dates', 'Intensely sweet, caramel, chewy', 'Date palm fruit, Middle East and North Africa', 'Year-round; harvest autumn'),
  ('dates, chopped', 'Intensely sweet, caramel; chopped for baking', 'Date palm fruit, chopped', 'Year-round'),
  ('egg yolks', 'Rich, fatty, custardy', 'Separated hen''s eggs', 'Year-round'),
  ('eggs, beaten', 'Neutral-rich; binds and sets', 'Whole hen''s eggs, beaten', 'Year-round'),
  ('époisses aop', 'Pungent, sticky, powerfully savoury washed rind', 'Cow''s milk, Burgundy, France', 'Best autumn to winter'),
  ('extra virgin olive oil 5 l', 'Fruity, peppery, grassy', 'First cold-pressed olives, Mediterranean', 'Year-round; pressed in autumn'),
  ('extra virgin olive oil 5l', 'Fruity, peppery, grassy', 'First cold-pressed olives, Mediterranean', 'Year-round; pressed in autumn'),
  ('fine dry breadcrumbs', 'Neutral and toasty; crisps when fried', 'Dried and milled bread', 'Year-round'),
  ('flour type 00 w260', 'Neutral, soft, finely milled wheat flour', 'Italian tipo 00 wheat flour, W260 strength', 'Year-round'),
  ('free-range egg yolks', 'Rich, deeply coloured, custardy', 'Separated free-range hen''s eggs', 'Year-round'),
  ('french dressing (vinaigrette) or italian dressing, chef''s choice', 'Sharp, oily, herbal', 'Oil-and-vinegar salad dressing', 'Year-round'),
  ('fresh basil, bunch', 'Sweet, peppery, aniseed-like herb', 'Ocimum basilicum, Mediterranean', 'Summer'),
  ('full-fat milk', 'Creamy, mildly sweet', 'Whole cow''s milk', 'Year-round'),
  ('garlic, finely chopped', 'Pungent and sharp raw, sweet when cooked', 'Allium sativum, chopped', 'Year-round; new season in summer'),
  ('gochugaru', 'Fruity, smoky, moderately hot chilli flake', 'Sun-dried Korean chilli, Korea', 'Year-round'),
  ('gochujang', 'Sweet, savoury, fermented chilli heat', 'Fermented chilli and rice paste, Korea', 'Year-round'),
  ('goji berries', 'Sweet-tart, faintly herbal dried berry', 'Dried Lycium barbarum, China', 'Year-round'),
  ('gold leaf edible', 'Flavourless; purely decorative', 'Hammered pure gold', 'Year-round'),
  ('golden beetroot', 'Sweet and earthy, milder than red beetroot', 'Golden Beta vulgaris root', 'Autumn to winter'),
  ('golden syrup', 'Buttery, caramel, very sweet', 'Partially inverted cane sugar syrup, UK', 'Year-round'),
  ('goose', 'Rich, dark, deeply fatty poultry', 'Farmed goose, Europe', 'Autumn to winter'),
  ('goose whole', 'Rich, dark, deeply fatty poultry', 'Whole farmed goose, Europe', 'Autumn to winter'),
  ('gooseberry', 'Sharp, tart, green and grassy', 'Ribes uva-crispa', 'Early summer'),
  ('gorgonzola', 'Creamy, salty, sharp blue', 'Cow''s milk, Lombardy and Piedmont, Italy', 'Year-round'),
  ('gorgonzola dop', 'Creamy, salty, sharp protected blue', 'Cow''s milk, Lombardy and Piedmont, Italy', 'Year-round'),
  ('grains of paradise', 'Peppery, citrusy, warm', 'Aframomum melegueta seed, West Africa', 'Year-round'),
  ('grana padano', 'Hard, nutty, savoury; gentler than parmesan', 'Cow''s milk, Po valley, Italy', 'Year-round'),
  ('grana padano dop', 'Hard, nutty, savoury protected grating cheese', 'Cow''s milk, Po valley, Italy', 'Year-round'),
  ('grand marnier', 'Sweet orange with cognac warmth', 'Cognac and bitter orange liqueur, France', 'Year-round'),
  ('granny smith apple', 'Very tart, crisp, green', 'Malus domestica cultivar', 'Autumn to spring'),
  ('granulated sugar', 'Clean sweetness', 'Refined cane or beet sugar', 'Year-round'),
  ('grape juice red', 'Sweet, musky, lightly tannic', 'Pressed red grapes', 'Year-round; pressed in autumn'),
  ('grape leaves in brine', 'Salty, sour, faintly tannic', 'Brined vine leaves, eastern Mediterranean', 'Year-round'),
  ('grapefruit', 'Bitter, sour, bright citrus', 'Citrus paradisi', 'Winter to spring'),
  ('grapeseed oil', 'Very neutral and clean; high smoke point', 'Pressed grape seeds', 'Year-round'),
  ('grappa', 'Fiery, grapey, aromatic', 'Distilled grape pomace, Italy', 'Year-round'),
  ('grayling', 'Delicate, sweet, faintly thyme-scented freshwater fish', 'Thymallus thymallus, alpine rivers', 'Autumn to winter'),
  ('green asparagus', 'Grassy, sweet, faintly bitter', 'Asparagus officinalis', 'Spring'),
  ('green bean', 'Fresh, grassy, snappy', 'Phaseolus vulgaris pod', 'Summer'),
  ('green beans', 'Fresh, grassy, snappy', 'Phaseolus vulgaris pods', 'Summer'),
  ('green bell pepper', 'Grassy, slightly bitter, crisp', 'Unripe Capsicum annuum', 'Summer to autumn'),
  ('green colour', 'Flavourless; colouring only', 'Food colouring', 'Year-round'),
  ('green curry sauce', 'Hot, herbal, coconut-rich', 'Thai green curry base', 'Year-round'),
  ('green kohlrabi leaves', 'Cabbagey, mildly peppery greens', 'Kohlrabi tops', 'Spring to autumn'),
  ('green lentil', 'Earthy and peppery; holds its shape', 'Lens culinaris, France and Canada', 'Year-round'),
  ('green olive tapenade', 'Salty, briny, herbal', 'Crushed green olives, capers and oil, Provence', 'Year-round'),
  ('green pea', 'Sweet, grassy, tender', 'Pisum sativum', 'Late spring to summer'),
  ('green peppercorns in brine', 'Fresh, mild, herbal pepper', 'Unripe Piper nigrum in brine', 'Year-round'),
  ('green sosa colouring', 'Flavourless; colouring only', 'Powdered food colouring, Sosa', 'Year-round'),
  ('green split pea', 'Earthy and sweet; cooks down to a purée', 'Split Pisum sativum', 'Year-round'),
  ('green tea powder', 'Grassy, bitter, umami', 'Ground green tea leaves, Japan', 'Year-round; spring harvest'),
  ('green tomatoes', 'Tart, firm, grassy', 'Unripe tomatoes', 'Late summer to autumn'),
  ('green zucchini flowers', 'Delicate, faintly sweet, squash-scented', 'Courgette blossoms', 'Summer'),
  ('green/yellow colour', 'Flavourless; colouring only', 'Food colouring', 'Year-round'),
  ('greengage', 'Honeyed, sweet, richly perfumed plum', 'Prunus domestica subsp. italica', 'Late summer'),
  ('greengage plum', 'Honeyed, sweet, richly perfumed plum', 'Prunus domestica subsp. italica', 'Late summer'),
  ('grenadine', 'Sweet-tart pomegranate syrup', 'Pomegranate syrup', 'Year-round'),
  ('grey shrimp', 'Sweet, briny, intensely shrimpy', 'Crangon crangon, North Sea', 'Spring to autumn'),
  ('grilled peach', 'Sweet, smoky, caramelised', 'Grilled Prunus persica', 'Summer'),
  ('grilled shiitake mushroom', 'Meaty, smoky, deeply umami', 'Grilled Lentinula edodes', 'Year-round'),
  ('grissini', 'Crisp, salty, toasty breadstick', 'Baked wheat dough, Turin, Italy', 'Year-round'),
  ('ground almond', 'Sweet, nutty, marzipan-like', 'Milled almonds', 'Year-round'),
  ('ground coffee', 'Roasted, bitter, aromatic', 'Roasted and milled coffee beans', 'Year-round'),
  ('ground lamb', 'Rich, gamey, fatty', 'Minced lamb', 'Year-round; peak spring'),
  ('ground paprika', 'Sweet, mildly smoky pepper powder', 'Milled dried Capsicum, Hungary and Spain', 'Year-round'),
  ('ground pork', 'Mild, sweet, fatty', 'Minced pork', 'Year-round'),
  ('ground red paprika', 'Sweet-sharp, deep red pepper powder', 'Milled dried red Capsicum', 'Year-round'),
  ('ground veal', 'Delicate, mild, lean', 'Minced veal', 'Year-round'),
  ('gruyère', 'Firm, nutty, salty-sweet', 'Cow''s milk, Fribourg, Switzerland', 'Year-round'),
  ('gruyère alpage aop', 'Complex, floral, intensely nutty', 'Summer alpine raw cow''s milk, Switzerland', 'Made in summer, sold from autumn'),
  ('gruyère aop', 'Firm, nutty, salty-sweet protected cheese', 'Raw cow''s milk, Fribourg, Switzerland', 'Year-round'),
  ('gruyère d''alpage aop', 'Complex, floral, intensely nutty', 'Summer alpine raw cow''s milk, Switzerland', 'Made in summer, sold from autumn'),
  ('guacamole', 'Creamy, limey, mildly spicy', 'Crushed avocado with lime and chilli, Mexico', 'Year-round'),
  ('guanaja 70% chocolate', 'Intense and bitter with a long cocoa finish', 'Valrhona dark couverture, 70% cocoa', 'Year-round'),
  ('guava', 'Musky, sweet, tropical and floral', 'Psidium guajava', 'Autumn to winter'),
  ('guinea fowl', 'Lean, faintly gamey poultry', 'Numida meleagris, farmed', 'Year-round; peak autumn'),
  ('gurnard', 'Firm, sweet, mild white fish', 'Triglidae, Atlantic and Mediterranean', 'Autumn to winter'),
  ('gyoza vegetable', 'Savoury, cabbagey, sesame-scented filling', 'Vegetable dumpling, Japan', 'Year-round'),
  ('gyoza wrapper', 'Neutral; thin and chewy once cooked', 'Wheat dough wrapper, Japan', 'Year-round'),
  ('habanero', 'Fiercely hot with apricot fruitiness', 'Capsicum chinense, Yucatán, Mexico', 'Summer to autumn'),
  ('habanero chili', 'Fiercely hot with apricot fruitiness', 'Capsicum chinense, Yucatán, Mexico', 'Summer to autumn'),
  ('haddock', 'Delicate, sweet, flaky white fish', 'Melanogrammus aeglefinus, North Atlantic', 'Autumn to winter'),
  ('hagenwiler schlosskäse', 'Semi-soft, buttery, mildly tangy', 'Cow''s milk, Thurgau, Switzerland', 'Year-round'),
  ('hake', 'Soft, sweet, fine-flaked white fish', 'Merluccius species, Atlantic', 'Autumn to winter'),
  ('half cream', 'Lightly creamy and pourable', 'Cow''s cream, around 25% fat', 'Year-round'),
  ('halibut', 'Firm, sweet, meaty white fish', 'Hippoglossus hippoglossus, North Atlantic', 'Spring to summer'),
  ('halloumi', 'Salty and squeaky; holds its shape on the grill', 'Sheep and goat''s milk, Cyprus', 'Year-round'),
  ('hamachi', 'Buttery, rich, clean yellowtail', 'Seriola quinqueradiata, Japan', 'Winter'),
  ('hard-boiled egg', 'Mild, faintly sulphurous, firm', 'Boiled hen''s egg', 'Year-round'),
  ('hare', 'Dark, strongly gamey, lean', 'Lepus europaeus, wild', 'Autumn to winter'),
  ('haricot bean', 'Mild and creamy; absorbs surrounding flavour', 'Dried Phaseolus vulgaris', 'Year-round'),
  ('harissa', 'Hot, smoky, garlicky chilli paste', 'Chilli and spice paste, Tunisia', 'Year-round'),
  ('hash browns', 'Crisp outside, soft potato inside', 'Grated fried potato', 'Year-round'),
  ('hatcho miso', 'Very dark, savoury, faintly bitter', 'Pure soybean miso, Aichi, Japan', 'Year-round'),
  ('hauskäse vorderländerart', 'Semi-hard, mild, buttery', 'Cow''s milk, Appenzell Vorderland, Switzerland', 'Year-round'),
  ('hazelnut', 'Sweet, toasty, buttery', 'Corylus avellana, Piedmont and Turkey', 'Year-round; harvest autumn'),
  ('hazelnut flour', 'Sweet, nutty, rich', 'Milled hazelnuts', 'Year-round'),
  ('hazelnut oil', 'Intensely nutty and delicate', 'Pressed roasted hazelnuts', 'Year-round'),
  ('hazelnut paste', 'Deeply toasted, sweet, oily', 'Ground roasted hazelnuts', 'Year-round'),
  ('hazelnut praline', 'Caramelised sugar and toasted hazelnut', 'Caramelised hazelnuts, ground to a paste', 'Year-round'),
  ('hazelnuts, chopped', 'Sweet, toasty, crunchy', 'Chopped Corylus avellana', 'Year-round'),
  ('hearts of palm', 'Mild, faintly artichoke-like, crisp', 'Inner palm core, South America', 'Year-round'),
  ('hedgehog mushroom', 'Sweet, nutty, faintly peppery', 'Hydnum repandum, European woodland', 'Autumn'),
  ('heirloom tomatoes', 'Sweet and complex, with varied acidity', 'Traditional tomato varieties', 'Summer'),
  ('hemp seed', 'Nutty, grassy, soft', 'Cannabis sativa seed', 'Year-round'),
  ('hemp seeds', 'Nutty, grassy, soft', 'Cannabis sativa seed', 'Year-round'),
  ('hen of the woods', 'Earthy, peppery, meaty', 'Grifola frondosa, at the base of oaks', 'Autumn'),
  ('herb salad', 'Fresh, varied, aromatic leaves', 'Mixed soft herbs and salad leaves', 'Spring to autumn'),
  ('herbes de provence', 'Floral, resinous, herbal', 'Dried Provençal herb blend, France', 'Year-round'),
  ('herring', 'Oily, rich, distinctly savoury', 'Clupea harengus, North Atlantic and Baltic', 'Late spring to autumn'),
  ('hibiscus flowers', 'Tart, cranberry-like, floral', 'Dried Hibiscus sabdariffa calyces', 'Year-round'),
  ('hidaka kombu', 'Mild, softly savoury kelp', 'Saccharina angustata, Hokkaido, Japan', 'Year-round'),
  ('himalayan pink salt', 'Clean, mineral saltiness', 'Rock salt, Punjab, Pakistan', 'Year-round'),
  ('hobelbutter note', 'Rich and creamy; shaved into curls', 'Firm butter for shaving', 'Year-round'),
  ('hoisin sauce', 'Sweet, salty, fermented soy with five-spice', 'Fermented soybean sauce, China', 'Year-round'),
  ('hojicha powder', 'Roasted and toasty, with little bitterness', 'Roasted green tea, Japan', 'Year-round'),
  ('hokkaido pumpkin', 'Sweet, chestnutty, dense', 'Cucurbita maxima; skin is edible', 'Autumn to winter'),
  ('hokkaido squash', 'Sweet, chestnutty, dense', 'Cucurbita maxima; skin is edible', 'Autumn to winter'),
  ('hollandaise pro', 'Buttery, lemony, rich emulsion', 'Prepared hollandaise base', 'Year-round'),
  ('hon mirin', 'Sweet, mellow, faintly alcoholic', 'Brewed sweet rice seasoning, Japan', 'Year-round'),
  ('hondashi granules', 'Instantly savoury and smoky-fishy', 'Instant bonito dashi granules, Japan', 'Year-round'),
  ('honeycomb', 'Floral, waxy, intensely sweet', 'Comb honey from the hive', 'Summer to autumn'),
  ('honeydew melon', 'Sweet, floral, juicy', 'Cucumis melo', 'Summer'),
  ('horse meat', 'Lean, faintly sweet, mineral-rich', 'Equine meat, Europe', 'Year-round'),
  ('horseradish cream', 'Hot, sinus-clearing, creamy', 'Grated horseradish in cream', 'Year-round'),
  ('horseradish fresh', 'Fiercely pungent and sharp', 'Armoracia rusticana root', 'Autumn to spring'),
  ('hot sauce', 'Hot, sharp, vinegary', 'Fermented chilli sauce', 'Year-round'),
  ('hot water', 'Neutral', 'Potable water, heated', 'Year-round'),
  ('house bbq dry rub', 'Sweet, smoky, peppery', 'House spice and sugar rub', 'Year-round'),
  ('house bbq sauce', 'Sweet, smoky, tangy', 'House barbecue sauce', 'Year-round'),
  ('house dressing', 'Balanced, tangy, oily', 'House salad dressing', 'Year-round'),
  ('hühnerbrust (salzlake, pochiert)', 'Mild, juicy, evenly seasoned', 'Brined and poached chicken breast', 'Year-round'),
  ('hummus', 'Creamy, nutty, lemony', 'Chickpeas and tahini, Levant', 'Year-round'),
  ('ice cream vanilla pro', 'Sweet, creamy, vanilla-scented', 'Prepared vanilla ice cream base', 'Year-round'),
  ('ice-cold water', 'Neutral', 'Chilled potable water', 'Year-round'),
  ('iceberg lettuce', 'Crisp, watery, very mild', 'Lactuca sativa var. capitata', 'Summer to autumn'),
  ('ichimi togarashi', 'Straight, clean chilli heat', 'Ground red chilli, Japan', 'Year-round'),
  ('icing sugar', 'Clean sweetness; dissolves instantly', 'Finely milled sugar with starch', 'Year-round'),
  ('ikura or tobiko', 'Briny, popping, richly savoury roe', 'Salmon roe or flying-fish roe, Japan', 'Autumn for salmon roe; year-round frozen'),
  ('illanka chocolate', 'Fruity, red-berry, intense dark', 'Valrhona single-origin dark couverture, Peru', 'Year-round'),
  ('inca (physalis) tomato', 'Sweet-tart, tropical, faintly tomato-like', 'Physalis peruviana, Andes', 'Late summer to autumn'),
  ('instant yeast', 'Neutral; yeasty aroma while proving', 'Dried Saccharomyces cerevisiae', 'Year-round'),
  ('invert sugar', 'Very sweet and smooth; keeps bakes moist', 'Hydrolysed sucrose syrup', 'Year-round'),
  ('invertase', 'Flavourless; softens fondant centres', 'Enzyme preparation', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
