-- 178_ingredient_info_backfill_batch8.sql
-- Ingredient info backfill — batch 8 (Richard, 23.7.2026). Same safety contract as db/171–177:
-- ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by name,
-- never overwrites — idempotent. Price, kitchen_id and is_personal are never touched.
-- 174 names from the live remaining list, 'iqf mango chunks' → 'menma'.
with m(name, flavour, origin, season) as (values
  ('iqf mango chunks', 'Sweet, resinous, tropical', 'Individually quick-frozen mango', 'Year-round'),
  ('iqf raspberries', 'Sharp, perfumed, sweet-tart', 'Individually quick-frozen raspberries', 'Year-round'),
  ('isomalt', 'Barely sweet; used for clear sugar work', 'Sugar alcohol from beet sucrose', 'Year-round'),
  ('jackfruit young', 'Neutral and faintly tart; shreds like meat', 'Unripe Artocarpus heterophyllus, South Asia', 'Year-round; fresh in summer'),
  ('jalapeño fresh', 'Grassy, bright, moderately hot', 'Capsicum annuum, Mexico', 'Summer to autumn'),
  ('jalapeño or green chilli', 'Grassy, bright, moderately hot', 'Fresh green Capsicum annuum', 'Summer to autumn'),
  ('jamón ibérico', 'Deep, nutty, melting cured ham', 'Acorn-fed Iberian pork, Spain', 'Year-round'),
  ('jamón serrano', 'Salty, dry, lightly nutty cured ham', 'Cured white-pig leg, Spain', 'Year-round'),
  ('japanese curry roux', 'Sweet, mild, savoury spiced roux', 'Blocked curry roux, Japan', 'Year-round'),
  ('jasmine rice', 'Floral, soft, faintly milky long grain', 'Oryza sativa, Thailand', 'Year-round'),
  ('jasmine rice premium', 'Strongly floral, soft, aromatic long grain', 'Top-grade Thai Hom Mali rice', 'Year-round'),
  ('jerk seasoning', 'Hot, allspice-warm, thyme-scented', 'Jamaican spice blend', 'Year-round'),
  ('jerusalem artichoke', 'Sweet, nutty, faintly smoky tuber', 'Helianthus tuberosus', 'Autumn to early spring'),
  ('jicama', 'Crisp, watery, faintly sweet', 'Pachyrhizus erosus root, Mexico', 'Autumn to spring'),
  ('jinhua ham or bacon', 'Intensely savoury, salty, dry-cured', 'Jinhua ham, Zhejiang, China, or cured bacon', 'Year-round'),
  ('john dory', 'Firm, sweet, finely textured white fish', 'Zeus faber, Atlantic and Mediterranean', 'Autumn to spring'),
  ('juniper berries', 'Resinous, piney, faintly citrus', 'Juniperus communis cones, Europe', 'Year-round; harvest autumn'),
  ('juniper berry', 'Resinous, piney, faintly citrus', 'Juniperus communis cone, Europe', 'Year-round; harvest autumn'),
  ('junmai daiginjo sake', 'Delicate, fruity, highly polished rice', 'Brewed rice, Japan', 'Year-round'),
  ('junmai sake', 'Full, rice-forward, gently savoury', 'Brewed rice, Japan', 'Year-round'),
  ('kaffir lime leaf', 'Sharply citrus, floral, perfumed', 'Citrus hystrix leaf, Southeast Asia', 'Year-round'),
  ('kahlua', 'Sweet, coffee, rum-warm liqueur', 'Coffee liqueur, Mexico', 'Year-round'),
  ('kala namak', 'Sulphurous, egg-like, mineral salt', 'Himalayan black salt, South Asia', 'Year-round'),
  ('kalamata olives', 'Fruity, winey, meaty black olive', 'Kalamata olives, Messenia, Greece', 'Year-round; harvest autumn'),
  ('kale', 'Robust, mineral, faintly bitter', 'Brassica oleracea var. sabellica', 'Autumn to winter; sweeter after frost'),
  ('kamut flour', 'Sweet, buttery, nutty ancient wheat', 'Milled khorasan wheat', 'Year-round'),
  ('kanpachi', 'Clean, firm, lightly sweet amberjack', 'Seriola dumerili, Japan', 'Summer to autumn'),
  ('kappa carrageenan', 'Flavourless; sets a firm, brittle gel', 'Extract of red seaweed', 'Year-round'),
  ('karashi mustard', 'Sharp, hot, clean Japanese mustard', 'Brown mustard powder, Japan', 'Year-round'),
  ('kataifi', 'Neutral; bakes to a crisp golden nest', 'Shredded filo pastry, Greece and Turkey', 'Year-round'),
  ('katsu curry roux', 'Sweet, mild, savoury curry sauce base', 'Blocked curry roux, Japan', 'Year-round'),
  ('katsuobushi', 'Smoky, savoury, intensely umami', 'Dried and fermented skipjack tuna, Japan', 'Year-round'),
  ('katsuobushi (bonito flakes)', 'Smoky, savoury, intensely umami', 'Shaved dried skipjack tuna, Japan', 'Year-round'),
  ('kecap manis', 'Thick, sweet, molasses-dark soy', 'Sweetened soy sauce, Indonesia', 'Year-round'),
  ('kefir', 'Tangy, effervescent, lightly yeasty', 'Fermented milk, Caucasus', 'Year-round'),
  ('kefir grains note', 'Sour and yeasty; a starter culture, not eaten alone', 'Live kefir culture', 'Year-round'),
  ('ketchup', 'Sweet, sour, tomato-rich', 'Tomato condiment', 'Year-round'),
  ('kidney bean', 'Earthy, creamy, holds its shape', 'Dried Phaseolus vulgaris', 'Year-round'),
  ('kidney beans', 'Earthy, creamy, hold their shape', 'Dried Phaseolus vulgaris', 'Year-round'),
  ('kimchi', 'Sour, funky, garlicky, chilli-hot', 'Fermented napa cabbage, Korea', 'Year-round; traditionally made in autumn'),
  ('kimchi paste', 'Pungent, garlicky, chilli-hot seasoning', 'Chilli, garlic and fish sauce paste, Korea', 'Year-round'),
  ('kinako', 'Toasty, nutty, faintly sweet', 'Roasted soybean flour, Japan', 'Year-round'),
  ('kinako powder', 'Toasty, nutty, faintly sweet', 'Roasted soybean flour, Japan', 'Year-round'),
  ('king crab', 'Sweet, firm, richly marine', 'Paralithodes camtschaticus, North Pacific', 'Autumn to winter'),
  ('king oyster mushroom', 'Meaty, mild, faintly nutty', 'Pleurotus eryngii, cultivated', 'Year-round'),
  ('king prawn', 'Sweet, firm, briny', 'Large farmed or wild prawn', 'Year-round'),
  ('kirsch', 'Dry, stony, cherry-scented spirit', 'Distilled cherries, Switzerland and Alsace', 'Year-round'),
  ('kiwi', 'Sharp, green, tropical-tart', 'Actinidia deliciosa', 'Autumn to spring'),
  ('kiwi purée', 'Sharp, green, tropical-tart', 'Sieved kiwi fruit', 'Year-round'),
  ('knochenmark', 'Rich, fatty, deeply savoury', 'Beef bone marrow', 'Year-round'),
  ('knöpfli fresh', 'Soft, eggy, mildly wheaty dumpling', 'Fresh egg dough dumplings, Switzerland', 'Year-round'),
  ('kohlrabi', 'Sweet, crisp, faintly cabbagey', 'Brassica oleracea var. gongylodes', 'Spring to autumn'),
  ('kohlrabi fresh', 'Sweet, crisp, faintly cabbagey', 'Brassica oleracea var. gongylodes', 'Spring to autumn'),
  ('koji rice', 'Sweet, faintly mushroomy, aromatic', 'Rice inoculated with Aspergillus oryzae, Japan', 'Year-round'),
  ('kombu', 'Deeply savoury, marine, glutamate-rich kelp', 'Dried Saccharina japonica, Japan', 'Year-round'),
  ('kombu dashi powder', 'Clean, savoury, marine', 'Powdered kelp stock, Japan', 'Year-round'),
  ('korean chilli', 'Fruity, smoky, moderately hot', 'Dried Korean chilli', 'Year-round'),
  ('koshihikari rice', 'Sweet, glossy, sticky short grain', 'Oryza sativa Koshihikari, Japan', 'Year-round'),
  ('kumquat', 'Sweet peel, sharply sour flesh', 'Citrus japonica', 'Winter to early spring'),
  ('kürbis', 'Sweet, earthy, dense squash', 'Cucurbita species', 'Autumn to winter'),
  ('kurozu', 'Mellow, malty, softly sour black vinegar', 'Aged brown rice vinegar, Japan', 'Year-round'),
  ('l''etivaz aop', 'Firm, smoky, intensely alpine', 'Raw cow''s milk cooked over wood fire, Vaud, Switzerland', 'Made in summer, sold from autumn'),
  ('labneh', 'Thick, tangy, lightly salty strained yoghurt', 'Strained yoghurt, Levant', 'Year-round'),
  ('läckerli', 'Honeyed, spiced, chewy', 'Honey and spice biscuit, Basel, Switzerland', 'Year-round; peak at Christmas'),
  ('ladyfinger biscuit', 'Dry, sweet, sponge-light', 'Savoiardi sponge biscuit, Italy', 'Year-round'),
  ('ladyfingers', 'Dry, sweet, sponge-light', 'Savoiardi sponge biscuits, Italy', 'Year-round'),
  ('lager beer', 'Crisp, malty, lightly bitter', 'Bottom-fermented beer', 'Year-round'),
  ('laksa leaf or coriander', 'Pungent, citrus-herbal', 'Persicaria odorata or Coriandrum sativum', 'Year-round'),
  ('laksa paste', 'Hot, nutty, lemongrass-scented', 'Spice and chilli paste, Malaysia and Singapore', 'Year-round'),
  ('lamb bone', 'Savoury and gelatinous; the base of lamb stock', 'Lamb skeleton', 'Year-round'),
  ('lamb leg', 'Lean, gamey, deeply flavoured', 'Lamb hind leg', 'Year-round; peak spring'),
  ('lamb loin', 'Tender, mild, evenly fatted', 'Lamb saddle loin', 'Year-round; peak spring'),
  ('lamb rack', 'Tender, sweet, richly fatted', 'Lamb rib rack', 'Year-round; peak spring'),
  ('lamb reduction', 'Deep, glossy, intensely lamb-savoury', 'Reduced lamb stock', 'Year-round'),
  ('lamb saddle', 'Tender, mild, prime cut', 'Lamb saddle', 'Year-round; peak spring'),
  ('lamb shank', 'Rich, gelatinous, deeply gamey when braised', 'Lamb foreleg or hind shank', 'Autumn to winter'),
  ('lamb shoulder', 'Fatty, gamey, falls apart when slow-cooked', 'Lamb shoulder', 'Year-round; peak spring'),
  ('lamb trim/offcut', 'Gamey and fatty; for mince, stock and sauces', 'Lamb trimmings', 'Year-round'),
  ('landjäger', 'Smoky, salty, firm air-dried sausage', 'Cured beef and pork sausage, Switzerland and southern Germany', 'Year-round'),
  ('langoustine', 'Sweet, delicate, finely marine', 'Nephrops norvegicus, North Atlantic', 'Spring to autumn'),
  ('langoustines', 'Sweet, delicate, finely marine', 'Nephrops norvegicus, North Atlantic', 'Spring to autumn'),
  ('lap cheong', 'Sweet, fatty, wine-scented cured sausage', 'Cured pork sausage, China', 'Year-round'),
  ('lardo', 'Silky, herbal, melting cured back fat', 'Cured pork back fat, Tuscany, Italy', 'Year-round'),
  ('lasagne sheets', 'Neutral, wheaty; carries the sauce', 'Durum wheat pasta sheets, Italy', 'Year-round'),
  ('lavender honey', 'Floral, delicate, softly perfumed', 'Honey from lavender fields, Provence', 'Summer harvest; year-round'),
  ('lemon (zest, infusion only)', 'Bright, oily citrus aroma without acidity', 'Citrus limon peel', 'Year-round; peak winter'),
  ('lemon balm', 'Soft, lemony, mildly minty herb', 'Melissa officinalis', 'Spring to autumn'),
  ('lemon juice', 'Sharp, clean, acidic', 'Pressed Citrus limon', 'Year-round; peak winter'),
  ('lemon olive oil', 'Fruity oil with bright citrus lift', 'Olives pressed with lemons, Mediterranean', 'Year-round'),
  ('lemon purée', 'Intensely sour, aromatic citrus', 'Sieved lemons', 'Year-round'),
  ('lemon thyme', 'Herbal, resinous, distinctly lemony', 'Thymus citriodorus', 'Spring to autumn'),
  ('lemon verbena fresh', 'Intensely lemony, floral, clean', 'Aloysia citrodora leaf', 'Summer'),
  ('lemon wedges, for garnish', 'Sharp, clean citrus', 'Citrus limon, cut for service', 'Year-round; peak winter'),
  ('lemon zest', 'Bright, oily, perfumed citrus', 'Grated Citrus limon peel', 'Year-round; peak winter'),
  ('lemon-infused olive oil', 'Fruity oil with bright citrus lift', 'Olive oil infused with lemon', 'Year-round'),
  ('lemon-yellow colour', 'Flavourless; colouring only', 'Food colouring', 'Year-round'),
  ('lemongrass', 'Citrus, floral, faintly gingery', 'Cymbopogon citratus, Southeast Asia', 'Year-round'),
  ('levain', 'Sour, lactic, faintly wheaty', 'Naturally leavened wheat starter', 'Year-round'),
  ('light miso paste', 'Sweet, mild, gently salty', 'Short-fermented rice and soybean miso, Japan', 'Year-round'),
  ('light soy sauce', 'Salty, clean, savoury', 'Fermented soybean sauce, China', 'Year-round'),
  ('lime dressing', 'Sharp, citrus, lightly sweet', 'Lime-based salad dressing', 'Year-round'),
  ('lime juice', 'Sharp, floral, distinctly bitter-edged', 'Pressed Citrus aurantifolia', 'Year-round'),
  ('lime leaf', 'Sharply citrus, floral, perfumed', 'Citrus hystrix leaf, Southeast Asia', 'Year-round'),
  ('lime oil', 'Intense, perfumed lime aroma', 'Cold-pressed lime peel oil', 'Year-round'),
  ('lime purée', 'Sharp, floral, intensely sour', 'Sieved limes', 'Year-round'),
  ('lime wedge', 'Sharp, floral citrus', 'Citrus aurantifolia, cut for service', 'Year-round'),
  ('lime zest', 'Perfumed, oily, bitter-bright', 'Grated lime peel', 'Year-round'),
  ('limoncello', 'Sweet, intensely lemony liqueur', 'Lemon peel liqueur, Amalfi coast, Italy', 'Year-round'),
  ('ling', 'Firm, mild, meaty white fish', 'Molva molva, North Atlantic', 'Winter to spring'),
  ('lingonberry', 'Sharp, tart, faintly bitter berry', 'Vaccinium vitis-idaea, Nordic forests', 'Late summer to autumn'),
  ('linguine', 'Neutral, wheaty, silky flat strand', 'Durum wheat pasta, Liguria, Italy', 'Year-round'),
  ('liquid egg white', 'Neutral; whips to a stable foam', 'Pasteurised separated egg white', 'Year-round'),
  ('liquid egg yolk', 'Rich, fatty, custardy', 'Pasteurised separated egg yolk', 'Year-round'),
  ('liquid honey', 'Floral and sweet; pours clear', 'Filtered honey', 'Year-round'),
  ('liquid nitrogen note', 'Flavourless; freezes on contact', 'Cryogenic nitrogen, kitchen use only', 'Year-round'),
  ('liquid whole egg', 'Neutral-rich; binds and sets', 'Pasteurised whole egg', 'Year-round'),
  ('liver sausage', 'Rich, mineral, softly spreadable', 'Pork liver sausage, central Europe', 'Year-round'),
  ('lobster', 'Sweet, firm, luxuriously marine', 'Homarus gammarus or americanus', 'Spring to autumn'),
  ('lobster bisque base', 'Deep, shellfish-rich, brandy-warm', 'Reduced lobster shell stock', 'Year-round'),
  ('lobster meat', 'Sweet, firm, delicately marine', 'Picked lobster tail and claw', 'Spring to autumn'),
  ('lobster shells and heads', 'Intensely shellfish-savoury when roasted', 'Lobster carcasses for stock', 'Spring to autumn'),
  ('long pepper', 'Warm, sweet-hot, faintly floral', 'Piper longum catkin, India and Indonesia', 'Year-round'),
  ('longeole', 'Coarse, fennel-scented, lightly smoky sausage', 'Pork sausage IGP, Geneva, Switzerland', 'Autumn to winter'),
  ('lotus root', 'Crisp, faintly sweet, starchy', 'Nelumbo nucifera rhizome, East Asia', 'Autumn to winter'),
  ('lotus seed', 'Mild, starchy, faintly sweet', 'Nelumbo nucifera seed, East Asia', 'Year-round'),
  ('lovage', 'Intensely celery-like, savoury, herbal', 'Levisticum officinale', 'Spring to autumn'),
  ('lumpfish roe', 'Salty, briny, mildly fishy', 'Cyclopterus lumpus roe, North Atlantic', 'Winter to spring'),
  ('lupini bean', 'Firm, bitter until cured, then nutty', 'Lupinus albus, Mediterranean', 'Year-round'),
  ('lupini beans', 'Firm, bitter until cured, then nutty', 'Lupinus albus, Mediterranean', 'Year-round'),
  ('lychee', 'Perfumed, floral, sweetly juicy', 'Litchi chinensis, South China', 'Early summer'),
  ('ma kombu', 'Sweet, refined, deeply savoury kelp', 'Saccharina japonica, Hokkaido, Japan', 'Year-round'),
  ('mac & cheese sauce', 'Creamy, cheesy, richly savoury', 'Cheese béchamel', 'Year-round'),
  ('macadamia', 'Buttery, sweet, richly oily', 'Macadamia integrifolia, Australia and Hawaii', 'Year-round'),
  ('macadamia nut', 'Buttery, sweet, richly oily', 'Macadamia integrifolia, Australia and Hawaii', 'Year-round'),
  ('mace', 'Warm, delicate, more floral than nutmeg', 'Aril of Myristica fragrans, Indonesia', 'Year-round'),
  ('mackerel', 'Oily, strong, richly savoury', 'Scomber scombrus, North Atlantic', 'Summer to autumn'),
  ('madeira', 'Nutty, caramelised, gently oxidised fortified wine', 'Fortified wine, Madeira, Portugal', 'Year-round'),
  ('maldon salt', 'Clean saline crunch; finishing salt', 'Pyramid sea salt flakes, Essex, England', 'Year-round'),
  ('malt extract', 'Sweet, malty, faintly bitter', 'Concentrated barley malt', 'Year-round'),
  ('malt vinegar', 'Sharp, malty, brown-toned', 'Malted barley vinegar, England', 'Year-round'),
  ('maltose', 'Mildly sweet, very sticky', 'Malt-derived sugar syrup', 'Year-round'),
  ('maltose or extra honey', 'Mildly sweet and sticky, or floral and sweet', 'Malt syrup or honey', 'Year-round'),
  ('manchego', 'Firm, nutty, sheepy-sweet', 'Manchega sheep''s milk, La Mancha, Spain', 'Year-round'),
  ('manchego cheese', 'Firm, nutty, sheepy-sweet', 'Manchega sheep''s milk, La Mancha, Spain', 'Year-round'),
  ('mandarin', 'Sweet, soft, low-acid citrus', 'Citrus reticulata', 'Late autumn to winter'),
  ('mangetout', 'Sweet, grassy, crisp flat pod', 'Pisum sativum var. saccharatum', 'Late spring to summer'),
  ('mango', 'Sweet, resinous, tropical', 'Mangifera indica', 'Spring to summer'),
  ('mango purée', 'Sweet, resinous, tropical', 'Sieved mango', 'Year-round'),
  ('manjari chocolate', 'Bright, red-fruited, acidic dark chocolate', 'Valrhona dark couverture, 64% cocoa', 'Year-round'),
  ('maple syrup grade a', 'Sweet, woody, faintly caramel', 'Boiled maple sap, Canada and northeast USA', 'Year-round; tapped in early spring'),
  ('marcona almond', 'Round, sweet, buttery almond', 'Marcona almonds, Spain', 'Year-round; harvest autumn'),
  ('marcona almonds', 'Round, sweet, buttery almonds', 'Marcona almonds, Spain', 'Year-round; harvest autumn'),
  ('margarine', 'Neutral-fatty, mildly buttery', 'Emulsified vegetable fat', 'Year-round'),
  ('marjoram fresh', 'Sweet, warm, gently oregano-like', 'Origanum majorana', 'Spring to autumn'),
  ('marrons glacés', 'Intensely sweet, chestnutty, vanilla-scented', 'Candied chestnuts, France and Italy', 'Autumn to winter'),
  ('marrow bones split', 'Rich, fatty, deeply savoury', 'Split beef marrow bones', 'Year-round'),
  ('marsala', 'Nutty, raisined, gently sweet fortified wine', 'Fortified wine, Marsala, Sicily', 'Year-round'),
  ('marsala wine', 'Nutty, raisined, gently sweet fortified wine', 'Fortified wine, Marsala, Sicily', 'Year-round'),
  ('marzipan', 'Sweet, almond-rich, dense', 'Ground almonds and sugar', 'Year-round'),
  ('masa harina', 'Toasty, distinctly corn, faintly limey', 'Nixtamalised maize flour, Mexico', 'Year-round'),
  ('mascarpone cream base', 'Rich, milky, barely sweet', 'Mascarpone cream preparation, Italy', 'Year-round'),
  ('massaman curry paste', 'Warm-spiced, mild, peanut-friendly', 'Thai-Muslim curry paste, southern Thailand', 'Year-round'),
  ('matcha', 'Grassy, bitter, deeply umami', 'Stone-ground shade-grown green tea, Japan', 'Year-round; spring harvest'),
  ('matcha powder', 'Grassy, bitter, deeply umami', 'Stone-ground shade-grown green tea, Japan', 'Year-round; spring harvest'),
  ('mature cheddar', 'Sharp, crumbly, deeply savoury', 'Cow''s milk, Somerset, England', 'Year-round'),
  ('mayonnaise', 'Rich, eggy, gently acidic emulsion', 'Egg yolk and oil emulsion', 'Year-round'),
  ('mayonnaise pro', 'Rich, eggy, stable emulsion', 'Prepared catering mayonnaise', 'Year-round'),
  ('medjool date', 'Intensely sweet, caramel, fudgy', 'Medjool date palm fruit, Jordan valley and Morocco', 'Year-round; harvest autumn'),
  ('medjool dates', 'Intensely sweet, caramel, fudgy', 'Medjool date palm fruit, Jordan valley and Morocco', 'Year-round; harvest autumn'),
  ('megrim', 'Delicate, soft, mild flatfish', 'Lepidorhombus whiffiagonis, northeast Atlantic', 'Autumn to winter'),
  ('melon purée', 'Sweet, floral, watery-fresh', 'Sieved melon', 'Year-round; fruit peaks summer'),
  ('membrillo', 'Dense, sweet, perfumed quince paste', 'Quince paste, Spain', 'Year-round; made in autumn'),
  ('membrillo sticks note', 'Dense, sweet, perfumed quince paste cut for service', 'Quince paste, Spain', 'Year-round; made in autumn'),
  ('menma', 'Salty, sour, gently crunchy', 'Fermented bamboo shoot, Japan', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
