-- 179_ingredient_info_backfill_batch9.sql
-- Ingredient info backfill — batch 9 (Richard, 23.7.2026). Same safety contract as db/171–178:
-- ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by name,
-- never overwrites — idempotent. Price, kitchen_id and is_personal are never touched.
-- 174 names from the live remaining list, 'mentsuyu' → 'pickled red onions'.
with m(name, flavour, origin, season) as (values
  ('mentsuyu', 'Sweet, savoury, dashi-rich noodle base', 'Soy, mirin and dashi concentrate, Japan', 'Year-round'),
  ('merguez', 'Spicy, cumin-warm, lamb-forward sausage', 'Lamb sausage, North Africa', 'Year-round'),
  ('merguez sausage', 'Spicy, cumin-warm, lamb-forward sausage', 'Lamb sausage, North Africa', 'Year-round'),
  ('meringue powder', 'Neutral-sweet; whips to a stable foam', 'Dried egg white with sugar', 'Year-round'),
  ('meringue shells', 'Sweet, brittle, dissolving', 'Baked egg white and sugar', 'Year-round'),
  ('micro greens mix', 'Concentrated, fresh, varied leaf flavours', 'Seedling leaves, cultivated', 'Year-round'),
  ('micro mint or shiso', 'Cool and minty, or herbal and faintly aniseed', 'Micro herb seedlings', 'Year-round'),
  ('mild olive oil', 'Soft, buttery, low-bitterness', 'Refined and blended olive oil, Mediterranean', 'Year-round'),
  ('milk chocolate 35%', 'Sweet, milky, lightly cocoa', 'Milk chocolate couverture, 35% cocoa', 'Year-round'),
  ('milk chocolate 40%', 'Balanced milk and cocoa, less sweet', 'Milk chocolate couverture, 40% cocoa', 'Year-round'),
  ('milk chocolate couverture', 'Sweet, milky, smoothly melting', 'High-cocoa-butter milk chocolate', 'Year-round'),
  ('milk powder', 'Concentrated, faintly cooked-milk sweetness', 'Spray-dried milk', 'Year-round'),
  ('millet', 'Mild, nutty, faintly corn-like grain', 'Panicum miliaceum', 'Year-round'),
  ('mimolette', 'Hard, nutty, faintly salty-caramel', 'Cow''s milk, Lille, France', 'Year-round'),
  ('mini burrata', 'Milky, creamy, fresh', 'Cow''s milk, Puglia, Italy', 'Year-round; best very fresh'),
  ('mini cucumbers', 'Cool, crisp, faintly sweet', 'Small-fruited Cucumis sativus', 'Summer'),
  ('mini lattich leaf', 'Tender, mild, faintly sweet leaf', 'Small lettuce leaves', 'Spring to autumn'),
  ('mint syrup', 'Sweet, cooling, intensely minty', 'Mint-infused sugar syrup', 'Year-round'),
  ('mirabelle plum', 'Honeyed, small, intensely sweet plum', 'Prunus domestica subsp. syriaca, Lorraine', 'Late summer'),
  ('mirin', 'Sweet, mellow, faintly alcoholic', 'Sweet rice seasoning, Japan', 'Year-round'),
  ('miso mayo', 'Rich, savoury, gently sweet', 'Mayonnaise with miso', 'Year-round'),
  ('miso paste', 'Salty, savoury, deeply fermented', 'Fermented soybean paste, Japan', 'Year-round'),
  ('mixed salad leaves (lettuce, frisée, radicchio)', 'Sweet, bitter and crisp together', 'Assorted salad leaves', 'Spring to autumn'),
  ('mixed vegetables (pea, carrot, corn)', 'Sweet, mild, varied', 'Mixed garden vegetables', 'Year-round; frozen or fresh in summer'),
  ('mizuna', 'Peppery, mild, feathery leaf', 'Brassica rapa var. nipposinica, Japan', 'Autumn to spring'),
  ('molasses', 'Dark, bitter-sweet, mineral', 'Sugar refining syrup', 'Year-round'),
  ('monkfish', 'Firm, sweet, lobster-like white fish', 'Lophius piscatorius, northeast Atlantic', 'Autumn to spring'),
  ('montasio', 'Firm, buttery, nutty when aged', 'Cow''s milk, Friuli, Italy', 'Year-round'),
  ('morbier', 'Supple, fruity, faintly barnyard; ash line through the centre', 'Cow''s milk, Franche-Comté, France', 'Year-round'),
  ('morbier aop', 'Supple, fruity, faintly barnyard protected cheese', 'Raw cow''s milk, Franche-Comté, France', 'Year-round'),
  ('morel', 'Deeply earthy, smoky, meaty', 'Morchella species, wild', 'Spring'),
  ('morel mushroom', 'Deeply earthy, smoky, meaty', 'Morchella species, wild', 'Spring'),
  ('mortadella', 'Soft, sweetly porky, pistachio-studded', 'Cooked pork sausage, Bologna, Italy', 'Year-round'),
  ('mostarda', 'Sweet candied fruit with a sharp mustard heat', 'Fruit in mustard syrup, northern Italy', 'Year-round; made in autumn'),
  ('mostarda di cremona', 'Whole candied fruit in mustard syrup', 'Cremona, Lombardy, Italy', 'Year-round; made in autumn'),
  ('mozzarella di bufala dop', 'Milky, lactic, springy and juicy', 'Water buffalo milk, Campania, Italy', 'Year-round; best very fresh'),
  ('muhammara', 'Sweet, smoky, nutty, gently hot', 'Roasted pepper and walnut dip, Syria', 'Year-round'),
  ('mulberry', 'Sweet, winey, faintly tart', 'Morus fruit', 'Summer'),
  ('mulled wine spice', 'Warm, sweet, citrus-and-clove', 'Cinnamon, clove and citrus spice blend', 'Autumn to winter'),
  ('müller-thurgau mild cheese', 'Semi-hard, mild, buttery', 'Cow''s milk washed in Müller-Thurgau wine, Switzerland', 'Year-round'),
  ('müller-thurgau spicy cheese', 'Semi-hard with a pronounced tang', 'Cow''s milk washed in Müller-Thurgau wine, Switzerland', 'Year-round'),
  ('müller-thurgau strong cheese', 'Firm, pungent, long-matured', 'Cow''s milk washed in Müller-Thurgau wine, Switzerland', 'Year-round'),
  ('mung bean', 'Sweet, soft, faintly grassy', 'Vigna radiata', 'Year-round'),
  ('mung beans dry', 'Sweet, soft, faintly grassy when cooked', 'Dried Vigna radiata', 'Year-round'),
  ('munster aop', 'Pungent washed rind, soft and meaty inside', 'Cow''s milk, Alsace and Vosges, France', 'Best autumn to winter'),
  ('muscat grape', 'Intensely perfumed, floral, sweet', 'Vitis vinifera Muscat', 'Late summer to autumn'),
  ('muscovado sugar', 'Dark, sticky, molasses-rich', 'Unrefined cane sugar, Mauritius and Philippines', 'Year-round'),
  ('mushrooms', 'Earthy, savoury, umami', 'Cultivated or wild fungi', 'Year-round; wild peak in autumn'),
  ('mussel', 'Sweet, briny, softly marine', 'Mytilus edulis, Atlantic and North Sea', 'Autumn to early spring'),
  ('mustard', 'Sharp, pungent, gently vinegary', 'Ground mustard seed condiment', 'Year-round'),
  ('mustard powder', 'Dry, fiercely pungent when wetted', 'Milled mustard seed', 'Year-round'),
  ('mutschli', 'Semi-hard, mild, creamy young cheese', 'Cow''s milk, Switzerland', 'Year-round'),
  ('naan bread', 'Soft, chewy, faintly charred', 'Leavened tandoor flatbread, South Asia', 'Year-round'),
  ('nam prik pao', 'Sweet, smoky, umami chilli jam', 'Roasted chilli paste, Thailand', 'Year-round'),
  ('nasturtium', 'Peppery, mustardy, bright', 'Tropaeolum majus leaf and flower', 'Summer to autumn'),
  ('nasturtium flower', 'Peppery, sweetly nectared, bright', 'Tropaeolum majus flower', 'Summer to autumn'),
  ('nduja', 'Fiery, soft, spreadably fatty', 'Spiced pork salume, Calabria, Italy', 'Year-round'),
  ('nectarine', 'Sweet, juicy, smooth-skinned stone fruit', 'Prunus persica var. nucipersica', 'Summer'),
  ('neri goma', 'Deeply nutty, thick, faintly bitter', 'Ground sesame paste, Japan', 'Year-round'),
  ('neutral glaze', 'Flavourless; gives pastry and fruit a shine', 'Pectin and sugar glaze', 'Year-round'),
  ('neutral oil', 'Flavourless; high smoke point', 'Refined vegetable oil', 'Year-round'),
  ('new potatoes', 'Sweet, waxy, thin-skinned', 'Early-lifted Solanum tuberosum', 'Late spring to early summer'),
  ('nigella seed', 'Oniony, faintly bitter, aromatic', 'Nigella sativa seed, South Asia and Middle East', 'Year-round'),
  ('nigella seeds', 'Oniony, faintly bitter, aromatic', 'Nigella sativa seed, South Asia and Middle East', 'Year-round'),
  ('nori', 'Marine, toasty, savoury', 'Dried Pyropia seaweed, Japan', 'Year-round'),
  ('nori sheets', 'Marine, toasty, savoury', 'Dried and pressed Pyropia seaweed, Japan', 'Year-round'),
  ('nori tsukudani', 'Salty, sweet, intensely marine paste', 'Simmered nori, Japan', 'Year-round'),
  ('nougatine', 'Caramelised sugar with toasted nuts; brittle', 'Caramel and almond confection, France', 'Year-round'),
  ('nuoc cham', 'Sharp, sweet, salty, chilli-hot', 'Fish sauce dipping sauce, Vietnam', 'Year-round'),
  ('nuoc mam', 'Intensely salty, funky, savoury', 'Fermented anchovy sauce, Vietnam', 'Year-round'),
  ('nut brittle', 'Hard, caramelised, toasty', 'Caramel and nut confection', 'Year-round'),
  ('nut mix roasted', 'Toasty, salty, varied nut flavours', 'Assorted roasted nuts', 'Year-round'),
  ('nut-nougat spread', 'Sweet, hazelnut, cocoa-rich', 'Hazelnut and cocoa spread', 'Year-round'),
  ('oat milk', 'Mild, cereal-sweet, creamy', 'Enzyme-treated oats and water', 'Year-round'),
  ('ocean perch', 'Firm, mild, faintly sweet white fish', 'Sebastes species, North Atlantic', 'Autumn to spring'),
  ('octopus', 'Sweet, mineral, firm-tender when slow-cooked', 'Octopus vulgaris, Mediterranean and Atlantic', 'Autumn to winter'),
  ('oil', 'Flavourless to lightly fruity, depending on type', 'Vegetable oil', 'Year-round'),
  ('okonomiyaki sauce', 'Sweet, fruity, savoury-thick', 'Worcestershire-style sauce, Japan', 'Year-round'),
  ('okra', 'Grassy, mild, mucilaginous when cut', 'Abelmoschus esculentus, Africa and South Asia', 'Summer to autumn'),
  ('onion marmalade', 'Sweet, jammy, gently acidic', 'Slow-cooked onions with sugar and vinegar', 'Year-round'),
  ('onion powder', 'Concentrated, sweet-savoury allium', 'Dried and milled onion', 'Year-round'),
  ('onion rings battered', 'Sweet onion in a crisp savoury coating', 'Battered and fried onion', 'Year-round'),
  ('opalys (white chocolate)', 'Milky, low-sugar, faintly vanilla', 'Valrhona white couverture, 33% cocoa butter', 'Year-round'),
  ('orange blossom water', 'Intensely floral, perfumed, faintly bitter', 'Distilled bitter orange blossom, North Africa', 'Year-round'),
  ('orange extract', 'Concentrated, sweet, perfumed citrus', 'Orange peel extract', 'Year-round'),
  ('orange juice fresh', 'Sweet, bright, mildly acidic', 'Pressed Citrus sinensis', 'Year-round; peak winter'),
  ('orange or yuzu juice', 'Sweet-bright, or sharply floral and sour', 'Pressed orange or yuzu', 'Winter'),
  ('orange ponzu', 'Citrus, soy-savoury, tangy', 'Ponzu with orange, Japan', 'Year-round'),
  ('orange zest', 'Oily, perfumed, faintly bitter citrus', 'Grated Citrus sinensis peel', 'Year-round; peak winter'),
  ('orecchiette', 'Neutral, wheaty, chewy little ears', 'Durum wheat pasta, Puglia, Italy', 'Year-round'),
  ('organic eggs', 'Rich, clean, deeply coloured yolk', 'Organically farmed hen''s eggs', 'Year-round'),
  ('orzo', 'Neutral, wheaty, rice-shaped', 'Durum wheat pasta, Italy and Greece', 'Year-round'),
  ('orzo pasta', 'Neutral, wheaty, rice-shaped', 'Durum wheat pasta, Italy and Greece', 'Year-round'),
  ('osetra caviar', 'Nutty, buttery, delicately marine', 'Acipenser gueldenstaedtii roe', 'Year-round; farmed'),
  ('ossau-iraty', 'Firm, nutty, sweetly sheepy', 'Sheep''s milk, Basque country and Béarn, France', 'Year-round; made spring to autumn'),
  ('ostrich egg note', 'Mild and eggy; one egg equals about two dozen hen''s eggs', 'Ostrich egg', 'Spring to summer'),
  ('ovomaltine powder', 'Malty, cocoa-sweet, toasty', 'Malt and cocoa drink powder, Switzerland', 'Year-round'),
  ('ox cheek', 'Deeply beefy, gelatinous when braised', 'Beef cheek muscle', 'Year-round'),
  ('ox cheek braised', 'Rich, sticky, deeply beefy', 'Slow-braised beef cheek', 'Year-round'),
  ('oxtail', 'Rich, gelatinous, intensely beefy', 'Beef tail', 'Year-round; best in winter'),
  ('oyster', 'Briny, mineral, creamy-sweet', 'Ostreidae, Atlantic coasts', 'Autumn to early spring'),
  ('oyster mushroom', 'Delicate, faintly aniseed, silky', 'Pleurotus ostreatus', 'Year-round; wild in autumn'),
  ('oyster sauce', 'Savoury, sweet, thick and glossy', 'Oyster extract sauce, China', 'Year-round'),
  ('oyster sauce premium', 'Deeply savoury with real oyster character', 'High-oyster-content sauce, China', 'Year-round'),
  ('oysters', 'Briny, mineral, creamy-sweet', 'Ostreidae, Atlantic coasts', 'Autumn to early spring'),
  ('paccheri', 'Neutral, wheaty, wide tubes that hold sauce', 'Durum wheat pasta, Campania, Italy', 'Year-round'),
  ('padron pepper', 'Grassy and mild — with the occasional hot one', 'Capsicum annuum, Galicia, Spain', 'Summer'),
  ('padron peppers', 'Grassy and mild — with the occasional hot one', 'Capsicum annuum, Galicia, Spain', 'Summer'),
  ('paella rice senia', 'Absorbent, creamy, holds its shape', 'Senia short-grain rice, Valencia, Spain', 'Year-round'),
  ('pak choi', 'Sweet stems, mild peppery leaves', 'Brassica rapa subsp. chinensis', 'Year-round; peak autumn'),
  ('palm sugar', 'Caramel, smoky, softly sweet', 'Boiled palm sap, Southeast Asia', 'Year-round'),
  ('panang curry paste', 'Rich, nutty, mildly hot', 'Thai curry paste, central Thailand', 'Year-round'),
  ('pancetta', 'Salty, porky, gently spiced', 'Cured pork belly, Italy', 'Year-round'),
  ('pandan extract', 'Grassy, vanilla-like, faintly coconut', 'Pandanus amaryllifolius extract, Southeast Asia', 'Year-round'),
  ('pandan juice', 'Grassy, vanilla-like, faintly coconut', 'Pressed pandan leaves, Southeast Asia', 'Year-round'),
  ('pandan leaf or vanilla pod', 'Grassy-vanilla, or sweet and deeply vanilla', 'Pandan leaf or cured vanilla pod', 'Year-round'),
  ('paneer', 'Mild, milky, firm and non-melting', 'Fresh acid-set cow''s milk cheese, South Asia', 'Year-round'),
  ('panettone', 'Sweet, buttery, citrus-and-raisin, airy', 'Enriched leavened cake, Milan, Italy', 'Winter; traditionally Christmas'),
  ('pangasius fillet', 'Mild, soft, faintly sweet white fish', 'Farmed Pangasius, Mekong delta, Vietnam', 'Year-round'),
  ('panko', 'Neutral; fries lighter and crisper than dry crumbs', 'Japanese crustless breadcrumbs', 'Year-round'),
  ('panko breadcrumb', 'Neutral; fries light and shatteringly crisp', 'Japanese crustless breadcrumbs', 'Year-round'),
  ('panna cotta base', 'Creamy, gently sweet, vanilla-scented', 'Cream and gelatine preparation, Italy', 'Year-round'),
  ('papaya', 'Musky, soft, sweetly tropical', 'Carica papaya', 'Year-round; peak summer'),
  ('pappardelle', 'Neutral, eggy, broad silky ribbons', 'Egg pasta, Tuscany, Italy', 'Year-round'),
  ('parmesan rind', 'Deeply savoury; flavours stocks and soups', 'Parmigiano Reggiano rind, Italy', 'Year-round'),
  ('parmigiano reggiano 24 months', 'Crystalline, nutty, intensely savoury', 'Raw cow''s milk, Emilia-Romagna, Italy', 'Year-round'),
  ('parmigiano reggiano 24m', 'Crystalline, nutty, intensely savoury', 'Raw cow''s milk, Emilia-Romagna, Italy', 'Year-round'),
  ('parsley root', 'Sweet, earthy, parsley-scented root', 'Petroselinum crispum var. tuberosum', 'Autumn to winter'),
  ('parsnip', 'Sweet, earthy, faintly spicy', 'Pastinaca sativa root', 'Autumn to winter; sweeter after frost'),
  ('partridge', 'Delicate, lightly gamey', 'Perdix perdix, wild and farmed', 'Autumn to winter'),
  ('passion fruit', 'Intensely sour, floral, tropical', 'Passiflora edulis', 'Year-round; peak winter'),
  ('passion fruit purée', 'Intensely sour, floral, tropical', 'Sieved passion fruit', 'Year-round'),
  ('passion fruit seeds note', 'Crunchy, faintly bitter; used for texture', 'Passiflora edulis seeds', 'Year-round'),
  ('pastis', 'Sweet, aniseed, herbal', 'Anise liqueur, Provence, France', 'Year-round'),
  ('pastrami', 'Peppery, coriander-warm, smoky cured beef', 'Cured and smoked beef, Romania and New York', 'Year-round'),
  ('patisson', 'Mild, faintly nutty summer squash', 'Cucurbita pepo, scallop-shaped', 'Summer to early autumn'),
  ('pea shoot', 'Sweet, grassy, intensely pea-like', 'Young Pisum sativum shoots', 'Spring to summer'),
  ('pea shoots', 'Sweet, grassy, intensely pea-like', 'Young Pisum sativum shoots', 'Spring to summer'),
  ('peach', 'Sweet, perfumed, juicy stone fruit', 'Prunus persica', 'Summer'),
  ('peanut', 'Toasty, oily, savoury-sweet', 'Arachis hypogaea', 'Year-round'),
  ('peanut butter', 'Rich, roasted, oily and salty', 'Ground roasted peanuts', 'Year-round'),
  ('peanut oil', 'Faintly nutty; high smoke point', 'Pressed peanuts', 'Year-round'),
  ('pear', 'Sweet, floral, granular-juicy', 'Pyrus communis', 'Late summer to winter'),
  ('pear purée', 'Sweet, floral, delicate', 'Sieved pears', 'Year-round'),
  ('pear williams purée', 'Sweet, musky, intensely perfumed pear', 'Sieved Williams pears', 'Year-round'),
  ('pearl barley', 'Nutty, chewy, faintly sweet', 'Polished Hordeum vulgare', 'Year-round'),
  ('pearl couscous', 'Neutral, chewy, toasty when browned', 'Rolled and toasted semolina, Levant', 'Year-round'),
  ('pearl onion', 'Sweet, mild, tender when glazed', 'Small Allium cepa', 'Summer to autumn'),
  ('pearl sugar', 'Sweet, crunchy; does not melt in the oven', 'Compressed sugar grains, Belgium and Scandinavia', 'Year-round'),
  ('peas', 'Sweet, grassy, tender', 'Pisum sativum', 'Late spring to summer'),
  ('pecan nut', 'Sweet, buttery, faintly bitter skin', 'Carya illinoinensis, southern USA', 'Year-round; harvest autumn'),
  ('pecans', 'Sweet, buttery, faintly bitter skin', 'Carya illinoinensis, southern USA', 'Year-round; harvest autumn'),
  ('pecorino romano', 'Hard, very salty, sharply sheepy', 'Sheep''s milk, Lazio and Sardinia, Italy', 'Year-round'),
  ('pecorino romano dop', 'Hard, very salty, sharply sheepy protected cheese', 'Sheep''s milk, Lazio and Sardinia, Italy', 'Year-round'),
  ('pectin nh', 'Flavourless; sets a re-meltable glaze or gel', 'Thermoreversible apple pectin', 'Year-round'),
  ('pectin yellow', 'Flavourless; sets firm fruit jellies', 'Slow-set apple pectin', 'Year-round'),
  ('pedro ximénez sherry', 'Intensely sweet, raisined, treacle-dark', 'Fortified wine, Jerez, Spain', 'Year-round'),
  ('penne', 'Neutral, wheaty, ridged tubes', 'Durum wheat pasta, Italy', 'Year-round'),
  ('peperoncini', 'Sharp, clean chilli heat', 'Dried small Capsicum, Italy', 'Year-round'),
  ('pepper', 'Pungent, woody, sharply hot', 'Piper nigrum', 'Year-round'),
  ('peppercorns & allspice', 'Pungent and woody with warm clove-nutmeg notes', 'Piper nigrum and Pimenta dioica', 'Year-round'),
  ('perch fillet', 'Delicate, sweet, finely flaked freshwater fish', 'Perca fluviatilis, Swiss and European lakes', 'Summer to autumn'),
  ('pernod or dry white wine', 'Aniseed-sweet, or crisp and acidic', 'Anise liqueur or dry white wine', 'Year-round'),
  ('persimmon', 'Honeyed, soft, faintly tannic', 'Diospyros kaki', 'Autumn to early winter'),
  ('persipan', 'Almond-like but sharper, faintly bitter', 'Apricot or peach kernel paste with sugar', 'Year-round'),
  ('pesto genovese', 'Basil, garlic, pine nut and sharp cheese', 'Basil pesto, Liguria, Italy', 'Year-round; best in summer'),
  ('pesto rosso', 'Sweet-savoury sun-dried tomato and nut', 'Red pesto, southern Italy', 'Year-round'),
  ('pheasant', 'Lean, distinctly gamey, delicate', 'Phasianus colchicus, wild and farmed', 'Autumn to winter'),
  ('philadelphia cream cheese', 'Mild, tangy, smoothly spreadable', 'Cream cheese, industrial', 'Year-round'),
  ('piccalilli', 'Sharp, mustard-yellow, crunchy pickle', 'Mustard vegetable pickle, England', 'Year-round'),
  ('pickled beetroot', 'Sweet, earthy, sharply vinegary', 'Beetroot in vinegar', 'Year-round'),
  ('pickled ginger', 'Sweet, sharp, cleanly gingery', 'Young ginger in sweet vinegar, Japan', 'Year-round'),
  ('pickled ginger (gari)', 'Sweet, sharp, cleanly gingery palate cleanser', 'Young ginger in sweet vinegar, Japan', 'Year-round'),
  ('pickled red onions', 'Sharp, sweet, bright pink', 'Red onion in vinegar', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
