-- 180_ingredient_info_backfill_batch10.sql
-- Ingredient info backfill — batch 10 (Richard, 23.7.2026). Same safety contract as db/171–179:
-- ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by name,
-- never overwrites — idempotent. Price, kitchen_id and is_personal are never touched.
-- 174 names from the live remaining list, 'pickled silverskin onions' → 'rock sugar'.
with m(name, flavour, origin, season) as (values
  ('pickled silverskin onions', 'Sharp, sweet, crunchy', 'Small onions in vinegar', 'Year-round'),
  ('pickling spice', 'Warm, aromatic, faintly sweet', 'Mustard, coriander and bay spice blend', 'Year-round'),
  ('piedmont hazelnuts', 'Intensely sweet, round, buttery', 'Tonda Gentile hazelnuts, Piedmont, Italy', 'Year-round; harvest autumn'),
  ('pig trotters', 'Rich, gelatinous, mildly porky', 'Pork feet', 'Year-round'),
  ('pike', 'Lean, firm, faintly sweet freshwater fish', 'Esox lucius, European lakes and rivers', 'Autumn to winter'),
  ('pike-perch', 'Delicate, sweet, finely flaked freshwater fish', 'Sander lucioperca, European lakes', 'Autumn to spring'),
  ('pike-perch fillet', 'Delicate, sweet, finely flaked freshwater fish', 'Sander lucioperca, European lakes', 'Autumn to spring'),
  ('pinch of salt', 'Clean saltiness; sharpens everything else', 'Sea or rock salt', 'Year-round'),
  ('pine honey', 'Dark, resinous, barely sweet', 'Honeydew honey from pine forests, Greece and Turkey', 'Autumn harvest; year-round'),
  ('pine nut', 'Buttery, resinous, delicately sweet', 'Pinus pinea seed, Mediterranean', 'Year-round; harvest autumn'),
  ('pine nuts mediterranean', 'Buttery, resinous, delicately sweet', 'Pinus pinea seed, Italy and Spain', 'Year-round; harvest autumn'),
  ('pineapple', 'Sweet, sharply acidic, tropical', 'Ananas comosus', 'Year-round; peak spring'),
  ('pink peppercorn', 'Sweet, resinous, faintly peppery', 'Schinus terebinthifolius berry, South America', 'Year-round'),
  ('pink peppercorns', 'Sweet, resinous, faintly peppery', 'Schinus terebinthifolius berries, South America', 'Year-round'),
  ('pinot noir cooking', 'Light, red-fruited, gently tannic', 'Pinot Noir wine for cooking', 'Year-round'),
  ('piri piri sauce', 'Hot, sharp, citrus-edged chilli sauce', 'Bird''s eye chilli sauce, Portugal and Mozambique', 'Year-round'),
  ('pistachio', 'Sweet, green, delicately resinous', 'Pistacia vera, Sicily and Iran', 'Year-round; harvest autumn'),
  ('pistachio paste', 'Intensely green, sweet, oily', 'Ground pistachios', 'Year-round'),
  ('pita bread', 'Soft, faintly wheaty; pockets when baked hot', 'Flatbread, eastern Mediterranean', 'Year-round'),
  ('pizza dough balls', 'Neutral, wheaty, faintly sour when proved slowly', 'Portioned leavened wheat dough', 'Year-round'),
  ('pizzoccheri', 'Nutty, earthy buckwheat ribbons', 'Buckwheat pasta, Valtellina, Italy', 'Autumn to winter'),
  ('plaice', 'Soft, sweet, delicate flatfish', 'Pleuronectes platessa, North Sea', 'Late spring to autumn'),
  ('plant-based mince', 'Savoury, faintly beany; takes on seasoning', 'Textured pea or soy protein', 'Year-round'),
  ('plantain', 'Starchy when green, sweet when black', 'Musa paradisiaca, tropics', 'Year-round'),
  ('planted steak (plant-based)', 'Savoury, firm, faintly pea-protein', 'Extruded pea protein, Switzerland', 'Year-round'),
  ('plum', 'Sweet-tart, juicy, faintly tannic skin', 'Prunus domestica', 'Late summer to early autumn'),
  ('poblano chili', 'Rich, mildly hot, faintly smoky', 'Capsicum annuum, Puebla, Mexico', 'Summer to autumn'),
  ('pointed cabbage', 'Sweet, tender, mildly cabbagey', 'Brassica oleracea var. capitata f. acuta', 'Spring to autumn'),
  ('polenta', 'Sweet corn, creamy when slow-cooked', 'Ground maize, northern Italy', 'Year-round'),
  ('polenta bramata', 'Coarse, distinctly corn, rustic texture', 'Coarse-ground maize, northern Italy', 'Year-round'),
  ('pollock', 'Mild, soft, faintly sweet white fish', 'Pollachius species, North Atlantic', 'Autumn to winter'),
  ('pomegranate', 'Sweet-tart, juicy, faintly tannic seeds', 'Punica granatum', 'Autumn to winter'),
  ('pomegranate molasses', 'Intensely sour-sweet, dark, fruity', 'Reduced pomegranate juice, Levant', 'Year-round'),
  ('pomelo', 'Mildly sweet, faintly bitter, dry-fleshed citrus', 'Citrus maxima, Southeast Asia', 'Winter'),
  ('ponzu', 'Citrus, soy-savoury, tangy', 'Citrus and soy seasoning, Japan', 'Year-round'),
  ('ponzu sauce', 'Citrus, soy-savoury, tangy', 'Citrus and soy seasoning, Japan', 'Year-round'),
  ('poolish', 'Faintly sour, yeasty, wheaty', 'Wet wheat pre-ferment', 'Year-round'),
  ('popcorn', 'Toasty, corn-sweet, salty', 'Popped Zea mays everta', 'Year-round'),
  ('popcorn kernels', 'Neutral until popped, then toasty and corn-sweet', 'Zea mays everta', 'Year-round'),
  ('popping candy', 'Sweet; crackles on the tongue', 'Carbonated sugar confection', 'Year-round'),
  ('poppy seed', 'Nutty, faintly bitter, crunchy', 'Papaver somniferum seed, central Europe', 'Year-round'),
  ('porcini', 'Deeply earthy, nutty, meaty', 'Boletus edulis, wild', 'Late summer to autumn'),
  ('porcini powder', 'Concentrated earthy umami', 'Dried and milled Boletus edulis', 'Year-round'),
  ('pork', 'Mild, sweet, evenly fatted', 'Sus domesticus', 'Year-round'),
  ('pork belly', 'Rich, fatty, crisps to crackling', 'Pork belly', 'Year-round'),
  ('pork caul fat', 'Faintly porky; melts away and bastes what it wraps', 'Pork membrane fat', 'Year-round'),
  ('pork cheeks', 'Sweet, gelatinous, tender when braised', 'Pork cheek muscle', 'Year-round'),
  ('pork cutlet', 'Mild, lean, quick-cooking', 'Pork loin chop or escalope', 'Year-round'),
  ('pork fillet', 'Very lean, tender, delicately flavoured', 'Pork tenderloin', 'Year-round'),
  ('pork jowl', 'Deeply porky, fatty, silky when cured', 'Pork cheek and jaw fat', 'Year-round'),
  ('pork knuckle', 'Rich, gelatinous, crisp-skinned when roasted', 'Pork hock', 'Autumn to winter'),
  ('pork lard', 'Clean, faintly porky cooking fat', 'Rendered pork fat', 'Year-round'),
  ('pork loin', 'Lean, mild, tender', 'Pork loin', 'Year-round'),
  ('pork mince', 'Mild, sweet, fatty', 'Minced pork', 'Year-round'),
  ('pork neck', 'Well-marbled, juicy, forgiving', 'Pork neck and collar', 'Year-round'),
  ('pork neck bone', 'Savoury and gelatinous; the base of pork stock', 'Pork neck bones', 'Year-round'),
  ('pork ribs', 'Rich, fatty, deeply porky', 'Pork rib rack', 'Year-round'),
  ('pork shoulder', 'Fatty, sweet, pulls apart when slow-cooked', 'Pork shoulder', 'Year-round'),
  ('pork spare rib', 'Fatty, meaty, rich when slow-cooked', 'Pork belly ribs', 'Year-round'),
  ('pork trotter', 'Rich, gelatinous, mildly porky', 'Pork foot', 'Year-round'),
  ('port wine', 'Sweet, raisined, warming fortified wine', 'Fortified wine, Douro valley, Portugal', 'Year-round'),
  ('portobello', 'Meaty, deeply earthy, open-gilled', 'Mature Agaricus bisporus', 'Year-round'),
  ('portobello mushroom', 'Meaty, deeply earthy, open-gilled', 'Mature Agaricus bisporus', 'Year-round'),
  ('potato gnocchi', 'Soft, mild, faintly potato-sweet', 'Potato and flour dumplings, Italy', 'Year-round'),
  ('potato starch', 'Flavourless; thickens clear and glossy', 'Extracted potato starch', 'Year-round'),
  ('potato starch or panko', 'Flavourless and glossy, or neutral and crisp', 'Potato starch or Japanese breadcrumbs', 'Year-round'),
  ('potatoes', 'Earthy, mild, starchy-sweet', 'Solanum tuberosum', 'Year-round; new season in early summer'),
  ('poussin', 'Delicate, tender, mildly chicken', 'Young chicken, about 500 g', 'Year-round'),
  ('praline paste', 'Caramelised sugar and toasted nut, oily', 'Ground caramelised nuts', 'Year-round'),
  ('prawn', 'Sweet, firm, briny', 'Farmed or wild prawn', 'Year-round'),
  ('preserved lemon', 'Intensely salty, sour, perfumed peel', 'Salt-cured lemons, North Africa', 'Year-round'),
  ('preserved lemons', 'Intensely salty, sour, perfumed peel', 'Salt-cured lemons, North Africa', 'Year-round'),
  ('preserved radish', 'Salty, crunchy, faintly sweet', 'Salt-cured daikon, China and Japan', 'Year-round'),
  ('pretzel', 'Salty, chewy, lye-scented crust', 'Lye-dipped wheat bread, southern Germany', 'Year-round'),
  ('pretzel salt', 'Clean saltiness; coarse and slow to dissolve', 'Coarse rock salt', 'Year-round'),
  ('prosciutto', 'Sweet, salty, melting dry-cured ham', 'Cured pork leg, Italy', 'Year-round'),
  ('prosciutto crudo', 'Sweet, salty, melting dry-cured ham', 'Cured pork leg, Parma or San Daniele, Italy', 'Year-round'),
  ('prosecco', 'Crisp, floral, lightly sparkling', 'Glera sparkling wine, Veneto, Italy', 'Year-round'),
  ('protein of choice', 'Varies with the protein selected', 'Meat, fish or plant protein, chef''s choice', 'Year-round'),
  ('provolone', 'Firm, milky, sharp when aged', 'Cow''s milk, southern and northern Italy', 'Year-round'),
  ('provolone or fontina', 'Sharp and firm, or mild and melting', 'Cow''s milk cheese, Italy', 'Year-round'),
  ('prunes', 'Deep, sweet, caramel-plum', 'Dried Prunus domestica, Agen, France', 'Year-round'),
  ('puff pastry block', 'Neutral and buttery; bakes to shattering layers', 'Laminated butter dough', 'Year-round'),
  ('puff pastry sheets', 'Neutral and buttery; bakes to shattering layers', 'Rolled laminated butter dough', 'Year-round'),
  ('pulled pork cooked', 'Sweet, smoky, deeply porky', 'Slow-cooked shredded pork shoulder', 'Year-round'),
  ('pumpkin seed', 'Nutty, green, faintly oily', 'Cucurbita pepo seed', 'Autumn; year-round dried'),
  ('pumpkin seed oil', 'Intensely nutty, dark green, toasty', 'Pressed roasted pumpkin seeds, Styria, Austria', 'Year-round'),
  ('pumpkin seeds', 'Nutty, green, faintly oily', 'Cucurbita pepo seeds', 'Autumn; year-round dried'),
  ('puntarelle', 'Bitter, crisp, faintly nutty', 'Cichorium intybus, Lazio, Italy', 'Winter'),
  ('purple carrot', 'Sweet, earthy, faintly peppery', 'Anthocyanin-rich Daucus carota', 'Autumn to winter'),
  ('purple sprouting broccoli', 'Sweet, mineral, tender-stemmed', 'Brassica oleracea var. italica', 'Late winter to spring'),
  ('purslane', 'Succulent, lemony, faintly salty', 'Portulaca oleracea', 'Summer'),
  ('puy lentil', 'Peppery, firm, holds its shape perfectly', 'Lentille verte du Puy AOP, Auvergne, France', 'Year-round'),
  ('puy lentils', 'Peppery, firm, hold their shape perfectly', 'Lentille verte du Puy AOP, Auvergne, France', 'Year-round'),
  ('quail', 'Delicate, faintly gamey, small-boned', 'Coturnix coturnix, farmed', 'Year-round'),
  ('quail egg', 'Rich, mild, intensely yolky for its size', 'Coturnix coturnix egg', 'Year-round'),
  ('quail eggs', 'Rich, mild, intensely yolky for their size', 'Coturnix coturnix eggs', 'Year-round'),
  ('quark', 'Fresh, tangy, lightly milky', 'Acid-set curd cheese, central Europe', 'Year-round'),
  ('quatre épices', 'Warm, peppery, clove-and-nutmeg', 'French four-spice blend', 'Year-round'),
  ('queso fresco', 'Mild, milky, lightly salty and crumbly', 'Fresh cow''s milk cheese, Mexico', 'Year-round'),
  ('quince', 'Perfumed, astringent raw, honeyed when cooked', 'Cydonia oblonga', 'Autumn'),
  ('quinoa', 'Nutty, faintly bitter, softly popping', 'Chenopodium quinoa, Andes', 'Year-round'),
  ('rabbit legs', 'Lean, mild, faintly gamey', 'Rabbit hind legs', 'Year-round'),
  ('rabbit saddle', 'Very lean, tender, delicate', 'Rabbit loin', 'Year-round'),
  ('rabbit whole', 'Lean, mild, faintly gamey', 'Whole farmed rabbit', 'Year-round'),
  ('rack of veal', 'Delicate, milky, finely textured', 'Veal rib rack', 'Year-round'),
  ('raclette cheese', 'Buttery, savoury, melts smoothly', 'Cow''s milk, Valais, Switzerland', 'Year-round; peak in winter'),
  ('raclette du valais aop', 'Rich, nutty, deeply savoury when melted', 'Raw cow''s milk, Valais, Switzerland', 'Year-round; peak in winter'),
  ('radicchio', 'Bitter, crisp, faintly sweet at the core', 'Cichorium intybus, Veneto, Italy', 'Autumn to winter'),
  ('radicchio leaf', 'Bitter, crisp, deep red', 'Cichorium intybus leaf, Italy', 'Autumn to winter'),
  ('radish', 'Peppery, crisp, watery-sharp', 'Raphanus sativus', 'Spring to autumn'),
  ('rainbow chard', 'Earthy leaf, sweet-acidic coloured stem', 'Beta vulgaris subsp. cicla', 'Summer to autumn'),
  ('raisin', 'Concentrated, sweet, faintly winey', 'Dried grapes', 'Year-round'),
  ('raisins', 'Concentrated, sweet, faintly winey', 'Dried grapes', 'Year-round'),
  ('rakkyo', 'Sweet, sharp, crunchy pickled bulb', 'Pickled Allium chinense, Japan', 'Year-round'),
  ('ramen noodle', 'Springy, faintly alkaline, wheaty', 'Kansui wheat noodle, Japan', 'Year-round'),
  ('ramen noodles', 'Springy, faintly alkaline, wheaty', 'Kansui wheat noodles, Japan', 'Year-round'),
  ('ramp bulbs', 'Pungent, garlicky, sweet when cooked', 'Allium tricoccum bulbs, North America', 'Spring'),
  ('rapeseed oil swiss', 'Clean, faintly grassy, mildly nutty', 'Pressed Swiss rapeseed', 'Year-round'),
  ('ras el hanout', 'Warm, floral, complexly spiced', 'North African spice blend, Morocco', 'Year-round'),
  ('raspberry', 'Sharp, perfumed, sweet-tart', 'Rubus idaeus', 'Summer to early autumn'),
  ('raspberry jam', 'Sweet, sharp, intensely berry', 'Cooked raspberries and sugar', 'Year-round'),
  ('raspberry purée', 'Sharp, perfumed, sweet-tart', 'Sieved raspberries', 'Year-round'),
  ('raspberry vinegar', 'Fruity, sharp, softly sweet', 'Raspberry-infused vinegar', 'Year-round'),
  ('ratte potatoes', 'Nutty, waxy, faintly chestnut', 'Ratte du Touquet potatoes, France', 'Summer to autumn'),
  ('raw milk', 'Full, sweet, richly dairy', 'Unpasteurised cow''s milk', 'Year-round'),
  ('raw onions', 'Sharp, pungent, faintly sweet', 'Allium cepa, uncooked', 'Year-round'),
  ('razor clam', 'Sweet, firm, distinctly marine', 'Ensis species, Atlantic sands', 'Autumn to spring'),
  ('razor clams', 'Sweet, firm, distinctly marine', 'Ensis species, Atlantic sands', 'Autumn to spring'),
  ('razor fish', 'Delicate, sweet, fine-textured', 'Xyrichtys novacula, Mediterranean', 'Summer to autumn'),
  ('real wasabi paste', 'Clean, green, fleetingly hot', 'Grated Eutrema japonicum rhizome, Japan', 'Year-round'),
  ('reblochon aop', 'Soft, nutty, faintly barnyard washed rind', 'Raw cow''s milk, Haute-Savoie, France', 'Best autumn to winter'),
  ('red cabbage', 'Sweet, peppery, deeply coloured', 'Brassica oleracea var. capitata f. rubra', 'Autumn to winter'),
  ('red chilli', 'Fruity, sharp, hot', 'Ripe Capsicum annuum', 'Summer to autumn'),
  ('red fermented bean curd', 'Salty, funky, intensely savoury', 'Fermented tofu in red yeast rice, China', 'Year-round'),
  ('red finger chilli', 'Fruity, moderately hot, clean', 'Ripe Capsicum annuum, long-fruited', 'Summer to autumn'),
  ('red lentil', 'Sweet, mild; cooks down to a purée', 'Split Lens culinaris', 'Year-round'),
  ('red lentils', 'Sweet, mild; cook down to a purée', 'Split Lens culinaris', 'Year-round'),
  ('red miso', 'Dark, salty, deeply fermented', 'Long-fermented soybean miso, Japan', 'Year-round'),
  ('red mullet', 'Sweet, distinctive, faintly shellfish-like', 'Mullus surmuletus, Mediterranean', 'Summer to autumn'),
  ('red pepper', 'Sweet, fruity, crisp', 'Ripe Capsicum annuum', 'Summer to autumn'),
  ('red rice camargue', 'Nutty, chewy, faintly earthy', 'Red rice, Camargue, France', 'Year-round'),
  ('red wine', 'Tannic, fruity, acidic', 'Fermented red grapes', 'Year-round'),
  ('red yuzu kosho', 'Hot, salty, intensely citrus', 'Red chilli, yuzu peel and salt, Japan', 'Year-round'),
  ('redcurrant', 'Sharp, bright, lightly sweet', 'Ribes rubrum', 'Summer'),
  ('redcurrant purée', 'Sharp, bright, lightly sweet', 'Sieved redcurrants', 'Year-round'),
  ('reduced teriyaki', 'Sweet, salty, glossy and concentrated', 'Reduced soy and mirin glaze, Japan', 'Year-round'),
  ('remoulade sauce', 'Creamy, tangy, herb-and-caper', 'Mayonnaise-based sauce, France', 'Year-round'),
  ('rhubarb', 'Fiercely sour, fresh, faintly floral', 'Rheum rhabarbarum stems', 'Spring to early summer'),
  ('rhubarb purée', 'Fiercely sour, fresh, faintly floral', 'Sieved cooked rhubarb', 'Year-round'),
  ('rhubarb stems, trimmed, cut into 5cm pieces', 'Fiercely sour, fresh, faintly floral', 'Rheum rhabarbarum stems, cut for cooking', 'Spring to early summer'),
  ('rice flakes', 'Mild, faintly sweet, quick to soften', 'Rolled rice', 'Year-round'),
  ('rice flour', 'Neutral, faintly sweet; fries very crisp', 'Milled rice', 'Year-round'),
  ('rice flour (joshinko/shiratamako blend)', 'Neutral and faintly sweet; gives a soft chew', 'Milled short-grain rice, Japan', 'Year-round'),
  ('rice noodle', 'Neutral, silky, slippery', 'Rice flour noodle, Southeast Asia', 'Year-round'),
  ('rice noodles', 'Neutral, silky, slippery', 'Rice flour noodles, Southeast Asia', 'Year-round'),
  ('rice paper', 'Neutral; softens to a translucent wrapper', 'Rice and tapioca sheet, Vietnam', 'Year-round'),
  ('rice paper wrapper', 'Neutral; softens to a translucent wrapper', 'Rice and tapioca sheet, Vietnam', 'Year-round'),
  ('rice syrup', 'Mildly sweet, malty, thick', 'Enzyme-converted rice syrup', 'Year-round'),
  ('rice vermicelli', 'Neutral, fine, quick to soften', 'Thin rice noodles, Southeast Asia', 'Year-round'),
  ('rice vinegar', 'Soft, mildly sweet, gently acidic', 'Fermented rice vinegar, East Asia', 'Year-round'),
  ('ricotta', 'Milky, faintly sweet, softly grainy', 'Whey cheese, Italy', 'Year-round'),
  ('rigatoni', 'Neutral, wheaty, ridged tubes', 'Durum wheat pasta, Italy', 'Year-round'),
  ('rillettes', 'Rich, salty, shreddedly fatty', 'Slow-cooked shredded pork in fat, France', 'Year-round'),
  ('ripe mango', 'Sweet, resinous, tropical', 'Mangifera indica, fully ripe', 'Spring to summer'),
  ('ripe tomato', 'Sweet, acidic, deeply savoury', 'Solanum lycopersicum, fully ripe', 'Summer to early autumn'),
  ('rishiri kombu', 'Clear, refined, gently savoury kelp', 'Saccharina japonica var. ochotensis, Hokkaido, Japan', 'Year-round'),
  ('rivella', 'Sweet, tangy, faintly milky soft drink', 'Milk-whey soft drink, Switzerland', 'Year-round'),
  ('roasted peanut', 'Toasty, oily, salty-savoury', 'Roasted Arachis hypogaea', 'Year-round'),
  ('roasted peppers in oil', 'Sweet, smoky, silky', 'Roasted Capsicum annuum in oil', 'Year-round'),
  ('roasted red pepper', 'Sweet, smoky, silky', 'Roasted ripe Capsicum annuum', 'Summer to autumn'),
  ('robiola', 'Soft, milky, gently tangy', 'Cow, goat or sheep''s milk, Piedmont and Lombardy, Italy', 'Year-round'),
  ('rock salt coarse', 'Clean, mineral saltiness; coarse crystals', 'Mined rock salt', 'Year-round'),
  ('rock sugar', 'Cleanly sweet, slow-dissolving', 'Crystallised sugar, East Asia', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
