-- 181_ingredient_info_backfill_batch11.sql
-- Ingredient info backfill — batch 11 (Richard, 23.7.2026). Same safety contract as db/171–180:
-- ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by name,
-- never overwrites — idempotent. Price, kitchen_id and is_personal are never touched.
-- 174 names from the live remaining list, 'rock sugar or brown sugar' → 'spelt flour'.
with m(name, flavour, origin, season) as (values
  ('rock sugar or brown sugar', 'Cleanly sweet, or sweet with molasses depth', 'Crystallised or unrefined cane sugar', 'Year-round'),
  ('rocket', 'Peppery, nutty, faintly bitter', 'Eruca vesicaria, Mediterranean', 'Spring to autumn'),
  ('rolled oats', 'Mild, creamy, cereal-sweet', 'Rolled Avena sativa', 'Year-round'),
  ('romaine lettuce', 'Crisp, sweet, faintly bitter ribs', 'Lactuca sativa var. longifolia', 'Spring to autumn'),
  ('romaine lettuce: 150g', 'Crisp, sweet, faintly bitter ribs', 'Lactuca sativa var. longifolia, portioned', 'Spring to autumn'),
  ('romanesco', 'Sweet, nutty, gentler than cauliflower', 'Brassica oleracea var. botrytis', 'Autumn to early winter'),
  ('romanesco fresh', 'Sweet, nutty, gentler than cauliflower', 'Brassica oleracea var. botrytis', 'Autumn to early winter'),
  ('romesco sauce', 'Sweet pepper, toasted nut, smoky', 'Pepper and almond sauce, Catalonia, Spain', 'Year-round'),
  ('rooibos tea', 'Sweet, woody, tannin-free', 'Aspalathus linearis, South Africa', 'Year-round'),
  ('roquefort aoc', 'Salty, sharp, intensely blue', 'Raw sheep''s milk, Aveyron, France', 'Year-round; made spring to summer'),
  ('roquefort aop', 'Salty, sharp, intensely blue protected cheese', 'Raw sheep''s milk, Roquefort-sur-Soulzon, France', 'Year-round; made spring to summer'),
  ('rose veal escalope', 'Delicate, milky, very lean', 'Rose veal top round, pounded thin', 'Year-round'),
  ('rose water', 'Intensely floral, perfumed', 'Distilled rose petals, Middle East', 'Year-round'),
  ('rosehip jam', 'Tart, floral, faintly earthy', 'Cooked Rosa canina hips', 'Year-round; picked in autumn'),
  ('rosemary sprig', 'Resinous, piney, camphorous', 'Salvia rosmarinus, Mediterranean', 'Year-round'),
  ('rösti prepared', 'Sweet potato inside, crisp and buttery outside', 'Grated pan-fried potato, Switzerland', 'Year-round'),
  ('royal jelly note', 'Sharply sour, faintly bitter; used by the drop', 'Honeybee secretion', 'Spring to summer'),
  ('ruby chocolate', 'Berry-tart, sweet, naturally pink', 'Ruby cocoa bean couverture', 'Year-round'),
  ('ruby port', 'Sweet, red-fruited, warming', 'Fortified wine, Douro valley, Portugal', 'Year-round'),
  ('ruchbrot', 'Nutty, faintly sour, dense wholemeal crumb', 'Ruch wheat bread, Switzerland', 'Year-round'),
  ('runner bean', 'Grassy, firm, faintly sweet', 'Phaseolus coccineus pod', 'Summer to early autumn'),
  ('rye flakes', 'Earthy, faintly sour, chewy', 'Rolled Secale cereale', 'Year-round'),
  ('rye flour', 'Earthy, sour-friendly, densely flavoured', 'Milled Secale cereale', 'Year-round'),
  ('sacha inchi', 'Green, nutty, faintly grassy', 'Plukenetia volubilis seed, Peru', 'Year-round'),
  ('saffron', 'Honeyed, hay-like, faintly medicinal', 'Crocus sativus stigmas, Iran and Spain', 'Year-round; harvest autumn'),
  ('saffron honey', 'Floral honey with a hay-like saffron finish', 'Honey infused with saffron', 'Year-round'),
  ('saffron strand', 'Honeyed, hay-like, intensely colouring', 'Crocus sativus stigma', 'Year-round; harvest autumn'),
  ('sago pearl', 'Neutral, chewy, translucent when cooked', 'Sago palm starch, Southeast Asia', 'Year-round'),
  ('saikyo miso', 'Very sweet, pale, low-salt', 'White rice miso, Kyoto, Japan', 'Year-round'),
  ('sake', 'Clean, rice-sweet, gently savoury', 'Brewed rice, Japan', 'Year-round'),
  ('sake cooking', 'Clean, rice-sweet; tenderises and deglazes', 'Cooking sake, Japan', 'Year-round'),
  ('sake kasu', 'Yeasty, sweet-savoury, faintly alcoholic lees', 'Sake pressing lees, Japan', 'Winter to spring'),
  ('salad burnet', 'Cool, cucumber-like, faintly nutty', 'Sanguisorba minor', 'Spring to autumn'),
  ('salametti', 'Salty, firm, gently spiced small salami', 'Cured pork sausage, Switzerland and Italy', 'Year-round'),
  ('salami', 'Salty, fatty, fermented-tangy', 'Cured pork sausage', 'Year-round'),
  ('salami milano', 'Fine-grained, mildly garlicky, sweetly porky', 'Cured pork salami, Milan, Italy', 'Year-round'),
  ('salmon', 'Rich, oily, sweetly marine', 'Salmo salar, North Atlantic and farmed', 'Year-round; wild in summer'),
  ('salmon fillet', 'Rich, oily, sweetly marine', 'Salmo salar fillet', 'Year-round; wild in summer'),
  ('salsa verde', 'Sharp, herbal, caper-and-anchovy savoury', 'Green herb sauce, Italy', 'Year-round'),
  ('salsiccia fresh', 'Coarse, fennel-scented, richly porky', 'Fresh pork sausage, Italy', 'Year-round'),
  ('salsify', 'Delicate, faintly oyster-like, earthy', 'Tragopogon porrifolius root', 'Autumn to winter'),
  ('salsify fresh', 'Delicate, faintly oyster-like, earthy', 'Tragopogon porrifolius root', 'Autumn to winter'),
  ('salt & pepper', 'Clean saltiness with woody pungency', 'Salt and Piper nigrum', 'Year-round'),
  ('salt and black pepper', 'Clean saltiness with woody pungency', 'Salt and black Piper nigrum', 'Year-round'),
  ('salt and freshly ground black pepper', 'Clean saltiness with sharp, aromatic pepper', 'Salt and freshly milled Piper nigrum', 'Year-round'),
  ('salt and pepper', 'Clean saltiness with woody pungency', 'Salt and Piper nigrum', 'Year-round'),
  ('salt and white pepper', 'Clean saltiness with earthy, fermented pepper', 'Salt and white Piper nigrum', 'Year-round'),
  ('salt cod', 'Intensely salty until soaked, then sweet and firm', 'Salt-cured Gadus morhua, Norway and Portugal', 'Year-round'),
  ('salted anchovies', 'Intensely salty, savoury, umami', 'Salt-cured Engraulis encrasicolus, Mediterranean', 'Year-round'),
  ('salted butter caramel', 'Sweet, bitter-edged, buttery, salty', 'Caramel with salted butter, Brittany, France', 'Year-round'),
  ('salted duck egg', 'Intensely salty white, rich sandy yolk', 'Brine-cured duck egg, China', 'Year-round'),
  ('salted napa cabbage', 'Salty, softened, faintly sweet', 'Salt-drawn Brassica rapa subsp. pekinensis', 'Autumn to winter'),
  ('sambal oelek', 'Clean, sharp, straight chilli heat', 'Ground fresh chilli paste, Indonesia', 'Year-round'),
  ('samphire', 'Salty, crunchy, distinctly marine', 'Salicornia europaea, coastal marshes', 'Summer'),
  ('san marzano dop tomatoes', 'Sweet, low-acid, dense-fleshed', 'Protected San Marzano tomatoes, Campania, Italy', 'Year-round; harvest late summer'),
  ('san marzano pdo tomatoes', 'Sweet, low-acid, dense-fleshed', 'Protected San Marzano tomatoes, Campania, Italy', 'Year-round; harvest late summer'),
  ('san marzano tomatoes', 'Sweet, low-acid, dense-fleshed plum tomato', 'San Marzano tomatoes, Campania, Italy', 'Year-round; harvest late summer'),
  ('sancho pepper', 'Citrus, numbing, faintly floral', 'Zanthoxylum piperitum, Japan', 'Year-round'),
  ('sandwich brie', 'Mild, buttery, softly mushroomy', 'Cow''s milk soft cheese, sliced', 'Year-round'),
  ('sardine', 'Oily, strong, richly savoury', 'Sardina pilchardus, Mediterranean and Atlantic', 'Late spring to autumn'),
  ('sardines', 'Oily, strong, richly savoury', 'Sardina pilchardus, Mediterranean and Atlantic', 'Late spring to autumn'),
  ('sashimi-grade fish', 'Clean, sweet, delicate raw', 'Fish handled to raw-consumption standard', 'Year-round'),
  ('saucisson vaudois', 'Smoky, coarse, gently spiced', 'Smoked pork sausage IGP, Vaud, Switzerland', 'Autumn to winter'),
  ('sauerkraut', 'Sour, salty, faintly cabbagey', 'Lacto-fermented white cabbage, central Europe', 'Autumn to winter'),
  ('sauternes or port', 'Honeyed and botrytised, or sweet and raisined', 'Sweet wine, Bordeaux or Douro', 'Year-round'),
  ('sauternes wine', 'Honeyed, botrytised, apricot-rich', 'Sweet wine, Sauternes, Bordeaux, France', 'Year-round'),
  ('savory', 'Peppery, thyme-like, resinous', 'Satureja hortensis or montana', 'Summer to autumn'),
  ('savoy cabbage', 'Sweet, tender, mildly cabbagey crinkled leaf', 'Brassica oleracea var. sabauda', 'Autumn to winter'),
  ('sbrinz', 'Extremely hard, nutty, intensely savoury', 'Raw cow''s milk, central Switzerland', 'Year-round'),
  ('sbrinz aop', 'Extremely hard, nutty, intensely savoury protected cheese', 'Raw cow''s milk, central Switzerland', 'Year-round'),
  ('sbrinz rinds', 'Deeply savoury; flavours stocks and soups', 'Sbrinz cheese rind, Switzerland', 'Year-round'),
  ('scallop', 'Sweet, delicate, faintly nutty', 'Pecten maximus, North Atlantic', 'Autumn to early spring'),
  ('scallops', 'Sweet, delicate, faintly nutty', 'Pecten maximus, North Atlantic', 'Autumn to early spring'),
  ('scamorza affumicata', 'Smoky, firm, mildly milky', 'Smoked cow''s milk cheese, southern Italy', 'Year-round'),
  ('schabziger', 'Fiercely herbal, salty, low-fat', 'Skimmed cow''s milk with blue fenugreek, Glarus, Switzerland', 'Year-round'),
  ('schüblig', 'Coarse, smoky, gently spiced boiling sausage', 'Pork and beef sausage, St. Gallen, Switzerland', 'Year-round'),
  ('scorzonera', 'Delicate, sweet, faintly earthy black salsify', 'Scorzonera hispanica root', 'Autumn to winter'),
  ('scotch bonnet chili', 'Fiercely hot with tropical fruitiness', 'Capsicum chinense, Caribbean', 'Summer to autumn'),
  ('sea bass', 'Firm, sweet, finely flaked', 'Dicentrarchus labrax, Atlantic and Mediterranean', 'Autumn to winter'),
  ('sea bass fillet', 'Firm, sweet, finely flaked', 'Dicentrarchus labrax fillet', 'Autumn to winter'),
  ('sea bass whole', 'Firm, sweet, finely flaked', 'Whole Dicentrarchus labrax', 'Autumn to winter'),
  ('sea bream', 'Sweet, firm, delicately marine', 'Sparus aurata, Mediterranean', 'Autumn to winter'),
  ('sea buckthorn', 'Intensely sour, tropical-tart, oily', 'Hippophae rhamnoides berry, coastal Europe', 'Late summer to autumn'),
  ('sea cucumber', 'Mild, gelatinous, absorbs surrounding flavour', 'Holothuroidea, East Asian waters', 'Year-round'),
  ('sea trout', 'Rich, delicate, between trout and salmon', 'Salmo trutta trutta, North Atlantic', 'Late spring to summer'),
  ('sea urchin', 'Briny, creamy, intensely iodine-sweet', 'Paracentrotus lividus roe, Mediterranean', 'Autumn to winter'),
  ('seedless grape', 'Sweet, juicy, mildly acidic', 'Vitis vinifera, seedless cultivars', 'Late summer to autumn'),
  ('seitan', 'Savoury, chewy, faintly wheaty', 'Cooked wheat gluten, East Asia', 'Year-round'),
  ('semolina', 'Nutty, faintly sweet, coarsely granular', 'Coarse durum wheat milling', 'Year-round'),
  ('sencha tea leaf', 'Grassy, astringent, gently sweet', 'Steamed green tea, Japan', 'Year-round; spring harvest'),
  ('serrano chili', 'Bright, grassy, sharply hot', 'Capsicum annuum, Puebla and Hidalgo, Mexico', 'Summer to autumn'),
  ('serrano ham', 'Salty, dry, lightly nutty cured ham', 'Cured white-pig leg, Spain', 'Year-round'),
  ('sesame brittle', 'Toasty, sweet, shatteringly crisp', 'Caramel and sesame confection', 'Year-round'),
  ('sesame seed', 'Nutty, toasty when roasted', 'Sesamum indicum seed', 'Year-round'),
  ('sesame seeds or tobiko', 'Toasty and nutty, or briny and popping', 'Sesame seeds or flying-fish roe', 'Year-round'),
  ('sevruga caviar', 'Intense, briny, small-grained', 'Acipenser stellatus roe', 'Year-round; farmed'),
  ('shallot, small dice', 'Sweet, delicate, less harsh than onion', 'Allium cepa var. aggregatum, finely diced', 'Year-round; new season in summer'),
  ('shaoxing wine', 'Nutty, savoury, faintly sweet rice wine', 'Fermented rice wine, Zhejiang, China', 'Year-round'),
  ('sheep cheese', 'Rich, nutty, distinctly sheepy', 'Sheep''s milk cheese', 'Year-round; made spring to autumn'),
  ('sheep milk', 'Rich, sweet, high in fat and protein', 'Ewe''s milk', 'Spring to autumn'),
  ('sherry vinegar', 'Nutty, sharp, oak-warm', 'Vinegar from sherry, Jerez, Spain', 'Year-round'),
  ('shichimi togarashi', 'Chilli-hot, citrus, sesame and nori', 'Seven-spice blend, Japan', 'Year-round'),
  ('shiitake', 'Meaty, smoky, deeply umami', 'Lentinula edodes, cultivated', 'Year-round'),
  ('shiitake fresh', 'Meaty, woodsy, umami-rich', 'Fresh Lentinula edodes', 'Year-round'),
  ('shiitake powder', 'Concentrated smoky umami', 'Dried and milled Lentinula edodes', 'Year-round'),
  ('shimeji', 'Firm, faintly nutty, mildly bitter raw', 'Hypsizygus tessulatus, cultivated', 'Year-round'),
  ('shio koji', 'Salty, sweet, gently fermented; tenderises', 'Koji, salt and water, Japan', 'Year-round'),
  ('shiragiku vinegar', 'Soft, mellow, faintly sweet rice vinegar', 'Brewed rice vinegar, Japan', 'Year-round'),
  ('shiro dashi', 'Light, savoury, dashi-and-soy concentrate', 'White soy and dashi base, Japan', 'Year-round'),
  ('shishito pepper', 'Grassy and mild, with the occasional hot one', 'Capsicum annuum, Japan', 'Summer to autumn'),
  ('shiso leaves', 'Herbal, minty, faintly aniseed', 'Perilla frutescens var. crispa, Japan', 'Summer'),
  ('short-grain sushi rice', 'Sweet, glossy, clings when cooked', 'Japonica short-grain rice, Japan', 'Year-round'),
  ('shortcrust pastry dough', 'Neutral, buttery, sandy-crumbed', 'Butter and flour pastry', 'Year-round'),
  ('shortcrust pastry shell', 'Neutral, buttery, crisply short', 'Blind-baked butter pastry case', 'Year-round'),
  ('shoyu koji', 'Savoury, sweet, deeply fermented', 'Koji fermented in soy sauce, Japan', 'Year-round'),
  ('shrimp', 'Sweet, firm, briny', 'Farmed or wild shrimp', 'Year-round'),
  ('shrimp paste', 'Pungent, salty, intensely fermented', 'Fermented shrimp paste, Southeast Asia', 'Year-round'),
  ('sichuan pepper', 'Citrus, floral, tongue-numbing', 'Zanthoxylum bungeanum husk, Sichuan, China', 'Year-round'),
  ('sichuan peppercorn', 'Citrus, floral, tongue-numbing', 'Zanthoxylum bungeanum husk, Sichuan, China', 'Year-round'),
  ('silken tofu', 'Delicate, milky, custard-soft', 'Undrained set soy curd, East Asia', 'Year-round'),
  ('single-clove garlic', 'Sweet, mellow, less harsh than ordinary garlic', 'Solo Allium sativum, Yunnan, China', 'Year-round'),
  ('skate wing', 'Sweet, faintly ammoniac if old, ribbon-fleshed', 'Raja species, northeast Atlantic', 'Autumn to spring'),
  ('skim milk', 'Thin, clean, mildly sweet', 'Cow''s milk with the fat removed', 'Year-round'),
  ('skirt steak', 'Loose-grained, deeply beefy, needs slicing across the grain', 'Beef diaphragm muscle', 'Year-round'),
  ('skyr', 'Thick, tangy, very low in fat', 'Strained cultured skimmed milk, Iceland', 'Year-round'),
  ('small chilli', 'Sharp, clean, hot', 'Small-fruited Capsicum', 'Summer to autumn'),
  ('small pasta', 'Neutral, wheaty; for soups and salads', 'Small durum wheat pasta shapes, Italy', 'Year-round'),
  ('smoked butter', 'Creamy with a clean wood-smoke finish', 'Cold-smoked butter', 'Year-round'),
  ('smoked duck breast', 'Rich, fatty, gently smoky', 'Cured and smoked duck breast', 'Year-round; peak autumn'),
  ('smoked eel', 'Rich, oily, deeply smoky', 'Smoked Anguilla anguilla, northern Europe', 'Autumn to winter'),
  ('smoked egg', 'Mild and eggy with a smoky edge', 'Cold-smoked hen''s egg', 'Year-round'),
  ('smoked garlic', 'Sweet, mellow, distinctly smoky', 'Smoked Allium sativum', 'Year-round'),
  ('smoked ham hock', 'Salty, smoky, gelatinous when simmered', 'Cured and smoked pork hock', 'Year-round'),
  ('smoked mackerel', 'Oily, rich, strongly smoky', 'Hot-smoked Scomber scombrus', 'Year-round'),
  ('smoked paprika', 'Sweet pepper with deep oak smoke', 'Smoked and milled Capsicum, Extremadura, Spain', 'Year-round'),
  ('smoked paprika hot', 'Smoky, sweet and distinctly hot', 'Smoked hot Capsicum, Spain', 'Year-round'),
  ('smoked paprika sweet', 'Smoky, sweet, gently earthy', 'Smoked sweet Capsicum, Spain', 'Year-round'),
  ('smoked salmon', 'Silky, salty, gently smoky', 'Cold-smoked Salmo salar', 'Year-round'),
  ('smoked salt', 'Clean saltiness with a wood-smoke finish', 'Smoked sea salt', 'Year-round'),
  ('smoked tofu', 'Firm, savoury, distinctly smoky', 'Pressed and smoked soy curd', 'Year-round'),
  ('smoked trout', 'Delicate, oily, gently smoky', 'Hot- or cold-smoked trout', 'Year-round'),
  ('snail', 'Earthy, mineral, firm-tender', 'Helix pomatia, farmed and wild', 'Spring to autumn'),
  ('snails', 'Earthy, mineral, firm-tender', 'Helix pomatia, farmed and wild', 'Spring to autumn'),
  ('snake bean', 'Grassy, dense, faintly nutty', 'Vigna unguiculata subsp. sesquipedalis, Asia', 'Summer to autumn'),
  ('snow crab', 'Sweet, delicate, finely fibrous', 'Chionoecetes opilio, North Atlantic and Pacific', 'Winter to spring'),
  ('snow peas', 'Sweet, grassy, crisp flat pod', 'Pisum sativum var. saccharatum', 'Late spring to summer'),
  ('soba noodle', 'Nutty, earthy buckwheat', 'Buckwheat noodle, Japan', 'Year-round'),
  ('soba noodles', 'Nutty, earthy buckwheat', 'Buckwheat noodles, Japan', 'Year-round'),
  ('sodium alginate', 'Flavourless; sets a gel on contact with calcium', 'Extract of brown seaweed', 'Year-round'),
  ('sofrito base', 'Sweet, slow-cooked onion, pepper and tomato', 'Aromatic cooking base, Spain and Latin America', 'Year-round'),
  ('soft brown butter', 'Nutty, toasted, deeply buttery', 'Browned and re-softened butter', 'Year-round'),
  ('soft butter', 'Rich, creamy, mildly sweet', 'Churned cream at room temperature', 'Year-round'),
  ('soju', 'Clean, faintly sweet, neutral spirit', 'Distilled rice or grain spirit, Korea', 'Year-round'),
  ('somen noodle', 'Very fine, delicate, faintly wheaty', 'Thin wheat noodle, Japan', 'Year-round; eaten cold in summer'),
  ('sorbet lemon pro', 'Sharp, clean, intensely lemon', 'Prepared lemon sorbet base', 'Year-round'),
  ('sorrel', 'Sharply sour, lemony, green', 'Rumex acetosa', 'Spring to autumn'),
  ('sorrento lemons igp', 'Perfumed, thick-skinned, mildly acidic', 'Protected Sorrento lemons, Campania, Italy', 'Winter to spring'),
  ('sorrento pgi lemons', 'Perfumed, thick-skinned, mildly acidic', 'Protected Sorrento lemons, Campania, Italy', 'Winter to spring'),
  ('sosa maltodextrin', 'Flavourless; turns fat into a loose powder', 'Tapioca maltodextrin, Sosa', 'Year-round'),
  ('sour cherry', 'Sharply tart, deep, faintly almond', 'Prunus cerasus', 'Summer'),
  ('sourdough starter', 'Sour, lactic, yeasty', 'Wild-fermented flour and water', 'Year-round'),
  ('soy lecithin', 'Flavourless; emulsifies and makes airs', 'Soybean-derived emulsifier', 'Year-round'),
  ('soya cream', 'Neutral-creamy, faintly beany', 'Soy-based cream alternative', 'Year-round'),
  ('soybean', 'Mild, beany, faintly sweet', 'Glycine max', 'Year-round'),
  ('spaetzle', 'Soft, eggy, mildly wheaty', 'Fresh egg dough noodles, southern Germany and Switzerland', 'Year-round'),
  ('spaghetti', 'Neutral, wheaty, round strand', 'Durum wheat pasta, Italy', 'Year-round'),
  ('spaghetti squash', 'Mild, faintly sweet; separates into strands', 'Cucurbita pepo', 'Autumn to winter'),
  ('sparkling water', 'Neutral with carbonic bite', 'Carbonated potable water', 'Year-round'),
  ('spätzli dry', 'Soft, eggy, mildly wheaty when boiled', 'Dried egg dough noodles, Switzerland', 'Year-round'),
  ('speck', 'Smoky, salty, juniper-scented cured ham', 'Cured and smoked pork leg, South Tyrol', 'Year-round'),
  ('speck alto adige', 'Smoky, salty, juniper-scented protected ham', 'Cured and smoked pork leg IGP, South Tyrol, Italy', 'Year-round'),
  ('speculoos spice blend', 'Warm, cinnamon-and-clove, faintly peppery', 'Belgian biscuit spice blend', 'Autumn to winter'),
  ('spelt flakes', 'Nutty, sweet, chewy ancient wheat', 'Rolled Triticum spelta', 'Year-round'),
  ('spelt flour', 'Nutty, sweet, gently wheaty', 'Milled Triticum spelta', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
