-- 182_ingredient_info_backfill_batch12.sql
-- Ingredient info backfill — batch 12 (Richard, 23.7.2026). Same safety contract as db/171–181:
-- ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by name,
-- never overwrites — idempotent. Price, kitchen_id and is_personal are never touched.
-- 174 names from the live remaining list, 'spice mix' → 'vanilla beans'.
--
-- Two entries here are NOT food: 'unspecified' (a placeholder a scan produced when it could not
-- read an ingredient) and 'vacuum bags 20x30' (packaging). They are filled with honest text that
-- says so, rather than left empty — an empty field reads as "we forgot", a plain statement does not.
with m(name, flavour, origin, season) as (values
  ('spice mix', 'Warm, aromatic, varies with the blend', 'Mixed ground spices', 'Year-round'),
  ('spider crab', 'Sweet, delicate, intensely marine', 'Maja squinado, Atlantic and Mediterranean', 'Autumn to spring'),
  ('spirulina powder', 'Marine, grassy, faintly bitter', 'Dried Arthrospira platensis', 'Year-round'),
  ('split peas', 'Earthy, sweet; cook down to a purée', 'Split Pisum sativum', 'Year-round'),
  ('sprouted mung beans', 'Crisp, fresh, faintly grassy', 'Germinated Vigna radiata', 'Year-round'),
  ('squab', 'Dark, rich, delicately gamey', 'Young farmed pigeon', 'Year-round; peak autumn'),
  ('squid', 'Sweet, mild, firm when quickly cooked', 'Loligo species, Atlantic and Mediterranean', 'Summer to autumn'),
  ('sriracha', 'Sweet, garlicky, moderately hot', 'Fermented chilli sauce, Thailand', 'Year-round'),
  ('st. albray cheese', 'Soft, creamy, mildly tangy washed rind', 'Cow''s milk, Bavaria, Germany', 'Year-round'),
  ('st. galler bratwurst', 'Fine-textured, milky, gently mace-scented', 'Veal and pork sausage IGP, St. Gallen, Switzerland', 'Year-round'),
  ('stabilizer', 'Flavourless; controls texture and stops separation', 'Hydrocolloid blend', 'Year-round'),
  ('stale bread', 'Neutral, dry, absorbent', 'Day-old bread', 'Year-round'),
  ('star anise', 'Sweet, warm, intensely liquorice', 'Illicium verum fruit, China and Vietnam', 'Year-round'),
  ('starfruit', 'Crisp, mildly sour, faintly floral', 'Averrhoa carambola', 'Autumn to winter'),
  ('sternenberger cheese', 'Semi-hard, mild, gently nutty', 'Cow''s milk, Zurich Oberland, Switzerland', 'Year-round'),
  ('stevia powder', 'Intensely sweet with a liquorice aftertaste', 'Stevia rebaudiana leaf extract', 'Year-round'),
  ('sticky rice', 'Sweet, dense, intensely chewy', 'Glutinous Oryza sativa, Southeast Asia', 'Year-round'),
  ('stilton', 'Crumbly, salty, deeply blue', 'Cow''s milk, Derbyshire and Nottinghamshire, England', 'Year-round; peak at Christmas'),
  ('stinging nettle', 'Deep, mineral, spinach-like once cooked', 'Urtica dioica, wild', 'Spring'),
  ('stock', 'Savoury, gelatinous, gently seasoned', 'Simmered bones or vegetables', 'Year-round'),
  ('stout', 'Roasted, bitter, coffee-dark', 'Dark top-fermented beer, Ireland and England', 'Year-round'),
  ('stracciatella cheese', 'Milky, creamy, shredded and loose', 'Cow''s milk, Puglia, Italy', 'Year-round; best very fresh'),
  ('stracciatella di burrata', 'Rich, milky, silky shreds in cream', 'Cow''s milk, Puglia, Italy', 'Year-round; best very fresh'),
  ('strawberry', 'Sweet, perfumed, gently acidic', 'Fragaria x ananassa', 'Late spring to summer'),
  ('strawberry jam', 'Sweet, perfumed, intensely berry', 'Cooked strawberries and sugar', 'Year-round'),
  ('strawberry purée', 'Sweet, perfumed, gently acidic', 'Sieved strawberries', 'Year-round'),
  ('streaky bacon, sliced', 'Salty, smoky, fatty; crisps well', 'Cured pork belly, sliced', 'Year-round'),
  ('strong white bread flour', 'Neutral, wheaty; high protein for good gluten', 'Milled hard wheat', 'Year-round'),
  ('sturgeon', 'Firm, meaty, faintly sweet', 'Acipenser species, farmed', 'Year-round'),
  ('sudachi', 'Sharp, green, intensely aromatic citrus', 'Citrus sudachi, Tokushima, Japan', 'Late summer to autumn'),
  ('suehiro (seasoned rice vinegar)', 'Mild, sweet-salty, gently acidic', 'Seasoned rice vinegar, Japan', 'Year-round'),
  ('suet', 'Clean, mildly beefy hard fat', 'Rendered beef kidney fat', 'Year-round'),
  ('sugar snap pea', 'Sweet, crunchy, wholly edible pod', 'Pisum sativum var. macrocarpon', 'Late spring to summer'),
  ('sugar snap peas', 'Sweet, crunchy, wholly edible pods', 'Pisum sativum var. macrocarpon', 'Late spring to summer'),
  ('sugar syrup', 'Cleanly sweet, neutral', 'Dissolved sugar and water', 'Year-round'),
  ('sumac', 'Sour, fruity, faintly astringent', 'Dried Rhus coriaria berries, Middle East', 'Year-round'),
  ('summer truffle', 'Gently earthy, nutty, mildly aromatic', 'Tuber aestivum, Italy and France', 'Late spring to summer'),
  ('sun-dried tomato', 'Concentrated, sweet-sour, chewy', 'Dried Solanum lycopersicum, southern Italy', 'Year-round'),
  ('sun-dried tomato paste', 'Intensely sweet-savoury, concentrated tomato', 'Ground sun-dried tomatoes', 'Year-round'),
  ('sunflower seed', 'Nutty, oily, faintly sweet', 'Helianthus annuus seed', 'Year-round'),
  ('sunflower seed butter', 'Rich, roasted, faintly bitter', 'Ground roasted sunflower seeds', 'Year-round'),
  ('surimi', 'Mild, sweet, faintly fishy; springy', 'Processed white fish paste, Japan', 'Year-round'),
  ('sushi rice', 'Sweet, glossy, clings when cooked', 'Japonica short-grain rice, Japan', 'Year-round'),
  ('sushi vinegar', 'Sweet, salty, gently acidic', 'Seasoned rice vinegar, Japan', 'Year-round'),
  ('swede', 'Sweet, earthy, faintly cabbagey', 'Brassica napus var. napobrassica', 'Autumn to winter'),
  ('sweet cherry', 'Sweet, juicy, faintly almond', 'Prunus avium', 'Early summer'),
  ('sweet chilli sauce', 'Sweet, mildly hot, sticky', 'Chilli and sugar sauce, Thailand', 'Year-round'),
  ('sweet paprika', 'Sweet, mild, deeply red pepper powder', 'Milled dried Capsicum, Hungary and Spain', 'Year-round'),
  ('sweet potato', 'Sweet, dense, faintly chestnutty', 'Ipomoea batatas', 'Autumn to winter'),
  ('sweet potato fries', 'Sweet, soft-centred, crisp when fried', 'Cut Ipomoea batatas', 'Year-round'),
  ('sweet vermouth', 'Sweet, herbal, faintly bitter fortified wine', 'Aromatised wine, Turin, Italy', 'Year-round'),
  ('sweetcorn kernels', 'Sweet, juicy, mildly starchy', 'Zea mays saccharata', 'Late summer to autumn'),
  ('sweetened condensed milk', 'Intensely sweet, thick, caramel-prone', 'Evaporated milk with sugar', 'Year-round'),
  ('swiss chard', 'Earthy leaf, sweet-acidic stem', 'Beta vulgaris subsp. cicla', 'Summer to autumn'),
  ('swiss gruyère cheese, sliced', 'Firm, nutty, salty-sweet', 'Cow''s milk, Fribourg, Switzerland, sliced', 'Year-round'),
  ('swiss mountain honey', 'Floral, resinous, deeply aromatic', 'Alpine honey, Switzerland', 'Summer harvest; year-round'),
  ('swordfish', 'Firm, meaty, mildly sweet', 'Xiphias gladius, Mediterranean and Atlantic', 'Summer to autumn'),
  ('t-bone steak', 'Beefy loin on one side, tender fillet on the other', 'Beef short loin with bone', 'Year-round'),
  ('tabasco', 'Sharp, vinegary, cleanly hot', 'Aged chilli and vinegar sauce, Louisiana, USA', 'Year-round'),
  ('taco shells', 'Toasty, corn-sweet, brittle', 'Fried maize tortillas, Mexico', 'Year-round'),
  ('taggiasca olive', 'Small, sweet, delicately fruity', 'Taggiasca olives, Liguria, Italy', 'Year-round; harvest autumn'),
  ('tagliatelle', 'Neutral, eggy, silky ribbons', 'Egg pasta, Emilia-Romagna, Italy', 'Year-round'),
  ('tahini', 'Nutty, faintly bitter, oily', 'Ground sesame seeds, Levant', 'Year-round'),
  ('tajná marinade', 'House marinade; flavour set by the kitchen', 'House preparation', 'Year-round'),
  ('takuan', 'Sweet, sharp, crunchy yellow pickle', 'Pickled daikon, Japan', 'Year-round'),
  ('taleggio dop', 'Soft, fruity, pungently washed rind', 'Cow''s milk, Lombardy, Italy', 'Year-round; best autumn to winter'),
  ('tamagoyaki', 'Sweet, savoury, layered omelette', 'Rolled egg omelette, Japan', 'Year-round'),
  ('tamari', 'Deep, rounded, wheat-free soy', 'Fermented soybean sauce, Japan', 'Year-round'),
  ('tamarind paste', 'Sour, fruity, faintly caramel', 'Tamarindus indica pulp, South Asia', 'Year-round'),
  ('tandoori masala', 'Warm, smoky, gently hot', 'North Indian spice blend', 'Year-round'),
  ('tapenade', 'Salty, briny, deeply olive', 'Crushed olives, capers and anchovy, Provence', 'Year-round'),
  ('tapioca starch', 'Flavourless; thickens clear and gives a chew', 'Cassava starch', 'Year-round'),
  ('taro', 'Nutty, starchy, faintly sweet', 'Colocasia esculenta corm, tropics', 'Autumn to winter'),
  ('taro root', 'Nutty, starchy, faintly sweet', 'Colocasia esculenta corm, tropics', 'Autumn to winter'),
  ('tarragon', 'Sweet, aniseed, faintly bitter', 'Artemisia dracunculus, France', 'Spring to autumn'),
  ('tarragon vinegar', 'Sharp with a sweet aniseed lift', 'Tarragon-infused vinegar, France', 'Year-round'),
  ('tartare sauce', 'Creamy, tangy, caper-and-gherkin', 'Mayonnaise-based sauce', 'Year-round'),
  ('tatsoi', 'Mild, mustardy, tender rosette leaf', 'Brassica rapa var. rosularis, East Asia', 'Autumn to spring'),
  ('tawny port', 'Nutty, caramelised, gently oxidised', 'Barrel-aged fortified wine, Douro valley, Portugal', 'Year-round'),
  ('teff flour', 'Earthy, faintly molasses-sweet', 'Milled Eragrostis tef, Ethiopia', 'Year-round'),
  ('tempeh', 'Nutty, firm, faintly mushroomy', 'Fermented whole soybean cake, Indonesia', 'Year-round'),
  ('tempura flour', 'Neutral; fries exceptionally light and crisp', 'Low-protein wheat flour blend, Japan', 'Year-round'),
  ('tête de moine', 'Firm, nutty, intense when shaved into rosettes', 'Raw cow''s milk, Jura, Switzerland', 'Year-round'),
  ('tête de moine aop', 'Firm, nutty, intense protected shaving cheese', 'Raw cow''s milk, Bellelay, Jura, Switzerland', 'Year-round'),
  ('tezu (hand-vinegar)', 'Mildly acidic; stops rice sticking to the hands', 'Vinegar and water, Japan', 'Year-round'),
  ('thai basil', 'Aniseed, peppery, faintly liquorice', 'Ocimum basilicum var. thyrsiflora, Southeast Asia', 'Summer'),
  ('thai basil stem', 'Aniseed and peppery; more robust than the leaf', 'Ocimum basilicum var. thyrsiflora stem', 'Summer'),
  ('thai chilli', 'Sharp, clean, fiercely hot', 'Capsicum frutescens, Thailand', 'Summer to autumn'),
  ('thai holy basil', 'Peppery, clove-warm, faintly medicinal', 'Ocimum tenuiflorum, Thailand', 'Summer'),
  ('thousand island dressing', 'Creamy, sweet, faintly tangy', 'Mayonnaise and tomato dressing, USA', 'Year-round'),
  ('thurgauer spezial cheese', 'Semi-hard, mild, gently aromatic', 'Cow''s milk, Thurgau, Switzerland', 'Year-round'),
  ('thyme sprig', 'Resinous, herbal, faintly floral', 'Thymus vulgaris, Mediterranean', 'Year-round'),
  ('tianmian jiang', 'Sweet, savoury, deeply fermented wheat paste', 'Sweet bean sauce, northern China', 'Year-round'),
  ('tiger prawn', 'Sweet, firm, distinctly briny', 'Penaeus monodon, farmed and wild', 'Year-round'),
  ('tigernuts', 'Sweet, nutty, faintly coconut', 'Cyperus esculentus tuber, Spain and West Africa', 'Year-round'),
  ('tilsiter', 'Semi-hard, tangy, faintly pungent', 'Cow''s milk, Switzerland and Germany', 'Year-round'),
  ('tilsiter aop', 'Semi-hard, tangy, protected Swiss cheese', 'Cow''s milk, Thurgau, Switzerland', 'Year-round'),
  ('timut pepper', 'Intensely grapefruit, floral, lightly numbing', 'Zanthoxylum armatum, Nepal', 'Year-round'),
  ('tipo 00 flour', 'Neutral, soft, very finely milled', 'Italian tipo 00 wheat flour', 'Year-round'),
  ('toasted pumpkin seeds and sage', 'Nutty and toasty with resinous, peppery sage', 'Roasted pumpkin seeds with Salvia officinalis', 'Autumn'),
  ('toasted sesame oil', 'Intensely nutty, toasty, aromatic', 'Pressed roasted sesame seeds, East Asia', 'Year-round'),
  ('toasted sesame seed', 'Nutty, toasty, crunchy', 'Roasted Sesamum indicum seed', 'Year-round'),
  ('toasted sourdough', 'Sour, wheaty, crisp-edged', 'Toasted naturally leavened bread', 'Year-round'),
  ('tofu', 'Mild, milky, faintly beany', 'Set soy curd, East Asia', 'Year-round'),
  ('tom yum paste', 'Sour, hot, lemongrass-and-galangal', 'Thai soup paste, Thailand', 'Year-round'),
  ('tomatillo', 'Sharp, green, faintly citrus', 'Physalis philadelphica, Mexico', 'Summer to autumn'),
  ('tomato juice', 'Savoury, acidic, lightly sweet', 'Pressed tomatoes', 'Year-round'),
  ('tomato passata', 'Clean, sweet-acidic, smooth', 'Sieved uncooked tomatoes, Italy', 'Year-round'),
  ('tomato paste double', 'Intensely concentrated, sweet-savoury', 'Twice-reduced tomato concentrate', 'Year-round'),
  ('tomato powder', 'Concentrated, sweet-savoury, umami', 'Dried and milled tomato', 'Year-round'),
  ('tomatoes', 'Sweet, acidic, deeply savoury when ripe', 'Solanum lycopersicum', 'Summer to early autumn'),
  ('tomme de chèvre', 'Firm, tangy, distinctly goaty', 'Goat''s milk, France', 'Year-round; made spring to autumn'),
  ('tomme vaudoise', 'Soft, bloomy, mushroomy and creamy', 'Cow''s milk, Vaud, Switzerland', 'Year-round'),
  ('tonic water', 'Bitter, citrus, lightly sweet', 'Quinine soft drink', 'Year-round'),
  ('tonka bean', 'Sweet, almond-and-vanilla, faintly hay-like', 'Dipteryx odorata seed, South America', 'Year-round'),
  ('tonkatsu sauce', 'Sweet, fruity, thickly savoury', 'Worcestershire-style sauce, Japan', 'Year-round'),
  ('toor dal', 'Earthy, nutty; cooks down soft', 'Split pigeon pea, South Asia', 'Year-round'),
  ('top-split hot dog bun', 'Soft, faintly sweet, buttery when griddled', 'Enriched wheat bun, New England, USA', 'Year-round'),
  ('toro', 'Intensely fatty, melting, richly sweet', 'Bluefin tuna belly, Japan', 'Winter'),
  ('totenbeinli', 'Hard, sweet, almond-rich biscuit', 'Almond biscuit, Graubünden, Switzerland', 'Year-round'),
  ('toulouse or garlic sausage', 'Coarse and porky, or richly garlicky', 'Fresh pork sausage, France', 'Year-round'),
  ('toulouse sausage', 'Coarse, porky, gently peppery', 'Fresh pork sausage, Toulouse, France', 'Year-round'),
  ('toum', 'Fiercely garlicky, whipped, faintly lemony', 'Garlic emulsion, Lebanon', 'Year-round'),
  ('transglutaminase', 'Flavourless; bonds protein surfaces together', 'Microbial enzyme preparation', 'Year-round'),
  ('treberwurst note', 'Smoky, spirit-scented; cooked in grape-marc distillate steam', 'Sausage cooked over marc distilling, Switzerland', 'Autumn to winter'),
  ('trimoline', 'Very sweet and smooth; keeps bakes soft', 'Invert sugar syrup', 'Year-round'),
  ('trimoline (invert sugar)', 'Very sweet and smooth; keeps bakes soft', 'Invert sugar syrup', 'Year-round'),
  ('tripe', 'Mild, faintly offaly, softly chewy', 'Ruminant stomach lining', 'Year-round'),
  ('triple sec', 'Sweet, bright, orange-peel bitter', 'Orange liqueur, France', 'Year-round'),
  ('trofie', 'Neutral, wheaty, tightly twisted', 'Durum wheat pasta, Liguria, Italy', 'Year-round'),
  ('tropea red onions', 'Notably sweet, mild, deep red', 'Cipolla Rossa di Tropea IGP, Calabria, Italy', 'Summer to autumn'),
  ('trout', 'Delicate, sweet, faintly earthy freshwater fish', 'Salmo trutta or Oncorhynchus mykiss, farmed', 'Year-round'),
  ('trout fillet', 'Delicate, sweet, finely flaked', 'Farmed trout fillet', 'Year-round'),
  ('trout roe', 'Briny, popping, delicately sweet', 'Trout eggs', 'Autumn to winter'),
  ('truffle black winter', 'Deeply earthy, musky, intensely aromatic', 'Tuber melanosporum, Périgord and Umbria', 'Winter'),
  ('truffle essence', 'Concentrated, musky, aromatic', 'Truffle extract preparation', 'Year-round'),
  ('truffle honey', 'Floral honey with a musky truffle finish', 'Honey infused with truffle', 'Year-round'),
  ('truffle oil', 'Powerfully musky; usually aroma compound, not real truffle', 'Aromatised oil', 'Year-round'),
  ('truffle paste', 'Earthy, musky, concentrated', 'Ground truffle and mushroom paste', 'Year-round'),
  ('truffle summer', 'Gently earthy, nutty, mildly aromatic', 'Tuber aestivum, Italy and France', 'Late spring to summer'),
  ('tuna', 'Meaty, rich, deeply savoury', 'Thunnus species', 'Year-round; peak summer'),
  ('tuna loin', 'Meaty, clean, richly savoury', 'Thunnus loin', 'Year-round; peak summer'),
  ('turbot', 'Firm, sweet, luxuriously fine flatfish', 'Scophthalmus maximus, North Sea and Atlantic', 'Spring to summer'),
  ('turkey breast', 'Lean, mild, dries easily if overcooked', 'Meleagris gallopavo breast', 'Year-round; peak autumn to winter'),
  ('turkey leg', 'Darker, richer, more sinewy than the breast', 'Meleagris gallopavo leg', 'Year-round; peak autumn to winter'),
  ('turkey thigh', 'Dark, juicy, deeply savoury', 'Meleagris gallopavo thigh', 'Year-round; peak autumn to winter'),
  ('turmeric', 'Earthy, bitter, intensely colouring', 'Curcuma longa rhizome, South Asia', 'Year-round'),
  ('turnip', 'Peppery, sweet, faintly mustardy', 'Brassica rapa root', 'Autumn to spring'),
  ('tzatziki', 'Cool, garlicky, tangy cucumber yoghurt', 'Yoghurt and cucumber dip, Greece', 'Year-round'),
  ('ube purée', 'Sweet, nutty, vanilla-like purple yam', 'Dioscorea alata, Philippines', 'Year-round'),
  ('udon noodle', 'Thick, chewy, faintly wheaty', 'Wheat noodle, Japan', 'Year-round'),
  ('udon noodles', 'Thick, chewy, faintly wheaty', 'Wheat noodles, Japan', 'Year-round'),
  ('umami seasoning', 'Deeply savoury; rounds out a dish', 'Glutamate-rich seasoning blend', 'Year-round'),
  ('ume vinegar', 'Sharply salty, sour, fruity', 'Brine from pickled ume plums, Japan', 'Year-round'),
  ('umeboshi', 'Intensely sour and salty', 'Pickled ume plums, Japan', 'Year-round; pickled in summer'),
  ('umeboshi plum', 'Intensely sour and salty', 'Pickled ume plum, Japan', 'Year-round; pickled in summer'),
  ('umeboshi vinegar', 'Sharply salty, sour, fruity', 'Brine from pickled ume plums, Japan', 'Year-round'),
  ('umeshu', 'Sweet, sour, almond-scented plum liqueur', 'Ume plum liqueur, Japan', 'Year-round'),
  ('unagi', 'Rich, oily, sweet-glazed', 'Grilled freshwater eel, Japan', 'Summer'),
  ('unspecified', 'Not an ingredient — a placeholder left when a scan could not read the line; replace it with the real ingredient', 'Placeholder entry', 'Not applicable'),
  ('urad dal', 'Earthy, faintly musky; cooks creamy', 'Split black gram, South Asia', 'Year-round'),
  ('urfa biber', 'Smoky, raisiny, gently hot', 'Sun-dried and sweated chilli, Urfa, Turkey', 'Year-round'),
  ('urner alpkäse', 'Firm, nutty, floral alpine cheese', 'Raw cow''s milk, Uri, Switzerland', 'Made in summer, sold from autumn'),
  ('us beef flank steak', 'Loose-grained, deeply beefy, best sliced thin', 'Beef flank, USA', 'Year-round'),
  ('usukuchi light soy sauce', 'Saltier and paler than dark soy; keeps colour light', 'Light soy sauce, Kansai, Japan', 'Year-round'),
  ('vacherin', 'Soft, creamy, woody and pungent', 'Cow''s milk soft cheese, Switzerland and France', 'Autumn to winter'),
  ('vacherin fribourgeois', 'Supple, nutty, faintly acidic; melts perfectly', 'Cow''s milk, Fribourg, Switzerland', 'Year-round'),
  ('vacherin fribourgeois aop', 'Supple, nutty protected melting cheese', 'Cow''s milk, Fribourg, Switzerland', 'Year-round'),
  ('vacherin mont d''or aop', 'Runny, woody, pungently creamy', 'Raw cow''s milk in spruce bark, Vaud, Switzerland', 'Autumn to early spring only'),
  ('vacherin mont-d''or aop', 'Runny, woody, pungently creamy', 'Raw cow''s milk in spruce bark, Vaud, Switzerland', 'Autumn to early spring only'),
  ('vacuum bags 20x30', 'Not an ingredient — packaging for sous-vide and storage', 'Food-safe vacuum pouches, 20x30 cm', 'Not applicable'),
  ('vadouvan', 'Mellow, oniony, gently curried', 'French-Indian spice blend, Pondicherry', 'Year-round'),
  ('vanilla bean paste', 'Sweet, deeply vanilla, seed-flecked', 'Vanilla planifolia seeds in syrup', 'Year-round'),
  ('vanilla beans', 'Sweet, floral, deeply aromatic', 'Cured Vanilla planifolia pods, Madagascar', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
