-- 183_ingredient_info_backfill_batch13.sql
-- Ingredient info backfill — batch 13, the LAST one (Richard, 23.7.2026). Same safety contract as
-- db/171–182: ONLY fills currently-empty fields (coalesce + nullif), matched case-insensitively by
-- name, never overwrites — idempotent. Price, kitchen_id and is_personal are never touched.
-- 176 names, 'vanilla extract' → 'zopf flour'. After this the remaining-names count should be 0.
with m(name, flavour, origin, season) as (values
  ('vanilla extract', 'Sweet, floral, deeply vanilla', 'Alcohol extract of Vanilla planifolia', 'Year-round'),
  ('vanilla ice base', 'Sweet, creamy, vanilla-scented', 'Prepared vanilla ice cream base', 'Year-round'),
  ('vanilla paste', 'Sweet, deeply vanilla, seed-flecked', 'Vanilla seeds in syrup', 'Year-round'),
  ('vanilla pod', 'Sweet, floral, deeply aromatic', 'Cured Vanilla planifolia pod, Madagascar', 'Year-round'),
  ('vanilla pod, split, seeds scraped out using a knife', 'Sweet, floral, deeply aromatic', 'Cured Vanilla planifolia pod, scraped', 'Year-round'),
  ('vanilla sugar', 'Sweet with a soft vanilla perfume', 'Sugar infused with vanilla', 'Year-round'),
  ('veal bones', 'Savoury and richly gelatinous; the base of white stock', 'Veal skeleton', 'Year-round'),
  ('veal cheek', 'Sweet, gelatinous, meltingly tender when braised', 'Veal cheek muscle', 'Year-round'),
  ('veal cutlet', 'Delicate, milky, very lean', 'Veal loin chop or escalope', 'Year-round'),
  ('veal escalopes (from top round or leg, pounded thin)', 'Delicate, milky, very lean', 'Veal top round or leg, pounded thin', 'Year-round'),
  ('veal fillet', 'Extremely tender, delicate, lean', 'Veal tenderloin', 'Year-round'),
  ('veal jus', 'Deep, glossy, gently savoury', 'Reduced veal stock', 'Year-round'),
  ('veal kidney', 'Mineral, distinctly offaly, firm', 'Veal kidney', 'Year-round'),
  ('veal liver', 'Delicate, mineral, faintly sweet', 'Veal liver', 'Year-round'),
  ('veal loin', 'Tender, milky, finely grained', 'Veal loin', 'Year-round'),
  ('veal or beef stock', 'Savoury, gelatinous; delicate or deeply meaty', 'Simmered veal or beef bones', 'Year-round'),
  ('veal shank', 'Rich, gelatinous, deeply savoury when braised', 'Veal shank, cut for osso buco', 'Year-round'),
  ('veal shoulder', 'Juicy, forgiving, gently savoury', 'Veal shoulder', 'Year-round'),
  ('veal spare rib', 'Delicate, fatty, tender when slow-cooked', 'Veal rib', 'Year-round'),
  ('veal spareribs', 'Delicate, fatty, tender when slow-cooked', 'Veal ribs', 'Year-round'),
  ('veal stock', 'Clean, gelatinous, gently savoury', 'Simmered veal bones', 'Year-round'),
  ('veal sweetbread', 'Delicate, creamy, faintly sweet', 'Veal thymus or pancreas', 'Spring to autumn'),
  ('veal sweetbreads', 'Delicate, creamy, faintly sweet', 'Veal thymus or pancreas', 'Spring to autumn'),
  ('veal tongue', 'Rich, tender, mildly beefy', 'Veal tongue', 'Year-round'),
  ('vegan butter', 'Neutral-fatty, mildly buttery', 'Emulsified plant fats', 'Year-round'),
  ('vegetable mayonnaise', 'Rich, tangy, egg-free emulsion', 'Plant-based mayonnaise', 'Year-round'),
  ('vegetable or chicken stock', 'Clean and vegetal, or rounded and savoury', 'Simmered vegetables or chicken bones', 'Year-round'),
  ('vegetable stock', 'Clean, vegetal, lightly sweet', 'Simmered vegetables and aromatics', 'Year-round'),
  ('vegetable stock paste', 'Concentrated, salty, vegetal', 'Reduced vegetable stock paste', 'Year-round'),
  ('veggie patty', 'Savoury, varied; depends on the blend', 'Vegetable and pulse patty', 'Year-round'),
  ('venison haunch', 'Lean, dark, distinctly gamey', 'Deer hind leg', 'Autumn to winter'),
  ('venison leg', 'Lean, dark, distinctly gamey', 'Deer leg', 'Autumn to winter'),
  ('venison loin', 'Tender, lean, elegantly gamey', 'Deer loin', 'Autumn to winter'),
  ('venison ragout', 'Deep, gamey, wine-and-juniper rich', 'Braised diced venison', 'Autumn to winter'),
  ('venison saddle', 'Tender, prime, delicately gamey', 'Deer saddle', 'Autumn to winter'),
  ('venison shoulder', 'Sinewy, deeply gamey; for braising and mince', 'Deer shoulder', 'Autumn to winter'),
  ('verbena tea', 'Intensely lemony, floral, clean', 'Dried Aloysia citrodora leaves', 'Year-round; picked in summer'),
  ('verjuice', 'Sharp, grapey, gentler than vinegar', 'Pressed unripe grapes', 'Year-round; pressed late summer'),
  ('verjus', 'Sharp, grapey, gentler than vinegar', 'Pressed unripe grapes, France', 'Year-round; pressed late summer'),
  ('vermicelles purée', 'Sweet, chestnutty, faintly vanilla', 'Sweetened chestnut purée, Switzerland and France', 'Autumn to winter'),
  ('vermouth dry', 'Herbal, bitter, crisply aromatic', 'Aromatised dry wine, Chambéry and Turin', 'Year-round'),
  ('vialone nano', 'Absorbent, creamy, keeps a firm bite', 'Semifino risotto rice, Veneto, Italy', 'Year-round'),
  ('viande des grisons', 'Lean, salty, air-dried beef with herbal notes', 'Air-dried beef, Graubünden, Switzerland', 'Year-round'),
  ('vietnamese coriander', 'Pungent, peppery, citrus-herbal', 'Persicaria odorata, Vietnam', 'Year-round'),
  ('vietnamese mint', 'Pungent, peppery, citrus-herbal', 'Persicaria odorata, Vietnam', 'Year-round'),
  ('vin santo', 'Sweet, nutty, raisined dessert wine', 'Dried-grape wine, Tuscany, Italy', 'Year-round'),
  ('vincotto', 'Dark, sweet-sour, syrupy', 'Cooked grape must, Puglia, Italy', 'Year-round'),
  ('vinegar', 'Sharp, acidic; character varies with the base', 'Acetic fermentation of wine, cider or grain', 'Year-round'),
  ('violet syrup', 'Sweet, intensely floral', 'Violet-infused sugar syrup', 'Year-round'),
  ('vital wheat gluten', 'Neutral; adds strength and chew to dough', 'Isolated wheat protein', 'Year-round'),
  ('vodka', 'Clean, neutral, faintly grainy', 'Distilled grain or potato spirit', 'Year-round'),
  ('vol-au-vent shells', 'Neutral, buttery, shatteringly layered', 'Baked puff pastry cases, France', 'Year-round'),
  ('waffle cones', 'Sweet, toasty, crisp', 'Baked batter cones', 'Year-round'),
  ('wagyu burger (140g)', 'Intensely marbled, buttery, deeply beefy', 'Minced wagyu beef, portioned', 'Year-round'),
  ('wagyu fat', 'Sweet, low-melting, richly beefy', 'Rendered wagyu beef fat', 'Year-round'),
  ('wagyu steak', 'Intensely marbled, buttery, melting', 'Wagyu beef, Japan and crossbreeds', 'Year-round'),
  ('wagyu trim', 'Richly marbled; for mince, fat and sauces', 'Wagyu beef trimmings', 'Year-round'),
  ('wakame', 'Silky, mildly sweet, gently marine', 'Undaria pinnatifida, Japan and Korea', 'Year-round; harvest spring'),
  ('walliser roggenbrot aop', 'Dense, sour, deeply rye', 'Protected rye bread, Valais, Switzerland', 'Year-round'),
  ('walliser trockenwurst', 'Firm, salty, gently spiced air-dried sausage', 'Dried sausage, Valais, Switzerland', 'Year-round'),
  ('walnut', 'Rich, buttery, faintly bitter skin', 'Juglans regia', 'Year-round; harvest autumn'),
  ('walnut butter', 'Rich, oily, faintly tannic', 'Ground walnuts', 'Year-round'),
  ('walnut oil', 'Intensely nutty, delicate, spoils quickly', 'Pressed walnuts, Périgord, France', 'Year-round'),
  ('warm water', 'Neutral', 'Potable water, warmed', 'Year-round'),
  ('wasabi', 'Clean, green, fleetingly hot', 'Eutrema japonicum rhizome, Japan', 'Year-round'),
  ('wasabi paste', 'Sharp, green, quickly fading heat', 'Wasabi or horseradish paste, Japan', 'Year-round'),
  ('wasabi powder', 'Sharp and hot once mixed with water', 'Dried wasabi or horseradish powder, Japan', 'Year-round'),
  ('water', 'Neutral', 'Potable water', 'Year-round'),
  ('water chestnut', 'Sweet, crisp; stays crunchy when cooked', 'Eleocharis dulcis corm, East Asia', 'Autumn to winter'),
  ('water chestnut flour', 'Neutral, faintly sweet; fries very crisp', 'Milled water chestnut', 'Year-round'),
  ('water chestnuts fresh', 'Sweet, crisp, juicy', 'Fresh Eleocharis dulcis corms, East Asia', 'Autumn to winter'),
  ('water or stock', 'Neutral, or savoury and gelatinous', 'Potable water or simmered stock', 'Year-round'),
  ('watercress', 'Peppery, mineral, sharply green', 'Nasturtium officinale, spring water beds', 'Spring to autumn'),
  ('watermelon', 'Sweet, watery, faintly floral', 'Citrullus lanatus', 'Summer'),
  ('watermelon radish', 'Peppery, crisp, sweet at the pink centre', 'Raphanus sativus var. longipinnatus', 'Autumn to winter'),
  ('watermelon seeds', 'Mild, nutty when toasted', 'Citrullus lanatus seeds', 'Summer; year-round dried'),
  ('weissbier', 'Banana-and-clove, cloudy, gently sweet', 'Wheat beer, Bavaria, Germany', 'Year-round'),
  ('wheat tortillas', 'Soft, neutral, faintly toasty', 'Wheat flatbread, Mexico and USA', 'Year-round'),
  ('whelk', 'Firm, mineral, distinctly marine', 'Buccinum undatum, North Atlantic', 'Autumn to spring'),
  ('whelks', 'Firm, mineral, distinctly marine', 'Buccinum undatum, North Atlantic', 'Autumn to spring'),
  ('whey', 'Thin, tangy, faintly sweet', 'Liquid left from cheesemaking', 'Year-round'),
  ('whipping cream', 'Rich, creamy; holds air when whipped', 'Cow''s cream, around 35% fat', 'Year-round'),
  ('whisky', 'Warm, malty, oak-and-smoke', 'Distilled malted grain, Scotland and Ireland', 'Year-round'),
  ('white asparagus', 'Delicate, faintly bitter, tender', 'Blanched Asparagus officinalis', 'Spring'),
  ('white asparagus fresh', 'Delicate, faintly bitter, tender', 'Blanched Asparagus officinalis', 'Spring'),
  ('white balsamic', 'Sweet-sour, clean; does not colour a dish', 'White grape must vinegar, Modena, Italy', 'Year-round'),
  ('white bean', 'Mild, creamy, absorbs flavour', 'Dried Phaseolus vulgaris', 'Year-round'),
  ('white cabbage', 'Sweet, crisp, mildly cabbagey', 'Brassica oleracea var. capitata', 'Autumn to winter'),
  ('white chocolate', 'Sweet, milky, vanilla-scented', 'Cocoa butter, milk and sugar', 'Year-round'),
  ('white chocolate couverture', 'Sweet, milky, smoothly melting', 'High-cocoa-butter white chocolate', 'Year-round'),
  ('white currant', 'Sharp, delicate, lightly sweet', 'Ribes rubrum, white cultivar', 'Summer'),
  ('white flour', 'Neutral, wheaty, all-purpose', 'Milled wheat endosperm', 'Year-round'),
  ('white garlic', 'Pungent and sharp raw, sweet when cooked', 'Allium sativum, white-skinned', 'Year-round; new season summer'),
  ('white grapes', 'Sweet, juicy, mildly acidic', 'Vitis vinifera, white cultivars', 'Late summer to autumn'),
  ('white miso', 'Sweet, mild, gently salty', 'Short-fermented rice miso, Japan', 'Year-round'),
  ('white miso paste', 'Sweet, mild, gently salty', 'Short-fermented rice miso, Japan', 'Year-round'),
  ('white onion', 'Sharp raw, cleanly sweet when cooked', 'Allium cepa, white cultivar', 'Year-round'),
  ('white peach', 'Perfumed, delicate, very sweet', 'Prunus persica, white-fleshed', 'Summer'),
  ('white peppercorns', 'Earthy, fermented, cleanly hot', 'Hulled Piper nigrum berries', 'Year-round'),
  ('white rum', 'Clean, faintly sweet, cane-scented', 'Distilled sugarcane, Caribbean', 'Year-round'),
  ('white truffle', 'Intensely garlicky, musky, heady', 'Tuber magnatum, Alba, Piedmont, Italy', 'Autumn only'),
  ('white truffle oil', 'Powerfully musky; usually aroma compound, not real truffle', 'Aromatised oil', 'Year-round'),
  ('white vinegar', 'Sharp, clean, uncomplicated acidity', 'Distilled vinegar', 'Year-round'),
  ('white wine', 'Crisp, fruity, acidic', 'Fermented white grapes', 'Year-round'),
  ('whitebait', 'Delicate, briny, eaten whole', 'Young herring or sprat, Atlantic', 'Spring to summer'),
  ('whitefish', 'Delicate, sweet, finely flaked lake fish', 'Coregonus species, alpine lakes', 'Autumn to winter'),
  ('whitefish fillet', 'Delicate, sweet, finely flaked lake fish', 'Coregonus fillet, alpine lakes', 'Autumn to winter'),
  ('whole almond', 'Sweet, nutty, faintly bitter skin', 'Prunus dulcis', 'Year-round; harvest autumn'),
  ('whole black pepper', 'Pungent, woody, sharply hot', 'Whole Piper nigrum berries', 'Year-round'),
  ('whole chicken', 'Mild, savoury, varied by cut', 'Gallus gallus domesticus', 'Year-round'),
  ('whole cream', 'Rich, creamy, mildly sweet', 'Cow''s cream, full fat', 'Year-round'),
  ('whole duck', 'Rich, dark, fatty-skinned poultry', 'Anas platyrhynchos domesticus', 'Year-round; peak autumn to winter'),
  ('whole egg', 'Neutral-rich; binds and sets', 'Hen''s egg', 'Year-round'),
  ('whole nutmeg', 'Warm, sweet, faintly resinous', 'Myristica fragrans seed, Indonesia and Grenada', 'Year-round'),
  ('whole rabbit', 'Lean, mild, faintly gamey', 'Whole farmed rabbit', 'Year-round'),
  ('whole salmon', 'Rich, oily, sweetly marine', 'Whole Salmo salar', 'Year-round; wild in summer'),
  ('whole trout', 'Delicate, sweet, faintly earthy', 'Whole farmed trout', 'Year-round'),
  ('whole turkey', 'Lean breast, rich dark leg meat', 'Meleagris gallopavo', 'Autumn to winter'),
  ('wholegrain flour', 'Nutty, earthy, densely wheaty', 'Milled whole wheat grain', 'Year-round'),
  ('wholegrain mustard', 'Sharp, grainy, gently vinegary', 'Whole mustard seeds in vinegar', 'Year-round'),
  ('wholemeal flour', 'Nutty, earthy, densely wheaty', 'Milled whole wheat grain', 'Year-round'),
  ('wiesenkäse', 'Semi-hard, mild, floral from meadow-fed milk', 'Cow''s milk, Switzerland', 'Year-round'),
  ('wild arugula', 'Intensely peppery, nutty, deeply cut leaf', 'Diplotaxis tenuifolia, Mediterranean', 'Spring to autumn'),
  ('wild boar loin', 'Dark, lean, strongly gamey', 'Sus scrofa loin', 'Autumn to winter'),
  ('wild boar shoulder', 'Dark, sinewy, deeply gamey when braised', 'Sus scrofa shoulder', 'Autumn to winter'),
  ('wild garlic', 'Garlicky, green, softly pungent', 'Allium ursinum leaf, European woodland', 'Spring'),
  ('wild herb', 'Varied, green, intensely aromatic', 'Foraged wild herbs', 'Spring to autumn'),
  ('wild mushroom', 'Earthy, woodsy, deeply savoury', 'Foraged forest fungi', 'Autumn; some in spring'),
  ('wild rice', 'Nutty, chewy, faintly smoky', 'Zizania palustris, North America', 'Year-round; harvest autumn'),
  ('wild strawberry', 'Intensely perfumed, small, sweet-tart', 'Fragaria vesca, wild', 'Early summer'),
  ('williamine', 'Dry, intensely pear-perfumed spirit', 'Distilled Williams pears, Valais, Switzerland', 'Year-round'),
  ('williams brandy', 'Dry, intensely pear-perfumed spirit', 'Distilled Williams pears', 'Year-round'),
  ('williams pear', 'Musky, perfumed, very juicy', 'Pyrus communis Williams', 'Late summer to autumn'),
  ('willisauer ringli', 'Hard, sweet, faintly spiced ring biscuit', 'Biscuit from Willisau, Lucerne, Switzerland', 'Year-round'),
  ('winter melon', 'Very mild, watery, faintly sweet', 'Benincasa hispida, East and South Asia', 'Autumn to winter'),
  ('winter savory', 'Peppery, resinous, more intense than summer savory', 'Satureja montana', 'Year-round; peak summer'),
  ('wolffish', 'Firm, sweet, faintly shellfish-like', 'Anarhichas lupus, North Atlantic', 'Winter to spring'),
  ('wonton wrapper', 'Neutral, thin, silky when boiled', 'Wheat dough wrapper, China', 'Year-round'),
  ('wonton wrappers', 'Neutral, thin, silky when boiled', 'Wheat dough wrappers, China', 'Year-round'),
  ('wood ear mushroom', 'Almost flavourless; prized for its crunch', 'Auricularia species, East Asia', 'Year-round'),
  ('wood sorrel', 'Sharply sour, lemony, delicate', 'Oxalis acetosella, woodland', 'Spring to summer'),
  ('worcestershire sauce', 'Savoury, tangy, anchovy-and-tamarind', 'Fermented condiment, Worcester, England', 'Year-round'),
  ('xanthan gum', 'Flavourless; thickens and stabilises', 'Fermented glucose polysaccharide', 'Year-round'),
  ('xo sauce', 'Intensely savoury, spicy, seafood-rich', 'Dried scallop and ham chilli sauce, Hong Kong', 'Year-round'),
  ('yakiniku sauce', 'Sweet, savoury, sesame-and-garlic', 'Grilled meat sauce, Japan', 'Year-round'),
  ('yakisoba sauce', 'Sweet, tangy, thickly savoury', 'Fried noodle sauce, Japan', 'Year-round'),
  ('yakitori tare', 'Sweet, salty, glossy soy glaze', 'Soy and mirin grilling glaze, Japan', 'Year-round'),
  ('yeast', 'Neutral; yeasty aroma while proving', 'Saccharomyces cerevisiae', 'Year-round'),
  ('yeast flakes', 'Savoury, cheesy, nutty', 'Deactivated nutritional yeast', 'Year-round'),
  ('yellow bell pepper', 'Sweet, fruity, crisp', 'Ripe yellow Capsicum annuum', 'Summer to autumn'),
  ('yellow curry paste', 'Warm, turmeric-rich, mildly hot', 'Thai curry paste, southern Thailand', 'Year-round'),
  ('yellow mustard', 'Mild, tangy, brightly yellow', 'Yellow mustard seed condiment, USA', 'Year-round'),
  ('yellow mustard seed', 'Mild, nutty, gently pungent', 'Sinapis alba seed', 'Year-round'),
  ('yellow mustard seeds', 'Mild, nutty, gently pungent', 'Sinapis alba seeds', 'Year-round'),
  ('yellow onion', 'Sharp raw, deeply sweet when cooked', 'Allium cepa, yellow cultivar', 'Year-round'),
  ('yellow split pea', 'Earthy, sweet; cooks down to a purée', 'Split Pisum sativum, yellow', 'Year-round'),
  ('yellowfin tuna', 'Lean, clean, mildly savoury', 'Thunnus albacares', 'Year-round; peak summer'),
  ('yogurt powder', 'Tangy, concentrated, milky', 'Spray-dried yoghurt', 'Year-round'),
  ('young ginger', 'Juicy, mild, faintly floral; no fibre', 'Young Zingiber officinale rhizome', 'Summer to early autumn'),
  ('yuba', 'Delicate, milky, faintly beany', 'Soy milk skin, Japan and China', 'Year-round'),
  ('yuca root', 'Starchy, mild, faintly sweet', 'Manihot esculenta root, South America', 'Year-round'),
  ('yusen vinegar', 'Soft, mellow, gently acidic rice vinegar', 'Brewed rice vinegar, Japan', 'Year-round'),
  ('yuzu', 'Sharp, floral, intensely perfumed citrus', 'Citrus junos, Japan', 'Late autumn to winter'),
  ('yuzu juice', 'Sharp, floral, intensely perfumed', 'Pressed Citrus junos, Japan', 'Year-round; fruit peaks winter'),
  ('yuzu kosho', 'Hot, salty, intensely citrus', 'Chilli, yuzu peel and salt, Japan', 'Year-round'),
  ('yuzu marmalade', 'Sweet, bitter-edged, deeply perfumed', 'Yuzu peel preserve, Japan and Korea', 'Year-round'),
  ('yuzu ponzu', 'Citrus, soy-savoury, tangy', 'Ponzu with yuzu, Japan', 'Year-round'),
  ('yuzu purée', 'Sharp, floral, intensely perfumed', 'Sieved Citrus junos', 'Year-round'),
  ('yuzu zest', 'Oily, perfumed, bitter-bright', 'Grated Citrus junos peel', 'Late autumn to winter'),
  ('yuzu-nut butter', 'Nutty and rich with a sharp citrus lift', 'Nut butter with yuzu', 'Year-round'),
  ('za''atar', 'Herbal, sour, sesame-toasty', 'Thyme, sumac and sesame blend, Levant', 'Year-round'),
  ('zha cai', 'Salty, sour, crunchy and hot', 'Pickled mustard stem, Sichuan, China', 'Year-round'),
  ('zhoug', 'Fiery, herbal, coriander-and-cardamom', 'Green chilli relish, Yemen', 'Year-round'),
  ('ziger', 'Fresh, mild, faintly tangy whey cheese', 'Whey cheese, Switzerland', 'Year-round'),
  ('zopf', 'Rich, buttery, softly enriched braided loaf', 'Butter-and-milk bread, Switzerland', 'Year-round; traditionally Sunday'),
  ('zopf flour', 'Neutral, soft; milled for enriched braided bread', 'Swiss Zopf flour blend', 'Year-round')
)
update ingredients i set
  flavour = coalesce(nullif(i.flavour,''), m.flavour),
  origin  = coalesce(nullif(i.origin,''),  m.origin),
  season  = coalesce(nullif(i.season,''),  m.season)
from m
where lower(trim(i.name)) = lower(trim(m.name));
