-- ChefOS — translates all German prep-sheet data (dish + item names) to English, per
-- Richard's request. Name-based updates, so it doesn't matter which seed file a row came
-- from. One genuinely ambiguous word is handled first with a scoped update: 'Salat' means
-- 'Lettuce' on the Lobby burger/sandwich but 'Salad' on the Extra staff meal. Safe to
-- re-run (updates simply match nothing the second time).

-- Ambiguous case first: Extra station's 'Salat' is a side salad, not lettuce
update prep_items set name = 'Salad' where name = 'Salat' and dish_id in (select id from prep_dishes where station = 'Extra');
update prep_items set name = 'Lettuce' where name = 'Salat';

-- Dishes
update prep_dishes set name = 'Butterhead Salad' where name = 'Kopfsalat';
update prep_dishes set name = 'Celery & Apple Salad' where name = 'Sellerie-Apfel Salat';
update prep_dishes set name = 'Baby Gem Caesar' where name = 'Mini Lattich Caesar';
update prep_dishes set name = 'Grilled Octopus' where name = 'Gegrillter Oktopus';
update prep_dishes set name = 'Wagyu Steak Salad' where name = 'Wagyu Steak Salat';
update prep_dishes set name = 'Veal Spare Ribs' where name = 'Kalbsspare ribs';
update prep_dishes set name = 'Luma Pork Chop' where name = 'Kotlett Luma Schwein';
update prep_dishes set name = 'US Beef Flank Steak' where name = 'US BEEF Flanksteak';
update prep_dishes set name = 'Ribelmais Poularde' where name = 'Ribelmais-Poularde';
update prep_dishes set name = 'Tuna' where name = 'Thunfisch';
update prep_dishes set name = 'Truffle Mac and Cheese' where name = 'Trüffel Mac and Cheese';
update prep_dishes set name = 'Wild Mushrooms' where name = 'Waldpilze';
update prep_dishes set name = 'Tomato Salad' where name = 'Tomatensalat';
update prep_dishes set name = 'Roasted Cauliflower' where name = 'Gerösteter Blumenkohl';
update prep_dishes set name = 'Truffle Mayonnaise' where name = 'Trüffel Mayonnaise';
update prep_dishes set name = 'Black Garlic Dip' where name = 'Schwarzer Knoblauch Dip';
update prep_dishes set name = 'Green Salad Tips' where name = 'Grüne Salatspitzen';
update prep_dishes set name = 'Aubergine Tartare' where name = 'Auberginen Tatar';
update prep_dishes set name = 'Duck Terrine' where name = 'Terrine von der Ente';
update prep_dishes set name = 'Hand-Cut Holzen Angus Beef Tartare' where name = 'Handgeschnittenes Tatar vom Holzen Angus Rind';
update prep_dishes set name = 'Bone Marrow of Bernese Oberland Pasture Beef' where name = 'Knochenmark vom Berner Oberländer Weiderind';
update prep_dishes set name = 'Tomato Consommé' where name = 'Tomatenconsommé';
update prep_dishes set name = 'Sardinian Artichoke' where name = 'Sardinische Artischocke';
update prep_dishes set name = 'Wild Garlic Gnocchi' where name = 'Bärlauch Gnocchi';
update prep_dishes set name = 'Mackerel in Escabeche' where name = 'Makrele im Escabechesud';
update prep_dishes set name = 'Oven-Baked Baby Turbot' where name = 'Baby Steinbutt aus dem Ofen';
update prep_dishes set name = 'Beef Fillet' where name = 'Rindsfilet';
update prep_dishes set name = 'Côte de Boeuf of Morucha Beef' where name = 'Côte de Boeuf vom Morucha Rind';
update prep_dishes set name = 'Profiterole' where name = 'Profiterol';
update prep_dishes set name = 'Rhubarb' where name = 'Rhabarber';
update prep_dishes set name = 'Schweizerhof Chocolate Mousse' where name = 'Schweizerhof Schokoladenmousse';
update prep_dishes set name = 'Maki Roll Selection' where name = 'Maki Rollen Auswahl';
update prep_dishes set name = 'Mezze Platter' where name = 'Mezze Teller';
update prep_dishes set name = 'Pumpkin Soup' where name = 'Kürbissuppe';
update prep_dishes set name = 'Roasted Seasonal Vegetables' where name = 'Geröstetes Saisongemüse';
update prep_dishes set name = 'Mushroom Risotto' where name = 'Pilzrisotto';
update prep_dishes set name = 'Fried Egg Plate' where name = 'Spiegelei-Teller';
update prep_dishes set name = 'Banquet Starter Plate' where name = 'Bankett Vorspeisenteller';
update prep_dishes set name = 'Banquet Poularde' where name = 'Bankett Poularde';
update prep_dishes set name = 'Banquet Dessert Plate' where name = 'Bankett Dessertteller';
update prep_dishes set name = 'Buffet Salad Bar' where name = 'Buffet Salatbar';
update prep_dishes set name = 'Staff Meal' where name = 'Mitarbeiteressen';

-- Items
update prep_items set name = 'Butterhead Heart' where name = 'Kopfsalatherz';
update prep_items set name = 'Wild Herbs' where name = 'Wildkräuter';
update prep_items set name = 'Radishes' where name = 'Radieschen';
update prep_items set name = 'Inca Tomatoes' where name = 'Inka Tomaten';
update prep_items set name = 'Olive Oil' where name = 'Olivenöl';
update prep_items set name = 'White Balsamic' where name = 'Weisser Balsamico';
update prep_items set name = 'Grilled Peach' where name = 'Gegrillter Pfirsich';
update prep_items set name = 'Herb Salad' where name = 'Kräutersalat';
update prep_items set name = 'Spiced Honey' where name = 'Gewürzhonig';
update prep_items set name = 'Celery Stalks' where name = 'Stangensellerie';
update prep_items set name = 'Walnuts' where name = 'Baumnüsse';
update prep_items set name = 'Baby Gem Leaves' where name = 'Mini Lattich Blätter';
update prep_items set name = 'Shaved Parmesan' where name = 'Parmesan gehobelt';
update prep_items set name = 'Caesar Dressing' where name = 'Ceasar Dressing';
update prep_items set name = 'Bacon' where name = 'Speck';
update prep_items set name = 'Octopus' where name = 'Oktopus';
update prep_items set name = 'Braised Peppers' where name = 'Peperoni geschmort';
update prep_items set name = 'Fennel Shavings' where name = 'Fenchelshavings';
update prep_items set name = 'Spinach' where name = 'Spinat';
update prep_items set name = 'Roasted Garlic' where name = 'Knoblauch geröstet';
update prep_items set name = 'Taggiasca Olives' where name = 'Taggiasca Oliven';
update prep_items set name = 'Flat-Leaf Parsley' where name = 'Blattpetersilie';
update prep_items set name = 'Mint' where name = 'Minze';
update prep_items set name = 'Avocado (ripe)' where name = 'Avocado (reif)';
update prep_items set name = 'Baby Spinach' where name = 'Jungspinat';
update prep_items set name = 'Crispy Onions' where name = 'Zwiebelknusper';
update prep_items set name = 'Lime Dressing' where name = 'Limetten Dressing';
update prep_items set name = 'Morucha Beef' where name = 'Morucha Rind';
update prep_items set name = 'Holzen Veal' where name = 'Holzen Kalb';
update prep_items set name = 'Luma Pork' where name = 'Luma Schwein';
update prep_items set name = 'Lettuce' where name = 'Lattich';
update prep_items set name = 'Tomato' where name = 'Tomate';
update prep_items set name = 'Cucumber' where name = 'Gurke';
update prep_items set name = 'Onion-Jalapeño Relish' where name = 'Zwiebel-Jalapeno Relish';
update prep_items set name = 'Thigh Steak' where name = 'Schenkelsteak';
update prep_items set name = 'Tuna' where name = 'Thunfisch';
update prep_items set name = 'Baked Potato' where name = 'Ofenkartoffel';
update prep_items set name = 'Thyme & Pecorino' where name = 'Thymian & Pecorino';
update prep_items set name = 'Truffle & Parmesan' where name = 'Trüffel & Parmesan';
update prep_items set name = 'Confit Wild Mushrooms' where name = 'Konfierte Waldpilze';
update prep_items set name = 'Cherry Tomato Mix' where name = 'Cherry Tomaten Mix';
update prep_items set name = 'Basil Pesto' where name = 'Basilikum-Pesto';
update prep_items set name = 'Pine Nuts' where name = 'Pinienkerne';
update prep_items set name = 'Roasted Cauliflower' where name = 'Blumenkohl geröstet';
update prep_items set name = 'Yuzu Nut Butter' where name = 'Yuzu-Nussbutter';
update prep_items set name = 'Sunflower Seeds' where name = 'Sonnenblumenkerne';
update prep_items set name = 'Herb Salad Tips' where name = 'Kräutersalatspitzen';
update prep_items set name = 'Italian Dressing' where name = 'Italienische Sauce';
update prep_items set name = 'House Dressing (Honey-Mustard)' where name = 'Haus-Sauce (Honig-Senf)';
update prep_items set name = 'Vinegar/Oil Dressing' where name = 'Essig/Öl Dressing';
update prep_items set name = 'Aubergine Tartare' where name = 'Auberginen-Tatar';
update prep_items set name = 'Toasted Pine Nuts' where name = 'Geröstete Pinienkerne';
update prep_items set name = 'Parmesan Shavings' where name = 'Parmesanhobel';
update prep_items set name = 'Duck Terrine (Leg/Heart/Breast/Liver/Lardo/Apple)' where name = 'Enten-Terrine (Keule/Herz/Brust/Leber/Lardo/Apfel)';
update prep_items set name = 'Pickled Vegetables' where name = 'Gepickeltes Gemüse';
update prep_items set name = 'Pear Sorbet' where name = 'Birnensorbet';
update prep_items set name = 'Sage Blossoms & Herbs' where name = 'Salbeiblüten & Kräuter';
update prep_items set name = 'Toasted Pistachios' where name = 'Geröstete Pistazien';
update prep_items set name = 'Beef Tartare (Holzen Angus)' where name = 'Rindstatar (Holzen Angus)';
update prep_items set name = 'Table Garnishes (Tableside Condiments)' where name = 'Tischgarnituren (Kondimente für Tischzubereitung)';
update prep_items set name = 'Bone Marrow' where name = 'Knochenmark';
update prep_items set name = 'Veal Jus' where name = 'Kalbsjus';
update prep_items set name = 'Shallots' where name = 'Schalotten';
update prep_items set name = 'Chives' where name = 'Schnittlauch';
update prep_items set name = 'Wild Herb Salad' where name = 'Wildkräutersalat';
update prep_items set name = 'Belper Knolle (grated)' where name = 'Belper Knolle (geraspelt)';
update prep_items set name = 'Tomato Consommé' where name = 'Tomatenconsommé';
update prep_items set name = 'Ravioles du Dauphiné (Mountain Ricotta)' where name = 'Ravioli Dauphinés (Bergricotta gefüllt)';
update prep_items set name = 'Herbs' where name = 'Kräuter';
update prep_items set name = 'Pea & Artichoke Purée' where name = 'Erbsen-Artischockenpüree';
update prep_items set name = 'Toasted Almonds' where name = 'Geröstete Mandeln';
update prep_items set name = 'Artichoke & Pea Salsa' where name = 'Artischocken-Erbsen Salsa';
update prep_items set name = 'Sorrel Espuma' where name = 'Sauerampfer Espuma';
update prep_items set name = 'Nut Beurre Blanc' where name = 'Nuss Beurre Blanc';
update prep_items set name = 'Herb Oil' where name = 'Kräuteröl';
update prep_items set name = 'Mustard Blossoms' where name = 'Senfblüten';
update prep_items set name = 'Grated Almond' where name = 'Geriebene Mandel';
update prep_items set name = 'Wild Garlic Gnocchi' where name = 'Bärlauch-Gnocchi';
update prep_items set name = 'Schlossberger Mountain Cheese' where name = 'Schlossberger Bergkäse';
update prep_items set name = 'Morels' where name = 'Morcheln';
update prep_items set name = 'Morel & White Wine Foam' where name = 'Morchel-Weissweinschaum';
update prep_items set name = 'Violet Blossoms' where name = 'Veilchenblüten';
update prep_items set name = 'Mackerel' where name = 'Makrele';
update prep_items set name = 'Escabeche Broth (Calamansi/Olive Oil/Mirepoix)' where name = 'Escabechesud (Kalamansisaft/Olivenöl/Mirepoix)';
update prep_items set name = 'Tomato, Grapefruit & Orange Salad' where name = 'Tomaten-Grapefruit-Orange Salat';
update prep_items set name = 'Olives' where name = 'Oliven';
update prep_items set name = 'Bacon Stock & Roasted Pepper Foam' where name = 'Speckfond-Peperoni Schaum';
update prep_items set name = 'Baby Turbot' where name = 'Baby Steinbutt';
update prep_items set name = 'Seasonal Market Vegetables' where name = 'Saisonales Marktgemüse';
update prep_items set name = 'Sides & Sauces of Choice' where name = 'Beilagen & Saucen nach Wahl';
update prep_items set name = 'Chicken Breast (Brined, Poached)' where name = 'Hühnerbrust (Salzlake, pochiert)';
update prep_items set name = 'Truffle & Mushroom Duxelles' where name = 'Trüffel-Pilzduxelles';
update prep_items set name = 'Chicken Leg (Confit)' where name = 'Hühnerschenkel (konfiert)';
update prep_items set name = 'Poultry Liver' where name = 'Geflügelleber';
update prep_items set name = 'Apple' where name = 'Apfel';
update prep_items set name = 'Black Périgord Truffle' where name = 'Schwarzer Perigord Trüffel';
update prep_items set name = 'Turned Mushrooms' where name = 'Tournierte Champignons';
update prep_items set name = 'Seasonal Vegetables' where name = 'Saisongemüse';
update prep_items set name = 'Beef Fillet (Holzen Angus, 200g)' where name = 'Rindsfilet (Holzen Angus, 200g)';
update prep_items set name = 'Red Wine & Onion Gel' where name = 'Rotwein-Zwiebelgel';
update prep_items set name = 'Duck Liver (Rossini Option)' where name = 'Entenleber (Rossini-Option)';
update prep_items set name = 'Truffle' where name = 'Trüffel';
update prep_items set name = 'Gold Leaf' where name = 'Blattgold';
update prep_items set name = 'Côte de Boeuf (Morucha Beef, approx. 600g/2 pers.)' where name = 'Côte de Boeuf (Morucha Rind, ca. 600g/2 Pers.)';
update prep_items set name = 'Choux Pastry' where name = 'Choux-Gebäck';
update prep_items set name = 'Sour Cream Ice Cream' where name = 'Sauerrahm Eis';
update prep_items set name = 'Sour Cream & Vanilla Whipped Ganache' where name = 'Sauerrahm-Vanille Whipped Ganache';
update prep_items set name = 'Bergamot Ice Parfait' where name = 'Bergamotte Eis Parfait';
update prep_items set name = 'Sponge (Almond/Bergamot)' where name = 'Biskuit (Mandel/Bergamotte)';
update prep_items set name = 'Strawberry Confit' where name = 'Erdbeerconfit';
update prep_items set name = 'Strawberry Whipped Ganache' where name = 'Erdbeer Whipped Ganache';
update prep_items set name = 'Strawberry Meringue' where name = 'Erdbeer Meringue';
update prep_items set name = 'Basil Ice Cream' where name = 'Basilikum Eis';
update prep_items set name = 'Elderflower Panna Cotta' where name = 'Holunderblüten Pannacotta';
update prep_items set name = 'Rhubarb Confit/Chips/Gel' where name = 'Rhabarber Confit/Chips/Gel';
update prep_items set name = 'Black Sesame Cracker' where name = 'Schwarzer Sesam Cracker';
update prep_items set name = 'Sesame, Lemon & Vanilla Ice Cream' where name = 'Sesam-Zitrone-Vanille Eis';
update prep_items set name = 'Baba Dough (Rum)' where name = 'Baba-Teig (Rum)';
update prep_items set name = 'Verbena Mousse' where name = 'Eisenkraut Mousse';
update prep_items set name = 'Verbena Ice Cream' where name = 'Eisenkraut Eis';
update prep_items set name = 'Honey Tuile' where name = 'Honig Hippe';
update prep_items set name = 'Honey & Passion Fruit Gel' where name = 'Honig-Passionsfrucht Gel';
update prep_items set name = 'Chocolate Mousse (Sambirano 68%)' where name = 'Schokoladenmousse (Sambirano 68%)';
update prep_items set name = 'Tonka Bean Chocolate Cream' where name = 'Tonkabohnen Choco Creme';
update prep_items set name = 'Caramelized Hazelnuts' where name = 'Karamellisierte Haselnüsse';
update prep_items set name = 'Hazelnut Ice Cream' where name = 'Haselnusseis';
update prep_items set name = 'Strawberry Compote' where name = 'Strawberry Compté';
update prep_items set name = 'Tuna Sashimi' where name = 'Thunfisch Sashimi';
update prep_items set name = 'Salmon Sashimi' where name = 'Lachs Sashimi';
update prep_items set name = 'Soy Sauce' where name = 'Sojasauce';
update prep_items set name = 'Pickled Ginger' where name = 'Eingelegter Ingwer';
update prep_items set name = 'Sushi Rice' where name = 'Sushi-Reis';
update prep_items set name = 'Nori Sheets' where name = 'Nori-Blätter';
update prep_items set name = 'Salmon' where name = 'Lachs';
update prep_items set name = 'Marinated Olives' where name = 'Marinierte Oliven';
update prep_items set name = 'Flatbread' where name = 'Fladenbrot';
update prep_items set name = 'Edamame Beans' where name = 'Edamame-Bohnen';
update prep_items set name = 'Sea Salt' where name = 'Meersalz';
update prep_items set name = 'Toast Bread' where name = 'Toastbrot';
update prep_items set name = 'Chicken Breast' where name = 'Pouletbrust';
update prep_items set name = 'French Fries' where name = 'Pommes Frites';
update prep_items set name = 'Pumpkin' where name = 'Kürbis';
update prep_items set name = 'Vegetable Stock' where name = 'Gemüsebouillon';
update prep_items set name = 'Cream' where name = 'Rahm';
update prep_items set name = 'Pumpkin Seed Oil' where name = 'Kürbiskernöl';
update prep_items set name = 'Potatoes' where name = 'Kartoffeln';
update prep_items set name = 'Salt' where name = 'Salz';
update prep_items set name = 'Risotto Rice' where name = 'Risottoreis';
update prep_items set name = 'Mixed Mushrooms' where name = 'Gemischte Pilze';
update prep_items set name = 'White Wine' where name = 'Weisswein';
update prep_items set name = 'Eggs' where name = 'Eier';
update prep_items set name = 'Smoked Salmon' where name = 'Geräucherter Lachs';
update prep_items set name = 'Beef Carpaccio' where name = 'Rindscarpaccio';
update prep_items set name = 'Salad Garnish' where name = 'Salatgarnitur';
update prep_items set name = 'Capers' where name = 'Kapern';
update prep_items set name = 'Poularde Breast' where name = 'Poulardenbrust';
update prep_items set name = 'Poultry Jus' where name = 'Geflügeljus';
update prep_items set name = 'Vegetable Garnish' where name = 'Gemüsegarnitur';
update prep_items set name = 'Potato Gratin' where name = 'Kartoffelgratin';
update prep_items set name = 'Seasonal Mousse' where name = 'Mousse nach Saison';
update prep_items set name = 'Fresh Fruit' where name = 'Frische Früchte';
update prep_items set name = 'Swiss Biscuits' where name = 'Guetzli';
update prep_items set name = 'Mixed Salads' where name = 'Gemischte Salate';
update prep_items set name = 'Dressings of Choice' where name = 'Dressings nach Wahl';
update prep_items set name = 'Toppings (Nuts/Croutons/Cheese)' where name = 'Toppings (Nüsse/Croutons/Käse)';
update prep_items set name = 'Staff Dish of the Day' where name = 'Tagesgericht Personal';
update prep_items set name = 'Side Dish' where name = 'Beilage';
update prep_items set name = 'Chef''s Choice Bites' where name = 'Häppchen nach Wahl des Küchenchefs';
