-- ChefOS -- REAL supplier-priced ingredients from Swiss wholesaler price lists (DRAFT for review).
--
-- Source 1: Caviezel Giovanettoni AG, 2026 frozen/fresh food supplier price list (92-page PDF,
--   pre-extracted to text). All prices below are quoted "article no." references back to this
--   catalog (e.g. "article no. 41501") so Richard can look up and double-check any line item.
-- Source 2: Swiss Gastro Solutions "Sortiment" catalog (5-page PDF, ~19 products) was reviewed
--   in full but contributed NOTHING to this file -- every item in it (Mini-Schinkengipfeli,
--   Apero-Chuechli, Frueglingsrollen, Jalapenos mit Frischkaese, Schinkengipfel, Wienerli im
--   Teig, Strudel, etc.) is a branded, pre-formed finished snack/pastry product, not a base
--   ingredient a chef would write into a recipe's ingredient list. Excluded per scope.
--
-- Currency conversion: all source prices are CHF, explicitly excl. VAT. This app's ingredients
--   table stores everything as price_currency = 'EUR' (a pre-existing quirk of the 535-row seed
--   data, kept for consistency -- the UI hardcodes a EUR symbol regardless of the stored
--   currency, so switching to CHF here would look wrong against the rest of the price book).
--   Conversion used: 1 CHF ~= 1.06 EUR (rough/approximate, NOT a live FX rate -- just enough to
--   keep these real Swiss prices roughly comparable to the rest of the EUR-denominated book).
--   All converted prices are rounded to 2 decimals.
--
-- Scope: only genuine base ingredients were extracted -- the kind of thing a chef actually
--   writes as a line in a recipe's ingredient table (e.g. "Broccoli", "Cream", "Whole Milk",
--   "Salmon Fillet", "Eggs"). Branded/prepared/finished convenience products (McCain, JOWA, HUG,
--   Frigemo, Kern & Sammet, Bina ready-meals, breaded/formed/panierte items, pre-dressed salads,
--   Boiron fruit-puree line, ready-made sauces branded as "SGS", frozen pastries, ice cream,
--   coffee capsules, canned goods, non-food) were deliberately skipped even though the source
--   catalog runs to thousands of SKUs. Vegetable "Gemuesemischungen" (pre-made mixes) were
--   skipped in favor of their single-vegetable components.
--
-- Summary: 104 rows total, no duplicate names within this batch.
--   ~50 are brand-new ingredients not previously in the 535-row seed (or its 32_* expansion).
--   ~54 match an existing ingredient name exactly and will UPDATE that row's price/currency/
--   notes only (via ON CONFLICT DO UPDATE) -- upgrading it from an ESTIMATED price to this
--   REAL, sourced Swiss wholesale price. No other column (category, nutrition, origin, etc.)
--   is touched on conflict, so nothing else on an existing row gets clobbered.
--   By category: Fruit 18, Vegetable 39 (incl. mushrooms), Seafood 8, Dairy 20,
--   Dairy Alternatives 1, Eggs 4, Sauces & Condiments 4, Oils & Vinegars 1,
--   Chocolate & Cocoa 4, Dry Goods & Pantry 2, Grains & Flour 1, Bakery 2.
--
-- Two deliberate name-collision decisions worth flagging for review:
--   1. "Salmon Fillet" and "Prawn" already exist in 32_ingredients_expansion_new.sql (as
--      ESTIMATED prices) -- this file updates both to the real Caviezel price.
--   2. A few sourced items were intentionally named to AVOID colliding with an existing row
--      that uses a different unit (pc vs kg/l) for the same concept, since ON CONFLICT DO
--      UPDATE here only touches price/currency/notes and would silently mismatch a kg/L price
--      against a 'pc' unit otherwise. Examples: "Liquid Egg Yolk" / "Liquid Egg White" /
--      "Liquid Whole Egg" (new kg-priced liquid-egg SKUs, distinct from the existing per-piece
--      "Egg Yolk"/"Egg White"/"Whole Egg" rows) and "Shortcrust Pastry Dough" (new kg-priced raw
--      dough roll, distinct from the existing per-piece blind-baked "Shortcrust Pastry Shell").
--
-- Deliberately NOT included: Kiwi, Orange, Melon, and Pineapple pricing from the source catalog
--   were all sourced from a pre-cut/convenience-format SKU (e.g. "Kiwi geschnitten", fresh-cut
--   fruit salad line) whose price reflects prep labor, not raw fruit cost -- updating the
--   existing plain "Kiwi"/"Orange"/"Pineapple" estimates with those numbers would have been
--   misleading, so those four were dropped rather than force-fit.
--
-- Run after 06_ingredients_seed.sql and 32_ingredients_expansion_new.sql. Review before
-- applying to production -- this is a DRAFT and has not been run against the live database.

-- Fruit
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Apple', ARRAY['Apfel']::text[], 'European', 'Fruit', 'kg', 4.35, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.10/kg -> EUR conversion @1.06), article no. 41501.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Apricot', ARRAY['Aprikosen']::text[], 'European', 'Fruit', 'kg', 6.82, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 6.43/kg -> EUR conversion @1.06), article no. 41817.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Blackberry', ARRAY['Brombeeren']::text[], 'European', 'Fruit', 'kg', 7.92, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 7.47/kg -> EUR conversion @1.06), article no. 40210.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Blackcurrant', ARRAY['Cassis']::text[], 'European', 'Fruit', 'kg', 16.63, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 15.69/kg -> EUR conversion @1.06), article no. 40250.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Cranberry', ARRAY['Cranberries']::text[], 'European', 'Fruit', 'kg', 20.03, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 18.90/kg -> EUR conversion @1.06), article no. 41613.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Strawberry', ARRAY['Erdbeeren']::text[], 'European', 'Fruit', 'kg', 6.57, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 6.20/kg -> EUR conversion @1.06), article no. 41330.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Blueberry', ARRAY['Heidelbeeren']::text[], 'European', 'Fruit', 'kg', 8.84, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 8.34/kg -> EUR conversion @1.06), article no. 41814.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Raspberry', ARRAY['Himbeeren']::text[], 'European', 'Fruit', 'kg', 8.78, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 8.28/kg -> EUR conversion @1.06), article no. 41811.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Elderberry', ARRAY['Holunder']::text[], 'European', 'Fruit', 'kg', 15.48, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 14.60/kg -> EUR conversion @1.06), article no. 41610.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Redcurrant', ARRAY['Johannisbeeren rot']::text[], 'European', 'Fruit', 'kg', 6.57, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 6.20/kg -> EUR conversion @1.06), article no. 40610.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Cherry', ARRAY['Kirschen']::text[], 'European', 'Fruit', 'kg', 7.12, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 6.72/kg -> EUR conversion @1.06), article no. 41818.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Sour Cherry', ARRAY['Sauerkirschen']::text[], 'European', 'Fruit', 'kg', 7.47, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 7.05/kg -> EUR conversion @1.06), article no. 41505.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Mango', ARRAY['Mango']::text[], 'European', 'Fruit', 'kg', 6.13, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.78/kg -> EUR conversion @1.06), article no. 41810.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Lingonberry', ARRAY['Preiselbeeren']::text[], 'European', 'Fruit', 'kg', 10.08, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 9.51/kg -> EUR conversion @1.06), article no. 31718.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Rhubarb', ARRAY['Rhabarber']::text[], 'European', 'Fruit', 'kg', 5.37, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.07/kg -> EUR conversion @1.06), article no. 41816.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Plum', ARRAY['Zwetschgen']::text[], 'European', 'Fruit', 'kg', 3.77, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 3.56/kg -> EUR conversion @1.06), article no. 41506.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Chestnut', ARRAY['Marroni']::text[], 'European', 'Fruit', 'kg', 15.39, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 14.52/kg -> EUR conversion @1.06), article no. 34115.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Apfelmus', ARRAY['Applesauce']::text[], 'European', 'Fruit', 'kg', 4.54, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.28/kg -> EUR conversion @1.06), article no. 29510.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Vegetable
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Artichoke Hearts', ARRAY['Artischockenherzen']::text[], 'European', 'Vegetable', 'kg', 11.61, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 10.95/kg -> EUR conversion @1.06), article no. 34089.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Swiss Chard', ARRAY['Blattmangold']::text[], 'European', 'Vegetable', 'kg', 7.10, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 6.70/kg -> EUR conversion @1.06), article no. 34051.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Cauliflower', ARRAY['Blumenkohl']::text[], 'European', 'Vegetable', 'kg', 6.19, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.84/kg -> EUR conversion @1.06), article no. 31955.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Green Beans', ARRAY['Bohnen fein']::text[], 'European', 'Vegetable', 'kg', 5.27, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.97/kg -> EUR conversion @1.06), article no. 31966.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Broccoli', ARRAY['Broccoli']::text[], 'European', 'Vegetable', 'kg', 6.02, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.68/kg -> EUR conversion @1.06), article no. 31963.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Butter Beans', ARRAY['Butterbohnen']::text[], 'European', 'Vegetable', 'kg', 6.19, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.84/kg -> EUR conversion @1.06), article no. 30320.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Edamame', ARRAY['Edamame']::text[], 'Asian', 'Vegetable', 'kg', 6.71, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 6.33/kg -> EUR conversion @1.06), article no. 31978.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Peas', ARRAY['Gartenerbsen']::text[], 'European', 'Vegetable', 'kg', 5.62, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.30/kg -> EUR conversion @1.06), article no. 31932.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Kale', ARRAY['Federkohl']::text[], 'European', 'Vegetable', 'kg', 7.10, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 6.70/kg -> EUR conversion @1.06), article no. 34078.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Fennel', ARRAY['Fenchel']::text[], 'European', 'Vegetable', 'kg', 9.28, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 8.75/kg -> EUR conversion @1.06), article no. 34063.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Carrot', ARRAY['Karotten']::text[], 'European', 'Vegetable', 'kg', 4.63, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.37/kg -> EUR conversion @1.06), article no. 30840.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Snow Peas', ARRAY['Kefen']::text[], 'European', 'Vegetable', 'kg', 9.97, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 9.41/kg -> EUR conversion @1.06), article no. 31936.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Chickpea', ARRAY['Kichererbsen']::text[], 'European', 'Vegetable', 'kg', 7.53, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 7.10/kg -> EUR conversion @1.06), article no. 34102.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Kohlrabi', ARRAY['Kohlrabi']::text[], 'European', 'Vegetable', 'kg', 5.23, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.93/kg -> EUR conversion @1.06), article no. 31964.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Culinary Pumpkin', ARRAY['Kürbis']::text[], 'European', 'Vegetable', 'kg', 6.53, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 6.16/kg -> EUR conversion @1.06), article no. 31717.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Lettuce', ARRAY['Lattich']::text[], 'European', 'Vegetable', 'kg', 8.90, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 8.40/kg -> EUR conversion @1.06), article no. 31969.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Leek', ARRAY['Lauch']::text[], 'European', 'Vegetable', 'kg', 4.96, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.68/kg -> EUR conversion @1.06), article no. 31310.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Corn Kernels', ARRAY['Maiskörner']::text[], 'European', 'Vegetable', 'kg', 3.68, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 3.47/kg -> EUR conversion @1.06), article no. 32809.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Parsnip', ARRAY['Pastinaken']::text[], 'European', 'Vegetable', 'kg', 8.37, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 7.90/kg -> EUR conversion @1.06), article no. 34070.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Bell Pepper', ARRAY['Peperoni']::text[], 'European', 'Vegetable', 'kg', 5.51, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.20/kg -> EUR conversion @1.06), article no. 33235.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Romanesco', ARRAY['Romanesco']::text[], 'European', 'Vegetable', 'kg', 7.01, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 6.61/kg -> EUR conversion @1.06), article no. 31961.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Brussels Sprouts', ARRAY['Rosenkohl']::text[], 'European', 'Vegetable', 'kg', 5.16, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.87/kg -> EUR conversion @1.06), article no. 31714.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Red Cabbage', ARRAY['Rotkraut']::text[], 'European', 'Vegetable', 'kg', 6.25, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.90/kg -> EUR conversion @1.06), article no. 34065.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Fava Beans', ARRAY['Saubohnen']::text[], 'European', 'Vegetable', 'kg', 10.49, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 9.90/kg -> EUR conversion @1.06), article no. 34069.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Salsify', ARRAY['Schwarzwurzeln']::text[], 'European', 'Vegetable', 'kg', 6.33, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.97/kg -> EUR conversion @1.06), article no. 31962.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Green Asparagus', ARRAY['Spargeln grün']::text[], 'European', 'Vegetable', 'kg', 12.46, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 11.75/kg -> EUR conversion @1.06), article no. 32520.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'White Asparagus', ARRAY['Spargeln weiss']::text[], 'European', 'Vegetable', 'kg', 17.59, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 16.59/kg -> EUR conversion @1.06), article no. 32510.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Spinach', ARRAY['Blattspinat']::text[], 'European', 'Vegetable', 'kg', 5.42, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.11/kg -> EUR conversion @1.06), article no. 31945.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Sweet Potato', ARRAY['Süsskartoffeln']::text[], 'European', 'Vegetable', 'kg', 10.74, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 10.13/kg -> EUR conversion @1.06), article no. 3-329.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Sugar Snap Peas', ARRAY['Sugar Snaps']::text[], 'European', 'Vegetable', 'kg', 8.00, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 7.55/kg -> EUR conversion @1.06), article no. 31938.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Tomato', ARRAY['Tomaten']::text[], 'European', 'Vegetable', 'kg', 4.19, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 3.95/kg -> EUR conversion @1.06), article no. 32730.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Zucchini', ARRAY['Zucchetti']::text[], 'European', 'Vegetable', 'kg', 5.86, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.53/kg -> EUR conversion @1.06), article no. 31967.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Onion', ARRAY['Zwiebeln']::text[], 'European', 'Vegetable', 'kg', 4.52, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.26/kg -> EUR conversion @1.06), article no. 31942.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Sun-Dried Tomato', ARRAY['Tomaten gedörrt']::text[], 'European', 'Vegetable', 'kg', 19.08, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 18.00/kg -> EUR conversion @1.06), article no. 27860.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Sauerkraut', ARRAY['Sauerkraut roh']::text[], 'European', 'Vegetable', 'kg', 3.70, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 3.49/kg -> EUR conversion @1.06), article no. 28015.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Button Mushrooms', ARRAY['Champignons']::text[], 'European', 'Vegetable', 'kg', 5.04, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.75/kg -> EUR conversion @1.06), article no. 70112.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Chanterelle', ARRAY['Eierschwämme']::text[], 'European', 'Vegetable', 'kg', 24.34, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 22.96/kg -> EUR conversion @1.06), article no. 70232.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Morel', ARRAY['Morcheln']::text[], 'European', 'Vegetable', 'kg', 64.59, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 60.93/kg -> EUR conversion @1.06), article no. 70330.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Porcini', ARRAY['Steinpilze']::text[], 'European', 'Vegetable', 'kg', 22.83, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 21.54/kg -> EUR conversion @1.06), article no. 70516.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Seafood
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Trout Fillet', ARRAY['Forellenfilet']::text[], 'European', 'Seafood', 'kg', 17.59, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 16.59/kg -> EUR conversion @1.06), article no. 60567.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Cod Loin', ARRAY['Kabeljaurücken']::text[], 'European', 'Seafood', 'kg', 21.83, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 20.59/kg -> EUR conversion @1.06), article no. 60562.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Salmon Fillet', ARRAY['Lachsfilet']::text[], 'European', 'Seafood', 'kg', 30.48, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 28.75/kg -> EUR conversion @1.06), article no. 60140.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Pangasius Fillet', ARRAY['Pangasiusfilet']::text[], 'European', 'Seafood', 'kg', 10.97, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 10.35/kg -> EUR conversion @1.06), article no. 60130.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Arctic Char Fillet', ARRAY['Seesaiblingfilet']::text[], 'European', 'Seafood', 'kg', 27.35, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 25.80/kg -> EUR conversion @1.06), article no. 60540.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Pike-Perch Fillet', ARRAY['Zanderfilet']::text[], 'European', 'Seafood', 'kg', 21.94, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 20.70/kg -> EUR conversion @1.06), article no. 60559.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Prawn', ARRAY['Crevetten']::text[], 'European', 'Seafood', 'kg', 27.28, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 25.74/kg -> EUR conversion @1.06), article no. 60948.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Cooked Prawn', ARRAY['Crevetten gekocht, geschält']::text[], 'European', 'Seafood', 'kg', 21.65, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 20.42/kg -> EUR conversion @1.06), article no. 60941.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Dairy
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Whole Milk', ARRAY['Vollmilch']::text[], 'European', 'Dairy', 'l', 1.69, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 1.59/L -> EUR conversion @1.06), article no. 10.1065.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Skim Milk', ARRAY['Magermilch']::text[], 'European', 'Dairy', 'l', 1.85, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 1.75/L -> EUR conversion @1.06), article no. 06.813.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Whipping Cream', ARRAY['Vollrahm 35%']::text[], 'European', 'Dairy', 'l', 8.16, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 7.70/L -> EUR conversion @1.06), article no. 10.1062.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Half Cream', ARRAY['Halbrahm 25%']::text[], 'European', 'Dairy', 'l', 10.53, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 9.93/L -> EUR conversion @1.06), article no. 06.768.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Crème Fraîche', ARRAY['Crème fraîche 35%']::text[], 'European', 'Dairy', 'kg', 21.23, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 20.03/kg -> EUR conversion @1.06), article no. 06.772.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Butter', ARRAY['Die Butter']::text[], 'European', 'Dairy', 'kg', 20.27, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 19.12/kg -> EUR conversion @1.06), article no. 06.707.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Cream Cheese', ARRAY['Philadelphia Nature']::text[], 'European', 'Dairy', 'kg', 15.68, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 14.79/kg -> EUR conversion @1.06), article no. 06.546.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Cottage Cheese', ARRAY['Hüttenkäse']::text[], 'European', 'Dairy', 'kg', 10.39, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 9.80/kg -> EUR conversion @1.06), article no. 06.940.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Mascarpone', ARRAY['Mascarpone']::text[], 'European', 'Dairy', 'kg', 18.74, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 17.68/kg -> EUR conversion @1.06), article no. 06.467.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Ricotta', ARRAY['Ricotta']::text[], 'European', 'Dairy', 'kg', 10.53, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 9.93/kg -> EUR conversion @1.06), article no. 0-4054.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Feta', ARRAY['Feta Kolios']::text[], 'European', 'Dairy', 'kg', 19.66, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 18.55/kg -> EUR conversion @1.06), article no. 06.945.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Mozzarella', ARRAY['Mozzarella Stange']::text[], 'European', 'Dairy', 'kg', 18.05, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 17.03/kg -> EUR conversion @1.06), article no. 06.463.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Emmentaler', ARRAY['Emmental']::text[], 'European', 'Dairy', 'kg', 21.04, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 19.85/kg -> EUR conversion @1.06), article no. 06.906.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Gruyère', ARRAY['Greyerzer']::text[], 'European', 'Dairy', 'kg', 23.43, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 22.10/kg -> EUR conversion @1.06), article no. 06.911.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Sbrinz', ARRAY['Sbrinz']::text[], 'European', 'Dairy', 'kg', 28.45, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 26.84/kg -> EUR conversion @1.06), article no. 06.915.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Grana Padano', ARRAY['Grana Padano']::text[], 'European', 'Dairy', 'kg', 29.10, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 27.45/kg -> EUR conversion @1.06), article no. 06.485.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Appenzeller', ARRAY['Appenzeller']::text[], 'European', 'Dairy', 'kg', 21.68, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 20.45/kg -> EUR conversion @1.06), article no. 06.890.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Raclette Cheese', ARRAY['Raclette']::text[], 'European', 'Dairy', 'kg', 26.55, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 25.05/kg -> EUR conversion @1.06), article no. 06.438.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Brie', ARRAY['Brie de Meaux']::text[], 'European', 'Dairy', 'kg', 29.74, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 28.06/kg -> EUR conversion @1.06), article no. 06.997.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Gorgonzola', ARRAY['Gorgonzola Reale']::text[], 'European', 'Dairy', 'kg', 36.04, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 34.00/kg -> EUR conversion @1.06), article no. 06.487.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Dairy Alternatives
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Margarine', ARRAY['Becel Margarine']::text[], 'European', 'Dairy Alternatives', 'kg', 13.25, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 12.50/kg -> EUR conversion @1.06), article no. 0-4044.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Eggs
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Egg', ARRAY['CH-Eier']::text[], 'European', 'Eggs', 'pc', 0.50, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 0.47/pc -> EUR conversion @1.06), article no. 07335.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Liquid Egg Yolk', ARRAY['Eigelb pasteurisiert']::text[], 'European', 'Eggs', 'kg', 14.58, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 13.75/kg -> EUR conversion @1.06), article no. 06.954.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Liquid Egg White', ARRAY['Eiweiss therm.']::text[], 'European', 'Eggs', 'kg', 10.60, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 10.00/kg -> EUR conversion @1.06), article no. 06.955.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Liquid Whole Egg', ARRAY['Vollei pasteurisiert']::text[], 'European', 'Eggs', 'kg', 9.28, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 8.75/kg -> EUR conversion @1.06), article no. 06.953.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Sauces & Condiments
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Ketchup', ARRAY['Ketchup']::text[], 'European', 'Sauces & Condiments', 'kg', 2.82, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 2.66/kg -> EUR conversion @1.06), article no. 29633.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Mayonnaise', ARRAY['Mayonnaise']::text[], 'European', 'Sauces & Condiments', 'kg', 7.87, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 7.42/kg -> EUR conversion @1.06), article no. 2990401.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Mustard', ARRAY['Senf mild']::text[], 'European', 'Sauces & Condiments', 'kg', 5.86, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.53/kg -> EUR conversion @1.06), article no. 2990411.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Hummus', ARRAY['Hummus']::text[], 'European', 'Sauces & Condiments', 'kg', 9.54, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 9.00/kg -> EUR conversion @1.06), article no. 29766.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Oils & Vinegars
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Olive Oil', ARRAY['Olivenöl']::text[], 'European', 'Oils & Vinegars', 'l', 4.07, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 3.84/L -> EUR conversion @1.06), article no. 2993005.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Chocolate & Cocoa
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Dark Chocolate Couverture', ARRAY['Couverture Noir']::text[], 'European', 'Chocolate & Cocoa', 'kg', 25.23, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 23.80/kg -> EUR conversion @1.06), article no. 78060.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'White Chocolate Couverture', ARRAY['Couverture Blanca']::text[], 'European', 'Chocolate & Cocoa', 'kg', 23.32, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 22.00/kg -> EUR conversion @1.06), article no. 78064.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Milk Chocolate Couverture', ARRAY['Milch Couverture Classic']::text[], 'European', 'Chocolate & Cocoa', 'kg', 20.35, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 19.20/kg -> EUR conversion @1.06), article no. 78065.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Cooking Chocolate', ARRAY['Kochschokolade']::text[], 'European', 'Chocolate & Cocoa', 'kg', 20.41, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 19.25/kg -> EUR conversion @1.06), article no. 78068.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Dry Goods & Pantry
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Breadcrumb', ARRAY['Paniermehl']::text[], 'European', 'Dry Goods & Pantry', 'kg', 6.00, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.66/kg -> EUR conversion @1.06), article no. 78356.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Coffee Beans', ARRAY['Röstkaffee in Bohnen']::text[], 'European', 'Dry Goods & Pantry', 'kg', 16.54, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 15.60/kg -> EUR conversion @1.06), article no. 78107.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Grains & Flour
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Bulgur', ARRAY['Bulgur']::text[], 'European', 'Grains & Flour', 'kg', 9.92, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 9.36/kg -> EUR conversion @1.06), article no. 73120.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

-- Bakery
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Puff Pastry Block', ARRAY['Blätterteig']::text[], 'European', 'Bakery', 'kg', 9.19, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 8.67/kg -> EUR conversion @1.06), article no. 29167.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes) values ('11111111-1111-4111-8111-111111111111', 'Shortcrust Pastry Dough', ARRAY['Kuchenteig']::text[], 'European', 'Bakery', 'kg', 9.05, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 8.54/kg -> EUR conversion @1.06), article no. 29166.') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes;

