-- ChefOS -- expanded supplier-priced ingredients (backlog t51), 2026-07-13.
--
-- Source: SAME Caviezel Giovanettoni AG 2026 price list already used in db/46_supplier_ingredients.sql
-- (db/46 extracted 104 base ingredients from this catalog; this batch adds items db/46 did NOT
-- already cover, specifically: fruit purees (professional pastry base ingredients), a handful of
-- missing base vegetables/dairy, and -- the main point of this batch, per Richard's explicit ask
-- to emphasize local ingredients and suppliers -- the full 'Kase aus der Region' (regional cheese)
-- section: genuine small local suppliers (Hungerbuehler, Straehl, Mueller-Thurgau) from the Bodensee/
-- Thurgau area where the catalog's own supplier (Caviezel Giovanettoni, Arbon) operates.
--
-- Same honesty standard as db/46: every price is a REAL quoted wholesale price (not an AI guess),
-- traceable back to an article number in the source catalog. Currency conversion: CHF -> EUR @ 1.06
-- (same rate as db/46, kept consistent -- not a live FX rate).
--
-- Still excluded, same scope rule as db/46: branded/formed/breaded convenience products (the
-- catalog's entire meat/poultry section is pre-formed patties, nuggets, Cordon Bleu etc., not raw
-- cuts -- none of it qualifies as a base ingredient a chef writes into a recipe line), flavoured
-- yogurt variants (30+ SKUs, kept to one plain Yogurt entry), premixed vegetable blends, and
-- branded bakery/dessert/ice-cream lines.
--
-- Summary: 49 rows total, no duplicates with db/46's existing 104.

insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Pineapple', ARRAY['Ananas-Tidbits']::text[], 'Universal', 'Fruit', 'kg', 7.0, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 6.6/kg -> EUR conversion @1.06), article no. 41813. Frozen chunks.', NULL) on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Apple Purée', ARRAY['Apfelmark']::text[], 'European', 'Fruit', 'kg', 13.17, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 12.42/kg -> EUR conversion @1.06), article no. 82010. Boiron fruit purée, unsweetened, for pastry/sauce work.', 'France') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Apricot Purée', ARRAY['Aprikosenmark']::text[], 'European', 'Fruit', 'kg', 16.83, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 15.88/kg -> EUR conversion @1.06), article no. 82210. Boiron fruit purée, unsweetened.', 'France') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Banana Purée', ARRAY['Bananenmark']::text[], 'European', 'Fruit', 'kg', 14.63, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 13.8/kg -> EUR conversion @1.06), article no. 82310. Boiron fruit purée, unsweetened.', 'Costa Rica') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Pear Purée', ARRAY['Birnenmark']::text[], 'European', 'Fruit', 'kg', 14.19, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 13.39/kg -> EUR conversion @1.06), article no. 82411. Boiron fruit purée, unsweetened.', 'France') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Blood Orange Purée', ARRAY['Blutorangenmark']::text[], 'European', 'Fruit', 'kg', 15.14, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 14.28/kg -> EUR conversion @1.06), article no. 82420. Boiron fruit purée, unsweetened.', 'Sicily') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Blackcurrant Purée', ARRAY['Cassismark']::text[], 'European', 'Fruit', 'kg', 17.79, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 16.78/kg -> EUR conversion @1.06), article no. 82610. Boiron fruit purée, unsweetened — distinct SKU from whole Blackcurrant.', 'France') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Strawberry Purée', ARRAY['Erdbeermark']::text[], 'European', 'Fruit', 'kg', 14.63, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 13.8/kg -> EUR conversion @1.06), article no. 82710. Boiron fruit purée.', 'Poland/Spain') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Raspberry Purée', ARRAY['Himbeermark']::text[], 'European', 'Fruit', 'kg', 20.13, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 18.99/kg -> EUR conversion @1.06), article no. 83210. Boiron fruit purée.', 'Serbia/Poland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Cherry Purée', ARRAY['Kirschenmark']::text[], 'European', 'Fruit', 'kg', 21.69, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 20.46/kg -> EUR conversion @1.06), article no. 83510. Boiron fruit purée, unsweetened.', 'France') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Kiwi Purée', ARRAY['Kiwimark']::text[], 'European', 'Fruit', 'kg', 15.73, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 14.84/kg -> EUR conversion @1.06), article no. 83610. Boiron fruit purée, unsweetened.', 'France') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Coconut Purée', ARRAY['Kokosnussmark']::text[], 'Asian', 'Fruit', 'kg', 19.26, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 18.17/kg -> EUR conversion @1.06), article no. 83710. Boiron fruit purée.', 'Thailand') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Mango Purée', ARRAY['Mangomark']::text[], 'Asian', 'Fruit', 'kg', 18.08, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 17.06/kg -> EUR conversion @1.06), article no. 83910. Boiron fruit purée, unsweetened.', 'India') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Passion Fruit Purée', ARRAY['Passionsfrucht-Saft']::text[], 'Universal', 'Fruit', 'kg', 19.41, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 18.31/kg -> EUR conversion @1.06), article no. 84510. Boiron fruit purée, unsweetened.', 'Ecuador/Peru') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Lemon Purée', ARRAY['Zitronenmark']::text[], 'European', 'Fruit', 'kg', 13.97, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 13.18/kg -> EUR conversion @1.06), article no. 85015. Boiron fruit purée, unsweetened.', 'Italy') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Lime Purée', ARRAY['Limessaft']::text[], 'Universal', 'Fruit', 'kg', 16.68, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 15.74/kg -> EUR conversion @1.06), article no. 83810. Boiron fruit purée, unsweetened.', 'Brazil/Mexico') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Blueberry Purée', ARRAY['Heidelbeermark']::text[], 'European', 'Fruit', 'kg', 25.05, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 23.63/kg -> EUR conversion @1.06), article no. 83115. Boiron fruit purée, unsweetened — distinct SKU from whole Blueberry.', 'Poland/Serbia') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Redcurrant Purée', ARRAY['Johannisbeermark']::text[], 'European', 'Fruit', 'kg', 19.84, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 18.72/kg -> EUR conversion @1.06), article no. 83310. Boiron fruit purée.', 'France/Poland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Kidney Beans', ARRAY['Kidney Bohnen']::text[], 'Universal', 'Vegetable', 'kg', 7.95, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 7.5/kg -> EUR conversion @1.06), article no. 34101. Frozen, cooked.', NULL) on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Corn on the Cob', ARRAY['Maiskolben']::text[], 'Universal', 'Vegetable', 'kg', 6.23, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.88/kg -> EUR conversion @1.06), article no. 31515. Frozen, whole cob ~250g.', NULL) on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Canned Tuna Chunks', ARRAY['Thunfisch rosé Chunks']::text[], 'Universal', 'Seafood', 'kg', 8.83, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 8.33/kg -> EUR conversion @1.06), article no. 29620. In sunflower oil, drained weight basis.', NULL) on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Yogurt', ARRAY['Jogurt Nature']::text[], 'European', 'Dairy', 'kg', 3.83, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 3.61/kg -> EUR conversion @1.06), article no. 06.220. Plain, unsweetened, bulk.', 'Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Quark', ARRAY['Magerquark']::text[], 'European', 'Dairy', 'kg', 5.51, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.2/kg -> EUR conversion @1.06), article no. 06.528. Low-fat curd cheese.', 'Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Bodensee Cheese', ARRAY['Bodensee Käse']::text[], 'European', 'Dairy', 'kg', 19.13, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 18.05/kg -> EUR conversion @1.06), article no. 06.421. Regional cheese, whole wheel ~5kg.', 'Lake Constance region, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Bonaparte Cheese', ARRAY['Bonaparte']::text[], 'European', 'Dairy', 'kg', 27.23, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 25.69/kg -> EUR conversion @1.06), article no. 06.468. Regional soft cheese, whole wheel ~1.6kg.', 'Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Hauskäse Vorderländerart', ARRAY['Hauskäse Vorderländerart']::text[], 'European', 'Dairy', 'kg', 20.83, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 19.65/kg -> EUR conversion @1.06), article no. 06666. Mild regional cheese from Hungerbühler, local supplier; quarter wheel ~2kg.', 'Vorderland, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Der Scharfe Maxx', ARRAY['Der scharfe Maxx']::text[], 'European', 'Dairy', 'kg', 25.97, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 24.5/kg -> EUR conversion @1.06), article no. 06.430. Sharp regional cheese, whole wheel ~7kg.', 'Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Sandwich Brie', ARRAY['Sandwichbrie']::text[], 'European', 'Dairy', 'kg', 18.29, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 17.25/kg -> EUR conversion @1.06), article no. 0.144. From Strähl, local supplier; log ~1.3kg.', 'Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Sternenberger Cheese', ARRAY['Sternenberger']::text[], 'European', 'Dairy', 'kg', 19.03, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 17.95/kg -> EUR conversion @1.06), article no. 06.624. Quarter-fat regional cheese, whole wheel ~4kg.', 'Sternenberg, Thurgau, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Müller-Thurgau Mild Cheese', ARRAY['Müller-Thurgau mild']::text[], 'European', 'Dairy', 'kg', 19.82, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 18.7/kg -> EUR conversion @1.06), article no. 08.001. From Müller-Thurgau, local Thurgau dairy; quarter wheel ~1.5-1.8kg.', 'Thurgau, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Müller-Thurgau Spicy Cheese', ARRAY['Müller-Thurgau würzig']::text[], 'European', 'Dairy', 'kg', 21.09, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 19.9/kg -> EUR conversion @1.06), article no. 08.002. From Müller-Thurgau, local Thurgau dairy.', 'Thurgau, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Müller-Thurgau Strong Cheese', ARRAY['Müller-Thurgau rezent']::text[], 'European', 'Dairy', 'kg', 22.68, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 21.4/kg -> EUR conversion @1.06), article no. 08.003. From Müller-Thurgau, local Thurgau dairy.', 'Thurgau, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Almensberger Cheese', ARRAY['Almensberger']::text[], 'European', 'Dairy', 'kg', 17.38, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 16.4/kg -> EUR conversion @1.06), article no. 08.004. From Müller-Thurgau, local Thurgau dairy.', 'Thurgau, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Hagenwiler Schlosskäse', ARRAY['Hagenwiler Schlosskäse']::text[], 'European', 'Dairy', 'kg', 21.09, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 19.9/kg -> EUR conversion @1.06), article no. 08.005. From Müller-Thurgau, local Thurgau dairy.', 'Hagenwil, Thurgau, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Thurgauer Spezial Cheese', ARRAY['Thurgauer Spezial Riemen']::text[], 'European', 'Dairy', 'kg', 24.27, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 22.9/kg -> EUR conversion @1.06), article no. 08.006. From Müller-Thurgau, local Thurgau dairy.', 'Thurgau, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Wiesenkäse', ARRAY['Wiesenkäse']::text[], 'European', 'Dairy', 'kg', 20.09, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 18.95/kg -> EUR conversion @1.06), article no. 08.007. From Müller-Thurgau, local Thurgau dairy.', 'Thurgau, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Cambozola', ARRAY['Cambozola']::text[], 'European', 'Dairy', 'kg', 30.05, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 28.35/kg -> EUR conversion @1.06), article no. 06.470. Blue-veined soft cheese, whole wheel ~2.2kg.', 'Germany') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Chaumes Cheese', ARRAY['Chaumes']::text[], 'European', 'Dairy', 'kg', 46.27, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 43.65/kg -> EUR conversion @1.06), article no. 06.540. Washed-rind soft cheese, whole wheel ~2.2kg.', 'France') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'St. Albray Cheese', ARRAY['St. Albray']::text[], 'European', 'Dairy', 'kg', 45.0, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 42.45/kg -> EUR conversion @1.06), article no. 06.543. Soft cheese, whole wheel ~2.2kg.', 'France') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Tête de Moine', ARRAY['Tête de Moine']::text[], 'European', 'Dairy', 'kg', 28.09, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 26.5/kg -> EUR conversion @1.06), article no. 06.922. Traditionally shaved into rosettes with a girolle.', 'Jura, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Tilsiter', ARRAY['Tilsiter grün mild']::text[], 'European', 'Dairy', 'kg', 17.07, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 16.1/kg -> EUR conversion @1.06), article no. 06.878. Semi-hard cheese, whole wheel ~4kg.', 'Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Vacherin Fribourgeois', ARRAY['Freiburger Vacherin']::text[], 'European', 'Dairy', 'kg', 30.58, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 28.85/kg -> EUR conversion @1.06), article no. 06.926. Traditional for moitié-moitié fondue.', 'Fribourg, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Chällerhocker', ARRAY['Chällerhocker']::text[], 'European', 'Dairy', 'kg', 32.27, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 30.44/kg -> EUR conversion @1.06), article no. 06.431. Aged semi-hard specialty cheese.', 'St. Gallen, Switzerland') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Fusilli', ARRAY['Fusilli TK']::text[], 'European', 'Dry Goods & Pantry', 'kg', 5.35, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.05/kg -> EUR conversion @1.06), article no. 80559. Frozen pasta.', 'Italy') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Elbow Macaroni', ARRAY['Hörnli TK']::text[], 'European', 'Dry Goods & Pantry', 'kg', 4.35, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.1/kg -> EUR conversion @1.06), article no. 81752. Frozen pasta.', 'Italy') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Penne', ARRAY['Penne TK']::text[], 'European', 'Dry Goods & Pantry', 'kg', 5.35, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.05/kg -> EUR conversion @1.06), article no. 80600. Frozen pasta.', 'Italy') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Rigatoni', ARRAY['Rigatoni TK']::text[], 'European', 'Dry Goods & Pantry', 'kg', 4.35, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 4.1/kg -> EUR conversion @1.06), article no. 80530. Frozen pasta.', 'Italy') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Spaghetti', ARRAY['Spaghettinester TK']::text[], 'European', 'Dry Goods & Pantry', 'kg', 6.06, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 5.72/kg -> EUR conversion @1.06), article no. 82001. Frozen pasta, portioned nests.', 'Italy') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
insert into ingredients (kitchen_id, name, aliases, cuisine, category, unit, price, price_currency, notes, origin) values ('11111111-1111-4111-8111-111111111111', 'Tagliatelle', ARRAY['Tagliatellenester TK']::text[], 'European', 'Dry Goods & Pantry', 'kg', 8.13, 'EUR', 'Price from Caviezel Giovanettoni AG 2026 supplier price list (CHF 7.67/kg -> EUR conversion @1.06), article no. 82003. Frozen pasta, portioned nests.', 'Italy') on conflict (kitchen_id, lower(name)) do update set price = excluded.price, price_currency = excluded.price_currency, notes = excluded.notes, origin = excluded.origin;
