-- Sautero -- Michelin-chef pass, batch 1: Salads & Starters (11 recipes) (2026-07-14).
--
-- Richard asked Claude (acting as a 30-year Michelin-starred chef) to improve the 173 real
-- recipes, excluding the spa recipe, sushi, and Asian-cuisine recipes. Reading the actual
-- exported data (recipes_rows.csv, 2026-07-14): the ingredients + method fields are already
-- professional-grade -- nothing there needed rewriting. What's genuinely missing across nearly
-- every recipe is the rest of the 20-field format: chef_notes, storage, shelf_life, equipment,
-- and plating_suggestions are blank. This batch fills those in for the Salads & Starters
-- category (fully in-scope -- no sushi/Asian/spa items here) as the first demonstration batch,
-- before continuing through the remaining ~120 in-scope recipes.
--
-- These are professional-standard suggestions (food-safety shelf lives, standard technique
-- tips, plating language) -- not verified against this specific kitchen's exact practice.
-- Review before treating them as gospel, same as any AI-generated content in this app.
--
-- TEST ON chefos-staging FIRST, same as every other migration.

update recipes set equipment = 'Whisk or blender for the dressing; salad spinner', chef_notes = 'Dress at the very last moment — butterhead wilts fast under acid and oil. Keep spare croutons dry until plating so they stay crisp.', storage = 'Dijon dressing keeps refrigerated, airtight, up to 5 days — re-whisk before use as it will separate.', shelf_life = 'Dressing: 5 days refrigerated. Assembled salad: serve immediately, do not hold.', plating_suggestions = 'Build height with the torn leaves rather than laying them flat; scatter croutons last so they stay visible and crisp, dressing pooled lightly at the base of the plate.' where id = '05c39289-2aff-42ae-9cf6-9ba3be902a0d';
update recipes set equipment = 'Sharp chef''s knife (no food processor); chilled mixing bowl; ring mould (optional)', chef_notes = 'Use only beef rated for raw consumption by your supplier, hand-cut same day of service. Keep the bowl, knife, and beef cold throughout — warmth is the main enemy of both texture and food safety here.', storage = 'Prepare to order — this is not a hold item. Raw fillet trim keeps refrigerated (0-2°C) up to the supplier''s use-by date, but once cut and mixed, serve within the hour.', shelf_life = 'Same-day prep only; discard any unserved mixed tartare at the end of service.', plating_suggestions = 'Classic quenelle or ring-moulded disc, raw yolk nested on top, toast points fanned alongside — keep the garnish minimal so the beef stays the focus.' where id = '16381c64-b57d-4ce0-a46c-1bcdfef0e4d1';
update recipes set equipment = 'Grill or ridged grill pan; blender for the dressing', chef_notes = 'Char hard and fast at the end rather than cooking longer — the octopus should already be tender from its initial cook, so grilling here is for colour and smoke, not doneness.', storage = 'Sherry dressing keeps refrigerated, airtight, up to 1 week. Cooked octopus (pre-grill) keeps refrigerated up to 3 days.', shelf_life = 'Dressing: 7 days refrigerated. Plated dish: serve immediately.', plating_suggestions = 'Slice the octopus on a slight bias for maximum surface area, fan over the dressed vegetables, and finish glossy with a final spoon of dressing rather than a dry plate.' where id = '243220c0-094b-4189-896a-b5c95fabcf09';
update recipes set equipment = 'Escargot dish or trays with wells; piping bag (optional) for the herb butter', chef_notes = 'Push the snail in first, then seal with butter on top — butter on the bottom only leaves the shell undressed and burns before the snail heats through.', storage = 'Herb butter can be rolled in cling film and kept refrigerated up to 1 week, or frozen up to 1 month — portion before freezing for faster service.', shelf_life = 'Herb butter: 1 week refrigerated / 1 month frozen. Baked: serve immediately.', plating_suggestions = 'Serve straight from the escargot dish, still bubbling, with crusty bread and a small fork or tongs — the dish itself is the presentation, no extra plating needed.' where id = '2d81fd25-7b01-4b43-b74a-33641bb70879';
update recipes set equipment = 'Small pot for infusing the honey; grill or hot pan for the peach', chef_notes = 'Strain the spiced honey while still warm — it thickens and gets much harder to pass through a sieve once cool.', storage = 'Spiced honey is shelf-stable at room temperature in a sealed jar for several weeks; the grilled peach is best made same-day.', shelf_life = 'Spiced honey: several weeks at room temperature. Assembled plate: serve immediately, burrata weeps once cut.', plating_suggestions = 'Split the burrata open just before serving so the centre stays creamy; scatter, don''t stack, the tomatoes and peach around it.' where id = '4d3a7bac-42eb-46d2-a246-612a87331157';
update recipes set equipment = 'Blender for the pesto', chef_notes = 'Fold the parmesan into the pesto by hand rather than blending it in — the method already gets this right; worth flagging to junior cooks since it''s the detail most likely to get skipped under pressure and turn the pesto bitter.', storage = 'Pesto keeps refrigerated, surface covered with a film of olive oil to prevent oxidation, up to 5 days.', shelf_life = 'Pesto: 5 days refrigerated (press plastic wrap directly onto the surface). Dressed tomatoes: best within 1-2 hours of cutting.', plating_suggestions = 'Tear, don''t slice, the stracciatella for texture; dot the pesto rather than pooling it, so each bite gets a hit rather than the plate reading one-note.' where id = '662f5545-71cd-4ca8-a3bc-21e41b03a247';
update recipes set equipment = 'Blender for the dressing; mandoline (optional, for fine apple/celery cuts)', chef_notes = 'Cut the apple as close to service as possible — even with acid in the dressing, exposed apple browns within 10-15 minutes.', storage = 'Roquefort dressing keeps refrigerated, airtight, up to 4-5 days — it''s dairy-based, don''t push it further.', shelf_life = 'Dressing: 4-5 days refrigerated. Assembled salad: serve within 15 minutes of cutting the apple.', plating_suggestions = 'Keep the radicchio leaves whole or torn large as a base, pile the celery-apple mix loosely on top so the caramelized walnuts stay visible, not buried.' where id = '7400fb78-ad8c-4c16-a113-ffaf76095fa4';
update recipes set difficulty = 'Medium', equipment = 'Heavy-bottomed skillet (for a true sear); slotted spoon', chef_notes = 'Don''t overcrowd the pan — scallops need space to sear rather than steam. If there''s enough rendered pancetta fat, use it as your searing medium; it adds flavour the neutral oil won''t.', storage = 'Pancetta crumble keeps in an airtight container at room temperature up to 2 days, or refrigerated up to 5 days — recrisp in a dry pan if it''s softened before serving.', shelf_life = 'Crumble: 2 days room temp / 5 days refrigerated. Scallops: cook to order, do not hold.', plating_suggestions = 'Sauce the plate with the brown butter first, scallops on top seared-side up so the crust is visible, crumble scattered last so it stays crisp.' where id = '7c6f3542-2361-46ff-b34f-0d9211ee9329';
update recipes set equipment = 'Hot pan or grill; fine strainer for the dressing (optional, for a cleaner finish)', chef_notes = 'Wagyu''s high fat content means it goes from perfect to overcooked fast — pull it slightly under your target, since carryover during the rest is more pronounced than with leaner cuts.', storage = 'Lime dressing keeps refrigerated, airtight, up to 1 week — shake before use as it will separate.', shelf_life = 'Dressing: 7 days refrigerated. Sliced wagyu: serve immediately, avocado oxidizes within the hour.', plating_suggestions = 'Fan the sliced wagyu over the dressed greens rather than piling it, so each slice shows its sear; spoon the chimichurri in dots, not a single pool, for visual movement across the plate.' where id = '86918516-b95c-45a0-bc6e-7f27e28bf7b5';
update recipes set equipment = 'Water bath / immersion circulator; instant-read thermometer (critical); hot clean knife for slicing', chef_notes = 'The 45°C internal target is the whole recipe — a few degrees over and the fat renders out and the torchon falls apart on slicing. Wipe and reheat the knife between every slice for clean cuts.', storage = 'Torchon keeps refrigerated, well-wrapped, up to 5 days once cooked and chilled. Gelée keeps refrigerated up to 3 days.', shelf_life = 'Torchon: 5 days refrigerated (raw foie gras itself: use by the supplier''s date before cooking). Gelée: 3 days refrigerated.', plating_suggestions = 'Slice thick enough to hold its shape (about 1.5cm) but not so thick it feels heavy; scatter the gelée cubes rather than centring them, and lean the toasted brioche against the torchon rather than underneath it so it doesn''t go soggy.' where id = '8bb1ab91-9c0a-451a-926e-dcb46fcb4b8f';
update recipes set equipment = 'Blender for the dressing', chef_notes = 'This dressing recipe is a large batch (3L+) — scale down for à la carte service, or keep it in rotation as a house dressing used across multiple dishes.', storage = 'Caesar dressing (egg-based) keeps refrigerated, airtight, up to 3-4 days — shorter than an oil-only dressing because of the raw yolk.', shelf_life = 'Dressing: 3-4 days refrigerated, raw-egg-based. Assembled salad: serve immediately, leaves wilt fast under the dressing''s acidity.', plating_suggestions = 'Stack whole baby lettuce leaves loosely rather than chopping them, so the Caesar dressing coats rather than drowns them; shave parmesan tableside if possible for aroma.' where id = 'a274b46a-69ab-4127-9dab-20fed5b6e508';
