-- ChefOS -- Michelin-chef pass, batch 2: Dressings & Cold Sauces (8 of 11 recipes) (2026-07-15).
--
-- Same treatment as batch 1 (db/64): fill in the blank professional fields
-- (chef_notes/storage/shelf_life/equipment/plating_suggestions), leave the already-solid
-- ingredients/method alone.
--
-- 3 of the 11 recipes in this category were excluded per the Asian-cuisine exclusion rule,
-- same logic as the rest of the pass: Yuzu Dressing (ponzu/mirin/sancho/yuzu kosho -- clearly
-- Japanese), Beetroot Salsa (built around yuzu juice as the defining flavour, same call as
-- the Yuzu Cauliflower borderline case flagged earlier), and Nuoc Cham (Vietnamese dipping
-- sauce). Guacamole/Hummus recipes that merely use sushi vinegar as an acid substitute were
-- KEPT -- the dish itself isn't Asian, just one ingredient choice, same reasoning as the
-- Karamelizovana Cibula borderline case.
--
-- Professional-standard suggestions, not verified against this specific kitchen's exact
-- practice -- review before treating as gospel, same as any AI-generated content here.
--
-- TEST ON chefos-staging FIRST, same as every other migration.

update recipes set equipment = 'Mixing bowl; fork or potato masher (not a food processor — keeps texture)', chef_notes = 'Make close to service — even with lime juice, avocado starts browning within an hour. Taste for salt twice: once after mashing, again after folding in the other ingredients, since they dilute the seasoning.', storage = 'Press plastic wrap directly onto the surface (no air gaps) and refrigerate — this slows browning more than the lime juice does.', shelf_life = 'Best within 4-6 hours refrigerated, surface-wrapped. Visible browning isn''t unsafe, just less appealing — trim and re-taste before serving.', plating_suggestions = 'Leave it rustic and chunky rather than smoothing it out — the texture is the point; a lime wedge alongside signals freshness.' where id = '14354529-7932-4c2f-b5ca-f47f440c9418';
update recipes set equipment = 'Blender or whisk + a steady hand for the oil stream; a stand mixer with whisk attachment works well for larger batches', chef_notes = 'The emulsion lives or dies on how slowly you start adding the oil — go drop by drop at first, only speeding up once it visibly thickens. If it splits, whisking a fresh yolk in separately and slowly re-incorporating the split mixture will usually rescue it.', storage = 'Keeps refrigerated, airtight, up to 5 days — raw-egg-based, don''t push it further.', shelf_life = '5 days refrigerated.', plating_suggestions = 'A small quenelle or a thin ribboned line reads more considered than a dollop — black garlic''s colour is striking enough not to need much else around it.' where id = '2838de24-fdb8-4994-9a7e-72408fc9d577';
update recipes set equipment = 'Dehydrator or low oven (for the 8-hour dry); mortar and pestle', chef_notes = 'This is a long, mostly hands-off process — start it a day ahead. The tomatoes should shrivel and concentrate, not turn fully leathery; check at the 6-hour mark if your oven runs hot.', storage = 'Dried tomato mix keeps refrigerated, airtight, up to 4-5 days once combined with the cheese and reduction.', shelf_life = '4-5 days refrigerated.', plating_suggestions = 'Rough and rustic is correct here — don''t over-process into a paste, the point is visible texture from the pounded mix.' where id = '3e6a3ad6-9bca-4543-829e-71ad51a5e454';
update recipes set equipment = 'Mixing bowl; fork or masher', chef_notes = 'This batch scales for volume service (from 4.5kg whole avocado) — the mayonnaise and sushi vinegar help it hold slightly better over service than a classic lime-only guacamole, useful if this needs to sit on a line.', storage = 'Press plastic wrap directly onto the surface, refrigerate.', shelf_life = 'Holds a little longer than classic guacamole thanks to the mayonnaise — still best within 6-8 hours refrigerated, surface-wrapped.', plating_suggestions = 'Consistent texture batch to batch since it''s built to a ratio — good for scooped quenelles that need to look uniform across many plates.' where id = '506d85b3-d070-4d0b-a1e3-3bcd1882b38e';
update recipes set equipment = 'Oven for roasting; blender or food processor', chef_notes = 'Roast the beetroot whole and unpeeled in foil — peeling before roasting loses moisture and colour. Peel while still warm; once cold the skin grips much harder.', storage = 'Keeps refrigerated, airtight, up to 4-5 days — the parmesan shortens its life slightly compared to a dairy-free pesto.', shelf_life = '4-5 days refrigerated.', plating_suggestions = 'The colour is the whole appeal — use it as a bold swipe or dot rather than folding it into something else and losing the magenta.' where id = '51c647e9-5b2c-44eb-9cc4-3200bd3dc04b';
update recipes set equipment = 'Blender or food processor, ideally high-powered for a silky finish', chef_notes = 'Blend the tahini/garlic/liquid base first before adding the chickpeas — it emulsifies more smoothly than dumping everything in at once. The final extra blend (to incorporate air) genuinely changes the texture — don''t skip it.', storage = 'Keeps refrigerated, airtight, up to 5 days. The beetroot variation keeps the same.', shelf_life = '5 days refrigerated.', plating_suggestions = 'Swirl a well into the centre for oil or garnish rather than a flat surface — classic presentation, and it stops toppings sliding off.' where id = '89f0de75-2903-44f4-a154-ac43740c22d1';
update recipes set equipment = 'Whisk or jar for shaking', chef_notes = 'Two draft ratios are recorded here — confirm with the kitchen which is the current standard before scaling up, so the batch matches what''s actually being served.', storage = 'Keeps refrigerated, airtight, up to 1-2 weeks — vinaigrette-style, no dairy or egg.', shelf_life = '1-2 weeks refrigerated; shake or re-whisk before use as it will separate.', plating_suggestions = 'Dress just before serving, not in advance — even an oil-based dressing will wilt delicate leaves if it sits.' where id = '9ad10df3-a5b1-46e6-9508-c80792ae3d99';
update recipes set equipment = 'Mixing bowl', chef_notes = 'Dice the avocado last, right before combining — it''s the first thing to brown and the most visually obvious if it does.', storage = 'Best made to order; if holding, press plastic wrap onto the surface and refrigerate briefly.', shelf_life = 'Same-day, ideally within 1-2 hours of dicing the avocado.', plating_suggestions = 'Keep the dice visible and distinct rather than crushing it together — the different colours (avocado, tomato, chilli, coriander) should read as separate pieces.' where id = 'a24b31c3-51ee-4dba-b7f2-db8bed9926c3';
