-- Sautero -- Michelin-chef pass, batch 3: Bakery & Bread (12 of 12 recipes) (2026-07-15).
--
-- Same treatment as batch 1 (db/64) and batch 2 (db/66): fill in the blank professional
-- fields (chef_notes/storage/shelf_life/equipment/plating_suggestions), leave the
-- already-solid ingredients/method alone.
--
-- No Asian-cuisine exclusions needed here -- all 12 are Western bakery items.
--
-- Professional-standard suggestions, not verified against this specific kitchen's exact
-- practice -- review before treating as gospel, same as any AI-generated content here.
--
-- TEST ON chefos-staging FIRST, same as every other migration.

update recipes set equipment = 'Baguette perforated tray or couche (linen proofing cloth); lame or razor blade for scoring; steam source in the oven (spray bottle or ice cubes in a tray)', chef_notes = 'Poolish should be bubbly and just starting to collapse at the centre before mixing -- under-ripe poolish gives less flavour, over-ripe turns sour and weakens the dough. Score at a shallow angle (20-30 degrees) in one confident motion; hesitant scoring tears the crust instead of opening it cleanly.', storage = 'Best eaten within a few hours of baking -- no lean bread like this holds well. If needed, wrap in paper (not plastic, which softens the crust) at room temperature for same-day service.', shelf_life = 'Crust noticeably softens within 4-6 hours; for longer storage, slice and freeze rather than holding at room temperature.', plating_suggestions = 'Let it cool at least 20 minutes before cutting -- slicing hot traps steam inside and gums the crumb.' where id = '0cac2957-be05-4205-880a-98209efd08c7';

update recipes set equipment = 'Banneton (proofing basket) or a well-floured bowl lined with a tea towel; Dutch oven or baking stone with steam for the bake', chef_notes = 'Starter must pass the float test (a spoonful floats in water) before mixing, not just "looks bubbly" -- an unripe starter gives a dense, gummy crumb no amount of extra proofing will fix. Bulk-ferment by feel and volume increase (about 50%), not by the clock -- timing shifts a lot with kitchen temperature.', storage = 'Store cut-side down on a wooden board or in a paper bag at room temperature -- plastic traps moisture and turns the crust soft/chewy within hours.', shelf_life = '2-3 days at room temperature (sourdough keeps longer than commercial-yeast bread thanks to the acidity); freezes well sliced.', plating_suggestions = 'Full cool-down (at least 1 hour) before slicing is non-negotiable here -- the crumb is still setting internally right after baking.' where id = '1a15e86f-9dfc-44a2-83c8-d41c43a44043';

update recipes set equipment = 'Stand mixer with dough hook (hand-mixing this much butter into dough is impractical); loaf tins', chef_notes = 'Add the butter only after the dough has already developed full gluten strength (windowpane test) -- adding it earlier blocks gluten formation and the dough never comes together. Keep the dough cool throughout mixing (butter should stay solid, not melt in) or it turns greasy instead of enriched.', storage = 'Keeps well wrapped at room temperature for 2 days thanks to the butter/egg content; refrigerate to extend, but bring back to room temperature before serving as the fat firms up cold.', shelf_life = '2-3 days at room temperature, well wrapped; freezes very well.', plating_suggestions = 'The torn, feathery crumb is the whole point of a good brioche -- pull rather than slice for the bread basket where possible.' where id = '2ab8f437-3efa-4010-9adc-c9ee5c2c88a3';

update recipes set equipment = 'Bench scraper for dividing and shaping into balls', chef_notes = 'Balling the dough tightly (a taut, smooth surface with the seam pinched underneath) is what gives the rise structure for a good crust -- a loosely shaped ball spreads flat instead of puffing at the edges. Bring to room temperature before stretching if it was refrigerated; cold dough tears instead of stretching.', storage = 'Portioned balls keep refrigerated, lightly oiled and covered, 24-48 hours -- flavour actually improves with a slow cold ferment.', shelf_life = '2 days refrigerated; freeze portioned if holding longer.', plating_suggestions = 'Stretch by hand rather than rolling with a pin -- a pin knocks out the air bubbles that give the baked crust its structure.' where id = '382825cf-a17e-4d90-a6e5-84a70fc2dce5';

update recipes set equipment = '900g loaf tin, greased or lined', chef_notes = 'Proof just to the rim of the tin before baking, not over it -- an over-proofed loaf collapses the moment it hits the oven and gives a dense band under the crust. Tap the base after baking; a hollow sound means it is fully cooked through.', storage = 'Keep in a bread bag or wrapped at room temperature -- this loaf has no crust texture worth preserving unwrapped, unlike the lean breads above.', shelf_life = '3-4 days at room temperature, well wrapped; slices freeze well for toasting later.', plating_suggestions = 'Let cool fully before slicing for sandwiches -- warm sandwich bread compresses and tears under a knife.' where id = '41b48d60-9e81-40b5-b73d-be62fd8cc89b';

update recipes set equipment = 'Rolling pin (or dough sheeter if available); ruler for consistent triangle sizing; proofing box or warm humid spot (about 24-27C) for the final proof', chef_notes = 'Butter and dough must be the same firmness before each fold -- if the butter is colder than the dough it cracks and tears through instead of laminating in even layers; if warmer, it squeezes out. Chill between every fold (minimum 30 minutes) -- skipping this is the single most common reason lamination collapses into a dense, bready croissant.', storage = 'Best baked fresh -- shaped, unbaked croissants can be held overnight in the fridge or frozen for a longer hold, then proofed and baked to order.', shelf_life = 'Baked croissants are best within a few hours; unbaked shaped dough freezes well for up to a month.', plating_suggestions = 'The honeycomb layer structure should be visible at the cut ends -- trim tips neatly before baking so the layers show cleanly.' where id = '50a768b3-1b5b-418c-bee6-5235d6dd0682';

update recipes set equipment = 'Loaf tins; bench scraper for cutting the rolled log into strands for braiding', chef_notes = 'Chill the rolled, filled log briefly before cutting and braiding -- a warm log squeezes the chocolate filling out through the cut instead of leaving neat swirled layers. Braid loosely rather than tight, since the dough still needs room to expand during proofing.', storage = 'Keeps wrapped at room temperature for 2 days; the chocolate filling means it dries out faster than plain brioche if left uncovered.', shelf_life = '2 days at room temperature, well wrapped; freezes well sliced.', plating_suggestions = 'The swirled cross-section is the entire visual appeal -- always slice to show the cut face, never serve the whole loaf uncut for plating purposes.' where id = '5efb24a7-8071-4a78-954a-ec414b4b9645';

update recipes set equipment = 'One 30x20cm tray, generously oiled; fingers for dimpling', chef_notes = 'Dimple firmly all the way to the tray base, not just the surface -- shallow dimples spring back during baking and disappear, losing the signature pools of oil. A wetter dough than feels comfortable is correct here; resist adding extra flour, which makes the crumb dense instead of open.', storage = 'Best the day it is baked; wrap at room temperature if holding overnight.', shelf_life = '1-2 days at room temperature; toast or re-warm rather than serving day-old focaccia cold.', plating_suggestions = 'Cut into rustic squares or strips rather than neat portions -- the irregular open crumb and oil pools are the point.' where id = '6f613b4b-d75e-4213-83a1-0108c7bcc7eb';

update recipes set equipment = 'Baking tray or tin sized so rolls proof touching each other (this is what gives the soft, tearable sides)', chef_notes = 'Shape each roll by cupping and dragging it in a tight circular motion against an unfloured section of the bench -- a floured bench stops the dough from gripping and the ball never tightens properly. Space rolls to just touch when panned; the shared proofing/baking creates the classic soft pull-apart sides.', storage = 'Keep covered at room temperature -- these dry out fast once cut open to the air.', shelf_life = '1-2 days at room temperature, covered; freeze well.', plating_suggestions = 'Serve pull-apart in the baking tin or tray shape they proofed in -- separating them before service loses the soft-sided texture that makes them worth doing this way.' where id = '76f812b2-8479-4a9a-ae44-fd5085aa54a0';

update recipes set equipment = 'Panettone paper moulds; long skewers or knitting needles to hang the loaf upside down immediately after baking', chef_notes = 'This lives or dies on the starter/lievito madre strength -- a weak starter simply cannot lift this much butter, egg and sugar and the dough will collapse rather than rise. Hang upside down the moment it comes out of the oven until fully cool (several hours) -- this is not optional, it is what stops the tall structure from collapsing under its own weight while still hot.', storage = 'Wrap well once fully cooled; keeps at room temperature far longer than any other item in this list thanks to the high sugar/fat content acting as a natural preservative.', shelf_life = 'Up to 2-3 weeks well wrapped at room temperature -- genuinely the longest-keeping item here.', plating_suggestions = 'Slice with a serrated knife using a gentle sawing motion, or tear by hand -- the open, stretchy crumb compresses under a straight-down cut.' where id = '795abcb5-9ac6-4262-900e-4223ed104a14';

update recipes set equipment = 'Dutch oven with lid (the enclosed steam is what replaces kneading and gives the open crumb/crackly crust)', chef_notes = 'The long, slow ferment (12+ hours) is doing the work that kneading would normally do -- do not rush this by using more yeast or a warmer spot, which trades away the flavour and crumb structure that is the whole point of the method. Preheat the Dutch oven itself, not just the oven, before the dough goes in -- a cold pot loses the initial oven-spring.', storage = 'Best within a day of baking; store cut-side down on a board rather than in plastic.', shelf_life = '1-2 days at room temperature; the crust softens faster than a classic baguette since the crumb is wetter.', plating_suggestions = 'The irregular, large-holed crumb is the intended result of minimal handling -- don''t judge it against a tighter sandwich-loaf crumb.' where id = 'cc2e953b-1644-427e-a1c6-2db2b7ee9afb';

update recipes set equipment = 'Baking tray; pastry brush for the egg wash', chef_notes = 'Roll strands evenly along their whole length (not just the ends) before braiding, or the finished loaf bulges unevenly. Egg wash twice -- once before the final proof (sets a base sheen, absorbs into the surface) and again just before baking (gives the deep golden shine Zopf is known for).', storage = 'Keeps wrapped at room temperature -- the egg-enriched dough behaves similarly to brioche.', shelf_life = '2-3 days at room temperature, well wrapped; freezes well.', plating_suggestions = 'Traditionally sliced thickly on the diagonal for the breakfast table -- this is a Sunday-morning bread, plate it accordingly rather than as a dinner-service side.' where id = 'dd2a6a42-220e-48a6-a0b1-6baf079b4002';
