#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ChefOS merged-docs builder (Richard, 17.7.2026 — "z 11 dokumentov spravíme 5").

The 11 source documents in `visual data/` stay the EDITABLE sources (every standing
workflow keeps updating feature_status.html, backlog.html, … exactly as before).
This script generates the 4 merged, tabbed documents from them:

    produkt.html  = feature_status.html + tasklist.html
    plan.html     = status.html + planning.html + backlog.html
    biznis.html   = monetization.html + automation.html
    znacka.html   = presentation.html + ChefOS_Manifesto.html + VISUAL_GUIDE.html

(+ Critical Review stays standalone at CRITICAL_REVIEW/latest.html — it is a dated
archive regenerated by /audit, merging it would break that mechanism.)

Each source document is embedded WHOLE as a JSON string and rendered into an
<iframe srcdoc> when its tab is first opened — so the sources' own CSS/JS/lang
toggles can never collide with each other or with the shell. Every shell carries
the same top bar: 5 document links (cross-navigation) + its own section tabs.

Run manually after editing any source doc, or let the pre-commit hook do it —
it regenerates all four and fails the commit if they were stale.
"""
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VD = os.path.join(REPO, 'visual data')

MERGED = [
    {
        'file': 'produkt.html', 'icon': '📱', 'title': 'Produkt',
        'subtitle_sk': 'Čo appka vie — živá mapa funkcií + história shipnutého',
        'tabs': [
            ('Mapa funkcií', 'feature_status.html'),
            ('História', 'tasklist.html'),
        ],
    },
    {
        'file': 'plan.html', 'icon': '🗺️', 'title': 'Plán',
        'subtitle_sk': 'Kde sme a čo ďalej — teraz, denník, roadmapa',
        'tabs': [
            ('Teraz', 'status.html'),
            ('Denník', 'planning.html'),
            ('Roadmapa', 'backlog.html'),
        ],
    },
    {
        'file': 'biznis.html', 'icon': '💰', 'title': 'Biznis',
        'subtitle_sk': 'Peniaze dnu aj von — monetizácia, automatizácie, náklady',
        'tabs': [
            ('Monetizácia', 'monetization.html'),
            ('Automatizácie', 'automation.html'),
            ('Náklady', 'costs.html'),
        ],
    },
    {
        'file': 'znacka.html', 'icon': '🎨', 'title': 'Značka & vízia',
        'subtitle_sk': 'Navonok — investor deck, manifest, vizuálny štandard',
        'tabs': [
            ('Investor Deck', 'presentation.html'),
            ('Manifesto', 'ChefOS_Manifesto.html'),
            ('Visual Guide', 'VISUAL_GUIDE.html'),
        ],
    },
    # Poznámky (Richard, 18.7. bod 5): a live notebook column in the shared doc nav — every
    # note he dictates lands in poznamky_src.html and gets updated as things change.
    {
        'file': 'poznamky.html', 'icon': '📝', 'title': 'Poznámky',
        'subtitle_sk': 'Živý zápisník — nápady, na dokončenie, Richardove povinnosti',
        'tabs': [
            ('Poznámky', 'poznamky_src.html'),
        ],
    },
]

# The cross-navigation shown in every shell (Critical Review joins as the 5th).
NAV = [(m['icon'], m['title'], m['file']) for m in MERGED] + [('🔍', 'Critical Review', 'CRITICAL_REVIEW/latest.html')]


def build_one(spec):
    docs = {}
    for label, fname in spec['tabs']:
        path = os.path.join(VD, fname)
        with open(path, encoding='utf-8') as f:
            docs[fname] = f.read()

    nav_html = ''.join(
        f'<a href="{f}" class="doc-link{" current" if f == spec["file"] else ""}">{i} {t}</a>'
        for i, t, f in NAV
    )
    tabs_html = ''.join(
        f'<button class="tab{" active" if n == 0 else ""}" onclick="openTab({n})" id="tabBtn{n}">{label}</button>'
        for n, (label, _f) in enumerate(spec['tabs'])
    )
    # "<" must be escaped: the sources contain literal "</script>" inside their own scripts,
    # which would terminate the shell's <script> block if embedded raw.
    payload = json.dumps([docs[f] for _l, f in spec['tabs']], ensure_ascii=False).replace('<', '\\u003c')

    return f'''<!DOCTYPE html>
<html lang="sk">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Sautero — {spec['title']}</title>
<style>
  :root{{ --bg:#0A1A2F; --paper:#122845; --ink:#fff; --ink-dim:#9C949E; --rule:#223d57; --accent:#34F7D7; }}
  *{{ box-sizing:border-box; }}
  html,body{{ margin:0; padding:0; height:100%; }}
  body{{ background:var(--bg); color:var(--ink); font-family:-apple-system,BlinkMacSystemFont,Arial,sans-serif; display:flex; flex-direction:column; }}
  header{{ flex:none; border-bottom:1px solid var(--rule); background:var(--bg); }}
  .docnav{{ display:flex; gap:2px; overflow-x:auto; padding:8px 10px 0 10px; scrollbar-width:none; }}
  .docnav::-webkit-scrollbar{{ display:none; }}
  .doc-link{{ flex:none; font-size:11.5px; font-weight:700; color:var(--ink-dim); text-decoration:none; padding:7px 12px; border-radius:8px 8px 0 0; letter-spacing:0.02em; }}
  .doc-link:hover{{ color:var(--ink); }}
  .doc-link.current{{ color:#0A1A2F; background:var(--accent); }}
  .titlebar{{ display:flex; align-items:baseline; gap:12px; padding:10px 16px 2px 16px; flex-wrap:wrap; }}
  .titlebar h1{{ margin:0; font-size:18px; }}
  .titlebar .sub{{ font-size:11.5px; color:var(--ink-dim); }}
  .tabs{{ display:flex; gap:6px; padding:8px 16px 10px 16px; overflow-x:auto; scrollbar-width:none; }}
  .tabs::-webkit-scrollbar{{ display:none; }}
  .tab{{ flex:none; background:var(--paper); border:1px solid var(--rule); color:var(--ink-dim); font-size:12.5px; font-weight:700; padding:7px 16px; border-radius:999px; cursor:pointer; }}
  .tab.active{{ background:var(--accent); border-color:var(--accent); color:#0A1A2F; }}
  main{{ flex:1; min-height:0; position:relative; }}
  main iframe{{ position:absolute; inset:0; width:100%; height:100%; border:0; display:none; background:var(--bg); }}
  main iframe.show{{ display:block; }}
</style>
</head>
<body>
<header>
  <nav class="docnav">{nav_html}</nav>
  <div class="titlebar"><h1>{spec['icon']} {spec['title']}</h1><span class="sub">{spec['subtitle_sk']}</span></div>
  <div class="tabs">{tabs_html}</div>
</header>
<main id="frames"></main>
<script>
/* Each source document is embedded whole and rendered into its own iframe on first open —
   their CSS/JS/lang-toggles stay fully isolated from each other and from this shell. */
const DOCS = {payload};
const frames = [];
function openTab(n){{
  document.querySelectorAll('.tab').forEach((b,i)=>b.classList.toggle('active', i===n));
  frames.forEach(f=>f && f.classList.remove('show'));
  if(!frames[n]){{
    const f = document.createElement('iframe');
    f.srcdoc = DOCS[n];
    document.getElementById('frames').appendChild(f);
    frames[n] = f;
  }}
  frames[n].classList.add('show');
}}
openTab(0);
</script>
</body>
</html>
'''


def main():
    check = '--check' in sys.argv
    stale = []
    for spec in MERGED:
        out_path = os.path.join(VD, spec['file'])
        html = build_one(spec)
        existing = open(out_path, encoding='utf-8').read() if os.path.exists(out_path) else None
        if existing != html:
            if check:
                stale.append(spec['file'])
            else:
                with open(out_path, 'w', encoding='utf-8') as f:
                    f.write(html)
                print(f'build_docs: wrote {spec["file"]} ({len(html)//1024} KB, {len(spec["tabs"])} tabs)')
        else:
            print(f'build_docs: {spec["file"]} up to date')
    if check and stale:
        print('build_docs: STALE merged docs (run python3 scripts/build_docs.py): ' + ', '.join(stale))
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
