#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sautero work-hours meter.

Richard, 22.7.2026: the hours must be ALL the real time spent on the project — every second the
Claude Code app is open — taken from the ACTUAL data, not an estimate around git commits.

SOURCE OF TRUTH: the Claude Code session transcripts (~/.claude/projects/<proj>/*.jsonl). Every
user / assistant / tool event carries a timestamp; that stream is the real record of when the app
was open and in use (git commits only mark the moments code shipped — they missed reading,
planning, testing, discussion). We turn the discrete events into open-time per day with the
standard active-window model: consecutive events <= IDLE_CAP apart are one continuous open window;
a longer gap means the app was closed / away and starts a new window. Each window counts
(last - first) + LEAD (a short lead-in for opening + reading before the first captured event).
Days are attributed in Europe/Zurich (Bern).

The transcripts live only on the local machine, never in CI. So on --write we FREEZE the computed
per-day hours into a committed snapshot (scripts/work_hours_data.json) and propagate them into every
doc that carries `const WORK_HOURS = {...}`. CI (--check) validates the docs against that committed
snapshot — it never needs the transcripts.

MODES:
  (no flag)  print the per-day table (from transcripts if reachable, else the snapshot).
  --write    recompute from the transcripts (if present) -> refresh the snapshot + every source doc.
             If the transcripts aren't reachable, keep the committed snapshot and just propagate it
             (so a machine without the sessions can never wipe the numbers).
  --check    guard (CI): every doc's WORK_HOURS must match the committed snapshot exactly.
"""
import datetime
import glob
import json
import os
import re
import sys

BERN = datetime.timezone(datetime.timedelta(hours=2))  # Europe/Zurich, summer (the whole project)
IDLE_CAP = 30 * 60   # a gap longer than this = app was closed/away -> a new open window
LEAD = 5 * 60        # lead-in per window: opening the app + reading before the first captured event

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(REPO, 'scripts')
SNAPSHOT = os.path.join(SCRIPTS, 'work_hours_data.json')
# The Claude Code project store for this project (present only on the local machine, not in CI).
TRANSCRIPT_DIR = os.path.expanduser('~/.claude/projects/-Applications-FlutterLab-app')
# Generated shells are rebuilt by build_docs from their sources — never write them directly.
GENERATED = {'produkt.html', 'plan.html', 'biznis.html', 'znacka.html', 'poznamky.html'}
MEASURED_FROM = '2026-07-08'  # transcripts cover the whole project — every day is now measured


def _event_timestamps():
    """Every event timestamp across all session transcripts, as sorted unix seconds."""
    stamps = []
    for f in glob.glob(os.path.join(TRANSCRIPT_DIR, '*.jsonl')):
        try:
            fh = open(f, encoding='utf-8', errors='replace')
        except OSError:
            continue
        with fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    t = json.loads(line).get('timestamp')
                except Exception:
                    continue
                if isinstance(t, str):
                    try:
                        stamps.append(datetime.datetime.fromisoformat(t.replace('Z', '+00:00')).timestamp())
                    except ValueError:
                        pass
    return sorted(set(stamps))


def from_transcripts():
    """Per-day open-hours from the transcript event stream (the active-window model)."""
    stamps = _event_timestamps()
    if not stamps:
        return {}
    per_day = {}

    def flush(win_start, win_end):
        d = datetime.datetime.fromtimestamp(win_start, BERN).strftime('%Y-%m-%d')
        per_day[d] = per_day.get(d, 0) + (win_end - win_start) + LEAD

    wstart = prev = stamps[0]
    for t in stamps[1:]:
        if t - prev > IDLE_CAP:
            flush(wstart, prev)
            wstart = t
        prev = t
    flush(wstart, prev)
    return {d: round(v / 3600, 1) for d, v in sorted(per_day.items())}


def load_snapshot():
    try:
        return json.load(open(SNAPSHOT, encoding='utf-8')).get('days', {})
    except (OSError, ValueError):
        return {}


def save_snapshot(days):
    payload = {
        'source': 'claude-code-session-transcripts',
        'model': f'active windows · idle_cap={IDLE_CAP // 60}min · lead={LEAD // 60}min · Europe/Zurich',
        'generated': datetime.datetime.now(BERN).strftime('%Y-%m-%d %H:%M'),
        'note': 'Every second the Claude Code app is open, derived from real session logs. Regenerated by work_hours.py --write; the docs are validated against this by --check.',
        'days': days,
    }
    with open(SNAPSHOT, 'w', encoding='utf-8') as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write('\n')


def current_days():
    """Transcript-derived if the sessions are reachable, else the committed snapshot. The second
    value is True when it came fresh from the transcripts."""
    if os.path.isdir(TRANSCRIPT_DIR):
        days = from_transcripts()
        if days:
            return days, True
    return load_snapshot(), False


def render_block(days):
    return 'const WORK_HOURS = { ' + ', '.join(f"'{d}':{h}" for d, h in sorted(days.items())) + ' };'


def source_files():
    files = []
    for f in sorted(glob.glob(os.path.join(REPO, 'visual data', '*.html'))):
        if os.path.basename(f) in GENERATED:
            continue
        if 'const WORK_HOURS = {' in open(f, encoding='utf-8', errors='replace').read():
            files.append(f)
    return files


def parse_hours(text):
    m = re.search(r'const WORK_HOURS = \{(.*?)\};', text, re.DOTALL)
    if not m:
        return {}
    return {d: float(h) for d, h in re.findall(r"'(\d{4}-\d\d-\d\d)'\s*:\s*([\d.]+)", m.group(1))}


def cmd_write():
    days, from_tx = current_days()
    if not days:
        print('work_hours: no data (no transcripts and no snapshot) — nothing written.')
        return 0
    if from_tx:
        save_snapshot(days)
    block = render_block(days)
    changed = []
    for f in source_files():
        text = open(f, encoding='utf-8').read()
        new = re.sub(r'const WORK_HOURS = \{.*?\};', block, text, count=1, flags=re.DOTALL)
        new = re.sub(r"const WORK_HOURS_MEASURED_FROM = '[^']*';",
                     f"const WORK_HOURS_MEASURED_FROM = '{MEASURED_FROM}';", new)
        if new != text:
            open(f, 'w', encoding='utf-8').write(new)
            changed.append(os.path.basename(f))
    src = 'Claude Code sessions' if from_tx else 'committed snapshot'
    print(f'work_hours: wrote WORK_HOURS ({src}) into {len(changed)} doc(s): '
          f'{", ".join(changed) or "(all already current)"}')
    return 0


def cmd_check():
    snap = load_snapshot()
    if not snap:
        print('work_hours CHECK FAILED — scripts/work_hours_data.json is missing or empty. '
              'Run: python3 scripts/work_hours.py --write')
        return 1
    problems = []
    files = source_files()
    for f in files:
        have = parse_hours(open(f, encoding='utf-8').read())
        missing = [d for d in snap if d not in have]
        wrong = [d for d in snap if d in have and abs(have[d] - snap[d]) > 0.05]
        extra = [d for d in have if d not in snap]
        if missing or wrong or extra:
            problems.append(f'{os.path.basename(f)}: missing {missing or "-"}, '
                            f'wrong {wrong or "-"}, extra {extra or "-"}')
    if problems:
        print('work_hours CHECK FAILED — a doc\'s WORK_HOURS disagrees with the committed snapshot:')
        for p in problems:
            print('  ✗ ' + p)
        print('  Fix: python3 scripts/work_hours.py --write  (then rebuild docs).')
        return 1
    print(f'work_hours: OK — {len(files)} doc(s) match the snapshot through {max(snap)}.')
    return 0


def main():
    if '--write' in sys.argv:
        return cmd_write()
    if '--check' in sys.argv:
        return cmd_check()
    days, from_tx = current_days()
    total = round(sum(days.values()), 1)
    print(f"source: {'Claude Code session transcripts' if from_tx else 'committed snapshot'} "
          f"· total: {total} h")
    for d, h in sorted(days.items()):
        print(f'{d}  {h} h')
    print('\n' + render_block(days))
    print(f"const WORK_HOURS_MEASURED_FROM = '{MEASURED_FROM}';")


if __name__ == '__main__':
    sys.exit(main())
